Repository ArkEcosystem/core, pull requests merged in 2018-12, with the labels that each got.

#1555 [WIP] chore: dynamic fees on by default
  packages/crypto/lib/networks/ark/devnet.json
  packages/crypto/lib/networks/ark/mainnet.json
  packages/crypto/lib/networks/ark/testnet.json
Labels: review

#1559 chore: remove unnecessary await
  packages/core-blockchain/__tests__/blockchain.test.js
Labels: review

#1560 chore: wrong CONTRIBUTING link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: review

#1561 chore: adjust some package versions
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-vote-report/package.json
Labels: review

#1562 chore: remove jsdoc configs
  packages/core-api/jsdoc.json
  packages/core-blockchain/jsdoc.json
  packages/core-config/jsdoc.json
  packages/core-container/jsdoc.json
  packages/core-database-postgres/jsdoc.json
  packages/core-database/jsdoc.json
  packages/core-deployer/jsdoc.json
  packages/core-elasticsearch/jsdoc.json
  packages/core-error-tracker-bugsnag/jsdoc.json
  packages/core-event-emitter/jsdoc.json
  packages/core-forger/jsdoc.json
  packages/core-graphql/jsdoc.json
  packages/core-json-rpc/jsdoc.json
  packages/core-logger-winston/jsdoc.json
  packages/core-logger/jsdoc.json
  packages/core-p2p/jsdoc.json
  packages/core-snapshots-cli/jsdoc.json
  packages/core-snapshots/jsdoc.json
  packages/core-transaction-pool-mem/jsdoc.json
  packages/core-transaction-pool/jsdoc.json
  packages/core-utils/jsdoc.json
  packages/core-vote-report/jsdoc.json
  packages/core-webhooks/jsdoc.json
  packages/crypto/jsdoc.json
Labels: review

#1563 fix(core-api): return the correct total count for /api/v2/peers
  packages/core-api/CHANGELOG.md
  packages/core-api/lib/versions/2/handlers/peers.js
Labels: review

#1564 fix(core-transaction-pool): pass correct transaction data
  packages/core-transaction-pool/lib/interface.js
Labels: review

#1626 feat(core-api): allow block display via height in v2 API
  packages/core-api/CHANGELOG.md
  packages/core-api/lib/repositories/blocks.js
Labels: review

#1627 chore: update changelogs and bump versions
  packages/core-api/CHANGELOG.md
  packages/core-api/package.json
  packages/core-transaction-pool/CHANGELOG.md
  packages/core-transaction-pool/package.json
Labels: review

#1628 Develop
  .github/PULL_REQUEST_TEMPLATE.md
  packages/core-api/CHANGELOG.md
  packages/core-api/jsdoc.json
  packages/core-api/lib/repositories/blocks.js
  packages/core-api/lib/versions/2/handlers/peers.js
  packages/core-api/package.json
  packages/core-blockchain/__tests__/blockchain.test.js
  packages/core-blockchain/jsdoc.json
  packages/core-config/jsdoc.json
  packages/core-container/jsdoc.json
  packages/core-database-postgres/jsdoc.json
  packages/core-database/jsdoc.json
  packages/core-deployer/jsdoc.json
  packages/core-elasticsearch/jsdoc.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/jsdoc.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/jsdoc.json
  packages/core-forger/jsdoc.json
  packages/core-graphql/jsdoc.json
  packages/core-json-rpc/jsdoc.json
  packages/core-logger-winston/jsdoc.json
  packages/core-logger/jsdoc.json
  packages/core-p2p/jsdoc.json
  packages/core-snapshots-cli/jsdoc.json
  packages/core-snapshots/jsdoc.json
  packages/core-transaction-pool-mem/jsdoc.json
  packages/core-transaction-pool/CHANGELOG.md
  packages/core-transaction-pool/jsdoc.json
  packages/core-transaction-pool/lib/interface.js
  packages/core-transaction-pool/package.json
  packages/core-utils/jsdoc.json
  packages/core-vote-report/jsdoc.json
  packages/core-vote-report/package.json
  packages/core-webhooks/jsdoc.json
  packages/crypto/jsdoc.json
Labels: review

#1629 chore: increasing offset for delegate registration
  packages/crypto/lib/networks/ark/devnet.json
  packages/crypto/lib/networks/ark/mainnet.json
  packages/crypto/lib/networks/ark/testnet.json
Labels: review

#1630 fix(core-deployer): map keys based on object keys instead of values
  packages/core-deployer/lib/utils.js
Labels: review

#1634 perf(core-database-postgres): drop redundant and add missing index on blocks
  packages/core-database-postgres/lib/migrations/20181204100000-blocks-generator_public_key-index.sql
  packages/core-database-postgres/lib/migrations/index.js
Labels: review

#1635 chore(crypto): increase devnet block size at height 1000000
  packages/crypto/__tests__/managers/config.test.js
  packages/crypto/lib/networks/ark/devnet.json
Labels: review

#1632 chore: remove depcheck
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/generateConfig.js
  package.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-config/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-deployer/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool-mem/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  scripts/update-deps.sh
  yarn.lock
Labels: review

#1638 perf(core-database-postgres): add sender&receiver indexes
  packages/core-api/__tests__/v2/handlers/transactions.test.js
  packages/core-database-postgres/lib/migrations/20181204300000-transactions-sender-and-receiver-indexes.sql
  packages/core-database-postgres/lib/migrations/index.js
Labels: review

#1640 fix: supply calculation
  packages/core-api/lib/versions/1/handlers/blocks.js
  packages/core-utils/__tests__/supply-calculator.test.js
  packages/core-utils/lib/index.js
  packages/core-utils/lib/supply-calculator.js
  packages/core-vote-report/lib/handler.js
Labels: review

#1643 Develop
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/generateConfig.js
  README.md
  greenkeeper.json
  package.json
  packages/core-api/CHANGELOG.md
  packages/core-api/__tests__/v2/handlers/transactions.test.js
  packages/core-api/lib/repositories/blocks.js
  packages/core-api/lib/versions/1/handlers/blocks.js
  packages/core-api/lib/versions/2/handlers/blockchain.js
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-config/package.json
  packages/core-container/package.json
  packages/core-database-postgres/CHANGELOG.md
  packages/core-database-postgres/lib/migrations/20181204100000-blocks-generator_public_key-index.sql
  packages/core-database-postgres/lib/migrations/20181204200000-transactions-timestamp-index.sql
  packages/core-database-postgres/lib/migrations/20181204300000-transactions-sender-and-receiver-indexes.sql
  packages/core-database-postgres/lib/migrations/index.js
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-deployer/lib/utils.js
  packages/core-deployer/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/lib/monitor.js
  packages/core-p2p/package.json
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool-mem/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/__tests__/supply-calculator.test.js
  packages/core-utils/lib/index.js
  packages/core-utils/lib/supply-calculator.js
  packages/core-utils/package.json
  packages/core-vote-report/lib/handler.js
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/crypto/__tests__/managers/config.test.js
  packages/crypto/lib/networks/ark/devnet.json
  packages/crypto/lib/networks/ark/mainnet.json
  packages/crypto/lib/networks/ark/testnet.json
  packages/crypto/package.json
  scripts/update-deps.sh
  yarn.lock
Labels: review

#1645 chore(core-api): increase cache generation timeout for block and transaction endpoints
  .circleci/config.yml
  packages/core-api/CHANGELOG.md
  packages/core-api/lib/versions/1/methods/blocks.js
  packages/core-api/lib/versions/1/methods/transactions.js
  packages/core-api/lib/versions/2/methods/blocks.js
  packages/core-api/lib/versions/2/methods/delegates.js
  packages/core-api/lib/versions/2/methods/transactions.js
  packages/core-api/lib/versions/2/methods/votes.js
  packages/core-api/lib/versions/2/methods/wallets.js
Labels: review

#1646 chore(core-api): make cache timeout configurable
  packages/core-api/CHANGELOG.md
  packages/core-api/lib/defaults.js
  packages/core-api/lib/versions/1/methods/accounts.js
  packages/core-api/lib/versions/1/methods/blocks.js
  packages/core-api/lib/versions/1/methods/delegates.js
  packages/core-api/lib/versions/1/methods/transactions.js
  packages/core-api/lib/versions/2/methods/blocks.js
  packages/core-api/lib/versions/2/methods/delegates.js
  packages/core-api/lib/versions/2/methods/transactions.js
  packages/core-api/lib/versions/2/methods/votes.js
  packages/core-api/lib/versions/2/methods/wallets.js
Labels: review

#1647 fix(core-api): ensure booleans for the cache timeout are handled
  packages/core-api/CHANGELOG.md
  packages/core-api/lib/versions/1/methods/accounts.js
  packages/core-api/lib/versions/1/methods/blocks.js
  packages/core-api/lib/versions/1/methods/delegates.js
  packages/core-api/lib/versions/1/methods/transactions.js
  packages/core-api/lib/versions/2/methods/blocks.js
  packages/core-api/lib/versions/2/methods/delegates.js
  packages/core-api/lib/versions/2/methods/transactions.js
  packages/core-api/lib/versions/2/methods/votes.js
  packages/core-api/lib/versions/2/methods/wallets.js
  packages/core-api/lib/versions/utils.js
  packages/core-api/package.json
Labels: review

#1648 feat(core-database-postgres): store executed migrations in the database
  packages/core-database-postgres/CHANGELOG.md
  packages/core-database-postgres/lib/connection.js
  packages/core-database-postgres/lib/migrations/20180304100000-create-migrations-table.sql
  packages/core-database-postgres/lib/migrations/20180305300000-create-blocks-table.sql
  packages/core-database-postgres/lib/migrations/20181129400000-add-block_id-index-to-transactions-table.sql
  packages/core-database-postgres/lib/migrations/20181204100000-add-generator_public_key-index-to-blocks-table.sql
  packages/core-database-postgres/lib/migrations/20181204200000-add-transactions-timestamp-index-to-blocks-table.sql
  packages/core-database-postgres/lib/migrations/20181204300000-add-transactions-sender-and-receiver-indices-to-transactions-table.sql
  packages/core-database-postgres/lib/migrations/index.js
  packages/core-database-postgres/lib/models/index.js
  packages/core-database-postgres/lib/models/migration.js
  packages/core-database-postgres/lib/queries/index.js
  packages/core-database-postgres/lib/queries/migrations/create.sql
  packages/core-database-postgres/lib/queries/migrations/find.sql
  packages/core-database-postgres/lib/repositories/index.js
  packages/core-database-postgres/lib/repositories/migrations.js
Labels: review

#1649 chore(core-database-postgres): properly split migrations and name them
  packages/core-database-postgres/lib/migrations/20181204200000-add-timestamp-index-to-blocks-table.sql
  packages/core-database-postgres/lib/migrations/20181204300000-add-sender_public_key-index-to-transactions-table.sql
  packages/core-database-postgres/lib/migrations/20181204400000-add-recipient_id-index-to-transactions-table.sql
  packages/core-database-postgres/lib/migrations/index.js
Labels: review

#1650 chore(core): update changelog and bump version
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: review

#1651 Develop
  .circleci/config.yml
  packages/core-api/CHANGELOG.md
  packages/core-api/lib/defaults.js
  packages/core-api/lib/versions/1/methods/accounts.js
  packages/core-api/lib/versions/1/methods/blocks.js
  packages/core-api/lib/versions/1/methods/delegates.js
  packages/core-api/lib/versions/1/methods/transactions.js
  packages/core-api/lib/versions/2/methods/blocks.js
  packages/core-api/lib/versions/2/methods/delegates.js
  packages/core-api/lib/versions/2/methods/transactions.js
  packages/core-api/lib/versions/2/methods/votes.js
  packages/core-api/lib/versions/2/methods/wallets.js
  packages/core-api/lib/versions/utils.js
  packages/core-api/package.json
  packages/core-database-postgres/CHANGELOG.md
  packages/core-database-postgres/lib/connection.js
  packages/core-database-postgres/lib/migrations/20180304100000-create-migrations-table.sql
  packages/core-database-postgres/lib/migrations/20180305300000-create-blocks-table.sql
  packages/core-database-postgres/lib/migrations/20181129400000-add-block_id-index-to-transactions-table.sql
  packages/core-database-postgres/lib/migrations/20181204100000-add-generator_public_key-index-to-blocks-table.sql
  packages/core-database-postgres/lib/migrations/20181204200000-add-timestamp-index-to-blocks-table.sql
  packages/core-database-postgres/lib/migrations/20181204300000-add-sender_public_key-index-to-transactions-table.sql
  packages/core-database-postgres/lib/migrations/20181204400000-add-recipient_id-index-to-transactions-table.sql
  packages/core-database-postgres/lib/migrations/index.js
  packages/core-database-postgres/lib/models/index.js
  packages/core-database-postgres/lib/models/migration.js
  packages/core-database-postgres/lib/queries/index.js
  packages/core-database-postgres/lib/queries/migrations/create.sql
  packages/core-database-postgres/lib/queries/migrations/find.sql
  packages/core-database-postgres/lib/repositories/index.js
  packages/core-database-postgres/lib/repositories/migrations.js
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: review

#1653 fix(core-json-rpc): return the encoded WIF for BIP38 wallets instead of the encrypted WIF
  .circleci/config.yml
  packages/core-json-rpc/CHANGELOG.md
  packages/core-json-rpc/__tests__/wallets.test.js
  packages/core-json-rpc/lib/server/methods/blocks/latest.js
  packages/core-json-rpc/lib/server/methods/wallets/bip38/create.js
  packages/core-json-rpc/lib/server/methods/wallets/bip38/show.js
  packages/core-json-rpc/lib/server/utils/bip38-keys.js
  packages/core-json-rpc/lib/server/utils/decrypt-wif.js
Labels: review

#1658 fix(crypto): perform second signature checks for multi-signature wallets
  .circleci/config.yml
  packages/core-api/CHANGELOG.md
  packages/core-api/package.json
  packages/core-json-rpc/CHANGELOG.md
  packages/core-json-rpc/package.json
  packages/crypto/CHANGELOG.md
  packages/crypto/__tests__/handlers/transactions/second-signature.test.js
  packages/crypto/lib/handlers/transactions/handler.js
  packages/crypto/package.json
Labels: review

#1659 Develop
  packages/core-api/CHANGELOG.md
  packages/core-api/package.json
  packages/core-json-rpc/CHANGELOG.md
  packages/core-json-rpc/__tests__/wallets.test.js
  packages/core-json-rpc/lib/server/methods/blocks/latest.js
  packages/core-json-rpc/lib/server/methods/wallets/bip38/create.js
  packages/core-json-rpc/lib/server/methods/wallets/bip38/show.js
  packages/core-json-rpc/lib/server/utils/bip38-keys.js
  packages/core-json-rpc/lib/server/utils/decrypt-wif.js
  packages/core-json-rpc/package.json
  packages/crypto/CHANGELOG.md
  packages/crypto/__tests__/handlers/transactions/second-signature.test.js
  packages/crypto/lib/handlers/transactions/handler.js
  packages/crypto/package.json
Labels: review

#1660 chore(core): update changelog and bump version
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: review

#1661 chore(core): update changelog and bump version (#1660)
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: review

#1665 fix: update second signature tests
  .circleci/config.yml
  packages/core-api/__tests__/v2/handlers/transactions.test.js
  packages/core-api/lib/versions/2/transformers/transaction.js
  packages/core-transaction-pool-mem/__tests__/__fixtures__/transactions.js
  packages/crypto/__tests__/handlers/transactions/second-signature.test.js
  packages/crypto/lib/handlers/transactions/second-signature.js
Labels: review

#1668 chore(package): update snyk to version 1.116.0
  package.json
Labels: review

#1667 chore(package): update xstate to version 4.2.1
  packages/core-blockchain/package.json
  packages/core-test-utils/package.json
Labels: review

#1673 fix(core-api): ensure safe integer range for block height lookups
  .circleci/config.yml
  packages/core-api/CHANGELOG.md
  packages/core-api/lib/repositories/blocks.js
  packages/core-api/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  yarn.lock
Labels: review

#1674 Develop
  package.json
  packages/core-api/CHANGELOG.md
  packages/core-api/__tests__/v2/handlers/transactions.test.js
  packages/core-api/lib/repositories/blocks.js
  packages/core-api/lib/versions/2/transformers/transaction.js
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-test-utils/package.json
  packages/core-transaction-pool-mem/__tests__/__fixtures__/transactions.js
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/crypto/__tests__/handlers/transactions/second-signature.test.js
  packages/crypto/lib/handlers/transactions/second-signature.js
  yarn.lock
Labels: review

#1686 chore(core): raise the minimum version to 2.0.12
  .circleci/config.yml
  packages/core/lib/config/devnet/peers.json
  packages/core/lib/config/mainnet/peers.json
  packages/core/lib/config/testnet.1/peers.json
  packages/core/lib/config/testnet.2/peers.json
  packages/core/lib/config/testnet.live/peers.json
  packages/core/lib/config/testnet/peers.json
  packages/crypto/lib/networks/ark/devnet.json
Labels: review

#1695 refactor: improve remote address checks
  packages/core-http-utils/lib/plugins/whitelist.js
  packages/core-http-utils/package.json
  packages/core-p2p/CHANGELOG.md
  packages/core-p2p/lib/server/plugins/accept-request.js
  packages/core-p2p/lib/server/versions/1/handlers.js
  packages/core-p2p/lib/server/versions/internal/handlers/blocks.js
  packages/core-p2p/lib/utils/is-myself.js
  packages/core-p2p/package.json
  packages/core/CHANGELOG.md
  packages/core/lib/config/mainnet/peers.json
  packages/core/package.json
  yarn.lock
Labels: review

#1696 Develop
  packages/core-api/package.json
  packages/core-http-utils/lib/plugins/whitelist.js
  packages/core-http-utils/package.json
  packages/core-p2p/CHANGELOG.md
  packages/core-p2p/lib/server/plugins/accept-request.js
  packages/core-p2p/lib/server/versions/1/handlers.js
  packages/core-p2p/lib/server/versions/internal/handlers/blocks.js
  packages/core-p2p/lib/utils/is-myself.js
  packages/core-p2p/package.json
  packages/core/CHANGELOG.md
  packages/core/lib/config/devnet/peers.json
  packages/core/lib/config/mainnet/peers.json
  packages/core/lib/config/testnet.1/peers.json
  packages/core/lib/config/testnet.2/peers.json
  packages/core/lib/config/testnet.live/peers.json
  packages/core/lib/config/testnet/peers.json
  packages/core/package.json
  packages/crypto/lib/networks/ark/devnet.json
  yarn.lock
Labels: review

#1703 chore(package): update pino to version 5.10.1
  packages/core-deployer/package.json
  packages/core-tester-cli/package.json
Labels: review

#1689 fix(core-p2p): malformed condition for filtering peers
  packages/core-p2p/src/monitor.ts
Labels: review, typescript

#1655 perf(core-api): Use a faster alternative to derive an estimate
  .circleci/config.yml
  packages/core-api/__tests__/repositories/transactions.test.ts
  packages/core-api/__tests__/v2/handlers/transactions.test.ts
  packages/core-api/src/repositories/blocks.ts
  packages/core-api/src/repositories/repository.ts
  packages/core-api/src/repositories/transactions.ts
  packages/core-deployer/src/index.ts
  packages/core-p2p/src/monitor.ts
Labels: review, typescript

#1722 chore(package): update @types/better-sqlite3 to version 5.0.1
  packages/core-transaction-pool/package.json
Labels: review

#1724 chore(package): update husky to version 1.2.1
  package.json
  yarn.lock
Labels: review

#1723 chore(package): update @sentry/node to version 4.4.2
  packages/core-error-tracker-sentry/package.json
Labels: review

#1726 fix(core-p2p): get difference in milliseconds
  packages/core-p2p/src/court/guard.ts
Labels: review

#1729 fix(core-blockchain): add missing log statement for block verification
  .circleci/config.yml
  packages/core-blockchain/src/blockchain.ts
Labels: review

#1728 feat(core-api): allow filtering of transactions for wallet resources
  packages/core-api/src/versions/2/wallets/schema.ts
Labels: review

#1730 refactor(core-p2p): adjust some ban durations
  packages/core-p2p/__tests__/court/guard.test.ts
  packages/core-p2p/src/court/offences.ts
Labels: review

#1731 fix(core-database): delegate ordering
  packages/core-api/__tests__/v2/handlers/delegates.test.ts
  packages/core-database/__tests__/repositories/delegates.test.ts
  packages/core-database/src/repositories/delegates.ts
Labels: review

#1737 fix(core-p2p): call updateNetworkStatusIfNotEnoughPeers in the correct context
  packages/core-p2p/package.json
  packages/core-p2p/src/monitor.ts
  yarn.lock
Labels: review

#1738 refactor(core-p2p): replace the network update timeout with a period check
  .circleci/config.yml
  packages/core-blockchain/src/state-machine.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/monitor.ts
Labels: review

#1739 chore(core-transaction-pool): update better-sqlite3 to version 5.2.0
  packages/core-transaction-pool/package.json
Labels: review

#1742 test(core-utils): increase coverage
  packages/core-utils/__tests__/__support__/mocks/core-container-calculator.ts
  packages/core-utils/__tests__/bignumify.test.ts
  packages/core-utils/__tests__/delegate-calculator.test.ts
  packages/core-utils/src/bignumify.ts
  packages/core-utils/src/create-table.ts
  packages/core-utils/src/index.ts
Labels: review

#1743 test(core-debugger-cli): increase coverage
  packages/core-debugger-cli/__tests__/utils.test.ts
  packages/core-debugger-cli/src/utils.ts
  yarn.lock
Labels: review

#1744 test(crypto): increase identity coverage
  packages/crypto/__tests__/identities/address.test.ts
  packages/crypto/__tests__/identities/keys.test.ts
  packages/crypto/__tests__/identities/public-key.test.ts
Labels: review

#1745 test(crypto): increase handler coverage
  packages/crypto/__tests__/handlers/transactions/delegate-registration.test.ts
  packages/crypto/__tests__/handlers/transactions/delegate-resignation.test.ts
  packages/crypto/__tests__/handlers/transactions/handler.test.ts
  packages/crypto/__tests__/handlers/transactions/ipfs.test.ts
  packages/crypto/__tests__/handlers/transactions/multi-payment.test.ts
  packages/crypto/__tests__/handlers/transactions/multi-signature.test.ts
  packages/crypto/__tests__/handlers/transactions/second-signature.test.ts
  packages/crypto/__tests__/handlers/transactions/timelock-transfer.test.ts
  packages/crypto/__tests__/handlers/transactions/vote.test.ts
  packages/crypto/src/handlers/transactions/vote.ts
Labels: review

#1746 test(crypto): increase handler coverage
  packages/crypto/__tests__/handlers/transactions/delegate-registration.test.ts
  packages/crypto/__tests__/handlers/transactions/delegate-resignation.test.ts
  packages/crypto/__tests__/handlers/transactions/handler.test.ts
  packages/crypto/__tests__/handlers/transactions/ipfs.test.ts
  packages/crypto/__tests__/handlers/transactions/multi-payment.test.ts
  packages/crypto/__tests__/handlers/transactions/multi-signature.test.ts
  packages/crypto/__tests__/handlers/transactions/second-signature.test.ts
  packages/crypto/__tests__/handlers/transactions/timelock-transfer.test.ts
  packages/crypto/__tests__/handlers/transactions/vote.test.ts
  packages/crypto/src/handlers/transactions/handler.ts
  packages/crypto/src/handlers/transactions/multi-payment.ts
  packages/crypto/src/handlers/transactions/multi-signature.ts
Labels: review

#1747 test(crypto): increase multi signature/payment coverage
  packages/crypto/__tests__/handlers/transactions/multi-payment.test.ts
  packages/crypto/__tests__/handlers/transactions/multi-signature.test.ts
  packages/crypto/src/handlers/transactions/handler.ts
  packages/crypto/src/handlers/transactions/multi-payment.ts
Labels: review

#1824 docs: changelog and readme formatting
  CHANGELOG.md
  README.md
Labels: review

#1827 chore(package): update ajv to version 6.6.2
  packages/core-api/package.json
  packages/core-p2p/package.json
Labels: review

#1829 fix(core-p2p): prevent the list of peers to become too short
  .circleci/config.yml
  packages/core-blockchain/lib/state-machine.js
  packages/core-p2p/CHANGELOG.md
  packages/core-p2p/__tests__/monitor.test.js
  packages/core-p2p/lib/monitor.js
  packages/core-p2p/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
Labels: review

#1732 fix(core-blockchain): discard blocks containing forged tx and stop process queue on fork
  packages/core-blockchain/__tests__/blockchain.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/queue/index.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-blockchain/src/state-storage.ts
  packages/core-database-postgres/src/connection.ts
  packages/core-database/src/interface.ts
  packages/core-p2p/src/court/guard.ts
  packages/core-p2p/src/monitor.ts
Labels: review

#1837 feat(core-p2p): milestone hash
  packages/core-blockchain/src/state-machine.ts
  packages/core-container/src/config/index.ts
  packages/core-p2p/__tests__/court/guard.test.ts
  packages/core-p2p/src/court/guard.ts
  packages/core-p2p/src/court/index.ts
  packages/core-p2p/src/court/offences.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/server/plugins/set-headers.ts
Labels: review

#1836 fix: check semver validity
  packages/core-p2p/__tests__/court/guard.test.ts
  packages/core-p2p/src/court/guard.ts
Labels: review

#1831 fix(core-database): ensure that delegate search deals with "undefined" as username
  packages/core-database/__tests__/repositories/delegates.test.ts
  packages/core-database/src/repositories/delegates.ts
Labels: review

#1838 chore: update changelog
  CHANGELOG.md
Labels: review

#1839 docs: add a document to provide upgrade steps
  UPGRADE.md
Labels: review

#1840 chore: add dynamic fee config to default plugin.js files
  packages/core/src/config/devnet/plugins.js
  packages/core/src/config/mainnet/plugins.js
  packages/core/src/config/testnet/plugins.js
Labels: review

#1841 fix(core-p2p): add the milestoneHash as a required header
  packages/core-p2p/src/server/plugins/accept-request.ts
Labels: review

#1842 fix(core-p2p): check both the peer and the headers for the milestone hash
  packages/core-p2p/src/court/guard.ts
Labels: review

#1843 fix(core-p2p): check milestoneHash on the peer instance
  packages/core-p2p/src/monitor.ts
Labels: review

#1844 fix: get exceptions through the crypto config and handle them
  packages/core-database/src/interface.ts
  packages/core-database/src/wallet-manager.ts
  packages/crypto/src/networks/devnet/dynamicFees.json
  packages/crypto/src/networks/mainnet/dynamicFees.json
  packages/crypto/src/networks/testnet/dynamicFees.json
Labels: review

#1852 feat: allow searching wallets by several addresses at once
  packages/core-api/__tests__/v2/handlers/wallets.test.ts
  packages/core-api/src/versions/2/wallets/schema.ts
  packages/core-database/__tests__/repositories/utils/filter-rows.test.ts
  packages/core-database/__tests__/repositories/wallets.test.ts
  packages/core-database/src/repositories/utils/filter-rows.ts
  packages/core-database/src/repositories/wallets.ts
Labels: review

#1833 Package up core-logger types
  .gitignore
  packages/core-logger-winston/src/index.ts
  packages/core-logger/__tests__/__stubs__/logger.ts
  packages/core-logger/__tests__/manager.test.ts
  packages/core-logger/package.json
  packages/core-logger/src/index.ts
  packages/core-logger/src/plugin.ts
Labels: review

#1864 chore: remove core-deployer
  .circleci/config.yml
  packages/core-deployer/.gitattributes
  packages/core-deployer/README.md
  packages/core-deployer/__tests__/builder/genesis-block.test.ts
  packages/core-deployer/package.json
  packages/core-deployer/src/builder/genesis-block.ts
  packages/core-deployer/src/index.ts
  packages/core-deployer/src/logger.ts
  packages/core-deployer/src/schema.ts
  packages/core-deployer/src/utils.ts
  packages/core-deployer/tsconfig.json
  yarn.lock
Labels: review

#1865 chore: setup dependency update command
  package.json
  packages/core-api/__tests__/v2/handlers/wallets.test.ts
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: review

#1866 chore: add missing type declarations
  packages/core-http-utils/package.json
  packages/core-json-rpc/package.json
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/src/transport/codecs/ark-codec.ts
  packages/core-snapshots/src/transport/verification.ts
  packages/core-webhooks/src/server/handler.ts
  packages/core/package.json
  packages/crypto/__tests__/models/block.test.ts
  packages/crypto/package.json
  packages/crypto/src/crypto/crypto.ts
  packages/crypto/src/models/block.ts
  packages/crypto/src/models/transaction.ts
  yarn.lock
Labels: :memo: review

#1870 ignore: bootstrap files for coverage
  .codecov.yml
Labels: review

#1872 feat(core-api): allow searching by several addresses on `/api/transactions/search`
  .circleci/config.yml
  packages/core-api/__tests__/repositories/transactions.test.ts
  packages/core-api/__tests__/repositories/utils/build-filter-query.test.ts
  packages/core-api/__tests__/v2/handlers/transactions.test.ts
  packages/core-api/package.json
  packages/core-api/src/repositories/blocks.ts
  packages/core-api/src/repositories/transactions.ts
  packages/core-api/src/repositories/utils/build-filter-query.ts
  packages/core-api/src/versions/2/transactions/schema.ts
Labels: review

#1887 chore: export core-logger-winston types.
  packages/core-logger-winston/__tests__/logger.test.ts
  packages/core-logger-winston/package.json
  packages/core-logger-winston/src/driver.ts
  packages/core-logger-winston/src/index.ts
  packages/core-logger-winston/src/plugin.ts
  packages/core-logger/src/logger.ts
Labels: :man_technologist: typescript, review

#1873 refactor: add minimum of minFeeBroadcast for getFeeStatistics query
  packages/core-api/src/repositories/repository.ts
  packages/core-api/src/repositories/transactions.ts
  packages/core-graphql/src/repositories/repository.ts
  packages/core-graphql/src/repositories/transactions.ts
Labels: :man_technologist: enhancement, :man_technologist: refactor, review

#1919 fix(core-database-postgres): set last block of all delegates during SPV
  packages/core-database-postgres/src/queries/spv/last-forged-blocks.sql
  packages/core-database-postgres/src/spv.ts
Labels: :crossed_swords: do not merge

#1917 refactor(crypto): export type definitions
  packages/core-blockchain/src/blockchain.ts
  packages/core-p2p/src/server/versions/1/handlers.ts
  packages/crypto/package.json
  packages/crypto/src/builder/index.ts
  packages/crypto/src/builder/transactions/delegate-registration.ts
  packages/crypto/src/builder/transactions/delegate-resignation.ts
  packages/crypto/src/builder/transactions/ipfs.ts
  packages/crypto/src/builder/transactions/multi-payment.ts
  packages/crypto/src/builder/transactions/multi-signature.ts
  packages/crypto/src/builder/transactions/second-signature.ts
  packages/crypto/src/builder/transactions/timelock-transfer.ts
  packages/crypto/src/builder/transactions/transaction.ts
  packages/crypto/src/builder/transactions/transfer.ts
  packages/crypto/src/builder/transactions/vote.ts
  packages/crypto/src/client.ts
  packages/crypto/src/crypto/crypto.ts
  packages/crypto/src/crypto/hdwallet.ts
  packages/crypto/src/crypto/message.ts
  packages/crypto/src/crypto/slots.ts
  packages/crypto/src/handlers/transactions/multi-payment.ts
  packages/crypto/src/identities/address.ts
  packages/crypto/src/identities/keys.ts
  packages/crypto/src/identities/public-key.ts
  packages/crypto/src/identities/wif.ts
  packages/crypto/src/index.ts
  packages/crypto/src/managers/config.ts
  packages/crypto/src/models/delegate.ts
  packages/crypto/src/models/transaction.ts
  packages/crypto/src/models/wallet.ts
  packages/crypto/src/utils/format-arktoshi.ts
  packages/crypto/src/validation/engine.ts
Labels: review

#1916 refactor(core-p2p): simplify updatePeersOnMissingBlocks()
  packages/core-p2p/src/monitor.ts
Labels: :crossed_swords: do not merge, review
