Repository ArkEcosystem/core, pull requests merged in 2018-07, with the labels that each got.

#730 P2P updates and tests and bugsfixes
  packages/core-p2p/__tests__/server/internal.test.js
  packages/core-p2p/__tests__/utils/is-myself.test.js
  packages/core-p2p/lib/monitor.js
  packages/core-p2p/lib/server/versions/internal/handlers.js
  packages/core-p2p/lib/utils/is-myself.js
Labels: bug, test

#741 State machine rebuild chain fix
  packages/core-blockchain/lib/blockchain.js
  packages/core-blockchain/lib/machines/actions/rebuild-from-network.js
  packages/core-blockchain/lib/machines/blockchain.js
  packages/core-blockchain/lib/state-machine.js
Labels: bug

#696 Add instructions to remove unnecessary texts on the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: discussion
