Repository ArkEcosystem/core, pull requests merged in 2019-09, with the labels that each got.

#2904 fix(core-blockchain): only shift milestoneHeights[] if at that height
  packages/core-blockchain/src/blockchain.ts
Labels: Complexity: Low, Type: Bugfix

#2906 fix(core-api): return block timestamp for v2 transactions
  packages/core-api/src/handlers/transactions/transformer.ts
Labels: Complexity: Low, Type: Bugfix

#2907 Backport bug fixes to master
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-webhooks/conditions.test.ts
  packages/core-p2p/src/enums.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core-p2p/src/socket-server/worker.ts
  packages/core-webhooks/src/conditions.ts
  packages/crypto/src/validation/index.ts
Labels: Complexity: Medium

#2908 release: 2.5.24
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2909 fix(core-p2p): disconnect if api reports different network
  __tests__/helpers/peers.ts
  __tests__/integration/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/mocks/core-container.ts
  __tests__/unit/core-p2p/mocks/event-emitter.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/utils.test.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-processor.ts
Labels: Complexity: Low, Type: Bugfix

#2911 misc(core-p2p): accept prerelease version
  packages/core-p2p/src/utils/is-valid-version.ts
Labels: Complexity: Low

#2910 perf(core-database-postgres): speed up nonce checks at DB level
  packages/core-database-postgres/src/migrations/20190905000000-change-set_row_nonce-to-use-max-nonce.sql
  packages/core-database-postgres/src/migrations/index.ts
Labels: Complexity: Low, Type: Performance

#2912 refactor(core-p2p): share rate limiter between workers
  packages/core-interfaces/src/core-p2p/network-monitor.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/rate-limiter.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-p2p/src/socket-server/worker.ts
  packages/core-p2p/src/utils/build-rate-limiter.ts
Labels: Complexity: Medium, Type: Refactor

#2903 misc(core-blockchain): log the reason for discarding a block
  packages/core-blockchain/src/blockchain.ts
  packages/core-utils/src/is-block-chained.ts
Labels: Complexity: Low, Status: Needs Changes

#2917 test: add e2e tests for more multisignature cases including htlc
  __tests__/e2e/tests/scenarios/scenario1/config.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/1.create-multisig-registration.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/2.check-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/3.transfer-multisig-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/4.create-lock-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/5.create-claim-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/6.check-multisig.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/config.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/shared.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/utils.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/1.create-multisig-registration.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/2.check-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/3.transfer-multisig-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/4.create-lock-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/5.create-refund-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/6.check-multisig.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/config.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/shared.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/utils.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/4.create-valid-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/5.create-invalid-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/6.check-multisig.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/config.js
Labels: Complexity: High, Test: Unit

#2918 fix(core-utils): use supply calculator in delegate approval calculation
  __tests__/unit/core-utils/mocks/core-container-calculator.ts
  packages/core-utils/src/delegate-calculator.ts
Labels: Complexity: Low, Type: Bugfix

#2916 refactor(core-transaction-pool): clear cached transaction ids after accepting block
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/unit/core-blockchain/stubs/state-storage.ts
  __tests__/unit/core-database/__fixtures__/state-storage-stub.ts
  __tests__/unit/core-state/__fixtures__/state-storage-stub.ts
  __tests__/unit/core-state/stores/state.test.ts
  __tests__/unit/core-transaction-pool/mocks/state.ts
  packages/core-interfaces/src/core-state/state-store.ts
  packages/core-state/src/stores/state.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/processor.ts
Labels: Complexity: Medium, Type: Refactor

#2920 fix(core-state): `buildVoteBalances` called too early
  packages/core-database-postgres/src/state-builder.ts
  packages/core-transactions/src/handlers/vote.ts
Labels: Complexity: Low, Type: Bugfix

#2914 refactor(core-blockchain): break loop if block contains v1 transaction
  packages/core-blockchain/src/processor/block-processor.ts
Labels: Complexity: Low, Type: Refactor

#2921 fix(core-state): `buildDelegateRanking` called too early
  packages/core-database-postgres/src/state-builder.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
Labels: Complexity: Low, Type: Bugfix

#2929 feat(core-api): add `/node/debug` endpoint
  packages/core-api/src/handlers/node/controller.ts
  packages/core-api/src/handlers/node/routes.ts
  packages/core-api/src/handlers/node/schema.ts
Labels: Complexity: Low, Type: Feature

#2928 fix(crypto): use 2 bytes to store number of payments
  __tests__/functional/transaction-forging/multi-payment.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/multi-payment.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/transactions/schemas.test.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/transactions/builders/transactions/multi-payment.ts
  packages/crypto/src/transactions/types/multi-payment.ts
Labels: Complexity: Low, Type: Bugfix

#2932 fix(core-database): add missing typeGroup and emit StateStarting
  __tests__/utils/config/testnet/plugins.js
  __tests__/utils/config/unitnet/plugins.js
  packages/core-database-postgres/src/migrations/20190917000000-add-asset-column-to-transactions-table.sql
  packages/core-database-postgres/src/migrations/index.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/queries/state-builder/delegates.sql
  packages/core-database-postgres/src/queries/state-builder/ipfs.sql
  packages/core-database-postgres/src/queries/state-builder/multi-signatures.sql
  packages/core-database-postgres/src/queries/state-builder/received-transactions.sql
  packages/core-database-postgres/src/queries/state-builder/second-signatures.sql
  packages/core-database/src/database-service.ts
  packages/core-event-emitter/src/index.ts
  packages/core-marketplace/package.json
  packages/core-marketplace/src/plugin.ts
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
Labels: Complexity: Low, Type: Bugfix

#2919 fix(core-transactions): reject delegate resignation if not enough inactive delegates
  __tests__/functional/transaction-forging/delegate-resignation.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-transaction-pool/src/wallet-manager.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
Labels: Type: Bugfix

#2926 fix(core-api): wallet search
  __tests__/integration/core-api/services/transaction-transformed.json
  __tests__/integration/core-api/utils.ts
  packages/core-api/src/handlers/delegates/schema.ts
  packages/core-api/src/handlers/delegates/transformer.ts
  packages/core-api/src/handlers/transactions/transformer.ts
  packages/core-api/src/handlers/wallets/transformer.ts
  packages/core-database/package.json
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/repositories/utils/sort-entries.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  yarn.lock
Labels: Complexity: Medium, Type: Bugfix

#2933 fix(core-database-postgres): use postgresql-9.5 compatible syntax
  packages/core-database-postgres/src/migrations/20190905000000-change-set_row_nonce-to-use-max-nonce.sql
Labels: Complexity: Low, Type: Bugfix

#2915 refactor(core-transactions): htlc implementation
  __tests__/functional/transaction-forging/htlc-claim.test.ts
  __tests__/functional/transaction-forging/htlc-lock.test.ts
  __tests__/functional/transaction-forging/htlc-refund.test.ts
  __tests__/unit/core-state/wallets/wallet-manager-htlc.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/htlc-lock.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/transactions/schemas.test.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/crypto/src/enums.ts
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/transactions/types/enums.ts
  packages/crypto/src/transactions/types/htlc-lock.ts
  packages/crypto/src/transactions/types/index.ts
  packages/crypto/src/transactions/types/ipfs.ts
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: High, Type: Refactor

#2936 fix(crypto): htlc lock buffer allocation
  packages/crypto/src/transactions/types/htlc-lock.ts
Labels: Complexity: Low, Status: Contributor Approved

#2937 fix(core-transaction-pool): sort by fee, nonce
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-transaction-pool/src/memory.ts
Labels: Complexity: Medium, Type: Bugfix

#2938 refactor(crypto): make error more verbose
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/transactions/factory.test.ts
  __tests__/unit/crypto/transactions/utils.test.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/transactions/deserializer.ts
  packages/crypto/src/transactions/factory.ts
Labels: Complexity: Low, Type: Refactor

#2945 fix(core-p2p): terminate connection when not authorized
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/socket-server/worker.test.ts
  packages/core-p2p/src/enums.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#2944 fix: htlc refund handler to use performGenericWalletChecks (+ fix e2e tests)
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/1.create-lock-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/1.create-lock-txs.action.js
  packages/core-transactions/src/handlers/htlc-refund.ts
Labels: Complexity: Low, Type: Bugfix

#2946 release: 2.5.25
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: High, Type: Release

#2942 perf: use lodash to efficiently remove forged transactions
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Performance

#2941 perf: Avoid O(m*n) when filtering pool txs and simplify the code
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Performance

#2943 chore(core-transactions): elaborate the unexpected nonce error
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/handlers/transaction.ts
Labels: Complexity: Low, Type: Task

#2953 Should not exit on `timedatectl` error.
  install.sh
Labels: Complexity: Low, Type: Bugfix

#2950 test: extend the TempWalletManager test to test the TempWalletManager class
  __tests__/unit/core-state/wallets/temp-wallet-manager.test.ts
Labels: Complexity: Low, Test: Unit

#2955 ci: setup github action workflows for testing and benchmarking
  .circleci/config.yml
  .github/workflows/benchmark.yml
  .github/workflows/test.yml
Labels: Complexity: Medium

#2956 ci: use different test coverage directories for each type
  .github/workflows/test.yml
Labels: Complexity: Low

#2957 chore: add vim's temporary files to .gitignore
  .gitignore
Labels: Complexity: Low

#2947 fix(core-state): index recipient wallets during bootstrap
  packages/core-transaction-pool/src/connection.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  yarn.lock
Labels: Complexity: Low, Type: Bugfix

#2962 refactor(core-p2p): make peer reply errors less verbose
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Type: Refactor

#2963 ci: split functional job into 1 job per type
  .github/workflows/functional.yml
  .github/workflows/test.yml
Labels: Complexity: High

#2961 refactor(crypto): change maximum recipients of multipayment via milestone
  __tests__/unit/core-container/__stubs__/config/milestones.json
  __tests__/unit/crypto/transactions/schemas.test.ts
  packages/crypto/src/networks/devnet/milestones.json
  packages/crypto/src/networks/mainnet/milestones.json
  packages/crypto/src/networks/testnet/milestones.json
  packages/crypto/src/networks/unitnet/milestones.json
  packages/crypto/src/transactions/types/schemas.ts
  packages/crypto/src/validation/keywords.ts
Labels: Complexity: Low, Type: Refactor

#2958 test(e2e): No need to run as root the chmod command when modifying own's files
  __tests__/e2e/README.md
Labels: Complexity: Low

#2965 chore: drop node 11 support
  .github/workflows/test.yml
  __tests__/e2e/bin/e2e
  __tests__/e2e/lib/config/docker/Dockerfile-11
  __tests__/e2e/lib/utils/sync.sh
  install.sh
Labels: Complexity: Medium, Type: Task

#2964 ci: setup github action workflow for e2e tests
  .circleci/config.yml
  .github/workflows/benchmark.yml
  .github/workflows/functional.yml
  .github/workflows/test.yml
  __tests__/e2e/lib/config/docker/Dockerfile-10.x
  __tests__/e2e/lib/config/docker/Dockerfile-12.x
  __tests__/e2e/lib/generate-files.js
Labels: Complexity: Medium, Status: Needs Review

#2949 refactor: strengthen a nonce check in performGenericWalletChecks()
  __tests__/integration/core-transaction-pool/processor.test.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/handlers/transaction.ts
Labels: Complexity: Medium, Type: Refactor

#2966 ci: temporarily disable pull_request.synchronize event
  .github/workflows/functional.yml
  .github/workflows/test.yml
Labels: Complexity: Low

#2951 refactor(pool): remove unnecessary check from validateTransactions()
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Refactor

#2959 fix(core-transactions): update wallet nonce when applying v1 transaction
  .github/workflows/benchmark.yml
  .github/workflows/functional.yml
  .github/workflows/test.yml
  __tests__/e2e/lib/utils/testnet.js
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/transaction.ts
Labels: Complexity: Low, Type: Bugfix

#2971 chore: remove trailing whitespace
  __tests__/e2e/lib/config/nginx/docker-compose.yml
  __tests__/e2e/lib/config/nginx/nginx.conf
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/1.create-lock-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/2.check-lock.test.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/4.check-claim.test.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/2.check-lock.test.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/4.check-refund.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/2.check-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/4.create-lock-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/5.create-claim-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-claim/6.check-multisig.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/2.check-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/4.create-lock-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/5.create-refund-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisig-htlc-refund/6.check-multisig.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/2.check-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/4.create-valid-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/5.create-invalid-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/6.check-multisig.test.js
  docker/production/devnet/docker-compose-build.yml
  docker/production/devnet/docker-compose.yml
  docker/production/mainnet/docker-compose-build.yml
  docker/production/mainnet/docker-compose.yml
  docker/production/purge_all.sh
  packages/core-database-postgres/src/queries/transactions/fee-statistics.sql
  packages/crypto/rollup.config.js
  scripts/docker/templates/testnet/purge_all.sh
Labels: Complexity: Medium, Type: Task

#2960 feat: expose `isValidPeer` via ajv format rule
  __tests__/functional/transaction-forging/bridgechain-update.test.ts
  __tests__/unit/core-marketplace/builders/bridgechain-registration.test.ts
  __tests__/unit/core-marketplace/builders/bridgechain-update.test.ts
  __tests__/unit/core-marketplace/helper.ts
  __tests__/unit/core-marketplace/transactions/bridgechain-registration.test.ts
  __tests__/unit/core-marketplace/transactions/bridgechain-update.test.ts
  __tests__/unit/crypto/utils/is-valid-peer.test.ts
  packages/core-marketplace/src/transactions/utils/bridgechain-schemas.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/utils/index.ts
  packages/crypto/package.json
  packages/crypto/src/utils/index.ts
  packages/crypto/src/utils/is-valid-peer.ts
  packages/crypto/src/validation/formats.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#2952 fix: range selection in pool's getTransactions()
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Bugfix

#2970 fix(core-blockchain): round deletion during rollback
  __tests__/unit/core-blockchain/machines/actions/fork.test.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  packages/core-blockchain/src/machines/actions/fork.ts
  packages/core-blockchain/src/machines/blockchain.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database-postgres/src/postgres-connection.ts
Labels: Complexity: Medium, Type: Bugfix

#2940 feat(core-api): endpoints for locks/businesses/bridgechains
  __tests__/integration/core-api/handlers/locks.test.ts
  __tests__/integration/core-api/utils.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
  __tests__/unit/core-state/wallets/wallet-index.test.ts
  packages/core-api/src/defaults.ts
  packages/core-api/src/handlers/bridgechains/controller.ts
  packages/core-api/src/handlers/bridgechains/index.ts
  packages/core-api/src/handlers/bridgechains/methods.ts
  packages/core-api/src/handlers/bridgechains/routes.ts
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-api/src/handlers/bridgechains/transformer.ts
  packages/core-api/src/handlers/businesses/controller.ts
  packages/core-api/src/handlers/businesses/index.ts
  packages/core-api/src/handlers/businesses/methods.ts
  packages/core-api/src/handlers/businesses/routes.ts
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-api/src/handlers/businesses/transformer.ts
  packages/core-api/src/handlers/delegates/methods.ts
  packages/core-api/src/handlers/index.ts
  packages/core-api/src/handlers/locks/controller.ts
  packages/core-api/src/handlers/locks/index.ts
  packages/core-api/src/handlers/locks/methods.ts
  packages/core-api/src/handlers/locks/routes.ts
  packages/core-api/src/handlers/locks/schema.ts
  packages/core-api/src/handlers/locks/transformer.ts
  packages/core-api/src/handlers/wallets/controller.ts
  packages/core-api/src/handlers/wallets/methods.ts
  packages/core-api/src/handlers/wallets/routes.ts
  packages/core-api/src/handlers/wallets/schema.ts
  packages/core-api/src/services/transformer.ts
  packages/core-blockchain/src/replay/memory-database-service.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/database-service-factory.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/index.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/repositories/utils/filter-rows.ts
  packages/core-database/src/repositories/utils/search-entries.ts
  packages/core-database/src/repositories/utils/sort-entries.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/delegates-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/index.ts
  packages/core-interfaces/src/core-database/business-repository/wallets-business-repository.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  packages/core-interfaces/src/core-database/database-repository/wallets-repository.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-marketplace/src/handlers/bridgechain-registration.ts
  packages/core-marketplace/src/handlers/business-registration.ts
  packages/core-state/src/wallets/wallet-index.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2973 fix(core-snapshots): remove bogus skipRoundRows
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/db/queries/rounds/round-range.sql
  packages/core-snapshots/src/utils.ts
Labels: Complexity: Low, Type: Bugfix

#2948 refactor(core-transaction-pool): don't accept expired v1 transactions
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-utils/src/expiration-calculator.ts
  packages/core-utils/src/index.ts
Labels: Complexity: Medium, Status: Contributor Approved, Status: Needs Changes, Type: Refactor

#2972 feat(core): allow CLI command configurations
  __tests__/unit/core-container/__stubs__/config/app.js
  __tests__/utils/config/testnet/app.js
  __tests__/utils/config/unitnet/app.js
  packages/core-api/src/handlers/index.ts
  packages/core/bin/config/devnet/app.js
  packages/core/bin/config/mainnet/app.js
  packages/core/bin/config/testnet/app.js
  packages/core/package.json
  packages/core/src/commands/core/run.ts
  packages/core/src/commands/forger/run.ts
  packages/core/src/commands/relay/run.ts
  packages/core/src/helpers/replay.ts
  packages/core/src/helpers/snapshot.ts
  packages/core/src/utils.ts
Labels: Complexity: High, Type: Feature

#2976 feat(core-api): find htlc unlock transactions
  __tests__/integration/core-api/handlers/locks.test.ts
  packages/core-api/src/defaults.ts
  packages/core-api/src/handlers/locks/controller.ts
  packages/core-api/src/handlers/locks/methods.ts
  packages/core-api/src/handlers/locks/routes.ts
  packages/core-api/src/handlers/locks/schema.ts
  packages/core-database-postgres/src/queries/index.ts
  packages/core-database-postgres/src/queries/transactions/find-by-htlc-locks.sql
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  packages/core-snapshots/src/db/index.ts
Labels: Complexity: Medium, Type: Feature

#2996 fix(core-snapshots): export/import transactions' type_group
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/db/queries/transactions/timestamp-range.sql
Labels: Complexity: Low, Type: Bugfix

#2979 feat(crypto): add multiSignWif to transaction builder
  __tests__/unit/crypto/transactions/builders/transactions/__shared__/transaction-builder.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
Labels: Complexity: Medium, Type: Feature

#2980 refactor(core-magistrate-crypto): export only namespaces
  __tests__/unit/core-magistrate/builders/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate/builders/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate/builders/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/builders/business-registration.test.ts
  __tests__/unit/core-magistrate/builders/business-resignation.test.ts
  __tests__/unit/core-magistrate/builders/business-update.test.ts
  __tests__/unit/core-magistrate/handlers/business-registration.test.ts
  __tests__/unit/core-magistrate/handlers/handlers.test.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/transactions/business-registration.test.ts
  __tests__/unit/core-magistrate/transactions/business-resgination.test.ts
  __tests__/unit/core-magistrate/transactions/business-update.test.ts
  packages/core-api/src/handlers/bridgechains/transformer.ts
  packages/core-api/src/handlers/businesses/transformer.ts
  packages/core-magistrate-crypto/src/index.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
Labels: Complexity: Medium, Type: Refactor
