Repository ArkEcosystem/core, pull requests merged in 2019-12, with the labels that each got.

#3311 feat(core-p2p): increase maximum token symbol length
  packages/core-p2p/src/schemas.ts
Labels: Bounty: Tier 6, Complexity: Low, Status: Collaborator Approved, Type: Feature

#3321 fix(core): fix "file path exists" error
  packages/core/src/commands/network/generate.ts
Labels: Bounty: Tier 6, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3317 chore: add tmp-shm and tmp-wal to .gitignore
  .gitignore
Labels: Bounty: Tier 6, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3310 refactor(core-api): accept address, publicKey, delegate name as business id
  __tests__/integration/core-api/handlers/businesses.test.ts
  packages/core-api/src/handlers/businesses/methods.ts
  packages/core-api/src/handlers/businesses/schema.ts
Labels: Bounty: Tier 4, Complexity: Medium, Status: Collaborator Approved, Type: Refactor

#3320 fix(core-database): handle forgedTotal and voteBalance in orderBy query param
  packages/core-database/src/repositories/utils/search-entries.ts
  packages/core-database/src/repositories/utils/sort-entries.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3323 chore: document canEnterTransactionPool()
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/interfaces.ts
Labels: Complexity: Low, Type: Task

#3313 fix(core-api): businesses/bridgechains search by name
  packages/core-api/src/handlers/blocks/schema.ts
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-api/src/handlers/delegates/schema.ts
  packages/core-api/src/handlers/locks/schema.ts
  packages/core-api/src/handlers/shared/schemas/address.ts
  packages/core-api/src/handlers/shared/schemas/generic-name.ts
  packages/core-api/src/handlers/shared/schemas/index.ts
  packages/core-api/src/handlers/shared/schemas/public-key.ts
  packages/core-api/src/handlers/transactions/schema.ts
  packages/core-api/src/handlers/votes/schema.ts
  packages/core-api/src/handlers/wallets/schema.ts
  packages/crypto/src/validation/schemas.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3331 feat(core-p2p): improve incoming WS message check + IP banning on worker
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Feature

#3332 release: 2.5.30
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3338 fix(crypto): throw error instead of omitting long vendorField values
  __tests__/unit/crypto/transactions/builders/transactions/transfer.test.ts
  __tests__/unit/crypto/transactions/schemas.test.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3334 fix(core): network generate command
  packages/core/src/commands/network/generate.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved

#3341 fix(core-database): don't assume blocksInCurrentRound is defined
  packages/core-database/src/database-service.ts
Labels: Complexity: Low, Type: Bugfix

#3344 refactor(core-api): add shared username schema
  packages/core-api/src/handlers/delegates/schema.ts
  packages/core-api/src/handlers/shared/schemas/index.ts
  packages/core-api/src/handlers/shared/schemas/username.ts
  packages/core-api/src/handlers/shared/schemas/wallet-id.ts
  packages/core-api/src/handlers/wallets/schema.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Refactor

#3336 fix(core-state): use parent findByPublicKey method for temp-wallet-manager
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  packages/core-state/src/wallets/temp-wallet-manager.ts
Labels: Complexity: Low, Type: Bugfix

#3342 refactor: make the canEnterTransactionPool() interface more robust
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/interfaces.ts
Labels: Complexity: Medium, Type: Refactor

#3350 fix(core magistrate): business/bridgechain update handlers - revertForSender
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/functional/transaction-forging/bridgechain-update.test.ts
  __tests__/functional/transaction-forging/business-update.test.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
Labels: Complexity: High, Type: Bugfix

#3352 core-p2p: relax postBlock rate limit
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  packages/core-p2p/src/utils/build-rate-limiter.ts
Labels: Complexity: Low

#3345 refactor(crypto): throw error if multi payment has less than two payments
  __tests__/unit/crypto/transactions/builders/transactions/multi-payment.test.ts
  __tests__/unit/crypto/transactions/schemas.test.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/transactions/builders/transactions/multi-payment.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Refactor

#3287 refactor: align maxPayload / maxTransactionBytes values
  __tests__/integration/core-forger/client.test.ts
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-forger/manager.test.ts
  __tests__/unit/core-p2p/socket-server/versions/peer/index.test.ts
  __tests__/unit/core-p2p/socket-server/worker.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/utils.test.ts
  __tests__/unit/crypto/blocks/block.test.ts
  __tests__/unit/crypto/blocks/deserializer.test.ts
  packages/core-forger/src/client.ts
  packages/core-forger/src/manager.ts
  packages/core-interfaces/src/core-p2p/peer-communicator.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/schemas.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-p2p/src/socket-server/worker.ts
  packages/core-p2p/src/utils/index.ts
  packages/core-p2p/src/utils/sc-codec.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transaction-pool/src/utils.ts
  packages/crypto/src/blocks/block.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#3319 feat(core-api): stricter resource-based orderBy schema
  packages/core-api/src/handlers/blocks/schema.ts
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-api/src/handlers/delegates/schema.ts
  packages/core-api/src/handlers/locks/schema.ts
  packages/core-api/src/handlers/peers/schema.ts
  packages/core-api/src/handlers/shared/iteratees.ts
  packages/core-api/src/handlers/shared/schemas/order-by.ts
  packages/core-api/src/handlers/transactions/schema.ts
  packages/core-api/src/handlers/votes/schema.ts
  packages/core-api/src/handlers/wallets/schema.ts
  packages/core-database/src/repositories/utils/search-entries.ts
  packages/core-database/src/repositories/utils/sort-entries.ts
Labels: Complexity: Medium, Status: Contributor Approved, Status: Needs Review, Type: Feature

#3354 fix(core-p2p): handle disconnect packets
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#3355 release: 2.5.31
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3356 release: 2.6.0-next.7
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3358 refactor(core-p2p): discover peers when checking network health
  __tests__/unit/core-p2p/network-monitor.test.ts
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Low, Type: Refactor

#3353 refactor: enable htlc types via dedicated milestone
  __tests__/helpers/transaction-factory.ts
  __tests__/unit/core-state/wallets/wallet-manager-htlc.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  packages/core-database/src/database-service.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core/bin/config/devnet/peers.json
  packages/crypto/src/networks/devnet/milestones.json
  packages/crypto/src/networks/testnet/milestones.json
  packages/crypto/src/networks/unitnet/milestones.json
  packages/crypto/src/transactions/types/htlc-claim.ts
  packages/crypto/src/transactions/types/htlc-lock.ts
  packages/crypto/src/transactions/types/htlc-refund.ts
Labels: Complexity: Medium, Type: Refactor

#3359 fix(core-p2p): master merge fixes for core-p2p worker
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#3360 refactor: call `checkNetworkHealth` more deterministically
  packages/core-blockchain/src/blockchain.ts
  packages/core-state/src/stores/state.ts
Labels: Complexity: Low, Type: Refactor
