Repository ArkEcosystem/core, pull requests merged in 2019-02, with the labels that each got.

#2046 fix(core-blockchain): invalid timestamp check
  packages/core-blockchain/__tests__/processor/block-processor.test.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2047 fix(core-p2p): check if state is available
  packages/core-p2p/src/court/guard.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2049 refactor(core-debugger-cli): replace commander.js with @oclif
  packages/core-debugger-cli/__tests__/commands/deserialize.test.ts
  packages/core-debugger-cli/__tests__/commands/identity.test.ts
  packages/core-debugger-cli/__tests__/commands/serialize.test.ts
  packages/core-debugger-cli/__tests__/commands/verify-second.test.ts
  packages/core-debugger-cli/__tests__/commands/verify.test.ts
  packages/core-debugger-cli/bin/debugger
  packages/core-debugger-cli/bin/run
  packages/core-debugger-cli/bin/run.cmd
  packages/core-debugger-cli/package.json
  packages/core-debugger-cli/src/commands/command.ts
  packages/core-debugger-cli/src/commands/deserialize.ts
  packages/core-debugger-cli/src/commands/identity.ts
  packages/core-debugger-cli/src/commands/serialize.ts
  packages/core-debugger-cli/src/commands/verify-second.ts
  packages/core-debugger-cli/src/commands/verify.ts
  packages/core-debugger-cli/src/index.ts
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  yarn.lock
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#2051 refactor(core-tester-cli): replace commander.js with @oclif
  packages/core-api/src/index.ts
  packages/core-api/src/plugin.ts
  packages/core-api/src/repositories/index.ts
  packages/core-api/src/server.ts
  packages/core-snapshots/src/index.ts
  packages/core-tester-cli/__tests__/commands/command.test.ts
  packages/core-tester-cli/__tests__/commands/delegate-registration.test.ts
  packages/core-tester-cli/__tests__/commands/second-signature.test.ts
  packages/core-tester-cli/__tests__/commands/transfer.test.ts
  packages/core-tester-cli/__tests__/commands/vote.test.ts
  packages/core-tester-cli/__tests__/shared.ts
  packages/core-tester-cli/__tests__/utils.test.ts
  packages/core-tester-cli/bin/run
  packages/core-tester-cli/bin/run.cmd
  packages/core-tester-cli/package.json
  packages/core-tester-cli/src/commands/command.ts
  packages/core-tester-cli/src/commands/delegate-registration.ts
  packages/core-tester-cli/src/commands/multi-signature.ts
  packages/core-tester-cli/src/commands/second-signature.ts
  packages/core-tester-cli/src/commands/transfer.ts
  packages/core-tester-cli/src/commands/vote.ts
  packages/core-tester-cli/src/flags.ts
  packages/core-tester-cli/src/index.ts
  packages/core-tester-cli/src/utils.ts
  packages/core/src/utils.ts
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#2052 refactor: move genesisBlock to network config and remove extraneous config
  packages/core-container/__tests__/__stubs__/config/dynamicFees.json
  packages/core-container/__tests__/config/loaders/file-loader.test.ts
  packages/core-container/src/config/index.ts
  packages/core-container/src/config/network.ts
  packages/core-container/src/config/schema.ts
  packages/core/src/config/testnet.1/delegates.json
  packages/core/src/config/testnet.1/peers.json
  packages/core/src/config/testnet.1/plugins.js
  packages/core/src/config/testnet.2/delegates.json
  packages/core/src/config/testnet.2/genesisBlock.json
  packages/core/src/config/testnet.2/peers.json
  packages/core/src/config/testnet.2/plugins.js
  packages/core/src/config/testnet.live/delegates.json
  packages/core/src/config/testnet.live/genesisBlock.json
  packages/core/src/config/testnet.live/peers.json
  packages/core/src/config/testnet.live/plugins.js
  packages/core/src/config/testnet/genesisBlock.json
  packages/crypto/__tests__/managers/config.test.ts
  packages/crypto/__tests__/models/block.test.ts
  packages/crypto/src/managers/config.ts
  packages/crypto/src/networks/devnet/genesisBlock.json
  packages/crypto/src/networks/devnet/index.ts
  packages/crypto/src/networks/mainnet/genesisBlock.json
  packages/crypto/src/networks/mainnet/index.ts
  packages/crypto/src/networks/testnet/genesisBlock.json
  packages/crypto/src/networks/testnet/index.ts
  packages/crypto/src/networks/unitnet/genesisBlock.json
  packages/crypto/src/networks/unitnet/index.ts
  scripts/upgrade/upgrade.js
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#2057 fix(crypto): disable multisig
  packages/crypto/__tests__/builder/transactions/multi-signature.test.ts
  packages/crypto/__tests__/handlers/transactions/multi-signature.test.ts
  packages/crypto/__tests__/models/transaction.test.ts
  packages/crypto/src/handlers/transactions/handler.ts
  packages/crypto/src/models/transaction.ts
  packages/crypto/src/networks/devnet/exceptions.json
  packages/crypto/src/networks/mainnet/exceptions.json
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#2059 misc: add github templates for docs, security and support
  .github/ISSUE_TEMPLATE/Documentation_issue.md
  .github/ISSUE_TEMPLATE/Security_vulnerabilities.md
  .github/ISSUE_TEMPLATE/Support_question.md
Labels: Complexity: Low, Status: Needs Review, Type: Maintenance

#2060 chore: few upgrade script fixes
  scripts/upgrade.sh
  scripts/upgrade/upgrade.js
Labels: Complexity: Low, Status: Needs Review, Type: Task

#2061 fix(core-p2p): return an empty array if the peers cache parsing fails
  packages/core-p2p/src/utils/restore-peers.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2058 fix(core-api): always sort transactions by sequence and the requested field
  packages/core-api/src/repositories/transactions.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2066 test: core-blockchain coverage
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/generateConfig.js
  .circleci/rebuild-db.sh
  packages/core-blockchain/__tests__/blockchain-networkStart.test.ts
  packages/core-blockchain/__tests__/blockchain.test.ts
  packages/core-blockchain/__tests__/processor/block-processor.test.ts
  packages/core-blockchain/__tests__/processor/handlers/accept-handler.test.ts
  packages/core-blockchain/__tests__/processor/handlers/exception-handler.test.ts
  packages/core-blockchain/__tests__/processor/handlers/unchained-handler.test.ts
  packages/core-blockchain/__tests__/queue/interface.test.ts
  packages/core-blockchain/__tests__/queue/process.test.ts
  packages/core-blockchain/__tests__/queue/rebuild.test.ts
  packages/core-blockchain/__tests__/state-machine.test.ts
  packages/core-blockchain/__tests__/state-storage.test.ts
  packages/core-blockchain/__tests__/utils/tick-sync-tracker.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database-postgres/__tests__/connection.test.ts
  packages/core-jest-matchers/__tests__/blockchain/dispatch.test.ts
  packages/core-jest-matchers/src/blockchain/dispatch.ts
Labels: Complexity: Undetermined, Status: Needs Review, Test: Unit

#2065 chore(docker): rename development to unitnet
  .gitignore
  install.sh
  scripts/docker/templates/development/purge.sh
  scripts/docker/templates/mainnet/docker-compose.yml
  scripts/docker/templates/unitnet/docker-compose.yml
  scripts/docker/templates/unitnet/purge.sh
Labels: Complexity: Low, Status: Needs Review, Type: Task

#2071 fix(crypto): add multisignature related exceptions
  packages/crypto/src/networks/mainnet/exceptions.json
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2074 chore: add upgrade scripts for future reference
  README.md
  UPGRADE.md
  upgrade/2.1.0/exchange.sh
  upgrade/2.1.0/normal.sh
Labels: Complexity: Medium, Status: Blocked, Status: Needs Review, Type: Task

#2075 chore(docker): changed forging secret and password handling
  docker/production/devnet/enc.sh
  docker/production/mainnet/enc.sh
Labels: Complexity: Medium, Status: Needs Review

#2073 fix(core-api): give user requested field priority for sorting
  packages/core-api/src/repositories/repository.ts
  packages/core-api/src/repositories/transactions.ts
  packages/core-p2p/src/server/versions/internal/handlers/transactions.ts
  packages/core-p2p/src/server/versions/internal/handlers/utils.ts
  packages/core-p2p/src/server/versions/remote/handlers/blockchain.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2076 fix(crypto): add multisignature related exceptions
  packages/crypto/src/networks/mainnet/exceptions.json
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2072 docs: 2.1.0 changelog
  CHANGELOG.md
Labels: Complexity: Low, Status: Blocked, Status: Needs Review, Type: Documentation

#2080 fix(core-transaction-pool): disallow multiple registrations for same delegate
  packages/core-transaction-pool/__tests__/guard.test.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/guard.ts
  packages/core-transaction-pool/src/mem.ts
Labels: Complexity: Medium, Status: Needs Review

#2081 chore: do not run tests in prepublishOnly
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  scripts/release.sh
Labels: Complexity: Low, Status: Needs Review, Type: Task

#2082 fix(core-api): configuration endpoint does not show dynamic fees
  packages/core-api/__tests__/v2/handlers/node.test.ts
  packages/core-api/src/versions/2/node/controller.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2083 fix(core-api): use the supply calculator in the v1 API
  packages/core-api/src/versions/1/blocks/controller.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2084 chore: 2.1.1 changelog and version bumps
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/__tests__/court/guard.test.ts
  packages/core-p2p/package.json
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-test-utils/src/helpers/container.ts
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  scripts/version.sh
Labels: Complexity: Undetermined, Status: Needs Review, Type: Task

#2091 fix: quorum issues
  packages/core-blockchain/src/blockchain.ts
  packages/core-forger/src/manager.ts
  packages/crypto/__tests__/crypto/slots.test.ts
  packages/crypto/src/crypto/slots.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2032 refactor(core-p2p): more extensive peer state verification
  packages/core-blockchain/__tests__/blockchain.test.ts
  packages/core-database-postgres/src/queries/blocks/find-by-height.sql
  packages/core-database-postgres/src/queries/index.ts
  packages/core-database-postgres/src/repositories/blocks.ts
  packages/core-database/__tests__/database-service.test.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-repository/blocks-repository.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/__tests__/monitor.test.ts
  packages/core-p2p/__tests__/peer-verifier.test.ts
  packages/core-p2p/__tests__/peer.test.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/peer.ts
  packages/core-utils/__tests__/capped-set.test.ts
  packages/core-utils/__tests__/nsect.test.ts
  packages/core-utils/src/capped-set.ts
  packages/core-utils/src/index.ts
  packages/core-utils/src/nsect.ts
Labels: Status: Blocked, Status: In Progress, Status: Needs Changes, Status: Needs Review, Status: Needs Testcase, Type: Refactor

#2093 fix(core-api): Proper hex validation
  packages/core-api/src/plugins/validation/formats/hex.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2096 refactor(core-p2p): allow longer version strings
  packages/core-p2p/src/server/plugins/validate-headers.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2095 Add Production Docker README.md and banner
  docker/production/README.md
  docker/production/ark-core-docker.png
Labels: Complexity: Medium, Status: Needs Review

#2097 release: 2.1.2
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-api/src/versions/1/transactions/controller.ts
  packages/core-api/src/versions/2/transactions/controller.ts
  packages/core-blockchain/package.json
  packages/core-blockchain/src/blockchain.ts
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-forger/src/manager.ts
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-interfaces/src/core-transaction-pool/transaction-pool.ts
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/__tests__/fixtures/block-with-transactions.json
  packages/core-p2p/__tests__/server/1.test.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/server/versions/1/handlers.ts
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/__tests__/__fixtures__/transactions.ts
  packages/core-transaction-pool/__tests__/connection.test.ts
  packages/core-transaction-pool/__tests__/guard.test.ts
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core-transaction-pool/src/guard.ts
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/__tests__/crypto/slots.test.ts
  packages/crypto/package.json
  packages/crypto/src/crypto/slots.ts
  packages/crypto/src/serializers/transaction.ts
  packages/crypto/src/validation/extensions/transactions/base.ts
Labels: Complexity: Undetermined, Status: Needs Review

#2099 misc: update develop with patches from master
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/__tests__/database-service.test.ts
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-interfaces/src/core-transaction-pool/transaction-pool.ts
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/__tests__/fixtures/block-with-transactions.json
  packages/core-p2p/__tests__/server/1.test.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/server/versions/1/handlers.ts
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/__tests__/__fixtures__/transactions.ts
  packages/core-transaction-pool/__tests__/connection.test.ts
  packages/core-transaction-pool/__tests__/guard.test.ts
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core-transaction-pool/src/guard.ts
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/__tests__/fixtures/transaction.ts
  packages/crypto/package.json
  packages/crypto/src/serializers/transaction.ts
  packages/crypto/src/validation/extensions/transactions/base.ts
Labels: Complexity: Undetermined, Status: Needs Review, Type: Maintenance

#2101 refactor(core-p2p): allow multiple minimum versions for alpha/beta/rc releases
  packages/core-p2p/__tests__/court/guard.test.ts
  packages/core-p2p/src/court/guard.ts
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/monitor.ts
  packages/core-test-utils/src/config/testnet/plugins.js
  packages/core-test-utils/src/config/unitnet/plugins.js
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2103 feat(core-api): add sorting to voters endpoint
  packages/core-api/__tests__/v2/handlers/delegates.test.ts
  packages/core-database/src/repositories/wallets.ts
Labels: Complexity: Low, Status: Collaborator Approved, Status: Needs Review, Type: Feature

#2104 refactor: rename arktoshi to satoshi to be generic
  packages/core-api/__tests__/v2/handlers/transactions.test.ts
  packages/core-database/__tests__/database-service.test.ts
  packages/core-database/__tests__/repositories/delegates.test.ts
  packages/core-database/__tests__/wallet-manager.test.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-test-utils/__tests__/generators/transactions/transfer.test.ts
  packages/core-tester-cli/__tests__/commands/delegate-registration.test.ts
  packages/core-tester-cli/__tests__/commands/second-signature.test.ts
  packages/core-tester-cli/__tests__/commands/transfer.test.ts
  packages/core-tester-cli/__tests__/commands/vote.test.ts
  packages/core-tester-cli/__tests__/utils.test.ts
  packages/core-tester-cli/src/commands/delegate-registration.ts
  packages/core-tester-cli/src/commands/multi-signature.ts
  packages/core-tester-cli/src/commands/second-signature.ts
  packages/core-tester-cli/src/commands/transfer.ts
  packages/core-tester-cli/src/commands/vote.ts
  packages/core-tester-cli/src/utils.ts
  packages/core-transaction-pool/__tests__/connection.test.ts
  packages/core-transaction-pool/__tests__/dynamic-fee.test.ts
  packages/core-transaction-pool/__tests__/guard.test.ts
  packages/core-transaction-pool/__tests__/pool-wallet-manager.test.ts
  packages/core-transaction-pool/src/dynamic-fee/matcher.ts
  packages/crypto/__tests__/constants.test.ts
  packages/crypto/__tests__/handlers/transactions/handler.test.ts
  packages/crypto/__tests__/models/delegate.test.ts
  packages/crypto/__tests__/models/wallet.test.ts
  packages/crypto/__tests__/utils/format-arktoshi.test.ts
  packages/crypto/__tests__/utils/format-satoshi.test.ts
  packages/crypto/__tests__/validation/extensions/transactions/delegate-registration.test.ts
  packages/crypto/__tests__/validation/extensions/transactions/multi-signature.test.ts
  packages/crypto/__tests__/validation/extensions/transactions/second-signature.test.ts
  packages/crypto/__tests__/validation/extensions/transactions/transfer.test.ts
  packages/crypto/__tests__/validation/extensions/transactions/vote.test.ts
  packages/crypto/src/constants.ts
  packages/crypto/src/models/block.ts
  packages/crypto/src/models/transaction.ts
  packages/crypto/src/models/wallet.ts
  packages/crypto/src/utils.ts
  packages/crypto/src/utils/format-satoshi.ts
  packages/crypto/src/utils/index.ts
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#2105 refactor: merge small utils into utils files
  packages/core-database-postgres/src/utils.ts
  packages/core-database-postgres/src/utils/camelize-columns.ts
  packages/core-database-postgres/src/utils/index.ts
  packages/core-database-postgres/src/utils/load-query-file.ts
  packages/core-snapshots/src/utils.ts
  packages/core-transaction-pool/src/guard.ts
  packages/core-transaction-pool/src/utils.ts
  packages/crypto/__tests__/builder/transactions/__shared__/transaction-builder.ts
  packages/crypto/__tests__/handlers/transactions/__fixtures__/transaction.ts
  packages/crypto/__tests__/handlers/transactions/__fixtures__/wallet.ts
  packages/crypto/__tests__/handlers/transactions/delegate-registration.test.ts
  packages/crypto/__tests__/handlers/transactions/delegate-resignation.test.ts
  packages/crypto/__tests__/handlers/transactions/handler.test.ts
  packages/crypto/__tests__/handlers/transactions/ipfs.test.ts
  packages/crypto/__tests__/handlers/transactions/multi-payment.test.ts
  packages/crypto/__tests__/handlers/transactions/multi-signature.test.ts
  packages/crypto/__tests__/handlers/transactions/second-signature.test.ts
  packages/crypto/__tests__/handlers/transactions/timelock-transfer.test.ts
  packages/crypto/__tests__/handlers/transactions/vote.test.ts
  packages/crypto/__tests__/models/block.test.ts
  packages/crypto/__tests__/models/delegate.test.ts
  packages/crypto/__tests__/models/wallet.test.ts
  packages/crypto/src/deserializers/block.ts
  packages/crypto/src/deserializers/transaction.ts
  packages/crypto/src/utils/bignum.ts
  packages/crypto/src/utils/format-satoshi.ts
  packages/crypto/src/utils/index.ts
  packages/crypto/src/utils/is-exception.ts
  packages/crypto/src/utils/sort-transactions.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2106 refactor: replace lodash.sortBy/orderBy with faster implementations
  packages/core-api/package.json
  packages/core-api/src/versions/2/delegates/methods.ts
  packages/core-database/package.json
  packages/core-database/src/repositories/delegates.ts
  packages/core-database/src/repositories/wallets.ts
  packages/core-jest-matchers/package.json
  packages/core-jest-matchers/src/api/block.ts
  packages/core-jest-matchers/src/api/peer.ts
  packages/core-jest-matchers/src/api/transaction.ts
  packages/core-jest-matchers/src/blockchain/execute-on-entry.ts
  packages/core-jest-matchers/src/models/delegate.ts
  packages/core-jest-matchers/src/models/transaction.ts
  packages/core-jest-matchers/src/models/wallet.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2108 fix(core-tester-cli): pass the base flags for programmatic calls
  packages/core-tester-cli/__tests__/commands/command.test.ts
  packages/core-tester-cli/__tests__/commands/delegate-registration.test.ts
  packages/core-tester-cli/__tests__/commands/second-signature.test.ts
  packages/core-tester-cli/__tests__/commands/vote.test.ts
  packages/core-tester-cli/src/commands/command.ts
  packages/core-tester-cli/src/commands/delegate-registration.ts
  packages/core-tester-cli/src/commands/multi-signature.ts
  packages/core-tester-cli/src/commands/second-signature.ts
  packages/core-tester-cli/src/commands/vote.ts
  packages/core-tester-cli/src/utils.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#2112 fix(core-p2p): disable peer verifier
  packages/core-p2p/src/peer.ts
  packages/core-utils/src/nsect.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2113 chore: run linting on CircleCI
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/generateConfig.js
Labels: Complexity: Low, Status: Needs Review, Type: Task

#2117 chore(release): 2.2.0-beta.4
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Status: Needs Review, Type: Task

#2120 refactor(core): Make it possible to disable a non-dev warning
  packages/core/src/helpers/update.ts
Labels: Complexity: Low, Status: Needs Review, Type: Task

#2107 Consolidate core-api's repos into core-database & core-database-postgres
  packages/core-api/src/repositories/blocks.ts
  packages/core-api/src/repositories/repository.ts
  packages/core-api/src/repositories/transactions.ts
  packages/core-api/src/repositories/utils/build-filter-query.ts
  packages/core-api/src/versions/2/blocks/methods.ts
  packages/core-api/src/versions/2/node/controller.ts
  packages/core-api/src/versions/2/transactions/methods.ts
  packages/core-database-postgres/src/models/block.ts
  packages/core-database-postgres/src/models/migration.ts
  packages/core-database-postgres/src/models/model.ts
  packages/core-database-postgres/src/models/round.ts
  packages/core-database-postgres/src/models/transaction.ts
  packages/core-database-postgres/src/models/wallet.ts
  packages/core-database-postgres/src/repositories/blocks.ts
  packages/core-database-postgres/src/repositories/repository.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database-postgres/src/repositories/wallets.ts
  packages/core-database/__tests__/database-service.test.ts
  packages/core-database/__tests__/repositories/delegates.test.ts
  packages/core-database/__tests__/repositories/wallets.test.ts
  packages/core-database/src/database-service-factory.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/index.ts
  packages/core-database/src/repositories/blocks-business-repository.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-database/src/repositories/utils/search-parameter-converter.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/blocks-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/index.ts
  packages/core-interfaces/src/core-database/business-repository/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/database-model/database-model.ts
  packages/core-interfaces/src/core-database/database-model/index.ts
  packages/core-interfaces/src/core-database/database-repository/blocks-repository.ts
  packages/core-interfaces/src/core-database/database-repository/repository.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-database/index.ts
  packages/core-interfaces/src/core-database/search/index.ts
  packages/core-interfaces/src/core-database/search/search-parameter-converter.ts
  packages/core-interfaces/src/core-database/search/search-parameters.ts
Labels: Bounty: Tier 0, Complexity: Undetermined, Status: Needs Changes, Status: Needs Review

#2119 refactor(core-elasticsearch): reduce duplication/complexity and fix wrong offset behaviour
  packages/core-api/__tests__/v1/utils.ts
  packages/core-api/__tests__/v2/utils.ts
  packages/core-database/src/database-service.ts
  packages/core-elasticsearch/package.json
  packages/core-elasticsearch/src/client.ts
  packages/core-elasticsearch/src/defaults.ts
  packages/core-elasticsearch/src/index.ts
  packages/core-elasticsearch/src/index/block.ts
  packages/core-elasticsearch/src/index/index.ts
  packages/core-elasticsearch/src/index/round.ts
  packages/core-elasticsearch/src/index/transaction.ts
  packages/core-elasticsearch/src/index/wallet.ts
  packages/core-elasticsearch/src/indices/base.ts
  packages/core-elasticsearch/src/indices/blocks.ts
  packages/core-elasticsearch/src/indices/index.ts
  packages/core-elasticsearch/src/indices/rounds.ts
  packages/core-elasticsearch/src/indices/transactions.ts
  packages/core-elasticsearch/src/indices/wallets.ts
  packages/core-elasticsearch/src/server.ts
  packages/core-elasticsearch/src/server/handler.ts
  packages/core-elasticsearch/src/server/index.ts
  packages/core-elasticsearch/src/server/routes.ts
  packages/core-elasticsearch/src/services/client.ts
  packages/core-elasticsearch/src/services/storage.ts
  packages/core-elasticsearch/src/storage.ts
  packages/core-elasticsearch/src/utils.ts
  packages/core-test-utils/src/config/index.js
  packages/core-tester-cli/__tests__/config.test.ts
  packages/core-tester-cli/src/config.ts
  yarn.lock
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#2123 refactor(core-p2p): Remove unnecessary ping() call
  packages/core-container/src/config/index.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/__tests__/court/guard.test.ts
  packages/core-p2p/__tests__/monitor.test.ts
  packages/core-p2p/src/court/guard.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/server/plugins/accept-request.ts
  packages/core-p2p/src/server/plugins/set-headers.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2121 refactor(core-p2p): Remove broken getRandomDownloadBlocksPeer()
  packages/core-interfaces/src/core-p2p/monitor.ts
  packages/core-p2p/__tests__/monitor.test.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer.ts
Labels: Complexity: Medium, Status: Needs Changes, Status: Needs Review, Type: Refactor

#2126 chore(core): remove accidentally committed env variables
  packages/core/bin/config/devnet/.env
  packages/core/bin/config/mainnet/.env
  packages/core/bin/config/testnet/.env
Labels: Complexity: Low, Status: Needs Review, Type: Task

#2124 refactor(core-webhooks): replace sqlite3 with lowdb
  packages/core-test-utils/src/config/testnet/plugins.js
  packages/core-test-utils/src/config/unitnet/plugins.js
  packages/core-test-utils/src/helpers/container.ts
  packages/core-webhooks/__tests__/__support__/setup.ts
  packages/core-webhooks/__tests__/__support__/utils.ts
  packages/core-webhooks/__tests__/server.test.ts
  packages/core-webhooks/package.json
  packages/core-webhooks/src/conditions.ts
  packages/core-webhooks/src/database.ts
  packages/core-webhooks/src/database/index.ts
  packages/core-webhooks/src/database/migrations/20180305163843-create-webhook.ts
  packages/core-webhooks/src/defaults.ts
  packages/core-webhooks/src/index.ts
  packages/core-webhooks/src/manager.ts
  packages/core-webhooks/src/server/handler.ts
  packages/core-webhooks/src/server/index.ts
  packages/core-webhooks/src/server/routes.ts
  packages/core-webhooks/src/server/schema.ts
  packages/core-webhooks/src/server/transformer.ts
  packages/core-webhooks/src/server/utils.ts
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
  yarn.lock
Labels: Complexity: Undetermined, Status: Blocked, Status: Needs Review, Type: Refactor

#2127 fix(core-elasticsearch): build failure
  packages/core-elasticsearch/src/indices/transactions.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2125 refactor(core-p2p): Improve fork handling in updatePeersOnMissingBlocks
  packages/core-blockchain/__tests__/state-machine.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-blockchain/src/state-storage.ts
  packages/core-interfaces/src/core-p2p/monitor.ts
  packages/core-p2p/__tests__/peer-verifier.test.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/peer.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2128 misc(core-p2p): remove superfluous log message
  packages/core-p2p/src/peer-verifier.ts
Labels: Complexity: Low, Status: Needs Review, Type: Maintenance

#2129 refactor(core-p2p): reduce logging noise
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/peer.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2132 chore(release): 2.2.0-beta.5
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Status: Needs Review, Type: Task

#2135 refactor(core-container): throw an error if the peers or plugins file are missing
  packages/core-container/src/config/loaders/file-loader.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2136 chore(release): 2.2.0-beta.6
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Status: Needs Review, Type: Task

#2138 fix(core): do not ignore the network flag in parseWithNetwork
  packages/core/src/commands/command.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2140 fix(core): overwrite the config path if an env variable is provided
  packages/core/src/commands/command.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2137 refactor(core-p2p): Improve selection of peer for downloading blocks
  packages/core-interfaces/src/core-p2p/monitor.ts
  packages/core-p2p/__tests__/monitor.test.ts
  packages/core-p2p/src/monitor.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2139 fix(core-blockchain): stuck at not ready to accept new block
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2141 chore(release): 2.2.0-beta.7
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots-cli/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Status: Needs Review, Type: Task

#2102 feat(core-p2p): Validate GET replies from other peers
  packages/core-p2p/__tests__/monitor.test.ts
  packages/core-p2p/__tests__/peer-verifier.test.ts
  packages/core-p2p/__tests__/peer.test.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/reply-schemas.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#2142 fix(core-api): pass query to findAllByVote method
  packages/core-api/src/versions/2/delegates/methods.ts
Labels: Complexity: Low, Status: Collaborator Approved, Status: Needs Review, Type: Bugfix

#2147 test(core-database): add tests to blocks & transactions business repos
  packages/core-database/__tests__/__fixtures__/mock-database-model.ts
  packages/core-database/__tests__/repositories/blocks-business-repository.test.ts
  packages/core-database/__tests__/repositories/delegates-business-repository.test.ts
  packages/core-database/__tests__/repositories/transactions-business-repository.test.ts
  packages/core-database/__tests__/repositories/utils/search-parameter-converter.test.ts
  packages/core-database/__tests__/repositories/wallets-business-repository.test.ts
  packages/core-database/src/repositories/blocks-business-repository.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-database/src/repositories/utils/search-parameter-converter.ts
  packages/core-interfaces/src/core-database/business-repository/blocks-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/search/search-parameter-converter.ts
Labels: Complexity: High, Status: Collaborator Approved, Status: Needs Review, Test: Unit

#2145 feat(core): configuration and channel support for the CLI
  packages/core/package.json
  packages/core/src/commands/command.ts
  packages/core/src/commands/config/cli.ts
  packages/core/src/commands/config/publish.ts
  packages/core/src/helpers/config.ts
  packages/core/src/helpers/update.ts
  packages/core/src/hooks/init/config.ts
  packages/core/src/hooks/init/update.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#2149 feat(core): merge core-snapshot-cli commands into core
  deprecated/core-snapshots-cli/README.md
  deprecated/core-snapshots-cli/__tests__/.gitkeep
  deprecated/core-snapshots-cli/bin/run
  deprecated/core-snapshots-cli/bin/run.cmd
  deprecated/core-snapshots-cli/package.json
  deprecated/core-snapshots-cli/src/commands/command.ts
  deprecated/core-snapshots-cli/src/commands/dump.ts
  deprecated/core-snapshots-cli/src/commands/restore.ts
  deprecated/core-snapshots-cli/src/commands/rollback.ts
  deprecated/core-snapshots-cli/src/commands/truncate.ts
  deprecated/core-snapshots-cli/src/commands/verify.ts
  deprecated/core-snapshots-cli/src/index.ts
  deprecated/core-snapshots-cli/src/utils.ts
  deprecated/core-snapshots-cli/tsconfig.json
  packages/core/package.json
  packages/core/src/commands/command.ts
  packages/core/src/commands/snapshot/dump.ts
  packages/core/src/commands/snapshot/restore.ts
  packages/core/src/commands/snapshot/rollback.ts
  packages/core/src/commands/snapshot/truncate.ts
  packages/core/src/commands/snapshot/verify.ts
  packages/core/src/helpers/snapshot.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#2144 fix(core-database): properly sort BigNumber values
  packages/core-api/__tests__/v2/handlers/delegates.test.ts
  packages/core-api/__tests__/v2/handlers/wallets.test.ts
  packages/core-api/__tests__/v2/utils.ts
  packages/core-api/package.json
  packages/core-database/__tests__/repositories/wallets.test.ts
  packages/core-database/package.json
  packages/core-database/src/database-service-factory.ts
  packages/core-database/src/repositories/delegates.ts
  packages/core-database/src/repositories/utils/sort-entries.ts
  packages/core-database/src/repositories/wallets.ts
  packages/core-http-utils/src/server/create-secure.ts
  packages/core-http-utils/src/server/create.ts
  packages/core-http-utils/src/server/monitor.ts
  packages/core-http-utils/src/server/mount.ts
  packages/core-jest-matchers/package.json
  yarn.lock
Labels: Complexity: Medium, Status: Needs Changes, Status: Needs Review, Type: Bugfix

#2150 fix(core): return correct suffix for core:restart command
  packages/core/src/commands/core/restart.ts
Labels: Bounty: Tier 5, Complexity: Low, Status: Collaborator Approved, Status: Needs Review, Type: Bugfix

#2151 refactor(core): more robust check for ensureDefaults
  packages/core/src/helpers/config.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2152 feat(core-p2p): Fetch list of peers from at least a few others
  packages/core-p2p/src/monitor.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#2153 refactor(core): require the user to take action for updates
  .circleci/config.yml
  packages/core/src/commands/config/cli.ts
  packages/core/src/commands/update.ts
  packages/core/src/helpers/prompts.ts
  packages/core/src/helpers/update.ts
  packages/core/src/hooks/init/update.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2154 refactor(core): replace pm2 with process manager
  packages/core/package.json
  packages/core/src/commands/command.ts
  packages/core/src/commands/config/cli.ts
  packages/core/src/commands/config/forger/bip38.ts
  packages/core/src/commands/config/forger/bip39.ts
  packages/core/src/commands/config/forger/index.ts
  packages/core/src/commands/config/publish.ts
  packages/core/src/commands/config/reset.ts
  packages/core/src/commands/core/log.ts
  packages/core/src/commands/core/restart.ts
  packages/core/src/commands/core/run.ts
  packages/core/src/commands/core/start.ts
  packages/core/src/commands/core/status.ts
  packages/core/src/commands/core/stop.ts
  packages/core/src/commands/env/get.ts
  packages/core/src/commands/env/list.ts
  packages/core/src/commands/env/paths.ts
  packages/core/src/commands/env/set.ts
  packages/core/src/commands/forger/log.ts
  packages/core/src/commands/forger/restart.ts
  packages/core/src/commands/forger/run.ts
  packages/core/src/commands/forger/start.ts
  packages/core/src/commands/forger/status.ts
  packages/core/src/commands/forger/stop.ts
  packages/core/src/commands/relay/log.ts
  packages/core/src/commands/relay/restart.ts
  packages/core/src/commands/relay/run.ts
  packages/core/src/commands/relay/start.ts
  packages/core/src/commands/relay/status.ts
  packages/core/src/commands/relay/stop.ts
  packages/core/src/commands/snapshot/dump.ts
  packages/core/src/commands/snapshot/restore.ts
  packages/core/src/commands/snapshot/rollback.ts
  packages/core/src/commands/snapshot/verify.ts
  packages/core/src/commands/top.ts
  packages/core/src/process-manager.ts
  packages/core/src/shared/log.ts
  packages/core/src/shared/restart.ts
  packages/core/src/shared/start.ts
  packages/core/src/shared/status.ts
  packages/core/src/shared/stop.ts
  packages/core/src/types.ts
  yarn.lock
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#2155 feat(core): ask for process restarts after updating
  packages/core/src/commands/command.ts
  packages/core/src/commands/config/cli.ts
  packages/core/src/commands/update.ts
  packages/core/src/helpers/prompts.ts
  packages/core/src/helpers/update.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#2158 perf(crypto): bcrypto
  benchmark/crypto/hash-algorithms.js
  benchmark/index.js
  packages/core-api/src/services/cache.ts
  packages/core-database/src/database-service.ts
  packages/core-snapshots/src/transport/verification.ts
  packages/crypto/__tests__/models/delegate.test.ts
  packages/crypto/package.json
  packages/crypto/src/crypto/hash-algorithms.ts
  packages/crypto/src/models/block.ts
  packages/crypto/src/models/delegate.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Performance

#2160 release: 2.2.0-beta.8
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Status: Needs Review, Type: Release

#2143 feat(core-api): search delegates by usernames
  packages/core-api/__tests__/v2/handlers/delegates.test.ts
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-database/__tests__/repositories/delegates-business-repository.test.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/repositories/utils/filter-rows.ts
Labels: Bounty: Tier 2, Complexity: Low, Status: Blocked, Status: Collaborator Approved, Status: Needs Review, Type: Feature

#2161 refactor(core): exit the CLI if snapshots are not available
  packages/core/src/commands/snapshot/dump.ts
  packages/core/src/commands/snapshot/restore.ts
  packages/core/src/commands/snapshot/rollback.ts
  packages/core/src/commands/snapshot/truncate.ts
  packages/core/src/commands/snapshot/verify.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2164 fix(core): reset configuration if --network is passed
  packages/core/src/commands/config/reset.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2162 fix(docker): remove force flag and add a forger check
  docker/production/entrypoint.sh
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2159 feat(crypto): increase vendor field length to 255 bytes
  packages/core-api/src/formats.ts
  packages/core-container/__tests__/__stubs__/config/milestones.json
  packages/crypto/__tests__/models/block.test.ts
  packages/crypto/__tests__/transactions/deserializers/transaction.test.ts
  packages/crypto/__tests__/validation/formats.test.ts
  packages/crypto/src/builder/transactions/transaction.ts
  packages/crypto/src/networks/devnet/milestones.json
  packages/crypto/src/networks/mainnet/milestones.json
  packages/crypto/src/networks/testnet/milestones.json
  packages/crypto/src/networks/unitnet/milestones.json
  packages/crypto/src/transactions/types/schemas.ts
  packages/crypto/src/utils.ts
  packages/crypto/src/validation/ajv-wrapper.ts
  packages/crypto/src/validation/formats.ts
Labels: Complexity: Medium, Status: Needs Changes, Status: Needs Review, Type: Feature

#2166 refactor(core-container): remove dead configuration code
  packages/core-container/__tests__/config/loaders/file-loader.test.ts
  packages/core-container/src/config/network.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2165 refactor: replace micromatch with nanomatch and remove heavy deps
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-http-utils/package.json
  packages/core-http-utils/src/plugins/whitelist.ts
  packages/core-http-utils/src/server/create-secure.ts
  packages/core-http-utils/src/server/create.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/utils/is-whitelisted.ts
  packages/core-vote-report/package.json
  packages/core-vote-report/src/server.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2163 refactor(core): use reload instead of restart and update the env vars
  packages/core/src/process-manager.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2167 refactor(crypto): benchmarks
  benchmark/block/create.js
  benchmark/index.js
  benchmark/transaction/create/0.js
  benchmark/transaction/deserialize/methods.js
  benchmark/transaction/serialize/0.js
  packages/crypto/src/crypto/crypto.ts
  packages/crypto/src/transactions/index.ts
  packages/crypto/src/transactions/serializers/block.ts
  packages/crypto/src/transactions/serializers/transaction.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2169 chore: move core-graphql to the deprecated folder
  .circleci/config.yml
  deprecated/core-graphql/.gitattributes
  deprecated/core-graphql/README.md
  deprecated/core-graphql/__tests__/__support__/setup.ts
  deprecated/core-graphql/__tests__/__support__/utils.ts
  deprecated/core-graphql/__tests__/api/address.test.ts
  deprecated/core-graphql/__tests__/api/block.test.ts
  deprecated/core-graphql/__tests__/api/blocks.test.ts
  deprecated/core-graphql/__tests__/api/transaction.test.ts
  deprecated/core-graphql/__tests__/api/transactions.test.ts
  deprecated/core-graphql/__tests__/api/wallet.test.ts
  deprecated/core-graphql/__tests__/api/wallets.test.ts
  deprecated/core-graphql/package.json
  deprecated/core-graphql/src/apollo-server.ts
  deprecated/core-graphql/src/defaults.ts
  deprecated/core-graphql/src/defs/index.ts
  deprecated/core-graphql/src/defs/inputs.ts
  deprecated/core-graphql/src/defs/root.ts
  deprecated/core-graphql/src/defs/types.ts
  deprecated/core-graphql/src/helpers/format-orderBy.ts
  deprecated/core-graphql/src/helpers/index.ts
  deprecated/core-graphql/src/helpers/unserialize-transactions.ts
  deprecated/core-graphql/src/index.ts
  deprecated/core-graphql/src/repositories/blocks.ts
  deprecated/core-graphql/src/repositories/index.ts
  deprecated/core-graphql/src/repositories/repository.ts
  deprecated/core-graphql/src/repositories/transactions.ts
  deprecated/core-graphql/src/repositories/utils/filter-query.ts
  deprecated/core-graphql/src/resolvers/index.ts
  deprecated/core-graphql/src/resolvers/queries/block/block.ts
  deprecated/core-graphql/src/resolvers/queries/block/blocks.ts
  deprecated/core-graphql/src/resolvers/queries/index.ts
  deprecated/core-graphql/src/resolvers/queries/transaction/transaction.ts
  deprecated/core-graphql/src/resolvers/queries/transaction/transactions.ts
  deprecated/core-graphql/src/resolvers/queries/wallet/wallet.ts
  deprecated/core-graphql/src/resolvers/queries/wallet/wallets.ts
  deprecated/core-graphql/src/resolvers/relationship/block.ts
  deprecated/core-graphql/src/resolvers/relationship/transaction.ts
  deprecated/core-graphql/src/resolvers/relationship/wallet.ts
  deprecated/core-graphql/src/server.ts
  deprecated/core-graphql/tsconfig.json
  yarn.lock
Labels: Complexity: High, Status: Needs Review, Type: Task

#2171 release: 2.2.0-beta.10
  deprecated/core-snapshots-cli/package.json
  lerna.json
  package.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Status: Needs Review, Type: Release

#2173 refactor(core): only ask to restart processes that are online
  packages/core/src/commands/command.ts
  packages/core/src/process-manager.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2168 refactor: replace dayjs-ext with dato
  .circleci/config.yml
  __tests__/unit/core-p2p/court/guard.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/crypto/crypto/slots.test.ts
  deprecated/core-graphql/package.json
  deprecated/core-graphql/src/repositories/transactions.ts
  packages/core-api/package.json
  packages/core-api/src/repositories/transactions.ts
  packages/core-database-postgres/package.json
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/package.json
  packages/core-interfaces/package.json
  packages/core-interfaces/src/core-transaction-pool/transaction-pool.ts
  packages/core-jest-matchers/package.json
  packages/core-p2p/package.json
  packages/core-p2p/src/court/guard.ts
  packages/core-p2p/src/court/offences.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer.ts
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
  packages/core-utils/package.json
  packages/core-utils/src/format-timestamp.ts
  packages/core/package.json
  packages/core/src/commands/top.ts
  packages/core/src/shared/status.ts
  packages/crypto/package.json
  packages/crypto/src/crypto/slots.ts
  yarn.lock
Labels: Complexity: Medium, Status: In Progress, Status: Needs Review, Type: Refactor

#2176 refactor(core-forger): use slot time for block timestamp
  packages/core-p2p/src/server/versions/internal/handlers/rounds.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2177 chore: update circleci config to fix coverage
  .circleci/config.yml
  .circleci/generateConfig.js
Labels: Complexity: Medium, Status: Needs Review, Type: Task

#2174 refactor: start 'stopped' process through start command
  packages/core/src/shared/start.ts
Labels: Complexity: Low, Status: Collaborator Approved, Status: Needs Review, Type: Refactor

#2178 refactor(core): add methods for online, stopped and errored states
  packages/core/src/commands/command.ts
  packages/core/src/enums.ts
  packages/core/src/process-manager.ts
  packages/core/src/shared/start.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2179 refactor(core): exit start commands if the process is already running
  packages/core/src/commands/command.ts
  packages/core/src/process-manager.ts
  packages/core/src/shared/start.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2180 refactor(core): add abortion state helpers
  packages/core/src/commands/command.ts
  packages/core/src/commands/core/start.ts
  packages/core/src/commands/forger/start.ts
  packages/core/src/commands/relay/start.ts
  packages/core/src/process-manager.ts
  packages/core/src/shared/log.ts
  packages/core/src/shared/restart.ts
  packages/core/src/shared/start.ts
  packages/core/src/shared/status.ts
  packages/core/src/shared/stop.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2181 release: 2.2.0-beta.11
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Status: Needs Review, Type: Release

#2182 chore: remove extraneous jest presets and config
  deprecated/core-graphql/package.json
  deprecated/core-logger-winston/package.json
  deprecated/core-snapshots-cli/package.json
  jest-preset.json
  package.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Status: Needs Review, Type: Task

#2183 chore: move @types to development dependencies
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Task

#2170 docs: 2.2.0 changelog
  CHANGELOG.md
Labels: Complexity: Low, Status: In Progress, Status: Needs Review, Type: Documentation

#2185 fix(core): pass the bip38 and password flags to the forger:run command
  packages/core/src/commands/forger/start.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2186 release: 2.2.0-beta.12
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Status: Needs Review, Type: Release

#2187 chore(crypto): add missing devDependencies
  packages/crypto/package.json
Labels: Complexity: Low, Status: Needs Review, Type: Task
