Repository ArkEcosystem/core, pull requests merged in 2019-08, with the labels that each got.

#2859 refactor: transaction registry
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  packages/core-database-postgres/src/state-builder.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/handler-registry.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/interfaces.ts
  packages/crypto/src/transactions/registry.ts
  packages/crypto/src/transactions/types/factory.ts
Labels: Complexity: High, Type: Refactor

#2853 build: Configure rollup for crypto package build
  packages/crypto/package.json
  packages/crypto/rollup.config.js
  yarn.lock
Labels: Complexity: Undetermined, Status: In Progress

#2854 fix(core-state): differentiate between wallets and delegates
  __tests__/integration/core-api/handlers/delegates.test.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet-manager.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#2863 fix(core-webhooks): create copy before deleting property
  packages/core-webhooks/src/server/index.ts
Labels: Complexity: Low, Type: Bugfix

#2864 fix(core-p2p): delete existing db
  packages/core-p2p/src/socket-server/payload-processor.ts
Labels: Complexity: Low, Type: Bugfix

#2865 refactor(core-transactions): make handler functions asynchronous
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-transaction-pool/wallet-manager.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-state/wallets/wallet-manager-htlc.test.ts
  __tests__/unit/core-state/wallets/wallet-manager-multipayment.test.ts
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  __tests__/unit/core-transaction-pool/__stubs__/connection.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-api/src/handlers/transactions/controller.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-interfaces/src/core-transaction-pool/connection.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transaction-pool/src/wallet-manager.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/interfaces.ts
Labels: Complexity: Undetermined, Type: Refactor

#2866 release: 2.4.17
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2844 refactor(core-database-postgres): add nonce column
  .codacy.yml
  __tests__/integration/core-transactions/handlers/delegate-resignation.test.ts
  __tests__/integration/core-transactions/handlers/vote.test.ts
  packages/core-database-postgres/src/migrations/20190806000000-add-nonce-column-to-transactions-table.sql
  packages/core-database-postgres/src/migrations/index.ts
  packages/core-database-postgres/src/models/transaction.ts
Labels: Complexity: Undetermined, Status: In Progress

#2867 feat(core-transactions): register wallet attributes before accessing them
  __tests__/unit/core-state/wallets/wallet-manager-htlc.test.ts
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  packages/core-state/src/wallets/wallet.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/handler-registry.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/interfaces.ts
Labels: Complexity: Medium, Type: Feature

#2869 feat(core-p2p): change minimum version via milestone
  __tests__/integration/core-p2p/__support__/mock-socket-server/manager.ts
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/integration/core-p2p/peer-processor.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/mocks/event-emitter.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/utils/is-valid-version.ts
Labels: Complexity: Medium, Type: Feature

#2855 feat(core-api): include core version in node/configuration
  __tests__/integration/core-api/handlers/node.test.ts
  packages/core-api/src/handlers/node/controller.ts
  packages/core-container/src/container.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Status: Contributor Approved, Status: In Progress, Type: Feature

#2654 feat(core): support updates via git
  packages/core/package.json
  packages/core/src/commands/config/cli.ts
  packages/core/src/commands/update.ts
  packages/core/src/helpers/config.ts
  packages/core/src/helpers/update.ts
  yarn.lock
Labels: Complexity: Medium, Status: In Progress, Type: Feature

#2875 fix(core-p2p): stricter schema on peer replies, disconnect on invalid requests
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/mocks/core-container.ts
  __tests__/unit/core-p2p/socket-server/utils/validate.test.ts
  packages/core-p2p/src/schemas.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: High, Type: Bugfix

#2876 release: 2.5.19
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2877 refactor(crypto): signature deserialization
  __tests__/unit/crypto/transactions/deserializer.test.ts
  packages/crypto/src/transactions/deserializer.ts
  packages/crypto/src/transactions/signer.ts
  packages/crypto/src/transactions/types/delegate-resignation.ts
  packages/crypto/src/transactions/types/htlc-claim.ts
  packages/crypto/src/transactions/types/htlc-lock.ts
  packages/crypto/src/transactions/types/htlc-refund.ts
  packages/crypto/src/transactions/types/ipfs.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/transactions/types/multi-signature.ts
  packages/crypto/src/transactions/verifier.ts
Labels: Complexity: High, Type: Refactor

#2878 refactor(core-api): return all types from the `/transactions/types` endpoint
  __tests__/integration/core-api/handlers/transactions.test.ts
  packages/core-api/package.json
  packages/core-api/src/handlers/transactions/controller.ts
Labels: Complexity: Low, Type: Refactor

#2873 feat(core-blockchain): enforce transactions' nonce order from blockPr…
  __tests__/unit/core-blockchain/mocks/database.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/processor/handlers/incompatible-transactions-handler.ts
  packages/core-blockchain/src/processor/handlers/index.ts
  packages/core-blockchain/src/processor/handlers/nonce-out-of-order-handler.ts
Labels: Complexity: Medium, Status: Needs Changes, Type: Feature

#2886 feat(core-p2p): use compression on the p2p level
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/socket-server/index.ts
Labels: Complexity: Low, Type: Feature

#2887 fix(core-webhooks): cast params in condition checks
  __tests__/unit/core-webhooks/conditions.test.ts
  packages/core-webhooks/src/conditions.ts
Labels: Bounty: Tier 3, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#2889 fix(crypto): ensure only one signature per participant
  __tests__/helpers/transaction-factory.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-state/src/wallets/wallet.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/transactions/deserializer.ts
  packages/crypto/src/transactions/factory.ts
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: Medium, Type: Bugfix

#2894 fix(crypto): use `anyOf` for transactions schema
  packages/crypto/src/validation/index.ts
Labels: Complexity: Low, Type: Bugfix

#2893 refactor(core-database): emit `forging.missing` earlier
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-database/database-service.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-service.ts
Labels: Complexity: Medium, Type: Refactor

#2895 refactor(core-database): emit missing `transaction.reverted` event and remove obsolete ones
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-forger/manager.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database/src/database-service.ts
  packages/core-event-emitter/src/index.ts
  packages/core-forger/src/client.ts
  packages/core-forger/src/manager.ts
Labels: Complexity: Medium, Type: Refactor

#2897 fix(core-blockchain): clear queue on invalid block
  packages/core-blockchain/src/blockchain.ts
Labels: Complexity: Low, Type: Bugfix

#2899 chore: drop node 10 from CircleCI and update .nvmrc to node 11
  .circleci/config.yml
  .nvmrc
Labels: Complexity: Low, Type: Task

#2898 fix(crypto): legacy multi signature verification
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/crypto/src/transactions/types/multi-signature.ts
  packages/crypto/src/transactions/verifier.ts
Labels: Complexity: Medium, Type: Bugfix

#2896 fix: move wallet manager "zero balance" check to transaction handlers
  __tests__/e2e/lib/utils/test-utils.js
  __tests__/e2e/tests/scenarios/scenario1/config.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/1.create-lock-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/2.check-lock.test.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/3.create-claim-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/4.check-claim.test.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/config.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/shared.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-claim/utils.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/1.create-lock-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/2.check-lock.test.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/3.create-refund-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/4.check-refund.test.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/config.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/shared.js
  __tests__/e2e/tests/scenarios/scenario1/htlc-refund/utils.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/1.create-multisig-registration.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/2.check-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/3.transfer-multisig-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/4.create-multisig-txs.action.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/5.check-multisig.test.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/config.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/shared.js
  __tests__/e2e/tests/scenarios/scenario1/multisignature/utils.js
  __tests__/integration/core-transaction-pool/processor.test.ts
  packages/core-transaction-pool/src/wallet-manager.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/transaction.ts
Labels: Complexity: High, Type: Bugfix
