Repository ArkEcosystem/core, pull requests merged in 2019-07, with the labels that each got.

#2763 fix(core-p2p): avoid iterating on non-iterable peerBlocks
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Type: Bugfix

#2764 fix(core-database-postgres): correct estimate if less than limit rows
  packages/core-database-postgres/src/repositories/repository.ts
Labels: Complexity: Low, Type: Bugfix

#2765 fix: try harder to return the requested number of transactions
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Bugfix

#2766 fix(core-transaction-pool): try harder to return the requested number of transactions
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Bugfix

#2767 release: 2.4.14
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2757 fix(crypto): reject future and expired transaction timestamps
  __tests__/helpers/transaction-factory.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-forger/delegate.test.ts
  __tests__/unit/crypto/blocks/block.test.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/networks/devnet/milestones.json
  packages/crypto/src/networks/mainnet/milestones.json
Labels: Complexity: Medium, Type: Bugfix

#2769 release: 2.5.0-next.6
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2770 refactor(core-database): delete last block if deserialization fails during init
  __tests__/integration/core-database-postgres/connection.test.ts
  packages/core-database/src/database-service.ts
Labels: Complexity: Medium, Type: Refactor

#2771 refactor(core-p2p): discover new peers sooner
  __tests__/integration/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  packages/core-interfaces/src/core-p2p/network-monitor.ts
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Medium, Type: Refactor

#2753 feat(core-database-postgres): enforce chained blocks at database level
  packages/core-database-postgres/src/migrations/20190626000000-enforce-chained-blocks.sql
  packages/core-database-postgres/src/migrations/index.ts
Labels: Complexity: Low, Type: Feature

#2774 fix(core-p2p): TypeError: Reduce of empty array with no initial value
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Low, Type: Bugfix

#2775 fix(core-database-postgres): drop check_previous_block with arguments
  packages/core-database-postgres/src/migrations/20190626000000-enforce-chained-blocks.sql
Labels: Complexity: Low, Type: Bugfix

#2768 chore(deps): update dependencies to latest versions
  __tests__/e2e/package.json
  deprecated/core-graphql/package.json
  deprecated/core-snapshots-cli/package.json
  package.json
  packages/core-api/package.json
  packages/core-api/src/handlers/delegates/methods.ts
  packages/core-api/src/handlers/node/controller.ts
  packages/core-api/src/handlers/peers/controller.ts
  packages/core-api/src/handlers/wallets/methods.ts
  packages/core-blockchain/package.json
  packages/core-blockchain/src/blockchain.ts
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database/package.json
  packages/core-database/src/database-service.ts
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-forger/src/manager.ts
  packages/core-http-utils/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-snapshots/src/transport/index.ts
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-tester-cli/src/commands/make/block.ts
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-wallet-api/package.json
  packages/core-wallet-api/src/server/index.ts
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/core/src/commands/config/reset.ts
  packages/core/src/commands/top.ts
  packages/core/src/helpers/update.ts
  packages/core/src/hooks/command_not_found/suggest.ts
  packages/core/src/hooks/init/update.ts
  packages/core/src/process-manager.ts
  packages/core/src/shared/status.ts
  packages/crypto/package.json
  tsconfig.json
  tslint.json
  yarn.lock
Labels: Complexity: Undetermined, Status: In Progress, Type: Task

#2772 feat(core-api): make it configurable whether to use estimates
  __tests__/integration/core-api/handlers/transactions.test.ts
  packages/core-api/package.json
  packages/core-api/src/handlers/transactions/transformer.ts
  packages/core-api/src/handlers/utils.ts
  packages/core-database-postgres/src/defaults.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/repositories/blocks.ts
  packages/core-database-postgres/src/repositories/repository.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Changes, Type: Feature

#2776 release: 2.5.0-next.7
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Status: In Progress, Type: Release

#2777 fix(crypto): raise bignumber maximum
  __tests__/unit/crypto/validation/keywords.test.ts
  packages/crypto/src/validation/keywords.ts
Labels: Complexity: Low, Type: Bugfix

#2782 backport: some fixes for the deployer
  __tests__/unit/core-utils/is-whitelisted.test.ts
  packages/core-api/src/defaults.ts
  packages/core-container/src/registrars/plugin.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-http-utils/src/plugins/whitelist.ts
  packages/core-interfaces/src/core-container/container.ts
  packages/core-utils/package.json
  packages/core-utils/src/index.ts
  packages/core-utils/src/is-whitelisted.ts
  packages/core-wallet-api/package.json
  packages/core-wallet-api/src/plugin.ts
  packages/core-wallet-api/src/server/index.ts
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
  yarn.lock
Labels: Complexity: Medium

#2783 release: 2.4.15
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2785 refactor(core): run GC earlier on potatos
  packages/core/package.json
  packages/core/src/shared/start.ts
Labels: Complexity: Low, Type: Refactor

#2784 refactor(core-p2p): refresh peer ports
  __tests__/integration/core-p2p/peer-communicator.test.ts
  packages/core-api/src/server.ts
  packages/core-database-postgres/src/state-builder.ts
  packages/core-interfaces/src/core-p2p/peer-communicator.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer.ts
  yarn.lock
Labels: Complexity: Medium, Type: Refactor

#2793 revert: let the user choose if they want to use @next release
  install.sh
Labels: Complexity: Low

#2794 release: 2.5.0-next.8
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2796 release: 2.5.0-next.9
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: High, Type: Release

#2797 fix(core-api): handle null url and malformed JSON payloads
  packages/core-api/src/server.ts
  packages/core-elasticsearch/src/server.ts
  packages/core-http-utils/package.json
  packages/core-http-utils/src/server/create.ts
  packages/core-webhooks/src/server/index.ts
Labels: Complexity: Low, Type: Bugfix

#2798 release: 2.5.0
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2799 chore(deps): bump @arkecosystem/exchange-json-rpc to 1.0.1
  packages/core-exchange-json-rpc/package.json
  yarn.lock
Labels: Complexity: Medium, Type: Task

#2800 fix(core-http-utils): loading of ssl certificate
  packages/core-container/src/registrars/plugin.ts
  packages/core-http-utils/src/server/create.ts
Labels: Complexity: Low, Type: Bugfix

#2801 release: 2.5.1
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2802 fix(core-p2p): accepted versions
  packages/core-p2p/src/defaults.ts
Labels: Complexity: Low, Type: Bugfix

#2781 fix: e2e tests
  .circleci/config.yml
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/3.resend-BtoC.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.0.doublespend.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.1.doublespend2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/utils.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.0.doubletransfer.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.1.doubletransfer2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.2.doublevote.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.3.doubledelreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.4.double2ndsigreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.1.transfer2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/1.create-transactions.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.0.transaction.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.1.transaction2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/utils.js
  __tests__/e2e/tsconfig.json
  __tests__/functional/transaction-forging/multi-payment.test.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Medium, Type: Bugfix

#2805 chore: merge master into develop
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-container/src/registrars/plugin.ts
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-http-utils/src/server/create.ts
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-p2p/src/defaults.ts
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Task

#2779 chore(crypto): remove unused function sortTransactions()
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/crypto/utils/sort-transactions.test.ts
  packages/crypto/src/utils/index.ts
Labels: Complexity: Medium, Type: Task

#2808 chore(deps): update dependencies to their latest versions
  package.json
  packages/core-api/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-winston/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2811 fix(core-snapshots): also fix the genesis block id during verify (#2809)
  packages/core-snapshots/src/transport/index.ts
Labels: Complexity: Low, Type: Bugfix

#2807 chore(crypto): export dist/index.js for cjs and umd
  packages/crypto/package.json
Labels: Complexity: Low, Type: Task

#2810 perf(core-database): lookup wallets by keys
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet-manager.ts
Labels: Complexity: Low, Type: Performance

#2812 release: 2.5.7
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2823 build(docker): add ntp and google servers for ntpd
  docker/production/Dockerfile
Labels: Complexity: Low

#2814 fix(core-api): return count of filtered peers
  packages/core-api/src/handlers/peers/controller.ts
  packages/core-api/src/handlers/peers/schema.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#2824 style: apply tslint and prettier formatting
  __tests__/e2e/lib/generate-files.js
  __tests__/e2e/lib/test-runner.js
  __tests__/e2e/lib/utils/test-utils.js
  __tests__/integration/core-blockchain/__support__/setup.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/integration/core-transaction-pool/wallet-manager.test.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/utils/validate-generator.ts
  packages/core-container/src/config/index.ts
  packages/core-database-postgres/src/repositories/blocks.ts
  packages/core-database-postgres/src/repositories/repository.ts
  packages/core-database/src/database-service.ts
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/transport/index.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-webhooks/src/listener.ts
  packages/crypto/src/managers/config.ts
Labels: Complexity: Medium, Type: Standards

#2827 chore: setup codacy configuration
  .codacy.yml
Labels: Complexity: Low, Type: Task

#2834 chore: setup probot/stale configuration
  .github/stale.yml
Labels: Complexity: Low, Type: Task

#2835 chore(readme): add lead maintainer information
  README.md
Labels: Complexity: Low, Type: Task

#2830 fix(core-database-postgres): prefix table names with schema
  packages/core-database-postgres/src/migrations/20190718000000-check_previous_block-add-schema.sql
  packages/core-database-postgres/src/migrations/index.ts
Labels: Complexity: Low, Type: Bugfix

#2837 perf(core-database): lookup delegates by key
  packages/core-database/src/repositories/delegates-business-repository.ts
Labels: Complexity: Low, Type: Performance

#2839 refactor(core-state): wallet model cleanup
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-api/__support__/utils/generate-round.ts
  __tests__/integration/core-api/handlers/delegates.test.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/unit/core-blockchain/mocks/database.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
  __tests__/unit/core-state/wallets/temp-wallet-manager.test.ts
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  __tests__/unit/core-state/wallets/wallet.test.ts
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/core-utils/delegate-calculator.test.ts
  packages/core-api/src/handlers/blocks/transformer.ts
  packages/core-api/src/handlers/delegates/transformer.ts
  packages/core-api/src/handlers/wallets/transformer.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/replay/memory-database-service.ts
  packages/core-blockchain/src/replay/replay-blockchain.ts
  packages/core-blockchain/src/utils/validate-generator.ts
  packages/core-database-postgres/src/models/round.ts
  packages/core-database-postgres/src/repositories/rounds.ts
  packages/core-database-postgres/src/state-builder.ts
  packages/core-database/package.json
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/repositories/utils/filter-rows.ts
  packages/core-database/src/repositories/utils/get-property.ts
  packages/core-database/src/repositories/utils/sort-entries.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-forger/package.json
  packages/core-forger/src/manager.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-p2p/server.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-state/package.json
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-state/src/wallets/wallet.ts
  packages/core-transaction-pool/src/wallet-manager.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-utils/src/delegate-calculator.ts
  packages/core-vote-report/src/handler.ts
  packages/crypto/src/interfaces/transactions.ts
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor

#2840 fix(core-utils): add content-type header
  packages/core-utils/src/httpie.ts
Labels: Complexity: Low, Type: Bugfix

#2842 refactor: transaction fees
  __tests__/unit/core-transaction-pool/dynamic-fee.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/crypto/managers/config.test.ts
  __tests__/unit/crypto/managers/fee.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/delegate-registration.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/delegate-resignation.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/ipfs.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/multi-payment.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/multi-signature.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/second-signature.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/timelock-transfer.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/transfer.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/vote.test.ts
  __tests__/unit/crypto/transactions/transaction.test.ts
  packages/core-state/src/stores/state.ts
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/dynamic-fee.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/interfaces.ts
  packages/crypto/package.json
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/managers/config.ts
  packages/crypto/src/managers/fee.ts
  packages/crypto/src/managers/index.ts
  packages/crypto/src/networks/devnet/milestones.json
  packages/crypto/src/networks/mainnet/milestones.json
  packages/crypto/src/transactions/builders/transactions/delegate-registration.ts
  packages/crypto/src/transactions/builders/transactions/delegate-resignation.ts
  packages/crypto/src/transactions/builders/transactions/ipfs.ts
  packages/crypto/src/transactions/builders/transactions/multi-payment.ts
  packages/crypto/src/transactions/builders/transactions/multi-signature.ts
  packages/crypto/src/transactions/builders/transactions/second-signature.ts
  packages/crypto/src/transactions/builders/transactions/timelock-transfer.ts
  packages/crypto/src/transactions/builders/transactions/transfer.ts
  packages/crypto/src/transactions/builders/transactions/vote.ts
  packages/crypto/src/transactions/registry.ts
  packages/crypto/src/transactions/types/delegate-registration.ts
  packages/crypto/src/transactions/types/delegate-resignation.ts
  packages/crypto/src/transactions/types/ipfs.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/transactions/types/multi-signature.ts
  packages/crypto/src/transactions/types/second-signature.ts
  packages/crypto/src/transactions/types/timelock-transfer.ts
  packages/crypto/src/transactions/types/transaction.ts
  packages/crypto/src/transactions/types/transfer.ts
  packages/crypto/src/transactions/types/vote.ts
  yarn.lock
Labels: Complexity: High, Type: Refactor

#2831 fix(core-api): return data directly if cache is disabled
  packages/core-api/src/handlers/utils.ts
Labels: Complexity: Low, Status: In Progress, Type: Bugfix

#2828 refactor(core-p2p): increase network timeouts
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/socket-server/index.ts
Labels: Complexity: Low, Type: Refactor

#2845 refactor(core-state): wallet manager indexes
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/repositories/transactions-business-repository.test.ts
  __tests__/unit/core-state/wallets/wallet-index.test.ts
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-database/src/repositories/utils/filter-rows.ts
  packages/core-database/src/repositories/utils/limit-rows.ts
  packages/core-interfaces/src/core-database/business-repository/wallets-business-repository.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/errors.ts
  packages/core-state/src/wallets/temp-wallet-manager.ts
  packages/core-state/src/wallets/wallet-index.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/wallet-manager.ts
Labels: Complexity: High, Type: Refactor

#2847 fix(core-api): internal server error caused by invalid orderBy field
  packages/core-database-postgres/src/repositories/repository.ts
Labels: Complexity: Low, Type: Bugfix

#2838 fix: multipayment balance / vote balance
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-state/wallets/wallet-manager-multipayment.test.ts
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-transactions/src/handlers/multi-payment.ts
Labels: Complexity: High, Type: Bugfix

#2843 test(core-transactions): initial tests for transactions handlers bootstrap methods
  __tests__/integration/core-transactions/__support__/setup.ts
  __tests__/integration/core-transactions/handlers/delegate-registration.test.ts
  __tests__/integration/core-transactions/handlers/delegate-resignation.test.ts
  __tests__/integration/core-transactions/handlers/ipfs.test.ts
  __tests__/integration/core-transactions/handlers/multi-payment.test.ts
  __tests__/integration/core-transactions/handlers/multi-signature.test.ts
  __tests__/integration/core-transactions/handlers/second-signature.test.ts
  __tests__/integration/core-transactions/handlers/transfer.test.ts
  __tests__/integration/core-transactions/handlers/vote.test.ts
  packages/core-database-postgres/src/queries/state-builder/assets-by-type.sql
  packages/core-database-postgres/src/state-builder.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/vote.ts
Labels: Complexity: High, Test: Unit

#2848 perf(core-p2p): improve transactions endpoint
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/socket-server/index.ts
  packages/core-p2p/src/socket-server/payload-processor.ts
Labels: Complexity: Medium, Type: Performance

#2850 fix(core-p2p): peer discovery limit
  __tests__/unit/core-p2p/network-monitor.test.ts
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Low, Type: Bugfix

#2849 release: 2.5.14
  CHANGELOG.md
Labels: Complexity: Low, Type: Release

#2851 fix(core-p2p): ensure payload database exists
  packages/core-p2p/package.json
  packages/core-p2p/src/socket-server/payload-processor.ts
Labels: Complexity: Low, Type: Bugfix

#2852 release: 2.5.0-next.10
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-p2p/src/defaults.ts
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: High, Type: Release

#2856 refactor(core-state): expose current block for transaction handlers
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet-manager.ts
Labels: Complexity: Medium, Type: Refactor
