Repository ArkEcosystem/core, pull requests merged in 2019-11, with the labels that each got.

#3187 fix(crypto): validate address of multi payment recipients
  __tests__/unit/crypto/transactions/deserializer.test.ts
  packages/crypto/src/networks/devnet/exceptions.json
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/transactions/utils.ts
Labels: Complexity: Low, Type: Bugfix

#3190 test(e2e): update framework
  __tests__/e2e/README.md
  __tests__/e2e/bin/e2e
  __tests__/e2e/lib/docker.js
  __tests__/e2e/lib/generate.js
  __tests__/e2e/lib/run.js
Labels: Complexity: Medium, Test: Unit

#3193 fix(core-api) include typeGroup in `/transactions/fees` and `/node/fees` endpoints
  __tests__/integration/core-api/handlers/node.test.ts
  __tests__/integration/core-api/handlers/transactions.test.ts
  packages/core-api/package.json
  packages/core-api/src/handlers/node/controller.ts
  packages/core-api/src/handlers/transactions/controller.ts
  packages/core-database-postgres/src/queries/transactions/fee-statistics.sql
Labels: Complexity: Medium

#3194 refactor(core-magistrate-transactions): require static fee
  __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
  __tests__/unit/core-magistrate/handlers/business-handlers.test.ts
  __tests__/unit/core-magistrate/handlers/business-registration.test.ts
  __tests__/unit/core-magistrate/handlers/handlers.test.ts
  __tests__/unit/core-transaction-pool/dynamic-fee.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
  packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
  packages/core-transaction-pool/src/dynamic-fee.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/interfaces.ts
Labels: Complexity: Medium, Type: Refactor

#3202 fix(core-state): remove delegate.rank for resigned delegates
  packages/core-state/src/wallets/wallet-manager.ts
Labels: Complexity: Low, Type: Bugfix

#3196 fix(core): prevent snapshot commands from running if core is running
  packages/core/src/commands/snapshot/dump.ts
  packages/core/src/commands/snapshot/restore.ts
  packages/core/src/commands/snapshot/rollback.ts
  packages/core/src/commands/snapshot/truncate.ts
  packages/core/src/commands/snapshot/verify.ts
Labels: Complexity: Low, Type: Bugfix

#3201 fix(core-transactions): allow unvoting a resigned delegate
  __tests__/functional/transaction-forging/vote.test.ts
  packages/core-transactions/src/handlers/vote.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Bugfix

#3205 feat(core-api): include business asset in wallet transformer
  packages/core-api/src/handlers/wallets/transformer.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Complexity: Low, Type: Feature

#3206 ci: add dependency caching
  .github/workflows/benchmark.yml
  .github/workflows/functional.yml
  .github/workflows/test.yml
Labels: Complexity: Medium

#3208 fix(core-p2p): stricter WS/SC events/messages handling
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  packages/core-interfaces/src/core-p2p/peer-connector.ts
  packages/core-p2p/src/constants.ts
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/schemas.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Medium, Type: Bugfix

#3209 release: 2.5.28
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3215 fix(core-magistrate-transactions): check for an exception before checking for invalid fees
  packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
Labels: Complexity: Low, Type: Bugfix

#3214 chore(crypto): add static fee exceptions
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Complexity: Low, Status: Needs Review, Type: Task

#3204 refactor(core-transactions): unique ipfs hashes
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.1.transaction2ndsig.action.js
  __tests__/functional/transaction-forging/ipfs.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/ipfs.ts
Labels: Bounty: Tier 3, Complexity: Low, Status: Contributor Approved, Status: Needs Review, Type: Refactor

#3217 fix(core-transactions): add ipfs exception handling
  packages/core-transactions/src/handlers/ipfs.ts
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3220 test(core-p2p): fix mock common block
  __tests__/integration/core-p2p/peer-communicator.test.ts
Labels: Complexity: Low, Test: Unit

#3221 feat(core-api): add `isExpired` property to locks response
  __tests__/integration/core-api/utils.ts
  __tests__/unit/core-utils/lock-expiration-calculator.test.ts
  packages/core-api/src/handlers/locks/transformer.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-utils/src/index.ts
  packages/core-utils/src/lock-expiration-calculator.ts
Labels: Complexity: Medium, Status: Contributor Approved, Type: Feature

#3213 fix(core-transactions): htlc bootstrap
  __tests__/integration/core-transactions/handlers/htlc-claim.test.ts
  __tests__/integration/core-transactions/handlers/htlc-refund.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-database-postgres/src/queries/state-builder/open-locks.sql
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
Labels: Complexity: Medium, Type: Bugfix

#3199 feat(core-magistrate-transactions): ensure unique genesisHash per bridgechain
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
  __tests__/functional/transaction-forging/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/helper.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
Labels: Bounty: Tier 3, Complexity: Medium, Status: Contributor Approved, Type: Feature

#3230 chore: update to TypeScript 3.7
  package.json
  yarn.lock
Labels: Complexity: Low, Type: Task

#3227 feat(core-api): filter locks by expiration status
  __tests__/integration/core-api/handlers/locks.test.ts
  __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
  packages/core-api/src/handlers/locks/schema.ts
  packages/core-api/src/handlers/locks/transformer.ts
  packages/core-api/src/handlers/wallets/schema.ts
  packages/core-database/src/repositories/utils/filter-rows.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#3228 feat(crypto): implement Address.fromWIF method
  __tests__/unit/crypto/identities/address.test.ts
  packages/crypto/src/identities/address.ts
Labels: Complexity: Low, Type: Feature

#3226 refactor(core-api): validate expiration type based on enum
  packages/core-api/src/handlers/locks/schema.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Refactor

#3231 refactor(crypto): move verifySignatures into Transactions.Verifier
  packages/core-state/src/wallets/wallet.ts
  packages/crypto/src/transactions/verifier.ts
Labels: Complexity: Medium, Type: Refactor

#3222 fix(core-transactions): add additional bridgechain registration exception handling
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Bounty: Tier 4, Complexity: Medium, Status: Collaborator Approved, Type: Bugfix

#3234 refactor(crypro): make deserializers static
  __tests__/unit/core-magistrate/transactions/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/transactions/business-registration.test.ts
  __tests__/unit/core-magistrate/transactions/business-resgination.test.ts
  __tests__/unit/core-magistrate/transactions/business-update.test.ts
  __tests__/unit/crypto/blocks/deserializer.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  benchmark/transaction/deserialize/methods.js
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/blocks/deserializer.ts
  packages/crypto/src/blocks/factory.ts
  packages/crypto/src/transactions/deserializer.ts
  packages/crypto/src/transactions/factory.ts
Labels: Complexity: Medium, Type: Refactor

#3233 fix(core-magistrate-transactions): case insensitive bridgechain comparison
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
Labels: Bounty: Tier 6, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3229 refactor(crypto): adjust generic name schema
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  __tests__/functional/transaction-forging/business-registration.test.ts
  packages/core-jest-matchers/src/functional/rejected.ts
  packages/crypto/src/validation/schemas.ts
Labels: Bounty: Tier 4, Complexity: Medium, Type: Refactor

#3240 fix(core-api): include query in wallets/{id}/locks cache
  packages/core-api/src/handlers/wallets/methods.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3243 refactor(core-api): add schema for orderBy query param
  __tests__/integration/core-api/handlers/blocks.test.ts
  packages/core-api/src/handlers/blocks/schema.ts
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-api/src/handlers/delegates/schema.ts
  packages/core-api/src/handlers/locks/schema.ts
  packages/core-api/src/handlers/peers/schema.ts
  packages/core-api/src/handlers/shared/schemas/index.ts
  packages/core-api/src/handlers/shared/schemas/order-by.ts
  packages/core-api/src/handlers/transactions/schema.ts
  packages/core-api/src/handlers/votes/schema.ts
  packages/core-api/src/handlers/wallets/schema.ts
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Type: Refactor

#3244 fix(core-database-postgres): return early only if there are rows
  packages/core-database-postgres/src/repositories/repository.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Bugfix

#3246 refactor(crypto): use transactionId ref in lockTransactionId schema definition
  packages/crypto/src/transactions/types/schemas.ts
  packages/crypto/src/validation/schemas.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Refactor

#3247 fix(crypto): adjust genericName regex and add tests
  __tests__/functional/transaction-forging/business-registration.test.ts
  packages/crypto/src/validation/schemas.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Bugfix

#3248 refactor(core-magistrate-transactions): more verbose static fee mismatch error
  __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Refactor

#3252 fix(core-transactions): do not attempt to convert vendorfield
  packages/core-transactions/src/handlers/htlc-lock.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Bugfix

#3250 feat(core): add command to clear transaction pool
  packages/core/src/commands/pool/clear.ts
Labels: Bounty: Tier 3, Complexity: Low, Status: Contributor Approved, Type: Feature

#3253 fix(crypto): replace ipfs exception
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Complexity: Low, Status: Contributor Approved, Status: Needs Review, Type: Bugfix

#3256 fix(core-transaction-pool): wallet-manager fallback to database wallet manager findByIndex() when no "local" match
  __tests__/integration/core-transaction-pool/wallet-manager.test.ts
  packages/core-transaction-pool/src/wallet-manager.ts
Labels: Complexity: Low, Type: Bugfix

#3260 style: replace native forEach with for-of
  __tests__/e2e/lib/run.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.0.doublespend.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.1.doublespend2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/2.check-tx.test.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.0.transaction.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.1.transaction2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/2.check-tx.test.js
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-api/handlers/locks.test.ts
  __tests__/integration/core-forger/client.test.ts
  __tests__/unit/core-container/registrars/plugin.test.ts
  __tests__/unit/core-snapshots/transport/codec.test.ts
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  __tests__/unit/core-utils/round-calculator.test.ts
  __tests__/unit/crypto/blocks/block.test.ts
  __tests__/unit/crypto/blocks/deserializer.test.ts
  __tests__/unit/crypto/identities/public-key.test.ts
  __tests__/unit/crypto/transactions/__support__/index.ts
  __tests__/unit/crypto/transactions/factory.test.ts
  __tests__/unit/crypto/transactions/utils.test.ts
  __tests__/unit/crypto/utils/network-list.ts
Labels: Bounty: Tier 4, Complexity: High, Status: Collaborator Approved, Type: Task

#3258 fix(core-magistrate): use genesisHash for bridgechainId
  __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
  __tests__/functional/transaction-forging/bridgechain-update.test.ts
  __tests__/helpers/transaction-factory.ts
  __tests__/unit/core-magistrate/builders/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate/builders/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/wallet.test.ts
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-magistrate-crypto/src/builders/bridgechain-resignation.ts
  packages/core-magistrate-crypto/src/interfaces.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-resignation.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/interfaces.ts
Labels: Complexity: Medium, Type: Bugfix

#3271 fix(core-forger): don't swallow BIP38 errors
  packages/core-forger/src/delegate.ts
Labels: Complexity: Low, Type: Bugfix

#3270 fix(core): remove password flag constraint for core:forger command
  packages/core/src/commands/command.ts
Labels: Complexity: Low, Type: Bugfix

#3268 fix(core-magistrate): use wallet publicKey for business id index
  __tests__/integration/core-api/handlers/businesses.test.ts
  __tests__/unit/core-magistrate/handlers/business-registration.test.ts
  __tests__/unit/core-magistrate/wallet.test.ts
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-api/src/handlers/businesses/methods.ts
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-api/src/handlers/wallets/transformer.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/interfaces.ts
  packages/core-magistrate-transactions/src/wallet-manager.ts
Labels: Complexity: Medium, Type: Bugfix

#3275 refactor(crypto): Set transactionBaseSchema fee minimum to 0
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Task

#3278 refactor(crypto): set minimum fee on transaction types
  __tests__/unit/crypto/transactions/schemas.test.ts
  packages/crypto/src/transactions/types/schemas.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Refactor

#3272 chore: handle Debian/Ubuntu derivate NodeJS install
  install.sh
Labels: Complexity: Low

#3280 test(core-magistrate): business / bridgechain e2e workflow
  __tests__/e2e/lib/run.js
  __tests__/e2e/lib/utils/test-utils.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/1.0.business-registration.action.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/1.1.check-business-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/2.0.business-update.action.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/2.1.check-business-update.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/3.0.bridgechain-registration.action.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/3.1.check-bridgechain-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/4.0.bridgechain-update.action.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/4.1.check-bridgechain-update.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/5.0.bridgechain-resignation.action.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/5.1.check-bridgechain-resignation.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/6.0.business-resignation.action.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/6.1.check-business-resignation.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/config.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/utils.js
  __tests__/e2e/tests/scenarios/scenario1/config.js
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Complexity: High, Test: Unit

#3283 chore: better handling Debian/Ubuntu derivatives NodeJS install
  install.sh
Labels: Complexity: Low

#3255 feat(core-magistrate-crypto): add ports to bridgechain registration/update
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/3.1.check-bridgechain-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/4.1.check-bridgechain-update.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/utils.js
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
  __tests__/functional/transaction-forging/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/builders/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/helper.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/wallet.test.ts
  packages/core-magistrate-crypto/src/builders/bridgechain-registration.ts
  packages/core-magistrate-crypto/src/builders/bridgechain-update.ts
  packages/core-magistrate-crypto/src/interfaces.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-resignation.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
  packages/core-magistrate-crypto/src/transactions/utils/bridgechain-schemas.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  yarn.lock
Labels: Bounty: Tier 2, Complexity: Medium, Status: Collaborator Approved, Status: Needs Review, Type: Feature

#3276 feat: Make roundInfo optional in databaseService.getActiveDelegates()
  __tests__/integration/core-blockchain/blockchain.test.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-service.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Status: Needs Testcase

#3293 fix(core-api): search by genesisHash in show method
  packages/core-api/src/handlers/bridgechains/methods.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Bugfix

#3292 feat(core-api): allow searching businesses and bridgechains by isResigned
  __tests__/integration/core-api/handlers/bridgechains.test.ts
  __tests__/integration/core-api/handlers/businesses.test.ts
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-api/src/handlers/delegates/transformer.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Complexity: Medium, Status: Contributor Approved, Type: Feature

#3296 refactor(crypto): fix genesis and exception transactions cache
  packages/crypto/src/utils/base58.ts
  packages/crypto/src/utils/index.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Refactor

#3291 fix(core-transactions): update sender's wallet after validation
  packages/core-transactions/src/handlers/transaction.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Bugfix

#3304 fix(core-transactions): add missing delegate attributes to walletAttributes
  packages/core-transactions/src/handlers/delegate-registration.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Status: Member Approved, Type: Bugfix
