Repository ArkEcosystem/core, pull requests merged in 2019-04, with the labels that each got.

#2352 refactor: replace various any with types, property visibility and interface naming
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-database/__fixtures__/mock-database-model.ts
  deprecated/core-graphql/src/repositories/repository.ts
  packages/core-api/src/versions/1/peers/controller.ts
  packages/core-api/src/versions/1/shared/controller.ts
  packages/core-api/src/versions/1/transactions/controller.ts
  packages/core-api/src/versions/2/shared/controller.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/machines/actions/fork.ts
  packages/core-blockchain/src/processor/handlers/block-handler.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-container/src/config/index.ts
  packages/core-container/src/config/network.ts
  packages/core-container/src/container.ts
  packages/core-container/src/environment.ts
  packages/core-container/src/registrars/plugin.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/models/model.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/repositories/repository.ts
  packages/core-database/src/database-service-factory.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/utils/search-parameter-converter.ts
  packages/core-interfaces/package.json
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-container/container.ts
  packages/core-interfaces/src/core-database/database-model/database-model.ts
  packages/core-interfaces/src/core-database/database-repository/repository.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-p2p/monitor.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-interfaces/src/shared/config.ts
  packages/core-json-rpc/src/server/services/database.ts
  packages/core-p2p/src/court/guard.ts
  packages/core-p2p/src/interfaces.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/plugin.ts
  packages/core-p2p/src/server/versions/1/handlers.ts
  packages/core-tester-cli/src/signer.ts
  packages/crypto/src/interfaces.ts
  packages/crypto/src/models/block.ts
  packages/crypto/src/transactions/serializers/block.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor

#2353 fix(core-blockchain): initialize active delegates on startup
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/mocks/blockchain.ts
  __tests__/unit/core-blockchain/mocks/database.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/crypto/src/crypto/crypto.ts
  packages/crypto/src/transactions/serializers/transaction.ts
Labels: Complexity: Medium, Type: Bugfix

#2354 release: 2.3.0-next.4
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2355 test: add TransactionFactory and RestClient as test helpers
  .circleci/config.yml
  .circleci/generateConfig.js
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/functional/transaction-forging/delegate-registration.test.ts
  __tests__/functional/transaction-forging/second-signature-registration.test.ts
  __tests__/functional/transaction-forging/transfer.test.ts
  __tests__/functional/transaction-forging/vote.test.ts
  __tests__/helpers/index.ts
  __tests__/helpers/rest-client.ts
  __tests__/helpers/transaction-factory.ts
  __tests__/integration/core-api/v2/handlers/transactions.test.ts
  __tests__/integration/core-json-rpc/blocks.test.ts
  __tests__/integration/core-json-rpc/wallets.test.ts
  __tests__/integration/core-p2p/server/1.test.ts
  __tests__/integration/core-p2p/server/internal.test.ts
  __tests__/integration/core-tester-cli/commands/debug/identity.test.ts
  __tests__/integration/core-transaction-pool/__fixtures__/transactions.ts
  __tests__/integration/core-transaction-pool/guard.test.ts
  __tests__/integration/core-transaction-pool/pool-wallet-manager.test.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/core-database/repositories/transactions-business-repository.test.ts
  __tests__/unit/core-database/wallet-manager.test.ts
  __tests__/unit/core-database/wallet.test.ts
  __tests__/unit/core-forger/manager.test.ts
  __tests__/unit/core-jest-matchers/transactions/valid-second-signature.test.ts
  __tests__/unit/core-logger-pino/logger.test.ts
  __tests__/unit/core-logger-signale/logger.test.ts
  __tests__/unit/core-logger-winston/logger.test.ts
  __tests__/unit/core-transaction-pool/__fixtures__/transactions.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/dynamic-fee.test.ts
  __tests__/unit/core-transaction-pool/guard.test.ts
  __tests__/unit/crypto/models/block.test.ts
  __tests__/unit/crypto/models/delegate.test.ts
  __tests__/unit/crypto/transactions/deserializers/transaction.test.ts
  __tests__/unit/shared/logger.ts
  __tests__/utils/generators/index.ts
  __tests__/utils/generators/transactions.ts
  packages/core-json-rpc/src/server/methods/wallets/transactions.ts
  packages/core-json-rpc/src/server/services/network.ts
  packages/core-logger-winston/package.json
  packages/crypto/src/transactions/deserializers/transaction.ts
  packages/crypto/src/transactions/serializers/transaction.ts
Labels: Complexity: Undetermined, Test: Functional, Test: Integration, Test: Unit

#2356 fix(crypto): use calculated id
  packages/crypto/src/crypto/crypto.ts
Labels: Complexity: Low, Type: Bugfix

#2357 refactor(core-api): remove active delegates endpoint
  __tests__/integration/core-api/v2/handlers/delegates.test.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  packages/core-api/src/versions/2/delegates/controller.ts
  packages/core-api/src/versions/2/delegates/methods.ts
  packages/core-api/src/versions/2/delegates/routes.ts
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/delegates-business-repository.ts
  packages/core-p2p/src/peer-verifier.ts
Labels: Bounty: Tier 4, Complexity: Medium, Status: Collaborator Approved, Type: Refactor

#2358 refactor(core-database): round logic
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/wallet.test.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-database/src/wallet.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-database/wallet-manager.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-utils/src/round-calculator.ts
Labels: Complexity: Medium, Type: Refactor

#2359 refactor(core-p2p): don't test private methods in the peer guard
  __tests__/unit/core-p2p/guard.test.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/court/index.ts
  packages/core-p2p/src/court/offences.ts
  packages/core-p2p/src/guard.ts
  packages/core-p2p/src/index.ts
  packages/core-p2p/src/interfaces.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer.ts
Labels: Complexity: High, Type: Refactor

#2360 refactor(core-p2p): remove height difference ban
  __tests__/unit/core-p2p/guard.test.ts
  packages/core-p2p/src/guard.ts
Labels: Complexity: Low, Type: Refactor

#2361 refactor(core-forger): check all hosts for 1 second to find a match
  packages/core-forger/package.json
  packages/core-forger/src/client.ts
  packages/core-p2p/src/socket-server/broker.ts
  packages/core-p2p/src/socket-server/index.ts
Labels: Complexity: Low, Type: Refactor

#2363 fix(core-p2p): frequent peer timeout errors
  packages/core-container/src/config/loaders/file-loader.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/server/plugins/accept-request.ts
Labels: Complexity: Low, Type: Bugfix

#2366 fix(core-p2p): remove ping timeout ban
  __tests__/unit/core-p2p/court/guard.test.ts
  __tests__/unit/core-p2p/peer.test.ts
  packages/core-interfaces/src/core-p2p/monitor.ts
  packages/core-p2p/src/court/offences.ts
  packages/core-p2p/src/errors.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/server/plugins/accept-request.ts
Labels: Complexity: Medium, Type: Bugfix

#2367 release: 2.3.0-next.5
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2368 test: fix core-p2p tests
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/generateConfig.js
  __tests__/integration/core-p2p/monitor.test.ts
  __tests__/integration/core-p2p/peer.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/guard.test.ts
  __tests__/unit/core-p2p/mocks/core-container.ts
  __tests__/unit/core-p2p/monitor.test.ts
  __tests__/unit/core-p2p/peer.test.ts
  packages/core-interfaces/src/core-p2p/monitor.ts
Labels: Complexity: High, Test: Unit

#2372 docs: 2.3.0 changelog
  CHANGELOG.md
Labels: Complexity: Low, Type: Documentation

#2369 feat(core-api): add rounds endpoint
  __tests__/integration/core-api/v2/handlers/rounds.test.ts
  packages/core-api/src/services/transformer.ts
  packages/core-api/src/versions/2/index.ts
  packages/core-api/src/versions/2/rounds/controller.ts
  packages/core-api/src/versions/2/rounds/index.ts
  packages/core-api/src/versions/2/rounds/methods.ts
  packages/core-api/src/versions/2/rounds/routes.ts
  packages/core-api/src/versions/2/rounds/schema.ts
  packages/core-api/src/versions/2/rounds/transformer.ts
Labels: Bounty: Tier 2, Complexity: Medium, Status: Collaborator Approved, Type: Feature

#2370 fix: cope with dynamic round sizes
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/mocks/container.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/mocks/core-container.ts
  __tests__/unit/core-p2p/mocks/core-container.ts
  __tests__/unit/core-utils/mocks/core-container.ts
  __tests__/unit/core-utils/round-calculator.test.ts
  __tests__/unit/crypto/crypto/slots.test.ts
  packages/core-api/src/versions/1/delegates/controller.ts
  packages/core-api/src/versions/1/delegates/schema.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-blockchain/src/utils/validate-generator.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-forger/src/manager.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-database/wallet-manager.ts
  packages/core-interfaces/src/shared/index.ts
  packages/core-interfaces/src/shared/interfaces.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/server/versions/internal/handlers/rounds.ts
  packages/core-snapshots/package.json
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/manager.ts
  packages/core-transaction-pool/src/pool-wallet-manager.ts
  packages/core-utils/package.json
  packages/core-utils/src/round-calculator.ts
  packages/core-vote-report/src/handler.ts
  packages/crypto/src/crypto/slots.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/managers/config.ts
Labels: Complexity: High, Type: Bugfix

#2376 fix: insert the genesis block as soon as the database is ready
  __tests__/unit/core-blockchain/state-machine.test.ts
  packages/core-api/src/services/transformer.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database/src/database-service.ts
Labels: Complexity: Low, Type: Bugfix

#2380 fix(core-logger-pino): initial rotation
  __tests__/unit/core-logger-pino/logger.test.ts
  packages/core-logger-pino/src/defaults.ts
  packages/core-logger-pino/src/driver.ts
Labels: Complexity: Low, Type: Bugfix

#2373 test(core-logger): unit tests for logger and manager
  __tests__/unit/core-logger/__stubs__/logger.ts
  __tests__/unit/core-logger/logger.test.ts
  __tests__/unit/core-logger/manager.test.ts
  packages/core-interfaces/src/core-logger/logger.ts
  packages/core-logger-winston/src/driver.ts
  packages/core-logger/src/logger.ts
Labels: Complexity: Medium, Test: Unit

#2377 feat(crypto): add Block.fromHex, Block.fromBytes and Block.fromData methods
  __tests__/integration/core-api/v1/handlers/transactions.test.ts
  __tests__/integration/core-api/v2/handlers/blocks.test.ts
  __tests__/integration/core-api/v2/handlers/delegates.test.ts
  __tests__/integration/core-api/v2/handlers/transactions.test.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-database-postgres/connection.test.ts
  __tests__/integration/core-forger/__fixtures__/blocks.ts
  __tests__/integration/core-forger/mocks/core-container.ts
  __tests__/integration/core-json-rpc/transactions.test.ts
  __tests__/integration/core-json-rpc/wallets.test.ts
  __tests__/integration/core-tester-cli/commands/make/block.test.ts
  __tests__/integration/core-transaction-pool/guard.test.ts
  __tests__/integration/core-transaction-pool/pool-wallet-manager.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/core-blockchain/processor/handlers/accept-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/exception-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-blockchain/state-storage.test.ts
  __tests__/unit/core-container/__stubs__/config/genesisBlock.json
  __tests__/unit/core-database/wallet-manager.test.ts
  __tests__/unit/core-forger/__fixtures__/block.ts
  __tests__/unit/core-forger/mocks/core-container.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/crypto/models/block.test.ts
  __tests__/utils/config/testnet/genesisBlock.json
  __tests__/utils/config/unitnet/genesisBlock.json
  __tests__/utils/fixtures/testnet/block-model.ts
  __tests__/utils/fixtures/unitnet/block-model.ts
  benchmark/block/create.js
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-container/src/container.ts
  packages/core-database/src/database-service.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/socket-server/versions/peer/index.ts
  packages/core-p2p/src/socket-server/versions/peer/schema.ts
  packages/core-tester-cli/src/commands/debug/deserialize.ts
  packages/core-tester-cli/src/commands/debug/verify.ts
  packages/crypto/src/models/block.ts
  packages/crypto/src/networks/devnet/genesisBlock.json
  packages/crypto/src/networks/mainnet/genesisBlock.json
  packages/crypto/src/networks/testnet/genesisBlock.json
  packages/crypto/src/networks/unitnet/genesisBlock.json
Labels: Complexity: Medium, Status: In Progress, Type: Feature

#2378 refactor(core-p2p): types, method visibility and various fixes
  __tests__/integration/core-p2p/network-monitor.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/mocks/p2p/peer-processor.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/peer-processor.test.ts
  packages/core-interfaces/src/core-p2p/peer-communicator.ts
  packages/core-interfaces/src/core-p2p/peer-processor.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Medium, Status: In Progress, Type: Refactor

#2382 fix(core-p2p): avoid duplicate connections with the same peer
  __tests__/integration/core-p2p/network-monitor.test.ts
  packages/core-api/src/versions/1/peers/transformer.ts
  packages/core-api/src/versions/2/peers/transformer.ts
  packages/core-interfaces/src/core-p2p/peer-connector.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/utils/socket.ts
Labels: Complexity: Low, Type: Bugfix

#2383 fix(core-p2p): set headers on peer instance
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Type: Bugfix

#2384 fix(core-tester-cli): init config manager from network preset
  __tests__/integration/core-tester-cli/commands/send/delegate-registration.test.ts
  __tests__/integration/core-tester-cli/commands/send/second-signature.test.ts
  __tests__/integration/core-tester-cli/commands/send/transfer.test.ts
  __tests__/integration/core-tester-cli/commands/send/vote.test.ts
  packages/core-tester-cli/src/commands/command.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#2375 refactor(core-container): bind plugin options before registering the plugin
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/rebuild-db.sh
  .codecov.yml
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-blockchain/__support__/setup.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-database-postgres/__support__/setup.ts
  __tests__/integration/core-p2p/__support__/mock-socket-server/worker.js
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/integration/core-p2p/network-monitor.test.ts
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/integration/core-transaction-pool/__support__/setup.ts
  __tests__/integration/core-transaction-pool/guard.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/mocks/container.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-blockchain/state-storage.test.ts
  __tests__/unit/core-container/container.test.ts
  __tests__/unit/core-container/registrars/plugin.test.ts
  __tests__/unit/core-p2p/mocks/core-container.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/peer-guard.test.ts
  __tests__/unit/core-transaction-pool/dynamic-fee.test.ts
  __tests__/unit/core-transaction-pool/guard.test.ts
  __tests__/unit/core-transaction-pool/mocks/core-container.ts
  packages/core-blockchain/src/config.ts
  packages/core-blockchain/src/index.ts
  packages/core-blockchain/src/plugin.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-blockchain/src/state-storage.ts
  packages/core-container/src/container.ts
  packages/core-container/src/environment.ts
  packages/core-container/src/registrars/plugin.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-interfaces/src/core-container/container.ts
  packages/core-interfaces/src/index.ts
  packages/core-interfaces/src/shared/config.ts
  packages/core-interfaces/src/shared/index.ts
  packages/core-p2p/src/config.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/network-state.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/plugin.ts
  packages/core-p2p/src/socket-server/utils/get-headers.ts
  packages/core-p2p/src/socket-server/versions/utils/index.ts
  packages/core-p2p/src/socket-server/worker.ts
  packages/core-transaction-pool/src/config.ts
  packages/core-transaction-pool/src/dynamic-fee/matcher.ts
  packages/core-transaction-pool/src/index.ts
  packages/core-transaction-pool/src/plugin.ts
Labels: Complexity: Medium, Status: In Progress, Type: Refactor

#2387 refactor(core-container): pass suffix to container
  packages/core-container/src/container.ts
  packages/core-interfaces/src/core-container/container.ts
  packages/core-logger-pino/package.json
  packages/core-logger-pino/src/driver.ts
  packages/core-logger/package.json
  packages/core-logger/src/factory.ts
  packages/core/src/commands/command.ts
  packages/core/src/commands/core/run.ts
  packages/core/src/commands/core/start.ts
  packages/core/src/commands/forger/run.ts
  packages/core/src/commands/forger/start.ts
  packages/core/src/commands/relay/run.ts
  packages/core/src/commands/relay/start.ts
  packages/core/src/shared/run.ts
  packages/core/src/shared/start.ts
Labels: Complexity: Medium, Type: Refactor

#2388 feat(core-api): return slip44 and wif via node/configuration
  __tests__/integration/core-api/v2/handlers/node.test.ts
  __tests__/unit/core-container/__stubs__/config/network.json
  packages/core-api/src/versions/2/node/controller.ts
  packages/core-container/src/config/schema.ts
  packages/crypto/src/networks/devnet/network.json
  packages/crypto/src/networks/mainnet/network.json
  packages/crypto/src/networks/testnet/network.json
  packages/crypto/src/networks/unitnet/network.json
Labels: Complexity: Low, Type: Feature

#2389 fix(core): pass cli flags correctly
  packages/core/src/commands/command.ts
  packages/core/src/commands/core/run.ts
  packages/core/src/commands/core/start.ts
  packages/core/src/commands/forger/run.ts
  packages/core/src/commands/forger/start.ts
  packages/core/src/commands/relay/run.ts
  packages/core/src/commands/relay/start.ts
  packages/core/src/shared/run.ts
  packages/core/src/shared/start.ts
Labels: Complexity: Medium, Type: Bugfix

#2390 fix(core-p2p): sync with network
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Low, Type: Bugfix

#2395 chore(crypto): bump vendorFieldLength and blockid activation heights
  packages/crypto/src/networks/mainnet/milestones.json
Labels: Complexity: Low

#2396 feat(core-event-emitter): add off method
  packages/core-event-emitter/src/emitter.ts
Labels: Complexity: Low, Type: Feature

#2394 fix(crypto): validate address is on network
  __tests__/unit/core-transaction-pool/__fixtures__/transactions.ts
  __tests__/unit/core-transaction-pool/guard.test.ts
  __tests__/unit/crypto/transactions/schemas.test.ts
  __tests__/unit/crypto/transactions/transaction.test.ts
  __tests__/unit/crypto/validation/ajv-wrapper.test.ts
  packages/crypto/src/networks/devnet/exceptions.json
  packages/crypto/src/validation/keywords.ts
  packages/crypto/src/validation/schemas.ts
Labels: Complexity: Low, Type: Bugfix

#2393 feat(core-api): add v2/node/fees endpoint
  __tests__/unit/core-database/repositories/transactions-business-repository.test.ts
  packages/core-api/package.json
  packages/core-api/src/repositories/transactions.ts
  packages/core-api/src/versions/1/loader/controller.ts
  packages/core-api/src/versions/2/node/controller.ts
  packages/core-api/src/versions/2/node/routes.ts
  packages/core-api/src/versions/2/node/schema.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  yarn.lock
Labels: Complexity: Medium, Type: Feature

#2400 refactor(core-p2p): simplify handlers and remove dead code
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/blockchain.test.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/blocks.test.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/network.test.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/rounds.test.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/transactions.test.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/utils.test.ts
  __tests__/unit/core-p2p/socket-server/versions/peer/index.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core-p2p/src/socket-server/versions/index.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-p2p/src/socket-server/versions/internal/handlers/blockchain.ts
  packages/core-p2p/src/socket-server/versions/internal/handlers/blocks.ts
  packages/core-p2p/src/socket-server/versions/internal/handlers/network.ts
  packages/core-p2p/src/socket-server/versions/internal/handlers/rounds.ts
  packages/core-p2p/src/socket-server/versions/internal/handlers/transactions.ts
  packages/core-p2p/src/socket-server/versions/internal/handlers/utils.ts
  packages/core-p2p/src/socket-server/versions/internal/index.ts
  packages/core-p2p/src/socket-server/versions/internal/schemas.ts
  packages/core-p2p/src/socket-server/versions/peer/index.ts
  packages/core-p2p/src/socket-server/versions/utils.ts
  packages/core-p2p/src/socket-server/versions/utils/index.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: High, Type: Refactor

#2399 refactor(core-p2p): make SocketCluster configurable
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/utils/config/testnet/plugins.js
  __tests__/utils/config/unitnet/plugins.js
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
Labels: Complexity: Medium, Type: Refactor

#2401 refactor(core-p2p): suspend peers if they exceed the rate limit
  __tests__/integration/core-forger/client.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/mocks/scworker.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/rounds.test.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/transactions.test.ts
  __tests__/unit/core-p2p/socket-server/worker.test.ts
  packages/core-forger/src/client.ts
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-p2p/src/socket-server/versions/utils.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: High, Type: Refactor

#2403 refactor(core-database): return boolean from verifyBlockchain and log errors
  __tests__/integration/core-database-postgres/connection.test.ts
  __tests__/unit/core-blockchain/mocks/database.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-service.ts
Labels: Complexity: Low, Type: Refactor

#2404 fix(core-database): handle unknown transaction search
  packages/core-database/src/repositories/transactions-business-repository.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#2406 release: 2.3.0-next.6
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2405 fix: prevent wallet managers from indexing/creating ghost wallets
  packages/core-database/src/wallet-manager.ts
  packages/core-transaction-pool/src/pool-wallet-manager.ts
Labels: Bounty: Tier 3, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#2402 refactor(core-p2p): throw response errors instead of returning a success boolean
  __tests__/integration/core-forger/client.test.ts
  __tests__/integration/core-p2p/__support__/mock-socket-server/manager.ts
  __tests__/integration/core-p2p/network-monitor.test.ts
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/integration/core-p2p/peer-verifier.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/blocks.test.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/rounds.test.ts
  __tests__/unit/core-p2p/socket-server/versions/peer/index.test.ts
  __tests__/unit/core-utils/is-blocked-chained.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-blockchain/src/utils/index.ts
  packages/core-forger/src/client.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-p2p/src/errors.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/reply-schemas.ts
  packages/core-p2p/src/schemas.ts
  packages/core-p2p/src/socket-server/errors.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core-p2p/src/socket-server/utils/validate.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-p2p/src/socket-server/versions/peer/index.ts
  packages/core-p2p/src/socket-server/versions/peer/schema.ts
  packages/core-p2p/src/utils/is-valid-peer.ts
  packages/core-utils/src/index.ts
  packages/core-utils/src/is-block-chained.ts
Labels: Complexity: Medium, Type: Refactor

#2408 refactor(core-p2p): store connection errors in connector
  __tests__/unit/core-p2p/peer-guard.test.ts
  packages/core-interfaces/src/core-p2p/peer-connector.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
Labels: Complexity: Low, Type: Refactor

#2409 refactor(core-p2p): suspend a peer directly with the noCommonBlocks punishment
  __tests__/unit/core-p2p/peer-guard.test.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer.ts
Labels: Complexity: Low, Type: Refactor

#2410 refactor(p2p): remove the status property from peers
  packages/core-api/src/versions/1/peers/controller.ts
  packages/core-api/src/versions/2/peers/controller.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/peer.ts
Labels: Complexity: Low, Type: Refactor

#2411 refactor(core-p2p): add peer state interface
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
Labels: Complexity: Low, Type: Refactor

#2412 refactor(core-forger): add interfaces, type hints and remove comments
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-forger/client.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-forger/manager.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-forger/src/client.ts
  packages/core-forger/src/delegate.ts
  packages/core-forger/src/interfaces.ts
  packages/core-forger/src/manager.ts
  packages/core-forger/src/plugin.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-p2p/src/utils/socket.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/interfaces/block.ts
Labels: Complexity: High, Type: Refactor

#2413 refactor: pass IBlockData instead of IBlock to isBlockChained
  __tests__/unit/core-utils/is-blocked-chained.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-utils/src/is-block-chained.ts
Labels: Complexity: Medium, Type: Refactor

#2417 refactor(crypto): remove extraneous Client class
  __tests__/unit/crypto/client.test.ts
  __tests__/unit/crypto/crypto/crypto.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/delegate-registration.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/delegate-resignation.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/ipfs.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/multi-payment.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/multi-signature.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/second-signature.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/timelock-transfer.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/transfer.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/vote.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/transactions/transaction.test.ts
  packages/core-tester-cli/src/signer.ts
  packages/crypto/src/client.ts
  packages/crypto/src/identities/keys.ts
  packages/crypto/src/index.ts
  packages/crypto/src/managers/config.ts
Labels: Complexity: Medium, Status: In Progress, Type: Refactor

#2418 refactor(crypto): add more type hints
  __tests__/unit/crypto/blocks/block.test.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/blocks/deserializer.ts
  packages/crypto/src/blocks/serializer.ts
  packages/crypto/src/crypto/crypto.ts
  packages/crypto/src/crypto/hash-algorithms.ts
  packages/crypto/src/crypto/message.ts
  packages/crypto/src/crypto/slots.ts
  packages/crypto/src/identities/address.ts
  packages/crypto/src/identities/wif.ts
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/managers/config.ts
  packages/crypto/src/managers/fee.ts
  packages/crypto/src/managers/network.ts
  packages/crypto/src/transactions/builders/transactions/delegate-registration.ts
  packages/crypto/src/transactions/builders/transactions/delegate-resignation.ts
  packages/crypto/src/transactions/builders/transactions/ipfs.ts
  packages/crypto/src/transactions/builders/transactions/multi-payment.ts
  packages/crypto/src/transactions/builders/transactions/multi-signature.ts
  packages/crypto/src/transactions/builders/transactions/second-signature.ts
  packages/crypto/src/transactions/builders/transactions/timelock-transfer.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
  packages/crypto/src/transactions/builders/transactions/transfer.ts
  packages/crypto/src/transactions/builders/transactions/vote.ts
  packages/crypto/src/transactions/deserializer.ts
  packages/crypto/src/transactions/registry.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/transactions/types/delegate-registration.ts
  packages/crypto/src/transactions/types/ipfs.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/transactions/types/multi-signature.ts
  packages/crypto/src/transactions/types/schemas.ts
  packages/crypto/src/transactions/types/second-signature.ts
  packages/crypto/src/transactions/types/timelock-transfer.ts
  packages/crypto/src/transactions/types/transaction.ts
  packages/crypto/src/transactions/types/transfer.ts
  packages/crypto/src/transactions/types/vote.ts
  packages/crypto/src/utils/bignum.ts
  packages/crypto/src/validation/keywords.ts
Labels: Complexity: High, Status: In Progress, Type: Refactor

#2421 refactor(core-database-postgres): add type hints and return types
  __tests__/unit/core-database/repositories/blocks-business-repository.test.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-database/repositories/transactions-business-repository.test.ts
  packages/core-api/src/repositories/blocks.ts
  packages/core-api/src/repositories/index.ts
  packages/core-api/src/repositories/repository.ts
  packages/core-api/src/repositories/transactions.ts
  packages/core-database-postgres/src/interfaces.ts
  packages/core-database-postgres/src/models/block.ts
  packages/core-database-postgres/src/models/migration.ts
  packages/core-database-postgres/src/models/model.ts
  packages/core-database-postgres/src/models/round.ts
  packages/core-database-postgres/src/models/transaction.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/repositories/blocks.ts
  packages/core-database-postgres/src/repositories/migrations.ts
  packages/core-database-postgres/src/repositories/repository.ts
  packages/core-database-postgres/src/repositories/rounds.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/blocks-business-repository.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/blocks-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/delegates-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/wallets-business-repository.ts
  packages/core-interfaces/src/core-database/database-connection.ts
  packages/core-interfaces/src/core-database/database-repository/blocks-repository.ts
  packages/core-interfaces/src/core-database/database-repository/repository.ts
  packages/core-interfaces/src/core-database/database-repository/rounds-repository.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  packages/core-interfaces/src/core-database/database-repository/wallets-repository.ts
Labels: Complexity: Undetermined, Status: In Progress, Type: Refactor

#2422 refactor(core-json-rpc): reduce complexity and add types
  __tests__/integration/core-json-rpc/__support__/request.ts
  __tests__/integration/core-json-rpc/__support__/setup.ts
  __tests__/integration/core-json-rpc/blocks.test.ts
  __tests__/integration/core-json-rpc/transactions.test.ts
  __tests__/integration/core-json-rpc/wallets.test.ts
  packages/core-json-rpc/src/interfaces.ts
  packages/core-json-rpc/src/server/index.ts
  packages/core-json-rpc/src/server/methods/blocks/info.ts
  packages/core-json-rpc/src/server/methods/blocks/latest.ts
  packages/core-json-rpc/src/server/methods/blocks/transactions.ts
  packages/core-json-rpc/src/server/methods/index.ts
  packages/core-json-rpc/src/server/methods/transactions/bip38/create.ts
  packages/core-json-rpc/src/server/methods/transactions/broadcast.ts
  packages/core-json-rpc/src/server/methods/transactions/create.ts
  packages/core-json-rpc/src/server/methods/transactions/info.ts
  packages/core-json-rpc/src/server/methods/wallets/bip38/create.ts
  packages/core-json-rpc/src/server/methods/wallets/bip38/show.ts
  packages/core-json-rpc/src/server/methods/wallets/create.ts
  packages/core-json-rpc/src/server/methods/wallets/info.ts
  packages/core-json-rpc/src/server/methods/wallets/transactions.ts
  packages/core-json-rpc/src/server/modules/blocks.ts
  packages/core-json-rpc/src/server/modules/index.ts
  packages/core-json-rpc/src/server/modules/transactions.ts
  packages/core-json-rpc/src/server/modules/wallets.ts
  packages/core-json-rpc/src/server/services/database.ts
  packages/core-json-rpc/src/server/services/network.ts
  packages/core-json-rpc/src/server/services/processor.ts
  packages/core-json-rpc/src/server/utils.ts
  packages/core-json-rpc/src/server/utils/bip38-keys.ts
  packages/core-json-rpc/src/server/utils/decrypt-wif.ts
Labels: Complexity: High, Status: In Progress, Type: Refactor

#2424 refactor(core-webhooks): drop no longer needed pagination
  __tests__/unit/core-webhooks/database.test.ts
  packages/core-json-rpc/src/server/modules.ts
  packages/core-json-rpc/src/server/modules/blocks.ts
  packages/core-json-rpc/src/server/modules/index.ts
  packages/core-json-rpc/src/server/modules/transactions.ts
  packages/core-json-rpc/src/server/modules/wallets.ts
  packages/core-webhooks/package.json
  packages/core-webhooks/src/database.ts
  packages/core-webhooks/src/listener.ts
  packages/core-webhooks/src/server/index.ts
  packages/core-webhooks/src/server/schema.ts
  packages/core-webhooks/src/server/utils.ts
  yarn.lock
Labels: Complexity: High, Type: Refactor

#2425 feat(core-json-rpc): allow setting a vendor field for transactions
  __tests__/integration/core-json-rpc/transactions.test.ts
  packages/core-json-rpc/src/server/modules.ts
Labels: Complexity: Medium

#2427 refactor: add more types and interfaces
  __tests__/unit/core-forger/manager.test.ts
  __tests__/unit/crypto/blocks/block.test.ts
  packages/core-api/package.json
  packages/core-container/src/config/file-loader.ts
  packages/core-container/src/config/index.ts
  packages/core-database-postgres/package.json
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/models/model.ts
  packages/core-database-postgres/src/repositories/repository.ts
  packages/core-database-postgres/src/sql/query-executor.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-elasticsearch/src/indices/base.ts
  packages/core-forger/src/manager.ts
  packages/core-forger/src/plugin.ts
  packages/core-interfaces/package.json
  packages/core-json-rpc/src/interfaces.ts
  packages/core-json-rpc/src/server/index.ts
  packages/core-json-rpc/src/server/modules.ts
  packages/core-json-rpc/src/server/services/database.ts
  packages/core-json-rpc/src/server/services/processor.ts
  packages/core-json-rpc/src/server/utils.ts
  packages/core-logger-winston/package.json
  packages/core-logger-winston/src/formatter.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/interfaces.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/utils/restore-peers.ts
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-utils/src/delegate-calculator.ts
  packages/core-utils/src/supply-calculator.ts
  packages/core-vote-report/src/handler.ts
  packages/core/package.json
  packages/crypto/package.json
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/transactions/builders/transactions/ipfs.ts
  yarn.lock
Labels: Complexity: Medium, Status: In Progress, Type: Refactor

#2430 refactor: block broadcast when block comes from forger
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/state-storage.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-blockchain/state-storage.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
Labels: Complexity: Low, Type: Refactor

#2428 fix(core-database): don't swallow errors in buildWallets
  __tests__/unit/core-database/__fixtures__/database-connection-stub.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-connection.ts
Labels: Complexity: Low, Type: Bugfix

#2432 fix(core-database): broken genesis wallet check
  packages/core-database-postgres/src/integrity-verifier.ts
Labels: Complexity: Low, Type: Bugfix

#2431 fix(core-database): wrong delegate order after start up
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-database/wallet-manager.test.ts
  packages/core-api/src/versions/2/delegates/methods.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-interfaces/src/core-database/wallet-manager.ts
Labels: Complexity: Medium, Type: Bugfix

#2433 feat(core-p2p): parallel block download
  __tests__/unit/core-p2p/network-monitor.test.ts
  packages/core-interfaces/src/core-p2p/network-monitor.ts
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Medium, Type: Feature

#2434 refactor(core-database-postgres): throw an error if there is a wallet integrity issue
  packages/core-database-postgres/src/integrity-verifier.ts
Labels: Complexity: Low, Status: In Progress, Type: Refactor

#2435 docs: 2.3.0 changelog
  CHANGELOG.md
Labels: Complexity: Low, Type: Documentation

#2437 feat(crypto): implement TransactionFactory
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/wallet-manager.test.ts
  __tests__/unit/core-forger/manager.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/transactions/transaction.test.ts
  benchmark/transaction/create/0.js
  packages/core-api/src/versions/1/transactions/transformer.ts
  packages/core-api/src/versions/2/transactions/transformer.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database/src/database-service.ts
  packages/core-elasticsearch/src/indices/transactions.ts
  packages/core-forger/src/manager.ts
  packages/core-snapshots/src/transport/codec.ts
  packages/core-snapshots/src/transport/verification.ts
  packages/core-tester-cli/src/commands/debug/deserialize.ts
  packages/core-tester-cli/src/commands/debug/serialize.ts
  packages/core-tester-cli/src/commands/debug/verify-second-signature.ts
  packages/core-tester-cli/src/commands/debug/verify.ts
  packages/core-transaction-pool/src/guard.ts
  packages/core-transaction-pool/src/storage.ts
  packages/crypto/src/blocks/deserializer.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
  packages/crypto/src/transactions/factory.ts
  packages/crypto/src/transactions/index.ts
  packages/crypto/src/transactions/types/transaction.ts
Labels: Complexity: High, Type: Feature

#2438 test(crypto): unit test the BlockFactory and TransactionFactory
  __tests__/unit/crypto/blocks/block.test.ts
  __tests__/unit/crypto/blocks/factory.test.ts
  __tests__/unit/crypto/transactions/factory.test.ts
  packages/crypto/src/blocks/factory.ts
  packages/crypto/src/transactions/factory.ts
  packages/crypto/src/transactions/serializer.ts
Labels: Complexity: Medium, Test: Unit

#2440 refactor(core-event-emitter): extend the node.js event emitter
  __tests__/unit/core-event-emitter/emitter.test.ts
  packages/core-event-emitter/src/emitter.ts
Labels: Complexity: Medium, Type: Refactor

#2442 test(core-json-rpc): test responses with verification failures
  __tests__/integration/core-json-rpc/transactions.test.ts
  packages/core-json-rpc/src/server/services/database.ts
Labels: Complexity: Medium, Test: Unit

#2443 refactor: always use crypto identities to work with keys and addresses
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-transaction-pool/guard.test.ts
  __tests__/integration/core-transaction-pool/pool-wallet-manager.test.ts
  __tests__/unit/core-database/wallet-manager.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/crypto/crypto/message.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/__shared__/transaction-builder.ts
  __tests__/unit/crypto/transactions/builders/transactions/second-signature.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/transfer.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/vote.test.ts
  __tests__/unit/crypto/transactions/schemas.test.ts
  __tests__/unit/crypto/transactions/transaction.test.ts
  __tests__/utils/fixtures/testnet/delegates.ts
  __tests__/utils/fixtures/unitnet/delegates.ts
  __tests__/utils/generators/wallets.ts
  __tests__/utils/identities.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-database/src/wallet.ts
  packages/core-forger/src/delegate.ts
  packages/core-json-rpc/src/server/modules.ts
  packages/core-json-rpc/src/server/utils.ts
  packages/core-tester-cli/src/commands/debug/identity.ts
  packages/core-tester-cli/src/commands/make/wallets.ts
  packages/core-transaction-pool/src/pool-wallet-manager.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core/src/commands/config/forger/bip38.ts
  packages/crypto/src/crypto/bip38.ts
  packages/crypto/src/crypto/message.ts
  packages/crypto/src/transactions/builders/transactions/second-signature.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
  packages/crypto/src/transactions/deserializer.ts
Labels: Complexity: Medium, Type: Refactor

#2444 refactor(crypto): split the Crypto class into Hash and Transaction
  __tests__/integration/core-api/repositories/transactions.test.ts
  __tests__/integration/core-api/v1/handlers/transactions.test.ts
  __tests__/integration/core-api/v2/handlers/transactions.test.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-json-rpc/transactions.test.ts
  __tests__/integration/core-transaction-pool/guard.test.ts
  __tests__/integration/core-transaction-pool/pool-wallet-manager.test.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
  __tests__/unit/core-database/wallet-manager.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/crypto/crypto/crypto.test.ts
  __tests__/unit/crypto/crypto/hdwallet.test.ts
  __tests__/unit/crypto/identities/address.test.ts
  __tests__/unit/crypto/identities/public-key.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/__shared__/transaction-builder.ts
  __tests__/unit/crypto/transactions/builders/transactions/delegate-registration.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/multi-signature.test.ts
  __tests__/unit/crypto/transactions/transaction.test.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/wallet.ts
  packages/core-forger/src/delegate.ts
  packages/core-jest-matchers/src/fields/address.ts
  packages/core-jest-matchers/src/fields/public-key.ts
  packages/core-jest-matchers/src/transactions/valid-second-signature.ts
  packages/core-jest-matchers/src/transactions/valid.ts
  packages/core-json-rpc/src/server/modules.ts
  packages/core-snapshots/src/transport/verification.ts
  packages/core-tester-cli/src/commands/debug/verify-second-signature.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core/src/commands/config/forger/bip38.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/blocks/factory.ts
  packages/crypto/src/crypto/crypto.ts
  packages/crypto/src/crypto/hash.ts
  packages/crypto/src/crypto/index.ts
  packages/crypto/src/crypto/message.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
  packages/crypto/src/transactions/factory.ts
  packages/crypto/src/transactions/types/transaction.ts
Labels: Complexity: High, Status: In Progress, Type: Refactor

#2445 fix(core-p2p): disable rate limit for forger
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/integration/core-p2p/mocks/p2p-options.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#2449 fix(core-p2p): still download blocks when network height <= our height
  __tests__/unit/core-p2p/network-monitor.test.ts
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Low, Type: Bugfix

#2452 release: 2.3.0
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2454 chore(deps): remove extraneous jest-mock-process dependency
  .snyk
  packages/core-container/package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2455 chore(deps): bump all dependencies to the latest version
  .snyk
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-forger/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2456 fix: issues after merging 2.3
  __tests__/unit/core-database/wallet-manager.test.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database/src/wallet-manager.ts
Labels: Complexity: Low, Type: Bugfix

#2458 fix(core-transaction-pool): refuse transactions from senders with pending second signature registrations
  .circleci/config.yml
  CHANGELOG.md
  __tests__/unit/core-blockchain/processor/handlers/accept-handler.test.ts
  __tests__/unit/core-transaction-pool/guard.test.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
Labels: Complexity: Medium, Type: Bugfix

#2459 fix(crypto): deserialize type > 0 with vendor field instead of skipping it
  CHANGELOG.md
  packages/crypto/src/transactions/deserializers/transaction.ts
Labels: Complexity: Low, Type: Bugfix

#2460 release: 2.3.1
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2462 fix(core-snapshots): use correct genesis block instead of hardcoding devnet
  packages/core-snapshots/src/transport/verification.ts
Labels: Complexity: Low, Type: Bugfix

#2464 fix(core): dont pass suffix flag to bip38 and bip39 command
  packages/core/src/commands/config/forger/index.ts
Labels: Complexity: Low, Type: Bugfix

#2465 release: 2.3.12
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2466 fix(crypto): don't use vendorField type as buffer encoding for IPFS
  packages/crypto/src/transactions/builders/transactions/ipfs.ts
Labels: Complexity: Low, Type: Bugfix

#2469 chore: fix absolute banner urls
  README.md
  deprecated/core-graphql/README.md
  deprecated/core-snapshots-cli/README.md
  packages/core-api/README.md
  packages/core-blockchain/README.md
  packages/core-container/README.md
  packages/core-database-postgres/README.md
  packages/core-database/README.md
  packages/core-elasticsearch/README.md
  packages/core-error-tracker-airbrake/README.md
  packages/core-error-tracker-bugsnag/README.md
  packages/core-error-tracker-raygun/README.md
  packages/core-error-tracker-rollbar/README.md
  packages/core-error-tracker-sentry/README.md
  packages/core-event-emitter/README.md
  packages/core-forger/README.md
  packages/core-http-utils/README.md
  packages/core-jest-matchers/README.md
  packages/core-json-rpc/README.md
  packages/core-logger-pino/README.md
  packages/core-logger-signale/README.md
  packages/core-logger-winston/README.md
  packages/core-logger/README.md
  packages/core-new-relic/README.md
  packages/core-p2p/README.md
  packages/core-snapshots/README.md
  packages/core-tester-cli/README.md
  packages/core-transaction-pool/README.md
  packages/core-transactions/README.md
  packages/core-utils/README.md
  packages/core-vote-report/README.md
  packages/core-webhooks/README.md
  packages/core/README.md
Labels: Bounty: Tier 6, Complexity: Medium, Status: Collaborator Approved, Type: Task

#2467 chore(crypto): remove unused methods to get/set/reset height
  __tests__/unit/crypto/crypto/slots.test.ts
  packages/crypto/src/crypto/slots.ts
Labels: Complexity: Low, Type: Task

#2472 docs(template): add release section to pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Low, Type: Documentation

#2473 refactor(crypto): make all Slots.* methods static
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/rounds.test.ts
  __tests__/unit/core-p2p/socket-server/versions/peer/index.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-utils/is-blocked-chained.test.ts
  __tests__/unit/crypto/blocks/block.test.ts
  __tests__/unit/crypto/crypto/slots.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/__shared__/transaction-builder.ts
  packages/core-api/src/versions/1/delegates/controller.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/utils/validate-generator.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-forger/src/manager.ts
  packages/core-p2p/src/network-state.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-tester-cli/src/commands/make/block.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-utils/src/is-block-chained.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/crypto/index.ts
  packages/crypto/src/crypto/slots.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
  yarn.lock
Labels: Complexity: High, Type: Refactor

#2471 fix(crypto): add exceptions for invalid recipients
  packages/crypto/src/networks/mainnet/exceptions.json
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#2476 refactor(core): remove support for old release channels
  packages/core/src/commands/config/cli.ts
  packages/core/src/commands/config/forger/index.ts
  packages/core/src/helpers/update.ts
  packages/core/src/hooks/init/update.ts
Labels: Complexity: Low, Type: Refactor

#2477 release: 2.3.14
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2478 release: 2.3.15
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2480 style: apply linting and formatting to e2e tests
  __tests__/e2e/lib/generate-files.js
  __tests__/e2e/lib/test-runner.js
  __tests__/e2e/lib/utils/test-utils.js
  __tests__/e2e/lib/utils/testnet.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/1.create-transactions.action.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/2.check-AtoB-forged.test.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/3.resend-BtoC.action.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/4.check-BtoC-forged.test.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/config.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/utils.js
  __tests__/e2e/tests/scenarios/scenario1/config.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.0.doublespend.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.1.doublespend2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/2.check-tx.test.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/config.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/utils.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.0.doubletransfer.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.1.doubletransfer2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.2.doublevote.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.3.doubledelreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.4.double2ndsigreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/2.check-tx.test.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/config.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/utils.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.0.transfer.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.1.transfer2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.2.vote.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.3.delreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.4.2ndsigreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/2.check-tx.test.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/config.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/utils.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/1.create-transactions.action.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/2.check-unconfirmed.test.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/3.stop-node.action.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/4.0.restart-node.action.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/4.1.check-tx-1.test.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/5.check-node-pool.test.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/config.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/utils.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.0.transaction.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.1.transaction2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/2.check-tx.test.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/config.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/utils.js
Labels: Complexity: Undetermined, Type: Standards

#2482 fix(core-database): initialize height on startup
  packages/core-database/src/database-service.ts
Labels: Complexity: Low, Type: Bugfix

#2483 release: 2.3.16
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2487 fix(core-forger): update configManager height
  packages/core-forger/src/manager.ts
Labels: Complexity: Low, Type: Bugfix

#2486 fix(core-snapshots): reset unfinished round after import
  packages/core-snapshots/src/manager.ts
  packages/crypto/src/transactions/serializers/block.ts
Labels: Complexity: Low, Type: Bugfix

#2488 release: 2.3.18
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2484 fix(core): parse only the last line of pm2 stdout
  packages/core/src/process-manager.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#2489 refactor: move in-memory wallet logic to core-state
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
  __tests__/unit/core-state/__fixtures__/database-connection-stub.ts
  __tests__/unit/core-state/__fixtures__/mock-database-model.ts
  __tests__/unit/core-state/__fixtures__/state-storage-stub.ts
  __tests__/unit/core-state/__fixtures__/wallets.json
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  __tests__/unit/core-state/wallets/wallet.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/core-utils/delegate-calculator.test.ts
  __tests__/unit/crypto/blocks/__fixtures__/wallet.ts
  __tests__/unit/crypto/transactions/__fixtures__/wallet.ts
  packages/core-database-postgres/src/plugin.ts
  packages/core-database/src/index.ts
  packages/core-state/package.json
  packages/core-state/src/index.ts
  packages/core-state/src/wallets/index.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-state/src/wallets/wallet.ts
  packages/core-transaction-pool/src/wallet-manager.ts
Labels: Complexity: High, Type: Refactor

#2461 feat(core-transaction-pool): Switch expiration to chain height
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/memory-transaction.test.ts
  __tests__/unit/core-transaction-pool/mocks/core-container.ts
  __tests__/unit/core-transaction-pool/mocks/state.ts
  __tests__/unit/core-transaction-pool/storage.test.ts
  __tests__/unit/core-transaction-pool/storage.with-mock.test.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/sequential-transaction.ts
  packages/core-transaction-pool/src/storage.ts
Labels: Complexity: Medium, Status: Needs Changes, Type: Feature

#2492 feat(core-state): in-memory storage for last N blocks and transactions
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/unit/core-blockchain/mocks/container.ts
  __tests__/unit/core-blockchain/stubs/state-storage.ts
  __tests__/unit/core-database/__fixtures__/state-storage-stub.ts
  __tests__/unit/core-database/mocks/core-container.ts
  __tests__/unit/core-p2p/mocks/state.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-state/mocks/container.ts
  __tests__/unit/core-state/stores/blocks.test.ts
  __tests__/unit/core-state/stores/state.test.ts
  __tests__/unit/core-state/stores/transactions.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/mocks/state.ts
  __tests__/unit/core-utils/ordered-capped-map.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/plugin.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database/src/database-service-factory.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-state/index.ts
  packages/core-interfaces/src/core-state/service.ts
  packages/core-interfaces/src/core-state/state-store.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-state/package.json
  packages/core-state/src/plugin.ts
  packages/core-state/src/service.ts
  packages/core-state/src/stores/blocks.ts
  packages/core-state/src/stores/state.ts
  packages/core-state/src/stores/transactions.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-utils/package.json
  packages/core-utils/src/index.ts
  packages/core-utils/src/ordered-capped-map.ts
  yarn.lock
Labels: Complexity: High, Status: In Progress, Type: Feature

#2496 refactor(core-transactions): reorganize exports
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/integration/core-transaction-pool/wallet-manager.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-database/src/database-service.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transaction-pool/src/wallet-manager.ts
  packages/core-transactions/src/handlers/handler-registry.ts
  packages/core-transactions/src/handlers/index.ts
  packages/core-transactions/src/index.ts
Labels: Complexity: Medium, Type: Refactor

#2495 refactor(core-transaction-pool): simplify by not using insertion order
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/storage.test.ts
  __tests__/unit/core-transaction-pool/storage.with-mock.test.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/sequential-transaction.ts
  packages/core-transaction-pool/src/storage.ts
Labels: Complexity: High, Status: Needs Changes, Type: Refactor

#2497 fix(core-transaction-pool): don't modify transaction's expiration
  packages/core-transaction-pool/src/memory.ts
Labels: Complexity: Low, Type: Bugfix

#2501 style: enable "no-use-before-declare" rule
  package.json
  packages/core-p2p/src/utils/is-valid-peer.ts
  packages/core/src/process-manager.ts
  packages/crypto/src/transactions/types/schemas.ts
  tslint.json
Labels: Complexity: Medium, Type: Standards

#2500 feat: batch block database inserts when syncing
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/integration/core-transaction-pool/wallet-manager.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/mocks/database.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-database/__fixtures__/database-connection-stub.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-database/database-connection.ts
  packages/core-interfaces/src/core-database/database-service.ts
Labels: Complexity: Medium, Type: Feature

#2499 fix: purge invalid transactions after a milestone change
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/2.check-tx.test.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/2.check-tx.test.js
  __tests__/helpers/transaction-factory.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/mocks/core-container.ts
  __tests__/unit/core-transaction-pool/storage.test.ts
  __tests__/unit/crypto/managers/config.test.ts
  packages/core-state/src/stores/state.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/memory.ts
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/managers/config.ts
  packages/crypto/src/transactions/types/transaction.ts
  yarn.lock
Labels: Complexity: High, Type: Bugfix

#2491 fix(core-json-rpc): avoid getting stuck on a unresponsive peer by picking a random one each time
  packages/core-json-rpc/src/index.ts
  packages/core-json-rpc/src/server/methods/blocks/info.ts
  packages/core-json-rpc/src/server/methods/blocks/latest.ts
  packages/core-json-rpc/src/server/methods/blocks/transactions.ts
  packages/core-json-rpc/src/server/methods/transactions/broadcast.ts
  packages/core-json-rpc/src/server/methods/transactions/info.ts
  packages/core-json-rpc/src/server/methods/wallets/info.ts
  packages/core-json-rpc/src/server/methods/wallets/transactions.ts
  packages/core-json-rpc/src/server/services/network.ts
  packages/core-json-rpc/src/server/services/processor.ts
Labels: Complexity: Medium, Type: Bugfix

#2502 fix(core-snapshots): asset import, include rounds table
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/db/queries/index.ts
  packages/core-snapshots/src/db/queries/rounds/round-range.sql
  packages/core-snapshots/src/manager.ts
  packages/core-snapshots/src/transport/codec.ts
  packages/core-snapshots/src/transport/verification.ts
  packages/core-snapshots/src/utils.ts
Labels: Complexity: Medium, Status: In Progress, Type: Bugfix

#2503 fix(core-p2p): accept requests to /transactions regardless of suspension
  packages/core-p2p/src/server/plugins/accept-request.ts
Labels: Complexity: Low, Type: Bugfix

#2504 release: 2.3.21
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2507 feat(core-p2p): filter peers that are on the same IP subnet
  __tests__/unit/core-p2p/peer-processor.test.ts
  packages/core-interfaces/src/core-p2p/peer-storage.ts
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/peer-storage.ts
Labels: Complexity: Low, Type: Feature

#2506 refactor(crypto): extract transaction verification out of the model
  __tests__/integration/core-json-rpc/transactions.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/transactions/transaction.test.ts
  __tests__/unit/crypto/transactions/verifier.test.ts
  package.json
  packages/core-jest-matchers/src/transactions/valid-second-signature.ts
  packages/core-jest-matchers/src/transactions/valid.ts
  packages/core-json-rpc/src/server/modules.ts
  packages/core-state/src/wallets/wallet.ts
  packages/core-tester-cli/src/commands/debug/verify-second-signature.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
  packages/crypto/src/transactions/factory.ts
  packages/crypto/src/transactions/index.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/transactions/types/transaction.ts
  packages/crypto/src/transactions/verifier.ts
  tslint-config.json
Labels: Complexity: High, Type: Refactor
