Repository ArkEcosystem/core, pull requests merged in 2019-06, with the labels that each got.

#2631 ci: enable node.js 12 jobs
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/generateConfig.js
  __tests__/e2e/lib/config/docker/Dockerfile-12
  package.json
  packages/core-database/src/repositories/wallets-business-repository.ts
  yarn.lock
Labels: Complexity: Low, Status: In Progress

#2644 ci: reuse steps for different node versions
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/generateConfig.js
  .circleci/rebuild-db.sh
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-blockchain/__support__/setup.ts
  __tests__/integration/core-database-postgres/__support__/setup.ts
  __tests__/integration/core-transaction-pool/__support__/setup.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  package.json
  packages/core-database/src/database-service.ts
  scripts/pre-commit.sh
Labels: Complexity: Undetermined, Status: In Progress

#2645 fix(core-api): off by one error in transaction confirmations
  packages/core-api/src/versions/2/transactions/transformer.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#2648 refactor(core-p2p): remove redundant p2p port from broadcast
  __tests__/helpers/peers.ts
  __tests__/integration/core-api/v1/handlers/peers.test.ts
  __tests__/integration/core-api/v2/handlers/peers.test.ts
  __tests__/integration/core-p2p/network-monitor.test.ts
  packages/core-api/src/versions/1/peers/transformer.ts
  packages/core-api/src/versions/2/peers/transformer.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/peer.ts
Labels: Complexity: Low, Type: Refactor

#2650 misc(core-snapshots): fix the link to the documentation
  packages/core-snapshots/README.md
Labels: Complexity: Low

#2652 refactor(core-p2p): improve logging
  packages/core-forger/src/manager.ts
  packages/core-p2p/src/socket-server/index.ts
Labels: Complexity: Low, Type: Refactor

#2646 fix(core): set the correct channel if core was directly installed with @next
  packages/core/src/commands/config/cli.ts
  packages/core/src/helpers/config.ts
  packages/core/src/hooks/init/config.ts
Labels: Complexity: Low, Type: Bugfix

#2653 fix(core-api): invalid orderBy causes internal server error
  packages/core-api/src/repositories/transactions.ts
Labels: Complexity: Low, Type: Bugfix

#2655 refactor(core-http-utils): remove whitelist access log
  deprecated/core-json-rpc/src/server/index.ts
  packages/core-api/src/server.ts
  packages/core-http-utils/src/plugins/whitelist.ts
  packages/core-p2p/src/utils/is-whitelisted.ts
  packages/core-webhooks/src/server/index.ts
Labels: Complexity: Low, Status: In Progress, Type: Refactor

#2656 fix(core-p2p): perform `acceptNewPeer` non-blocking
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#2658 misc: reword log message and fix typo
  deprecated/core-snapshots-cli/src/commands/restore.ts
  deprecated/core-snapshots-cli/src/commands/verify.ts
  packages/core-snapshots/src/utils.ts
  packages/core/src/commands/snapshot/restore.ts
  packages/core/src/commands/snapshot/verify.ts
Labels: Complexity: Low

#2651 fix(core-snapshots): avoid trying to INSERT duplicates in rounds
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/db/queries/index.ts
  packages/core-snapshots/src/db/queries/rounds/latest.sql
  packages/core-snapshots/src/manager.ts
  packages/core-snapshots/src/transport/index.ts
  packages/core-snapshots/src/transport/verification.ts
Labels: Complexity: Low, Type: Bugfix

#2657 fix(core-container): handle failing optional plugins gracefully
  packages/core-blockchain/src/plugin.ts
  packages/core-container/src/registrars/plugin.ts
  packages/core-database-postgres/src/plugin.ts
  packages/core-event-emitter/src/index.ts
  packages/core-interfaces/src/core-container/container.ts
  packages/core-logger-pino/src/plugin.ts
  packages/core-p2p/src/plugin.ts
  packages/core-state/src/plugin.ts
  packages/core-transaction-pool/src/plugin.ts
Labels: Complexity: Medium, Type: Bugfix

#2659 test(core-transaction-pool): add more tests for `getTransactionsForForging`
  __tests__/helpers/transaction-factory.ts
  __tests__/integration/core-api/v2/handlers/transactions.test.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/transactions.test.ts
  __tests__/unit/core-transaction-pool/__stubs__/connection.ts
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/utils/fixtures/testnet/delegates.ts
  packages/core-api/src/versions/1/transactions/controller.ts
  packages/core-api/src/versions/2/transactions/controller.ts
  packages/core-interfaces/src/core-p2p/server.ts
  packages/core-interfaces/src/core-transaction-pool/connection.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-transaction-pool/src/connection.ts
  packages/crypto/src/transactions/deserializer.ts
Labels: Complexity: High, Test: Unit

#2661 release: 2.4.0-next.10
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2660 docs: 2.4.0 changelog
  CHANGELOG.md
Labels: Complexity: Low, Status: In Progress, Type: Documentation

#2665 fix(core-transaction-pool): correctly purge invalid transactions from disk on start
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Bugfix

#2662 fix(core-snapshots): don't append duplicate rounds rows to a snapshot
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/db/queries/rounds/round-range.sql
  packages/core-snapshots/src/manager.ts
  packages/core-snapshots/src/utils.ts
Labels: Complexity: Low, Type: Bugfix

#2666 fix(core-transaction-pool): use temporary wallets for transaction validation
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Medium, Type: Bugfix

#2667 release: 2.4.0-next.11
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2670 fix(core-api): missing second signature of transactions
  packages/core-api/src/versions/1/transactions/transformer.ts
  packages/core-api/src/versions/2/transactions/transformer.ts
Labels: Complexity: Low, Type: Bugfix

#2673 perf(crypto): replace bs58check with bstring
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/crypto/crypto/bip38.test.ts
  packages/core-api/package.json
  packages/core-api/src/formats.ts
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-transactions/src/utils.ts
  packages/crypto/package.json
  packages/crypto/src/crypto/bip38.ts
  packages/crypto/src/identities/address.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/transactions/types/ipfs.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/transactions/types/timelock-transfer.ts
  packages/crypto/src/transactions/types/transfer.ts
  yarn.lock
Labels: Complexity: Medium, Type: Performance

#2674 fix(core-api): missing block confirmations on v2 endpoint
  packages/core-api/src/versions/2/blocks/transformer.ts
Labels: Complexity: Low, Type: Bugfix

#2675 refactor(crypto): move base58 functions to utils
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/crypto/crypto/bip38.test.ts
  __tests__/unit/crypto/utils/base58.test.ts
  packages/core-api/src/formats.ts
  packages/core-transactions/src/utils.ts
  packages/crypto/src/crypto/bip38.ts
  packages/crypto/src/identities/address.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/transactions/types/timelock-transfer.ts
  packages/crypto/src/transactions/types/transfer.ts
  packages/crypto/src/utils/base58.ts
  packages/crypto/src/utils/index.ts
Labels: Complexity: Medium, Type: Refactor

#2672 refactor(core-transaction-pool): expire transactions that don't have …
  __tests__/integration/core-blockchain/__support__/setup.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/manager.test.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/plugin.ts
Labels: Complexity: Medium, Type: Refactor

#2679 refactor(core-wallet-api): allow custom wallet api port
  packages/core-container/src/registrars/plugin.ts
  packages/core-utils/src/transform-plugins.ts
  packages/core-wallet-api/src/defaults.ts
  packages/core-wallet-api/src/plugin.ts
  packages/core-wallet-api/src/server/index.ts
  packages/core-webhooks/src/index.ts
Labels: Complexity: Low, Type: Refactor

#2680 release: 2.4.0-next.12
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2677 docs: 2.4.0 changelog
  CHANGELOG.md
Labels: Complexity: Low, Status: In Progress, Type: Documentation

#2678 fix: do not sort transactions in forger / update purgeByBlock logic for handling nonces
  __tests__/unit/core-forger/delegate.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-forger/src/delegate.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Medium, Type: Bugfix

#2682 release: 2.4.0
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2683 chore(docker): add CORE_LOG_LEVEL for mainnet
  docker/production/mainnet/mainnet.env
Labels: Complexity: Low, Type: Task

#2684 chore(env): update environment files
  packages/core/bin/config/devnet/.env
  packages/core/bin/config/mainnet/.env
  packages/core/bin/config/testnet/.env
Labels: Complexity: Low, Type: Task

#2685 fix(core-transaction-pool): delay transaction purge on start until after StateBuilder finished
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/mocks/core-container.ts
  docker/production/Dockerfile
  packages/core-database-postgres/src/state-builder.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Bugfix

#2687 fix(core-forger): ignore overheight block
  __tests__/unit/core-forger/manager.test.ts
  packages/core-forger/src/manager.ts
Labels: Complexity: Low, Type: Bugfix

#2686 fix(core-p2p): check claimed state of peer
  __tests__/integration/core-p2p/peer-verifier.test.ts
  packages/core-p2p/src/peer-verifier.ts
Labels: Complexity: Medium, Type: Bugfix

#2688 docs: 2.4.0 changelog
  CHANGELOG.md
Labels: Complexity: Low, Type: Documentation

#2681 chore(deps): use stable @arkecosystem/exchange-json-rpc
  packages/core-exchange-json-rpc/package.json
  packages/core/bin/config/devnet/.env
  packages/core/bin/config/mainnet/.env
  packages/core/bin/config/testnet/.env
Labels: Complexity: Low, Status: In Progress, Type: Task

#2692 refactor(core-database-postgres): use sql to calculate fee statistics
  packages/core-api/package.json
  packages/core-api/src/handlers/node/controller.ts
  packages/core-database-postgres/src/queries/index.ts
  packages/core-database-postgres/src/queries/transactions/fee-statistics.sql
  packages/core-database-postgres/src/repositories/transactions.ts
Labels: Complexity: Low, Type: Refactor

#2693 fix(core-p2p): increase rate limit to handle bigger networks
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/peer-verifier.ts
  yarn.lock
Labels: Complexity: Low, Type: Bugfix

#2689 refactor(core): start process in production env
  packages/core/src/shared/start.ts
Labels: Complexity: Low, Type: Refactor

#2695 release: 2.4.1
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: High, Type: Release

#2699 perf(crypto): cache genesis transaction ids
  packages/crypto/src/utils/index.ts
Labels: Complexity: Low, Type: Performance

#2700 fix(core-blockchain): take milestones into account when downloading blocks in parallel
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-blockchain/stubs/state-storage.ts
  __tests__/unit/core-database/__fixtures__/state-storage-stub.ts
  __tests__/unit/core-state/__fixtures__/state-storage-stub.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-state/state-store.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-state/src/stores/state.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/errors.ts
Labels: Complexity: Medium, Type: Bugfix

#2701 release: 2.4.12
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2702 release: 2.5.0-next.0
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2704 release: 2.5.0-next.1
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2703 fix(core-p2p): add 2.5 to minimum versions
  packages/core-p2p/src/defaults.ts
Labels: Complexity: Low, Type: Bugfix

#2707 fix(core-database-postgres): possible database corruption when writing and deleting blocks
  __tests__/integration/core-api/handlers/blocks.test.ts
  __tests__/integration/core-api/handlers/delegates.test.ts
  __tests__/unit/core-blockchain/mocks/database.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-database/__fixtures__/database-connection-stub.ts
  __tests__/unit/core-state/__fixtures__/database-connection-stub.ts
  __tests__/unit/core-state/mocks/database.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/queries/blocks/delete.sql
  packages/core-database-postgres/src/queries/transactions/delete-by-block.sql
  packages/core-database-postgres/src/repositories/blocks.ts
  packages/core-database-postgres/src/repositories/repository.ts
  packages/core-database-postgres/src/repositories/rounds.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-connection.ts
  packages/core-interfaces/src/core-database/database-repository/blocks-repository.ts
  packages/core-interfaces/src/core-database/database-repository/repository.ts
  packages/core-interfaces/src/core-database/database-repository/rounds-repository.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-verifier.ts
Labels: Complexity: Low, Type: Bugfix

#2671 chore(core-database-postgres): add foreign key on transactions block id
  __tests__/integration/core-api/handlers/delegates.test.ts
  __tests__/unit/core-database/__fixtures__/database-connection-stub.ts
  packages/core-database-postgres/src/migrations/20190606000000-add-block-id-foreign-key-on-transactions.sql
  packages/core-database-postgres/src/migrations/index.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/queries/common/truncate-all-tables.sql
  packages/core-database-postgres/src/queries/index.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-connection.ts
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/db/queries/index.ts
Labels: Complexity: Low, Status: In Progress, Status: Needs Changes

#2713 release: 2.5.0-next.2
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: High, Type: Release

#2711 fix(core-api): use CORE_API_DISABLED variable in defaults
  packages/core-api/src/defaults.ts
Labels: Complexity: Low, Type: Bugfix

#2714 refactor(core-p2p): only look for new peers when below minimum peers
  packages/core-interfaces/src/core-p2p/network-monitor.ts
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Low, Type: Refactor

#2710 feat(core-webhooks): add option to configure request timeout
  packages/core-webhooks/src/defaults.ts
  packages/core-webhooks/src/listener.ts
Labels: Complexity: Low, Type: Feature

#2717 feat(core-wallet-api): impose the same rate limit as the public API
  packages/core-api/src/defaults.ts
  packages/core-wallet-api/package.json
  packages/core-wallet-api/src/server/index.ts
  yarn.lock
Labels: Complexity: Low, Type: Feature

#2715 refactor(core-wallet-api): always keep the Wallet API enabled
  packages/core-wallet-api/src/defaults.ts
  packages/core-wallet-api/src/plugin.ts
Labels: Complexity: Low, Type: Refactor

#2716 chore(core-p2p): allow 2.4 and 2.5 nodes
  __tests__/unit/core-p2p/utils/is-valid-version.test.ts
  packages/core-p2p/src/defaults.ts
Labels: Complexity: Low, Type: Task

#2720 fix(core-p2p): forget peer when socket is disconnected
  packages/core-p2p/src/event-listener.ts
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Type: Bugfix

#2719 perf(core-p2p): improve peer block header check
  __tests__/integration/core-p2p/mocks/core-container.ts
  packages/core-p2p/src/peer-verifier.ts
Labels: Complexity: Low, Type: Performance

#2721 chore: export abstract builder for use by plugins
  packages/crypto/src/transactions/builders/index.ts
Labels: Complexity: Low, Type: Task

#2728 refactor(core-p2p): only fetch block headers when verifying peers
  __tests__/unit/core-blockchain/stubs/state-storage.ts
  __tests__/unit/core-database/__fixtures__/state-storage-stub.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/socket-server/versions/peer/index.test.ts
  __tests__/unit/core-state/__fixtures__/state-storage-stub.ts
  __tests__/unit/core-state/stores/state.test.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-p2p/peer-communicator.ts
  packages/core-interfaces/src/core-state/state-store.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/schemas.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-state/src/stores/state.ts
Labels: Complexity: Medium, Type: Refactor

#2727 refactor(core-p2p): delay peer discovery until after state initialization is done
  __tests__/helpers/peers.ts
  __tests__/unit/core-blockchain/mocks/p2p/network-monitor.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-interfaces/src/core-p2p/network-monitor.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/plugin.ts
  packages/core-p2p/src/schemas.ts
Labels: Complexity: Low, Type: Refactor

#2730 refactor(core-http-utils): remove createSecureServer method
  packages/core-api/src/server.ts
  packages/core-http-utils/src/index.ts
  packages/core-http-utils/src/server/create-secure.ts
  packages/core-http-utils/src/server/create.ts
Labels: Complexity: Low

#2729 refactor(core-p2p): improved rate limiting
  __tests__/integration/core-p2p/socket-server/peer-with-remote-access.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/socket-server/worker.test.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/enums.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/socket-server/rate-limiter.ts
  packages/core-p2p/src/socket-server/worker.ts
  yarn.lock
Labels: Complexity: Medium, Type: Refactor

#2733 fix(core-p2p): off-by-one error when fetching blocks from peer
  packages/core-p2p/src/peer-verifier.ts
Labels: Complexity: Low, Type: Bugfix

#2734 fix(core): check for user confirmation in snapshot commands
  packages/core/src/helpers/snapshot.ts
Labels: Complexity: Low, Type: Bugfix

#2735 test(core-api): transformer service and 404 assertions
  __tests__/integration/core-api/handlers/blocks.test.ts
  __tests__/integration/core-api/handlers/delegates.test.ts
  __tests__/integration/core-api/handlers/transactions.test.ts
  __tests__/integration/core-api/handlers/votes.test.ts
  __tests__/integration/core-api/handlers/wallets.test.ts
  __tests__/integration/core-api/services/block-raw.json
  __tests__/integration/core-api/services/block-transformed.json
  __tests__/integration/core-api/services/transaction-raw.json
  __tests__/integration/core-api/services/transaction-transformed.json
  __tests__/integration/core-api/services/transformer.test.ts
  packages/core-api/src/formats.ts
  packages/core-api/src/handlers/blockchain/controller.ts
  packages/core-api/src/handlers/blocks/controller.ts
  packages/core-api/src/handlers/blocks/transformer.ts
  packages/core-api/src/handlers/delegates/controller.ts
  packages/core-api/src/handlers/node/controller.ts
  packages/core-api/src/handlers/peers/controller.ts
  packages/core-api/src/handlers/peers/transformer.ts
  packages/core-api/src/handlers/rounds/controller.ts
  packages/core-api/src/handlers/transactions/controller.ts
  packages/core-api/src/handlers/votes/controller.ts
  packages/core-api/src/handlers/wallets/controller.ts
  packages/core-api/src/server.ts
Labels: Complexity: High, Test: Unit

#2718 refactor(core-wallet-api): respect the whitelist of the public API
  packages/core-api/src/defaults.ts
  packages/core-container/src/registrars/plugin.ts
  packages/core-http-utils/src/plugins/whitelist.ts
  packages/core-interfaces/src/core-container/container.ts
  packages/core-utils/package.json
  packages/core-utils/src/index.ts
  packages/core-utils/src/is-whitelisted.ts
  packages/core-wallet-api/package.json
  packages/core-wallet-api/src/plugin.ts
  packages/core-wallet-api/src/server/index.ts
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
Labels: Complexity: Medium, Type: Refactor

#2736 test(core-api): test /transactions/fees and /blockchain endpoints
  __tests__/integration/core-api/handlers/blockchain.test.ts
  __tests__/integration/core-api/handlers/blocks.test.ts
  __tests__/integration/core-api/handlers/peers.test.ts
  __tests__/integration/core-api/handlers/transactions.test.ts
Labels: Complexity: Medium, Test: Unit

#2737 test(core-api): /node/configuration/crypto endpoint
  __tests__/integration/core-api/handlers/node.test.ts
Labels: Complexity: Low, Status: In Progress, Test: Unit

#2738 test(core-api): /node/fees endpoint
  __tests__/integration/core-api/handlers/node.test.ts
  packages/core-database-postgres/src/repositories/transactions.ts
Labels: Complexity: Low, Test: Unit

#2741 chore(docker): Add Wallets API, remove PostgreSQL container port default mapping to localhost
  docker/production/devnet/devnet.env
  docker/production/devnet/docker-compose-build.yml
  docker/production/devnet/docker-compose.yml
  docker/production/mainnet/docker-compose-build.yml
  docker/production/mainnet/docker-compose.yml
Labels: Complexity: Low, Type: Refactor

#2742 docs(docker): Updated README
  docker/production/README.md
Labels: Complexity: Low

#2731 misc(core-p2p): log all socket errors
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Status: Needs Changes

#2744 refactor(core-database-postgres): exit on unexpected error
  packages/core-database-postgres/src/postgres-connection.ts
Labels: Complexity: Low, Type: Refactor

#2743 perf(core-p2p): download serialized blocks
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/unit/core-blockchain/mocks/database.ts
  __tests__/unit/core-state/mocks/database.ts
  __tests__/unit/crypto/validation/validator.test.ts
  packages/core-database-postgres/src/queries/blocks/height-range-with-transactions.sql
  packages/core-database-postgres/src/queries/index.ts
  packages/core-database-postgres/src/repositories/blocks.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-repository/blocks-repository.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/schemas.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/crypto/package.json
  packages/crypto/src/validation/schemas.ts
Labels: Complexity: Medium, Type: Refactor

#2745 refactor(core-p2p): block when rate limit exceeded
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/socket-server/versions/peer/index.test.ts
  packages/core-p2p/src/enums.ts
  packages/core-p2p/src/socket-server/rate-limiter.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-p2p/src/socket-server/worker.ts
  packages/crypto/package.json
Labels: Complexity: Medium, Type: Refactor

#2746 fix(core-blockchain): always attempt to download blocks after start
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/state-machine.ts
Labels: Complexity: Low, Type: Bugfix

#2747 release: 2.5.0-next.4
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2748 fix(core-utils): grant access if the whitelist is empty
  __tests__/unit/core-utils/is-whitelisted.test.ts
  packages/core-api/src/defaults.ts
  packages/core-container/src/registrars/plugin.ts
  packages/core-utils/src/is-whitelisted.ts
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
Labels: Complexity: Low, Type: Bugfix

#2749 release: 2.5.0-next.5
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2751 fix: do not purge transactions when a block is not accepted
  __tests__/unit/core-blockchain/mocks/transactionPool.ts
  __tests__/unit/core-state/mocks/transactionPool.ts
  __tests__/unit/core-transaction-pool/__stubs__/connection.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-blockchain/src/processor/handlers/verification-failed-handler.ts
  packages/core-interfaces/src/core-transaction-pool/connection.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Medium, Type: Bugfix

#2752 release: 2.4.13
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2754 fix: previous round order calculation
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-state/wallets/temp-wallet-manager.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/index.ts
  packages/core-state/src/wallets/temp-wallet-manager.ts
  packages/core-state/src/wallets/wallet-manager.ts
Labels: Complexity: Medium, Type: Bugfix

#2755 refactor(core-database-postgres): check error code instead of exiting blindly
  packages/core-database-postgres/src/postgres-connection.ts
Labels: Complexity: Low, Type: Refactor

#2739 fix: treat and return BigInt values as strings
  __tests__/integration/core-api/handlers/blockchain.test.ts
  __tests__/integration/core-api/handlers/delegates.test.ts
  __tests__/integration/core-api/handlers/transactions.test.ts
  __tests__/integration/core-api/handlers/wallets.test.ts
  __tests__/integration/core-api/services/block-transformed.json
  __tests__/integration/core-api/services/transaction-transformed.json
  __tests__/integration/core-api/services/transformer.test.ts
  __tests__/integration/core-api/utils.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-utils/delegate-calculator.test.ts
  __tests__/unit/core-utils/supply-calculator.test.ts
  packages/core-api/src/handlers/blocks/transformer.ts
  packages/core-api/src/handlers/delegates/transformer.ts
  packages/core-api/src/handlers/rounds/methods.ts
  packages/core-api/src/handlers/rounds/transformer.ts
  packages/core-api/src/handlers/shared/controller.ts
  packages/core-api/src/handlers/transactions/transformer.ts
  packages/core-api/src/handlers/wallets/transformer.ts
  packages/core-utils/src/delegate-calculator.ts
  packages/core-utils/src/supply-calculator.ts
  packages/core-vote-report/package.json
  packages/core-vote-report/src/handler.ts
Labels: Complexity: Medium, Type: Refactor

#2758 feat(core-api): return timestamp from /node/status
  __tests__/integration/core-api/handlers/node.test.ts
  packages/core-api/src/handlers/node/controller.ts
Labels: Complexity: Low, Type: Feature

#2756 refactor(core-transaction-pool): remove blockSender
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/unit/core-transaction-pool/__stubs__/connection.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-interfaces/src/core-transaction-pool/connection.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/processor.ts
Labels: Complexity: Medium, Type: Refactor

#2761 fix(core-blockchain): revert accepted blocks when saveBlocks fails
  __tests__/integration/core-database-postgres/connection.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/mocks/database.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-database-postgres/src/postgres-connection.ts
Labels: Complexity: Low, Type: Bugfix

#2760 feat(core-api): add nonce to wallet transformer
  __tests__/integration/core-api/utils.ts
  packages/core-api/src/handlers/wallets/transformer.ts
Labels: Complexity: Low, Type: Feature

#2762 fix: install.sh and docker
  docker/production/README.md
  docker/production/devnet/devnet.env
  docker/production/devnet/docker-compose-build.yml
  docker/production/devnet/docker-compose.yml
  docker/production/mainnet/docker-compose-build.yml
  docker/production/mainnet/docker-compose.yml
  install.sh
Labels: Complexity: Low, Type: Bugfix

#2723 refactor(core-database-postgres): remove the id column from rounds
  packages/core-database-postgres/src/migrations/20190619000000-drop-id-column-from-rounds-table.sql
  packages/core-database-postgres/src/migrations/index.ts
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/db/queries/rounds/latest.sql
  packages/core-snapshots/src/db/queries/rounds/round-range.sql
  packages/core-snapshots/src/manager.ts
  packages/core-snapshots/src/transport/codec.ts
  packages/core-snapshots/src/transport/verification.ts
  packages/core-snapshots/src/utils.ts
Labels: Complexity: Low, Status: Needs Changes, Type: Refactor

#2669 feat: Implement MultiPayment (AIP11)
  __tests__/functional/transaction-forging/multi-payment.test.ts
  __tests__/helpers/transaction-factory.ts
  __tests__/integration/core-tester-cli/commands/send/multi-payment.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/multi-payment.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/transactions/schemas.test.ts
  packages/core-jest-matchers/src/functional/accepted.ts
  packages/core-tester-cli/src/commands/send/multi-payment.ts
  packages/core-tester-cli/src/signer.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/networks/testnet/milestones.json
  packages/crypto/src/networks/unitnet/milestones.json
  packages/crypto/src/transactions/builders/transactions/multi-payment.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: High, Type: Feature

#2759 fix(core-snapshots): do not restore genesis block with wrong id
  packages/core-snapshots/src/transport/index.ts
  packages/core-snapshots/src/transport/verification.ts
Labels: Complexity: Low, Type: Bugfix
