Repository ArkEcosystem/core, pull requests merged in 2019-01, with the labels that each got.

#1926 refactor: extract jest matchers into its own package
  .circleci/config.yml
  packages/core-jest-matchers/.gitattributes
  packages/core-jest-matchers/README.md
  packages/core-jest-matchers/__tests__/blockchain/dispatch.test.ts
  packages/core-jest-matchers/__tests__/blockchain/execute-on-entry.test.ts
  packages/core-jest-matchers/__tests__/blockchain/transition.test.ts
  packages/core-jest-matchers/__tests__/fields/address.test.ts
  packages/core-jest-matchers/__tests__/fields/public-key.test.ts
  packages/core-jest-matchers/__tests__/models/delegate.test.ts
  packages/core-jest-matchers/__tests__/models/transaction.test.ts
  packages/core-jest-matchers/__tests__/models/wallet.test.ts
  packages/core-jest-matchers/__tests__/transactions/types/delegate-resignation.test.ts
  packages/core-jest-matchers/__tests__/transactions/types/delegate.test.ts
  packages/core-jest-matchers/__tests__/transactions/types/ipfs.test.ts
  packages/core-jest-matchers/__tests__/transactions/types/multi-payment.test.ts
  packages/core-jest-matchers/__tests__/transactions/types/multi-signature.test.ts
  packages/core-jest-matchers/__tests__/transactions/types/second-signature.test.ts
  packages/core-jest-matchers/__tests__/transactions/types/timelock-transfer.test.ts
  packages/core-jest-matchers/__tests__/transactions/types/transfer.test.ts
  packages/core-jest-matchers/__tests__/transactions/types/vote.test.ts
  packages/core-jest-matchers/__tests__/transactions/valid-second-signature.test.ts
  packages/core-jest-matchers/__tests__/transactions/valid.test.ts
  packages/core-jest-matchers/package.json
  packages/core-jest-matchers/src/api/block.ts
  packages/core-jest-matchers/src/api/index.ts
  packages/core-jest-matchers/src/api/peer.ts
  packages/core-jest-matchers/src/api/response.ts
  packages/core-jest-matchers/src/api/transaction.ts
  packages/core-jest-matchers/src/blockchain/dispatch.ts
  packages/core-jest-matchers/src/blockchain/execute-on-entry.ts
  packages/core-jest-matchers/src/blockchain/index.ts
  packages/core-jest-matchers/src/blockchain/transition.ts
  packages/core-jest-matchers/src/fields/address.ts
  packages/core-jest-matchers/src/fields/index.ts
  packages/core-jest-matchers/src/fields/public-key.ts
  packages/core-jest-matchers/src/index.ts
  packages/core-jest-matchers/src/models/delegate.ts
  packages/core-jest-matchers/src/models/index.ts
  packages/core-jest-matchers/src/models/transaction.ts
  packages/core-jest-matchers/src/models/wallet.ts
  packages/core-jest-matchers/src/transactions/index.ts
  packages/core-jest-matchers/src/transactions/types/delegate-resignation.ts
  packages/core-jest-matchers/src/transactions/types/delegate.ts
  packages/core-jest-matchers/src/transactions/types/index.ts
  packages/core-jest-matchers/src/transactions/types/ipfs.ts
  packages/core-jest-matchers/src/transactions/types/multi-payment.ts
  packages/core-jest-matchers/src/transactions/types/multi-signature.ts
  packages/core-jest-matchers/src/transactions/types/second-signature.ts
  packages/core-jest-matchers/src/transactions/types/timelock-transfer.ts
  packages/core-jest-matchers/src/transactions/types/transfer.ts
  packages/core-jest-matchers/src/transactions/types/vote.ts
  packages/core-jest-matchers/src/transactions/valid-second-signature.ts
  packages/core-jest-matchers/src/transactions/valid.ts
  packages/core-jest-matchers/tsconfig.json
  packages/core-test-utils/__tests__/matchers/transactions/types/transfer.test.ts
  packages/core-test-utils/__tests__/matchers/transactions/valid-second-signature.test.ts
  packages/core-test-utils/src/helpers/container.ts
  packages/core-test-utils/src/index.ts
Labels: :cloud: testing, review

#1927 feat(core-api): return the transaction expiration time via node/configuration
  packages/core-api/src/versions/2/node/controller.ts
Labels: :man_technologist: enhancement, review

#1930 refactor(core-api): implement a cache service to DRY the server method logic
  .circleci/config.yml
  packages/core-api/src/index.ts
  packages/core-api/src/services/cache.ts
  packages/core-api/src/services/index.ts
  packages/core-api/src/services/transformer.ts
  packages/core-api/src/versions/1/accounts/methods.ts
  packages/core-api/src/versions/1/blocks/methods.ts
  packages/core-api/src/versions/1/delegates/methods.ts
  packages/core-api/src/versions/1/transactions/methods.ts
  packages/core-api/src/versions/2/blocks/methods.ts
  packages/core-api/src/versions/2/delegates/methods.ts
  packages/core-api/src/versions/2/shared/controller.ts
  packages/core-api/src/versions/2/transactions/methods.ts
  packages/core-api/src/versions/2/votes/methods.ts
  packages/core-api/src/versions/2/wallets/methods.ts
  packages/core-api/src/versions/utils.ts
  packages/core-blockchain/src/index.ts
  packages/core-container/src/index.ts
  packages/core-database/__tests__/__fixtures__/dummy-class.ts
  packages/core-database/src/plugin.ts
  packages/core-elasticsearch/src/index.ts
  packages/core-error-tracker-bugsnag/src/index.ts
  packages/core-error-tracker-sentry/src/index.ts
  packages/core-forger/src/index.ts
  packages/core-graphql/src/index.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-blockchain/state-storage.ts
  packages/core-interfaces/src/core-container/container.ts
  packages/core-interfaces/src/core-p2p/monitor.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-interfaces/src/core-transaction-pool/index.ts
  packages/core-interfaces/src/core-transaction-pool/transaction-guard.ts
  packages/core-interfaces/src/core-transaction-pool/transaction-pool.ts
  packages/core-interfaces/src/index.ts
  packages/core-interfaces/src/shared/config.ts
  packages/core-json-rpc/src/index.ts
  packages/core-logger-winston/src/driver.ts
  packages/core-logger-winston/src/plugin.ts
  packages/core-logger/src/logger.ts
  packages/core-p2p/__tests__/court/guard.test.ts
  packages/core-p2p/__tests__/peer.test.ts
  packages/core-p2p/src/index.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/server/versions/1/handlers.ts
  packages/core-p2p/src/server/versions/internal/handlers/rounds.ts
  packages/core-snapshots/src/index.ts
  packages/core-test-utils/src/config/testnet/plugins.js
  packages/core-transaction-pool/__tests__/connection.test.ts
  packages/core-transaction-pool/__tests__/dynamic-fee.test.ts
  packages/core-transaction-pool/__tests__/guard.test.ts
  packages/core-transaction-pool/__tests__/pool-wallet-manager.test.ts
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/guard.ts
  packages/core-transaction-pool/src/plugin.ts
  packages/core-vote-report/src/handler.ts
  packages/core-vote-report/src/index.ts
  packages/core-webhooks/src/index.ts
Labels: :man_technologist: refactor, review

#1931 refactor(crypto): only allow vendor fields for type 0 & type 6
  packages/crypto/src/models/transaction.ts
  packages/crypto/src/networks/mainnet/exceptions.json
  packages/crypto/src/validation/extensions/transactions/timelock-transfer.ts
  packages/crypto/src/validation/rules/models/transactions/timelock-transfer.ts
Labels: :man_technologist: refactor, :see_no_evil: crypto

#1898 refactor(core-p2p): network state quorum calculation
  .circleci/generateConfig.js
  packages/core-forger/__tests__/client.test.ts
  packages/core-forger/__tests__/manager.test.ts
  packages/core-forger/package.json
  packages/core-forger/src/client.ts
  packages/core-forger/src/manager.ts
  packages/core-interfaces/src/core-p2p/monitor.ts
  packages/core-p2p/src/index.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/network-state.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/utils/index.ts
  packages/core-p2p/src/utils/network-state.ts
Labels: :man_technologist: refactor, review

#1948 refactor: export core-api types
  packages/core-api/__tests__/repositories/transactions.test.ts
  packages/core-api/__tests__/repositories/utils/build-filter-query.test.ts
  packages/core-api/package.json
  packages/core-api/src/index.ts
  packages/core-api/src/interfaces/index.ts
  packages/core-api/src/plugin.ts
  packages/core-api/src/repositories/blocks.ts
  packages/core-api/src/repositories/index.ts
  packages/core-api/src/repositories/repository.ts
  packages/core-api/src/repositories/transactions.ts
  packages/core-api/src/server.ts
Labels: Bounty: Tier 4, Type: Refactor

#1952 feat: new unit test network for unit tests
  packages/core-test-utils/src/config/unitnet/delegates.json
  packages/core-test-utils/src/config/unitnet/genesisBlock.json
  packages/core-test-utils/src/config/unitnet/peers.json
  packages/core-test-utils/src/config/unitnet/plugins.js
  packages/core-test-utils/src/config/unitnet/wallets.json
  packages/core-test-utils/src/config/unitnet/wallets2ndSig.json
  packages/core-test-utils/src/fixtures/index.ts
  packages/core-test-utils/src/fixtures/testnet/index.ts
  packages/core-test-utils/src/fixtures/unitnet/delegates.ts
  packages/core-test-utils/src/fixtures/unitnet/index.ts
  packages/core-test-utils/src/fixtures/unitnet/wallets.ts
  packages/core-test-utils/src/generators/transactions/transaction.ts
  packages/core-test-utils/src/generators/wallets.ts
  packages/core-test-utils/src/helpers/container.ts
  packages/crypto/src/networks/index.ts
  packages/crypto/src/networks/unitnet/exceptions.json
  packages/crypto/src/networks/unitnet/index.ts
  packages/crypto/src/networks/unitnet/milestones.json
  packages/crypto/src/networks/unitnet/network.json
Labels: Status: Needs Review, Test: General

#1950 tests(crypto): Increase coverage and mark private methods
  packages/crypto/__tests__/validation/validator.test.ts
  packages/crypto/src/validation/validator.ts
Labels: Bounty: Tier 4, Type: Refactor

#1954 fix(core-api): use correct schemas
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-api/src/versions/2/wallets/routes.ts
Labels: Status: Needs Review, Type: Bugfix

#1956 test: guard modify tx after sign + update core-transaction-pool tests with unitnet network
  packages/core-test-utils/src/config/unitnet/delegates.json
  packages/core-test-utils/src/config/unitnet/genesisBlock.json
  packages/core-test-utils/src/config/unitnet/wallets.json
  packages/core-test-utils/src/config/unitnet/wallets2ndSig.json
  packages/core-test-utils/src/fixtures/unitnet/blocks.ts
  packages/core-test-utils/src/fixtures/unitnet/delegates.ts
  packages/core-test-utils/src/fixtures/unitnet/index.ts
  packages/core-test-utils/src/generators/transactions/delegate.ts
  packages/core-test-utils/src/generators/transactions/signature.ts
  packages/core-test-utils/src/generators/transactions/transaction.ts
  packages/core-test-utils/src/generators/transactions/transfer.ts
  packages/core-test-utils/src/generators/transactions/vote.ts
  packages/core-transaction-pool/__tests__/__fixtures__/transactions.ts
  packages/core-transaction-pool/__tests__/__support__/setup.ts
  packages/core-transaction-pool/__tests__/connection.test.ts
  packages/core-transaction-pool/__tests__/guard.test.ts
  packages/core-transaction-pool/__tests__/pool-wallet-manager.test.ts
  packages/crypto/src/networks/unitnet/network.json
Labels: Status: Needs Review, Test: General

#1957 fix(core-api): return the database timestamp instead of deserialised
  packages/core-api/src/repositories/transactions.ts
  packages/core-api/src/versions/1/transactions/transformer.ts
  packages/core-api/src/versions/2/transactions/transformer.ts
  packages/core-snapshots-cli/src/commands/import.ts
Labels: Component: Public API, Status: Needs Review, Type: Bugfix

#1958 test(crypto): update handler tests to apply basic tests to all handlers
  packages/crypto/__tests__/handlers/transactions/handler.test.ts
Labels: Test: Unit

#1955 fix(core-api): prevent cold wallet response
  packages/core-api/__tests__/v1/handlers/accounts.test.ts
  packages/core-api/src/repositories/transactions.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-transaction-pool/src/pool-wallet-manager.ts
Labels: Bounty: Tier 4, Component: Blockchain, Component: Public API

#1953 refactor(core-blockchain): block processing
  packages/core-blockchain/__tests__/blockchain.test.ts
  packages/core-blockchain/__tests__/utils/is-blocked-chained.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-blockchain/src/processor/handlers/already-forged-handler.ts
  packages/core-blockchain/src/processor/handlers/block-handler.ts
  packages/core-blockchain/src/processor/handlers/index.ts
  packages/core-blockchain/src/processor/handlers/invalid-generator-handler.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/processor/handlers/verification-failed-handler.ts
  packages/core-blockchain/src/processor/index.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-blockchain/src/utils/index.ts
  packages/core-blockchain/src/utils/is-block-chained.ts
  packages/core-blockchain/src/utils/validate-generator.ts
  packages/core-database/src/interface.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-p2p/src/server/versions/1/handlers.ts
  packages/core-p2p/src/server/versions/internal/handlers/blocks.ts
Labels: Component: Blockchain, Status: Needs Review, Type: Refactor

#1975 test(core-debugger-cli): increase coverage
  packages/core-debugger-cli/__tests__/commands/identity.test.ts
  packages/crypto/__tests__/builder/transactions/multi-payment.test.ts
Labels: Bounty: Tier 5, Test: Unit

#1981 perf(core-blockchain): optimize StateStorage.getCommonBlocks()
  packages/core-blockchain/src/state-storage.ts
Labels: Status: Needs Review, Type: Performance

#1984 test(crypto): bignumber coverage
  packages/crypto/__tests__/client.test.ts
  packages/crypto/__tests__/validation/extensions/bignumber.test.ts
  packages/crypto/src/validation/extensions/bignumber.ts
Labels: Bounty: Tier 5, Test: Unit

#1985 fix(core-blockchain): port slot check from master
  packages/core-blockchain/__tests__/blockchain.test.ts
  packages/core-blockchain/__tests__/utils/is-blocked-chained.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/processor/handlers/exception-handler.ts
  packages/core-blockchain/src/processor/handlers/index.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-blockchain/src/utils/is-block-chained.ts
  packages/core-blockchain/src/utils/validate-generator.ts
  packages/core-database-postgres/src/repositories/blocks.ts
  packages/crypto/src/crypto/crypto.ts
  packages/crypto/src/crypto/slots.ts
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Status: Needs Review

#1966 test(core-logger-winston): increase coverage
  packages/core-logger-winston/__tests__/logger.test.ts
  packages/core-logger-winston/src/driver.ts
Labels: Bounty: Tier 4, Status: Needs Changes, Status: Tests Failing

#1987 feat(core-container): use system paths for configuration and data
  packages/core-blockchain/src/state-storage.ts
  packages/core-container/__tests__/container.test.ts
  packages/core-container/package.json
  packages/core-container/src/config/index.ts
  packages/core-container/src/environment.ts
  packages/core-database-postgres/package.json
  packages/core-database-postgres/src/connection.ts
  packages/core-logger-winston/src/defaults.ts
  packages/core-logger-winston/src/plugin.ts
  packages/core-test-utils/src/helpers/container.ts
  packages/core/__tests__/__support__/app.ts
  packages/core/src/index.ts
  yarn.lock
Labels: Status: Needs Review, Type: Feature

#1989 fix(core-container): always set path variables and overwrite custom ones
  packages/core-container/__tests__/container.test.ts
  packages/core-container/src/environment.ts
  packages/core-test-utils/src/helpers/container.ts
  packages/core/__tests__/__support__/app.ts
  packages/core/src/index.ts
Labels: Type: Bugfix

#1982 fix(core-database-postgres): off-by-one error in getBlocks()
  packages/core-blockchain/src/blockchain.ts
  packages/core-database-postgres/src/connection.ts
  packages/core-database/src/interface.ts
Labels: Type: Bugfix

#1990 chore: add missing @types
  package.json
  packages/core-api/package.json
  packages/core-api/src/services/cache.ts
  packages/core-api/src/versions/1/accounts/controller.ts
  packages/core-api/src/versions/1/blocks/controller.ts
  packages/core-api/src/versions/1/delegates/controller.ts
  packages/core-api/src/versions/1/peers/controller.ts
  packages/core-api/src/versions/1/transactions/controller.ts
  packages/core-api/src/versions/2/blocks/controller.ts
  packages/core-api/src/versions/2/delegates/controller.ts
  packages/core-api/src/versions/2/peers/controller.ts
  packages/core-api/src/versions/2/transactions/controller.ts
  packages/core-api/src/versions/2/votes/controller.ts
  packages/core-api/src/versions/2/wallets/controller.ts
  packages/core-blockchain/package.json
  packages/core-blockchain/src/queue/interface.ts
  packages/core-container/package.json
  packages/core-database/package.json
  packages/core-http-utils/package.json
  packages/core-json-rpc/package.json
  packages/core-json-rpc/src/server/index.ts
  packages/core-json-rpc/src/server/methods/index.ts
  packages/core-logger-winston/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-transaction-pool/__tests__/connection.test.ts
  packages/core-transaction-pool/package.json
  packages/core-webhooks/package.json
  packages/crypto/package.json
  packages/crypto/src/models/delegate.ts
  yarn.lock
Labels: Type: Task

#1997 refactor(core-json-rpc): mark __ methods as private
  packages/core-json-rpc/__tests__/blocks.test.ts
  packages/core-json-rpc/src/server/methods/blocks/transactions.ts
  packages/core-json-rpc/src/server/services/network.ts
  packages/core-json-rpc/src/server/services/processor.ts
Labels: Bounty: Tier 5

#1992 chore(core-database-postgres): use token in database name
  .circleci/config.yml
  .circleci/configTemplate.json
  package.json
  packages/core-container/src/container.ts
  packages/core-container/src/environment.ts
  packages/core-database-postgres/src/defaults.ts
  packages/core-test-utils/src/config/testnet/plugins.js
  packages/core-test-utils/src/config/unitnet/plugins.js
  packages/core/src/config/devnet/plugins.js
  packages/core/src/config/mainnet/plugins.js
  packages/core/src/config/testnet.1/plugins.js
  packages/core/src/config/testnet.2/plugins.js
  packages/core/src/config/testnet.live/plugins.js
  packages/core/src/config/testnet/plugins.js
  scripts/docker/generate-docker.js
  scripts/docker/templates/development/docker-compose.yml
  scripts/docker/templates/development/purge.sh
  scripts/docker/templates/devnet/Dockerfile
  scripts/docker/templates/devnet/docker-compose.yml
  scripts/docker/templates/devnet/entrypoint.sh
  scripts/docker/templates/devnet/purge_all.sh
  scripts/docker/templates/devnet/restore.sh
  scripts/docker/templates/mainnet/docker-compose.yml
  scripts/docker/templates/testnet/Dockerfile
  scripts/docker/templates/testnet/docker-compose.yml
  scripts/docker/templates/testnet/entrypoint.sh
  scripts/docker/templates/testnet/purge_all.sh
  scripts/docker/templates/testnet/restore.sh
Labels: Status: Needs Review, Type: Refactor

#2002 chore(crypto): add devnet blocks and transactions exceptions
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Status: Needs Review, Type: Task

#2009 feat(core-api): return wallet vote on v2 endpoints
  packages/core-api/__tests__/v2/utils.ts
  packages/core-api/src/versions/2/wallets/transformer.ts
Labels: Status: Needs Review, Type: Feature

#2013 refactor(core-logger-winston): add flag to disable extra spacing for readability
  packages/core-logger-winston/src/defaults.ts
  packages/core-logger-winston/src/formatter.ts
  packages/core-logger-winston/src/index.ts
  packages/core-logger-winston/src/plugin.ts
Labels: Type: Refactor

#2011 refactor(core-logger-winston): do not log empty values and stringify non-string values
  .gitignore
  packages/core-logger-winston/package.json
  packages/core-logger-winston/src/driver.ts
  packages/core-logger/src/logger.ts
Labels: Type: Refactor

#1999 chore: upgrade script for the 2.1 release
  UPGRADE.md
  package.json
  packages/core-container/src/environment.ts
  packages/core-json-rpc/src/defaults.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core-webhooks/__tests__/__support__/setup.ts
  packages/core-webhooks/src/defaults.ts
  scripts/upgrade.sh
  scripts/upgrade/test.sh
  scripts/upgrade/upgrade.js
  yarn.lock
Labels: Status: Needs Review, Type: Task

#2018 test(crypto): ser/deserialization on blocks and transaction
  packages/crypto/__tests__/builder/transactions/delegate-registration.test.ts
  packages/crypto/__tests__/builder/transactions/multi-payment.test.ts
  packages/crypto/__tests__/deserializers/block.test.ts
  packages/crypto/__tests__/deserializers/transaction.test.ts
  packages/crypto/__tests__/fixtures/block.ts
  packages/crypto/__tests__/fixtures/multi-transaction.ts
  packages/crypto/__tests__/fixtures/transaction.ts
  packages/crypto/__tests__/models/block.test.ts
  packages/crypto/__tests__/models/transaction.test.ts
  packages/crypto/__tests__/models/wallet.test.ts
  packages/crypto/__tests__/validation/engine.test.ts
  packages/crypto/src/builder/transactions/delegate-registration.ts
  packages/crypto/src/builder/transactions/ipfs.ts
  packages/crypto/src/builder/transactions/multi-payment.ts
  packages/crypto/src/builder/transactions/transaction.ts
  packages/crypto/src/deserializers/transaction.ts
  packages/crypto/src/serializers/transaction.ts
Labels: Test: Unit

#2016 chore: install script for core
  install.sh
Labels: Status: Blocked, Status: In Progress, Status: Needs Review, Type: Task

#2022 chore: update the plugins.js file through the upgrade script
  scripts/upgrade/upgrade.js
Labels: Type: Task

#2021 refactor(crypto): remove validation rules and validator
  packages/crypto/__tests__/handlers/transactions/multi-payment.test.ts
  packages/crypto/__tests__/validation/engine.test.ts
  packages/crypto/__tests__/validation/extensions/bignumber.test.ts
  packages/crypto/__tests__/validation/rules/address.test.ts
  packages/crypto/__tests__/validation/rules/models/transactions/common.ts
  packages/crypto/__tests__/validation/rules/models/transactions/delegate-registration.test.ts
  packages/crypto/__tests__/validation/rules/models/transactions/delegate-resignation.test.ts
  packages/crypto/__tests__/validation/rules/models/transactions/ipfs.test.ts
  packages/crypto/__tests__/validation/rules/models/transactions/multi-payment.test.ts
  packages/crypto/__tests__/validation/rules/models/transactions/multi-signature.test.ts
  packages/crypto/__tests__/validation/rules/models/transactions/second-signature.test.ts
  packages/crypto/__tests__/validation/rules/models/transactions/timelock-transfer.test.ts
  packages/crypto/__tests__/validation/rules/models/transactions/transfer.test.ts
  packages/crypto/__tests__/validation/rules/models/transactions/vote.test.ts
  packages/crypto/__tests__/validation/rules/public-key.test.ts
  packages/crypto/__tests__/validation/rules/username.test.ts
  packages/crypto/__tests__/validation/validator.test.ts
  packages/crypto/src/validation/engine.ts
  packages/crypto/src/validation/extensions/bignumber.ts
  packages/crypto/src/validation/extensions/transactions/base.ts
  packages/crypto/src/validation/index.ts
  packages/crypto/src/validation/rules/address.ts
  packages/crypto/src/validation/rules/index.ts
  packages/crypto/src/validation/rules/models/transactions/delegate-registration.ts
  packages/crypto/src/validation/rules/models/transactions/delegate-resignation.ts
  packages/crypto/src/validation/rules/models/transactions/ipfs.ts
  packages/crypto/src/validation/rules/models/transactions/multi-payment.ts
  packages/crypto/src/validation/rules/models/transactions/multi-signature.ts
  packages/crypto/src/validation/rules/models/transactions/second-signature.ts
  packages/crypto/src/validation/rules/models/transactions/timelock-transfer.ts
  packages/crypto/src/validation/rules/models/transactions/transfer.ts
  packages/crypto/src/validation/rules/models/transactions/vote.ts
  packages/crypto/src/validation/rules/public-key.ts
  packages/crypto/src/validation/rules/username.ts
  packages/crypto/src/validation/validator.ts
  packages/crypto/src/validation/validators/transaction.ts
Labels: Type: Refactor

#2025 fixed exit
  install.sh
Labels: Type: Bugfix

#2042 fix: Core-SV-009 and Core-SV-010
  .circleci/config.yml
  packages/core-blockchain/lib/blockchain.js
  packages/core-p2p/__tests__/utils/is-myself.test.js
  packages/core-p2p/lib/utils/is-myself.js
  packages/core/package.json
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2043 fix: add devnet tx exceptions
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#2044 refactor: remove progress tracker and further reduce log noise
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/utils/tick-sync-tracker.ts
  packages/core-database-postgres/src/spv.ts
  packages/core-interfaces/src/core-logger/logger.ts
  packages/core-logger-winston/__tests__/logger.test.ts
  packages/core-logger-winston/src/defaults.ts
  packages/core-logger-winston/src/driver.ts
  packages/core-logger-winston/src/formatter.ts
  packages/core-logger/__tests__/__stubs__/logger.ts
  packages/core-logger/src/logger.ts
  packages/core-p2p/src/monitor.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2045 fix(core-p2p): ip address validation
  packages/core-p2p/__tests__/utils/is-myself.test.ts
  packages/core-p2p/__tests__/utils/is-valid-peer.test.ts
  packages/core-p2p/src/court/guard.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/utils/index.ts
  packages/core-p2p/src/utils/is-myself.ts
  packages/core-p2p/src/utils/is-valid-peer.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix
