Repository ArkEcosystem/core, pull requests merged in 2019-10, with the labels that each got.

#2998 refactor(core): use default heap size regardless of available memory
  packages/core/src/shared/start.ts
Labels: Complexity: Low, Type: Refactor

#2999 refactor: remove asset migration heuristic
  packages/core-database-postgres/src/postgres-connection.ts
Labels: Complexity: Low, Type: Refactor

#3001 feat(crypto): allow passing height to `configManager.isNewMilestone`
  __tests__/unit/crypto/managers/config.test.ts
  packages/crypto/src/managers/config.ts
Labels: Complexity: Low, Type: Feature

#3008 fix(crypto): run ajv validator again when encountering exceptions
  __tests__/unit/crypto/blocks/factory.test.ts
  __tests__/unit/crypto/fixtures/block.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/validation/index.ts
  packages/crypto/src/validation/keywords.ts
Labels: Complexity: Medium, Type: Bugfix

#3005 refactor(core-api): add `vendorField` and `timestamp` to `/locks` endpoint
  __tests__/integration/core-api/handlers/locks.test.ts
  __tests__/integration/core-api/utils.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  packages/core-api/src/handlers/locks/schema.ts
  packages/core-database/src/repositories/utils/search-entries.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/transactions/builders/transactions/htlc-lock.ts
  packages/crypto/src/transactions/builders/transactions/multi-payment.ts
  packages/crypto/src/transactions/types/htlc-lock.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: Medium, Type: Refactor

#2994 refactor(core-api): integrate hapi-pagination to replace fork
  packages/core-api/package.json
  packages/core-api/src/defaults.ts
  packages/core-api/src/handlers/transactions/routes.ts
  packages/core-api/src/plugins/pagination/config.ts
  packages/core-api/src/plugins/pagination/decorate.ts
  packages/core-api/src/plugins/pagination/ext.ts
  packages/core-api/src/plugins/pagination/index.ts
  packages/core-api/src/server.ts
  yarn.lock
Labels: Complexity: High, Type: Refactor

#3011 feat(core-database): emit `round.missed` for each active delegate that didn't forge
  packages/core-database/src/database-service.ts
  packages/core-event-emitter/src/index.ts
Labels: Complexity: Low, Type: Feature

#3010 perf(crypto): replace bignumber.js with native BigInt
  __tests__/integration/core-api/handlers/locks.test.ts
  __tests__/integration/core-api/handlers/wallets.test.ts
  __tests__/integration/core-tester-cli/shared.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/unit/core-state/wallets/wallet.test.ts
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-utils/delegate-calculator.test.ts
  __tests__/unit/core-webhooks/conditions.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/transactions/factory.test.ts
  __tests__/unit/crypto/validation/keywords.test.ts
  packages/core-magistrate-crypto/src/interfaces.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-resignation.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-snapshots/src/transport/codec.ts
  packages/core-tester-cli/src/signer.ts
  packages/core-transaction-pool/src/dynamic-fee.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-utils/src/delegate-calculator.ts
  packages/core-vote-report/src/handler.ts
  packages/core-webhooks/src/conditions.ts
  packages/core/src/commands/network/generate.ts
  packages/crypto/package.json
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/blocks/deserializer.ts
  packages/crypto/src/blocks/serializer.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/transactions/types/htlc-lock.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/transactions/types/transfer.ts
  packages/crypto/src/utils/bignum.ts
  packages/crypto/src/validation/keywords.ts
  yarn.lock
Labels: Complexity: Medium, Type: Performance

#3015 perf(crypto): memoize base58 de/encoding
  packages/crypto/package.json
  packages/crypto/src/crypto/bip38.ts
  packages/crypto/src/identities/address.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/utils/base58.ts
  yarn.lock
Labels: Complexity: Low, Type: Performance

#3014 refactor: remove `vendorFieldHex`
  __tests__/integration/core-api/handlers/transactions.test.ts
  __tests__/integration/core-p2p/fixtures/block-with-transactions.json
  __tests__/unit/core-jest-matchers/models/transaction.test.ts
  __tests__/unit/core-jest-matchers/transactions/valid-second-signature.test.ts
  __tests__/unit/core-jest-matchers/transactions/valid.test.ts
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  __tests__/unit/crypto/fixtures/block.ts
  __tests__/unit/crypto/fixtures/multi-transaction.ts
  __tests__/unit/crypto/fixtures/transaction.ts
  __tests__/unit/crypto/transactions/builders/transactions/multi-payment.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/validation/formats.test.ts
  __tests__/utils/fixtures/unitnet/blocks.ts
  benchmark/fixtures/block/deserialized/transactions.json
  benchmark/fixtures/transaction/deserialized/0.json
  packages/core-api/src/handlers/blocks/schema.ts
  packages/core-api/src/handlers/transactions/schema.ts
  packages/core-api/src/handlers/votes/schema.ts
  packages/core-api/src/handlers/wallets/schema.ts
  packages/core-database-postgres/src/migrations/20191003000000-migrate-vendor-field-hex.sql
  packages/core-database-postgres/src/migrations/index.ts
  packages/core-database-postgres/src/models/transaction.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  packages/core-snapshots/src/transport/codec.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/transactions/deserializer.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/transactions/types/schemas.ts
  packages/crypto/src/transactions/types/transaction.ts
  packages/crypto/src/validation/formats.ts
Labels: Complexity: High, Type: Refactor

#3022 perf: ditch unnecessary reindex() in multi-payment bootstrap
  packages/core-transactions/src/handlers/multi-payment.ts
Labels: Complexity: Low, Type: Performance

#3023 perf(core-transactions): htlc bootstrap
  __tests__/integration/core-transactions/handlers/htlc-claim.test.ts
  __tests__/integration/core-transactions/handlers/htlc-refund.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-database-postgres/src/queries/index.ts
  packages/core-database-postgres/src/queries/state-builder/claimed-locks.sql
  packages/core-database-postgres/src/queries/state-builder/open-locks.sql
  packages/core-database-postgres/src/queries/state-builder/refunded-locks.sql
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/transaction-reader.ts
Labels: Complexity: Medium, Type: Performance

#2925 feat(core-snapshots): add support for transaction nonces
  __tests__/unit/core-snapshots/transport/codec.test.ts
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/db/queries/transactions/timestamp-higher.sql
  packages/core-snapshots/src/db/queries/transactions/timestamp-range.sql
  packages/core-snapshots/src/transport/codec.ts
  packages/core-snapshots/src/transport/index.ts
Labels: Complexity: Low, Type: Feature

#3027 refactor(core-http-utils): add trailing-slash plugin
  packages/core-http-utils/package.json
  packages/core-http-utils/src/plugins/trailing-slash.ts
  packages/core-http-utils/src/server/create.ts
  packages/core-vote-report/package.json
  packages/core-vote-report/src/server.ts
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor

#3028 chore(new-relic): update dependencies to support node.js 12
  packages/core-new-relic/package.json
  yarn.lock
Labels: Complexity: Low, Type: Task

#3025 fix(crypto): match the long version of bytebuffer
  __tests__/unit/crypto/transactions/deserializer.test.ts
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Low, Type: Task

#3036 fix(core-forger): use correct IV length for encryption
  __tests__/unit/core-forger/delegate.test.ts
  packages/core-forger/package.json
  packages/core-forger/src/delegate.ts
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Low, Type: Bugfix

#3034 refactor(core-api): integrate hapi-pagination to replace fork
  packages/core-api/package.json
  packages/core-api/src/defaults.ts
  packages/core-api/src/handlers/transactions/routes.ts
  packages/core-api/src/plugins/pagination/config.ts
  packages/core-api/src/plugins/pagination/decorate.ts
  packages/core-api/src/plugins/pagination/ext.ts
  packages/core-api/src/plugins/pagination/index.ts
  packages/core-api/src/server.ts
  yarn.lock
Labels: Complexity: High, Type: Refactor

#3035 release: 2.5.26
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3037 fix: basic validation on incoming p2p data + terminate socket on error
  __tests__/integration/core-p2p/socket-server/peer-with-remote-access.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  packages/core-p2p/src/socket-server/versions/utils.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#3049 chore(core-database-postgres): load migration file names automatically
  packages/core-database-postgres/src/migrations/index.ts
Labels: Complexity: Low, Type: Task

#3050 fix(core-p2p): convert isAppReady response to object
  packages/core-p2p/src/socket-server/versions/utils.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3048 fix(core-database-postgres): store vendor field in bytea
  packages/core-database-postgres/src/migrations/20191003000000-migrate-vendor-field-hex.sql
Labels: Complexity: Low, Type: Bugfix

#3057 chore: switch to TypeScript 3.6
  package.json
  packages/core-blockchain/package.json
  packages/core-p2p/package.json
  packages/core/package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#3056 refactor(core-p2p): cleanup socket errors
  __tests__/integration/core-p2p/__support__/mock-socket-server/manager.ts
  __tests__/integration/core-p2p/__support__/mock-socket-server/worker.js
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  packages/core-database-postgres/src/migrations/index.ts
  packages/core-p2p/src/enums.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-p2p/src/socket-server/worker.ts
  packages/core-p2p/src/utils/socket.ts
  packages/core-transaction-pool/src/processor.ts
Labels: Complexity: Medium, Type: Refactor

#3055 fix(crypto): handle mainnet address exceptions
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/crypto/identities/address.test.ts
  packages/core-container/src/config/index.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/state-builder.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/identities/address.ts
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/networks/mainnet/exceptions.json
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/transactions/types/htlc-lock.ts
  packages/crypto/src/transactions/types/transfer.ts
  packages/crypto/src/transactions/utils.ts
  packages/crypto/src/utils/index.ts
Labels: Complexity: Medium, Type: Bugfix

#3060 docs: 2.6.0 changelog
  CHANGELOG.md
Labels: Type: Documentation

#3058 chore(core-database-postgres): convert BYTEA to/from string
  packages/core-database-postgres/src/models/transaction.ts
Labels: Complexity: Medium, Type: Task

#3062 Block schema validation
  __tests__/unit/crypto/blocks/factory.test.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/validation/index.ts
Labels: Complexity: Low

#3051 chore(core): load core-p2p earlier
  __tests__/integration/core-transaction-pool/__support__/setup.ts
  __tests__/utils/config/testnet/plugins.js
  __tests__/utils/config/unitnet/plugins.js
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
Labels: Bounty: Tier 5, Complexity: Low, Status: Collaborator Approved, Type: Refactor

#3064 misc(crypto): add devnet milestones
  packages/core-p2p/src/defaults.ts
  packages/crypto/src/networks/devnet/milestones.json
Labels: Complexity: Low

#3065 release: 2.6.0-next.0
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3066 chore(core-exchange-json-rpc): bump @arkecosystem/exchange-json-rpc to 1.0.6
  packages/core-exchange-json-rpc/package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#3067 chore(crypto): updat milestone height
  packages/crypto/src/networks/devnet/milestones.json
Labels: Complexity: Low, Type: Task

#3069 fix(core-p2p): raise `getCommonBlocks` rate limit
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/utils/build-rate-limiter.ts
Labels: Complexity: Low, Type: Bugfix

#3072 chore: use node 12 as default version
  .github/workflows/benchmark.yml
  .github/workflows/functional.yml
  .github/workflows/test.yml
  .nvmrc
  install.sh
  vagrant/bootstrap.sh
Labels: Complexity: Low, Type: Task

#3077 chore(crypto): 2.6 prereleases after milestone
  packages/crypto/src/networks/devnet/milestones.json
Labels: Complexity: Low, Status: Contributor Approved, Type: Task

#3075 fix(core-api): add missing offset handling to /api/peers
  packages/core-api/src/handlers/peers/controller.ts
Labels: Complexity: Low, Type: Bugfix

#3081 fix(core-tester-cli): support nonces and chunk transactions before broadcast
  packages/core-tester-cli/package.json
  packages/core-tester-cli/src/commands/command.ts
  packages/core-tester-cli/src/commands/make/block.ts
  packages/core-tester-cli/src/signer.ts
Labels: Complexity: Medium, Type: Bugfix

#3083 feat(core-api): add `/transactions/schemas` endpoint
  packages/core-api/src/handlers/transactions/controller.ts
  packages/core-api/src/handlers/transactions/routes.ts
Labels: Complexity: Low, Type: Feature

#3084 refactor(core-event-emitter): add `stateBuilder.finished` to ApplicationEvents
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-database-postgres/package.json
  packages/core-database-postgres/src/state-builder.ts
  packages/core-event-emitter/src/index.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Refactor

#3082 refactor: make block ping log less confusing
  __tests__/unit/core-state/stores/state.test.ts
  packages/core-state/src/stores/state.ts
Labels: Complexity: Low, Type: Refactor

#3086 fix(core-transaction-pool): create new wallet if not found
  packages/core-database/src/database-service.ts
  packages/core-state/src/wallets/temp-wallet-manager.ts
Labels: Complexity: Low, Type: Bugfix

#3087 fix: use strict comparison to decide if a transaction should be enabled
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-payment.ts
Labels: Complexity: Low, Type: Bugfix

#3078 refactor(core-api): sort peers by height, latency
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-api/handlers/peers.test.ts
  packages/core-api/src/handlers/peers/controller.ts
Labels: Bounty: Tier 4, Complexity: Medium, Status: Collaborator Approved, Status: Needs Review, Type: Refactor

#3089 chore: print more details in log messages
  __tests__/unit/core-blockchain/state-machine.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Type: Task

#3091 refactor(core-api): format timestamp of locks
  __tests__/integration/core-api/handlers/locks.test.ts
  __tests__/integration/core-api/handlers/wallets.test.ts
  __tests__/integration/core-api/utils.ts
  packages/core-api/src/handlers/locks/transformer.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Status: Contributor Approved, Type: Refactor

#3095 fix(core-transactions): throw if transaction key is already taken
  __tests__/unit/core-transactions/handler-registry.test.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/transactions/registry.ts
Labels: Complexity: Low, Type: Bugfix

#3101 chore: update docker to node.js 12
  docker/production/Dockerfile
  scripts/docker/templates/devnet/Dockerfile
  scripts/docker/templates/testnet/Dockerfile
Labels: Complexity: Low

#3096 feat: expose transaction height, blockId and generatorPublicKey during bootstrap
  packages/core-database-postgres/src/queries/state-builder/assets-by-type.sql
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
Labels: Complexity: Low, Type: Feature

#3103 fix(core-p2p): properly terminate bad connections
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#3109 fix(core-database): set last height before initializing last block to use correct milestones
  packages/core-database/src/database-service.ts
Labels: Complexity: Low, Type: Bugfix

#3108 refactor(crypto): overwrite arrays when merging milestones
  __tests__/unit/crypto/managers/config.test.ts
  packages/crypto/src/managers/config.ts
Labels: Bounty: Tier 3, Complexity: Low, Status: Contributor Approved, Type: Refactor

#3121 refactor(core-magistrate): use type from core-interfaces
  packages/core-magistrate-transactions/package.json
  packages/core-magistrate-transactions/src/wallet-manager.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Refactor

#3112 fix(core-api): use numerics for typeGroups in /transactions/types
  __tests__/integration/core-api/handlers/transactions.test.ts
  packages/core-api/src/handlers/transactions/controller.ts
Labels: Complexity: Low, Type: Bugfix

#3128 fix(core-magistrate-transactions): emit correct event
  packages/core-magistrate-transactions/src/events.ts
Labels: Bounty: Tier 5, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3092 fix(core-p2p): parallel download
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/unit/core-blockchain/mocks/p2p/network-monitor.ts
  __tests__/unit/core-blockchain/mocks/p2p/peer-storage.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-state/mocks/p2p/network-monitor.ts
  __tests__/unit/core-state/mocks/p2p/peer-storage.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-interfaces/src/core-p2p/network-monitor.ts
  packages/core-interfaces/src/core-p2p/peer-communicator.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Medium

#3130 fix(core-magistrate): get connection from databaseservice
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
Labels: Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3118 refactor(core-magistrate): business and bridgechain ids as numbers
  __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
  __tests__/functional/transaction-forging/bridgechain-update.test.ts
  __tests__/helpers/transaction-factory.ts
  __tests__/unit/core-magistrate/builders/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate/builders/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
  __tests__/unit/core-magistrate/handlers/business-registration.test.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/wallet.test.ts
  packages/core-magistrate-crypto/src/builders/bridgechain-resignation.ts
  packages/core-magistrate-crypto/src/interfaces.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-resignation.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/interfaces.ts
  packages/core-magistrate-transactions/src/wallet-manager.ts
Labels: Complexity: Medium, Status: Contributor Approved, Type: Refactor

#3110 refactor(core-database): refactor searchBusinesses & searchBridgechains
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Complexity: Low, Status: Contributor Approved, Status: Needs Review, Type: Feature

#3119 feat(core-api): implement businesses/bridgechains endpoint
  packages/core-api/src/handlers/businesses/controller.ts
  packages/core-api/src/handlers/businesses/methods.ts
  packages/core-api/src/handlers/businesses/routes.ts
  packages/core-api/src/handlers/businesses/schema.ts
Labels: Complexity: Low, Status: Contributor Approved, Status: Needs Review, Type: Feature

#3132 feat(core-magistrate): ensure unique bridgechain name per business
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  __tests__/functional/transaction-forging/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Status: Contributor Approved, Status: Needs Review, Type: Feature

#3136 refactor(crypto): use multiPaymentLimit from milestone if available
  packages/crypto/src/transactions/builders/transactions/multi-payment.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Refactor

#3138 fix(core-blockchain): add transactions back to pool only after reverting all blocks
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-transaction-pool/connection.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Bugfix

#3142 fix(core): read `paths.config` instead of env variable
  __tests__/unit/core-transaction-pool/__stubs__/connection.ts
  packages/core/src/commands/chain/replay.ts
  packages/core/src/commands/core/run.ts
  packages/core/src/commands/forger/run.ts
  packages/core/src/commands/relay/run.ts
  packages/core/src/commands/snapshot/dump.ts
  packages/core/src/commands/snapshot/restore.ts
  packages/core/src/commands/snapshot/rollback.ts
  packages/core/src/commands/snapshot/truncate.ts
  packages/core/src/commands/snapshot/verify.ts
  packages/core/src/helpers/replay.ts
  packages/core/src/helpers/snapshot.ts
  packages/core/src/utils.ts
Labels: Complexity: Low, Type: Bugfix

#3141 refactor(core-magistrate-transactions): BridgechainUpdate errors
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
Labels: Bounty: Tier 4, Complexity: Low, Type: Refactor

#3143 refactor(core-magistrate-crypto): consolidate bridgechain schema and streamline its usage
  packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
  packages/core-magistrate-crypto/src/transactions/utils/bridgechain-schema.ts
  packages/core-magistrate-crypto/src/transactions/utils/bridgechain-schemas.ts
Labels: Bounty: Tier 4, Complexity: Medium, Type: Refactor

#3145 refactor(core-database): convert htlc lock vendorfield to string during bootstrap
  packages/core-transactions/src/handlers/htlc-lock.ts
Labels: Bounty: Tier 4, Complexity: Low, Type: Refactor

#3140 fix(core-p2p): uncaught IPC timeout
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#3146 Revert "refactor(core-magistrate-crypto): consolidate bridgechain schema and streamline its usage"
  packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
  packages/core-magistrate-crypto/src/transactions/utils/bridgechain-schema.ts
  packages/core-magistrate-crypto/src/transactions/utils/bridgechain-schemas.ts
Labels: Complexity: Medium, Type: Refactor

#3148 fix(core-magistrate-crypto): improve 'name' field validation to avoid illegal characters
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  __tests__/functional/transaction-forging/business-registration.test.ts
  __tests__/functional/transaction-forging/business-update.test.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
  packages/core-magistrate-crypto/src/transactions/utils/business-schema.ts
  packages/crypto/src/validation/schemas.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3150 polish(core-magistrate-crypto): remove redundant bridgechain schema properties
  packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved

#3147 refactor(core-api): fallback to core typegroup if querying by type
  __tests__/unit/core-database/repositories/transactions-business-repository.test.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
Labels: Bounty: Tier 4, Complexity: Low, Type: Refactor

#3137 refactor(core-magistrate): don't allow multiple business or bridgechain updates for the same id
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
  __tests__/functional/transaction-forging/bridgechain-update.test.ts
  __tests__/functional/transaction-forging/business-registration.test.ts
  __tests__/functional/transaction-forging/business-resignation.test.ts
  __tests__/functional/transaction-forging/business-update.test.ts
  __tests__/functional/transaction-forging/multi-payment.test.ts
  packages/core-jest-matchers/src/functional/accepted.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
Labels: Bounty: Tier 3, Complexity: Low, Status: Collaborator Approved, Status: Needs Review, Type: Refactor

#3156 refactor(core-magistrate-crypto): use 4 bytes instead of 8 bytes for bridgechainId
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-crypto/src/transactions/bridgechain-resignation.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
Labels: Complexity: Low, Type: Refactor

#3153 fix(core-database): correctly reduce indexed bridgechain entries
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#3152 refactor(crypto): change MaximumPaymentCountExceededError error
  packages/crypto/src/errors.ts
  packages/crypto/src/transactions/builders/transactions/multi-payment.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Refactor

#3155 fix(core-blockchain): write accepted blocks to database before rolling back
  __tests__/unit/core-blockchain/mocks/blockchain.ts
  __tests__/unit/core-blockchain/processor/handlers/accept-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/exception-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/state-machine.ts
Labels: Complexity: Low, Type: Bugfix

#3157 refactor(crypto): update multipayment limits
  __tests__/functional/transaction-forging/multi-payment.test.ts
  __tests__/unit/core-container/__stubs__/config/milestones.json
  __tests__/unit/crypto/transactions/deserializer.test.ts
  packages/crypto/src/networks/devnet/milestones.json
  packages/crypto/src/networks/mainnet/milestones.json
  packages/crypto/src/networks/testnet/milestones.json
  packages/crypto/src/networks/unitnet/milestones.json
Labels: Complexity: Low, Type: Refactor

#3158 fix(core-p2p): timeout promise race
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core-p2p/src/socket-server/worker.ts
  packages/core-p2p/src/utils/socket.ts
Labels: Complexity: Low, Type: Bugfix

#3160 feat(core-api): add additional fields to businesses search schema
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Feature

#3161 chore(core-p2p): improve log message
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Low, Type: Task

#3163 fix(core-p2p): call next() so that the request can proceed
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#3162 refactor(core-magistrate-crypto): use URI schema for website and repository validation
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
  __tests__/functional/transaction-forging/bridgechain-update.test.ts
  __tests__/functional/transaction-forging/business-registration.test.ts
  __tests__/functional/transaction-forging/business-resignation.test.ts
  __tests__/functional/transaction-forging/business-update.test.ts
  __tests__/unit/core-magistrate/builders/business-registration.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
  __tests__/unit/core-magistrate/helper.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate/transactions/business-registration.test.ts
  __tests__/unit/core-magistrate/wallet.test.ts
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
  packages/core-magistrate-crypto/src/transactions/utils/business-schema.ts
  packages/crypto/src/validation/schemas.ts
Labels: Bounty: Tier 2, Complexity: High, Status: Collaborator Approved

#3168 refactor(core-p2p): pluralize logs
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-verifier.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Refactor

#3166 refactor(core-api): more restrictive wallet id schema
  __tests__/integration/core-api/handlers/wallets.test.ts
  __tests__/unit/core-database/__fixtures__/wallets.json
  __tests__/unit/core-state/__fixtures__/wallets.json
  packages/core-api/src/handlers/shared/schemas/wallet-id.ts
  packages/core-api/src/handlers/wallets/schema.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Status: Needs Testcase, Type: Refactor

#3174 feat(core-container): log-process-errors
  packages/core-container/package.json
  packages/core-container/src/container.ts
  yarn.lock
Labels: Complexity: Medium, Type: Feature

#3170 feat(core-p2p): implement throttling on outgoing p2p communication
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/utils/index.ts
Labels: Complexity: Low, Type: Feature

#3178 fix(core-transactions): add `delegate.producedBlocks` attribute
  packages/core-transactions/src/handlers/delegate-registration.ts
Labels: Complexity: Low, Type: Bugfix

#3165 feat(core-api): add additional fields to bridgechains search schema
  __tests__/unit/core-database/repositories/utils/filter-rows.test.ts
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-database/src/repositories/utils/filter-rows.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Feature

#3171 fix(core-p2p): return error when app is not ready
  packages/core-forger/src/manager.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#3181 chore(core-database): remove misleading order by expirationValue
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Complexity: Low, Type: Task

#3183 refactor(core-transactions): rename handler parameter, check against correct walletManager
  __tests__/unit/core-magistrate/handlers/bridgechain-handlers.test.ts
  __tests__/unit/core-magistrate/handlers/business-handlers.test.ts
  __tests__/unit/core-magistrate/handlers/business-registration.test.ts
  __tests__/unit/core-state/wallets/wallet-manager-htlc.test.ts
  __tests__/unit/core-state/wallets/wallet-manager-multipayment.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/htlc-claim.ts
  packages/core-transactions/src/handlers/htlc-lock.ts
  packages/core-transactions/src/handlers/htlc-refund.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/interfaces.ts
Labels: Complexity: Medium, Type: Refactor

#3185 fix(core-transactions): reindex wallet when applying delegate resignation
  packages/core-transactions/src/handlers/delegate-resignation.ts
Labels: Complexity: Low, Status: Contributor Approved, Type: Bugfix
