Repository ArkEcosystem/core, pull requests merged in 2019-03, with the labels that each got.

#2175 refactor(crypto): de/serialization
  __tests__/integration/core-p2p/server/1.test.ts
  __tests__/integration/core-transaction-pool/guard.test.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-database/wallet-manager.test.ts
  __tests__/unit/core-p2p/court/guard.test.ts
  __tests__/unit/crypto/transactions/transaction.test.ts
  __tests__/unit/crypto/validation/ajv-wrapper.test.ts
  __tests__/unit/crypto/validation/keywords.test.ts
  benchmark/transaction/serialize/0.js
  packages/core-database-postgres/src/models/transaction.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/models/block.ts
  packages/crypto/src/transactions/deserializers/block.ts
  packages/crypto/src/transactions/deserializers/transaction.ts
  packages/crypto/src/transactions/serializers/block.ts
  packages/crypto/src/transactions/serializers/transaction.ts
  packages/crypto/src/transactions/types/schemas.ts
  packages/crypto/src/transactions/types/transaction.ts
  packages/crypto/src/transactions/types/transfer.ts
  packages/crypto/src/validation/keywords.ts
  packages/crypto/src/validation/schemas.ts
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#2189 feat(core-tester-cli): test the vendor field
  packages/core-tester-cli/src/commands/command.ts
  packages/core-tester-cli/src/commands/send/transfer.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#2191 feat(core-tester-cli): add the ability to send multiple waves
  packages/core-tester-cli/src/commands/command.ts
  packages/core-tester-cli/src/shared/send.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#2192 feat(core): add support for reinstalling the current version
  packages/core/src/commands/reinstall.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#2190 feat(core): add support for forced updates
  packages/core/src/commands/update.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#2196 fix(core): parse the network for the snapshot restore command
  packages/core/src/commands/snapshot/restore.ts
Labels: Complexity: Low, Type: Bugfix

#2197 release: 2.2.0-rc.0
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Type: Release

#2184 feat(core-api): more params for delegates search endpoint
  __tests__/integration/core-api/v2/handlers/delegates.test.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-utils/delegate-calculator.test.ts
  __tests__/unit/core-utils/has-some-property.test.ts
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-api/src/versions/2/delegates/transformer.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-utils/src/delegate-calculator.ts
  packages/core-utils/src/has-some-property.ts
  packages/core-utils/src/index.ts
Labels: Bounty: Tier 2, Complexity: Medium, Status: Collaborator Approved, Status: In Progress, Status: Needs Testcase, Type: Feature

#2204 fix(core-tester-cli): set crypto network for debug commands
  .circleci/config.yml
  __tests__/unit/core-tester-cli/commands/debug/deserialize.test.ts
  __tests__/unit/core-tester-cli/commands/debug/identity.test.ts
  __tests__/unit/core-tester-cli/commands/debug/serialize.test.ts
  __tests__/unit/core-tester-cli/commands/debug/verify-second.test.ts
  __tests__/unit/core-tester-cli/commands/debug/verify.test.ts
  packages/core-tester-cli/src/commands/command.ts
  packages/core-tester-cli/src/commands/debug/deserialize.ts
  packages/core-tester-cli/src/commands/debug/identity.ts
  packages/core-tester-cli/src/commands/debug/serialize.ts
  packages/core-tester-cli/src/commands/debug/verify-second-signature.ts
  packages/core-tester-cli/src/commands/debug/verify.ts
  packages/crypto/src/managers/index.ts
Labels: Complexity: Medium, Type: Bugfix

#2205 feat(core-api): add active delegates endpoint
  __tests__/integration/core-api/v2/handlers/delegates.test.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  packages/core-api/src/versions/2/delegates/controller.ts
  packages/core-api/src/versions/2/delegates/methods.ts
  packages/core-api/src/versions/2/delegates/routes.ts
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/delegates-business-repository.ts
  packages/core-p2p/src/peer-verifier.ts
Labels: Bounty: Tier 2, Complexity: Medium, Status: Collaborator Approved, Status: In Progress, Type: Feature

#2207 fix: vote balance update
  packages/core-blockchain/__tests__/blockchain.test.ts
  packages/core-database/__tests__/wallet-manager.test.ts
  packages/core-database/src/wallet-manager.ts
Labels: Complexity: Medium, Type: Bugfix

#2201 refactor: move transaction type specific logic into core-transactions
  __tests__/integration/core-transaction-pool/guard.test.ts
  __tests__/integration/core-transaction-pool/pool-wallet-manager.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/guard.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-interfaces/src/core-transaction-pool/transaction-guard.ts
  packages/core-interfaces/src/core-transaction-pool/transaction-pool.ts
  packages/core-transaction-pool/src/guard.ts
  packages/core-transaction-pool/src/mem.ts
  packages/core-transaction-pool/src/pool-wallet-manager.ts
  packages/core-transactions/package.json
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/interfaces.ts
  packages/core-transactions/src/service-registry.ts
  packages/core-transactions/src/services/delegate-registration.ts
  packages/core-transactions/src/services/delegate-resignation.ts
  packages/core-transactions/src/services/ipfs.ts
  packages/core-transactions/src/services/multi-payment.ts
  packages/core-transactions/src/services/multi-signature.ts
  packages/core-transactions/src/services/second-signature.ts
  packages/core-transactions/src/services/timelock-transfer.ts
  packages/core-transactions/src/services/transaction.ts
  packages/core-transactions/src/services/transfer.ts
  packages/core-transactions/src/services/vote.ts
  packages/core-transactions/src/utils.ts
  packages/crypto/src/transactions/types/transaction.ts
Labels: Complexity: High, Status: In Progress, Type: Refactor

#2208 refactor(core-forger): Increase timeout for getting the network state
  packages/core-forger/src/client.ts
  packages/core-forger/src/manager.ts
Labels: Complexity: Low, Type: Refactor

#2211 fix: vote balance update (develop)
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-database/wallet-manager.test.ts
  packages/core-api/src/versions/2/delegates/methods.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-utils/src/index.ts
Labels: Complexity: Medium, Type: Bugfix

#2210 refactor(core-blockchain): remove old fast rebuild code
  __tests__/unit/core-api/__support__/setup.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/machines/actions/fork.test.ts
  __tests__/unit/core-blockchain/machines/actions/rebuild-from-network.test.ts
  __tests__/unit/core-blockchain/machines/blockchain.test.ts
  __tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts
  __tests__/unit/core-blockchain/queue/interface.test.ts
  __tests__/unit/core-blockchain/queue/process.test.ts
  __tests__/unit/core-blockchain/queue/rebuild.test.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/utils/config/testnet/plugins.js
  __tests__/utils/config/unitnet/plugins.js
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/defaults.ts
  packages/core-blockchain/src/machines/actions/fork.ts
  packages/core-blockchain/src/machines/actions/rebuild-from-network.ts
  packages/core-blockchain/src/machines/blockchain.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/queue/index.ts
  packages/core-blockchain/src/queue/interface.ts
  packages/core-blockchain/src/queue/process.ts
  packages/core-blockchain/src/queue/rebuild.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-blockchain/src/state-storage.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
Labels: Complexity: Low, Status: In Progress, Type: Refactor

#2209 refactor: purely rely on in-memory wallets based on transactions
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-api/__support__/setup.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-database/__fixtures__/database-connection-stub.ts
  __tests__/unit/core-database/database-service.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-container/src/container.ts
  packages/core-database-postgres/src/index.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/migrations/20190307000000-drop-wallets-table.sql
  packages/core-database-postgres/src/migrations/index.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/queries/index.ts
  packages/core-database-postgres/src/queries/integrity-verifier/block-rewards.sql
  packages/core-database-postgres/src/queries/integrity-verifier/delegates-forged-blocks.sql
  packages/core-database-postgres/src/queries/integrity-verifier/delegates.sql
  packages/core-database-postgres/src/queries/integrity-verifier/last-forged-blocks.sql
  packages/core-database-postgres/src/queries/integrity-verifier/multi-signatures.sql
  packages/core-database-postgres/src/queries/integrity-verifier/received-transactions.sql
  packages/core-database-postgres/src/queries/integrity-verifier/second-signatures.sql
  packages/core-database-postgres/src/queries/integrity-verifier/sent-transactions.sql
  packages/core-database-postgres/src/queries/integrity-verifier/votes.sql
  packages/core-database-postgres/src/queries/spv/delegates-ranks.sql
  packages/core-database-postgres/src/queries/wallets/all.sql
  packages/core-database-postgres/src/queries/wallets/find-by-address.sql
  packages/core-database-postgres/src/queries/wallets/find-negative-balances.sql
  packages/core-database-postgres/src/queries/wallets/find-negative-vote-balances.sql
  packages/core-database-postgres/src/repositories/index.ts
  packages/core-database-postgres/src/repositories/wallets.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-interfaces/src/core-database/database-connection.ts
  packages/core-interfaces/src/core-database/database-service.ts
Labels: Complexity: High, Status: In Progress, Type: Refactor

#2213 fix(core-tester-cli): Fix the description of debug:serialize
  packages/core-tester-cli/src/commands/debug/serialize.ts
Labels: Complexity: Low, Type: Bugfix

#2214 feat(core-p2p): Don't spoil the quorum if the peer has !forgingAllowed
  packages/core-p2p/src/network-state.ts
Labels: Complexity: Low, Type: Feature

#2217 fix(core-transaction-pool): invalid transactions after rollback
  packages/core-blockchain/src/state-storage.ts
  packages/core-transaction-pool/__tests__/connection.test.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Bugfix

#2216 fix(core-blockchain): return if last downloaded block changed
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/state-machine.ts
Labels: Complexity: Low, Type: Bugfix

#2215 refactor(core-p2p): dont dump the reply when /peer/list validation fails
  packages/core-p2p/src/peer.ts
Labels: Complexity: Low, Type: Refactor

#2220 fix(core-blockchain): node stuck during sync
  packages/core-blockchain/src/state-machine.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Bugfix

#2218 feat(core): add restart flags to update command
  packages/core/package.json
  packages/core/src/commands/command.ts
  packages/core/src/commands/config/cli.ts
  packages/core/src/commands/reinstall.ts
  packages/core/src/commands/update.ts
Labels: Bounty: Tier 3, Complexity: Medium, Status: Collaborator Approved, Status: In Progress, Type: Feature

#2222 chore: circleci restore caching + re-organize jobs for unit / integration tests
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/generateConfig.js
Labels: Complexity: High, Type: Task

#2226 chore: merge master into develop
  .circleci/config.yml
  .circleci/configTemplate.json
  CHANGELOG.md
  __tests__/unit/core-database/wallet-manager.test.ts
  deprecated/core-graphql/package.json
  deprecated/core-logger-winston/package.json
  deprecated/core-snapshots-cli/package.json
  docker/production/Dockerfile
  install.sh
  lerna.json
  package.json
  packages/core-api/package.json
  packages/core-api/src/versions/1/transactions/controller.ts
  packages/core-blockchain/package.json
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-forger/src/client.ts
  packages/core-forger/src/index.ts
  packages/core-forger/src/manager.ts
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-p2p/src/network-state.ts
  packages/core-p2p/src/peer.ts
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/core/src/commands/command.ts
  packages/core/src/commands/core/start.ts
  packages/core/src/commands/forger/start.ts
  packages/core/src/commands/top.ts
  packages/core/src/helpers/prompts.ts
  packages/core/src/hooks/command_not_found/suggest.ts
  packages/core/src/process-manager.ts
  packages/core/src/shared/restart.ts
  packages/core/src/shared/start.ts
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2223 fix(core-tester-cli): Don't hide errors from HTTP failures
  packages/core-tester-cli/src/http-client.ts
Labels: Complexity: Low, Type: Bugfix

#2228 chore: sync version with npm
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Task

#2203 refactor: replace axios with got
  __tests__/integration/core-api/v1/utils.ts
  __tests__/integration/core-api/v2/utils.ts
  __tests__/integration/core-forger/client.test.ts
  __tests__/integration/core-json-rpc/__support__/request.ts
  __tests__/integration/core-json-rpc/blocks.test.ts
  __tests__/integration/core-json-rpc/transactions.test.ts
  __tests__/integration/core-json-rpc/wallets.test.ts
  __tests__/integration/core-tester-cli/commands/send/delegate-registration.test.ts
  __tests__/integration/core-tester-cli/commands/send/second-signature.test.ts
  __tests__/integration/core-tester-cli/commands/send/transfer.test.ts
  __tests__/integration/core-tester-cli/commands/send/vote.test.ts
  __tests__/integration/core-tester-cli/shared.ts
  __tests__/integration/core-vote-report/__support__/setup.ts
  __tests__/integration/core-vote-report/server.test.ts
  __tests__/integration/core-webhooks/__support__/setup.ts
  __tests__/integration/core-webhooks/__support__/utils.ts
  __tests__/integration/core-webhooks/server.test.ts
  __tests__/unit/core-http-utils/plugins/content-type.test.ts
  __tests__/unit/core-p2p/monitor.test.ts
  __tests__/unit/core-p2p/peer-verifier.test.ts
  __tests__/unit/core-p2p/peer.test.ts
  __tests__/utils/helpers/api.ts
  package.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-container/src/config/loaders/file-loader.ts
  packages/core-forger/package.json
  packages/core-forger/src/client.ts
  packages/core-http-utils/package.json
  packages/core-json-rpc/package.json
  packages/core-json-rpc/src/server/index.ts
  packages/core-json-rpc/src/server/methods/blocks/latest.ts
  packages/core-json-rpc/src/server/services/network.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/peer.ts
  packages/core-tester-cli/package.json
  packages/core-tester-cli/src/http-client.ts
  packages/core-utils/package.json
  packages/core-utils/src/httpie.ts
  packages/core-utils/src/index.ts
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core-webhooks/src/manager.ts
  yarn.lock
Labels: Complexity: High, Type: Refactor

#2221 feat(core-tester-cli): add make:block command
  __tests__/integration/core-tester-cli/commands/make/block.test.ts
  packages/core-tester-cli/src/commands/command.ts
  packages/core-tester-cli/src/commands/make/block.ts
  packages/core-tester-cli/src/commands/make/wallets.ts
Labels: Complexity: Medium, Type: Feature

#2229 fix(core-api): properly sort semver versions
  __tests__/integration/core-api/v2/handlers/peers.test.ts
  packages/core-api/package.json
  packages/core-api/src/versions/2/peers/controller.ts
Labels: Complexity: Medium, Type: Bugfix

#2231 refactor(core-forger): always use latest available height
  __tests__/unit/core-forger/manager.test.ts
  packages/core-forger/src/manager.ts
  packages/core-p2p/src/network-state.ts
Labels: Complexity: Medium, Type: Refactor

#2233 fix(crypto): keep old vendor field padding
  packages/crypto/src/transactions/serializers/transaction.ts
Labels: Complexity: Low, Type: Bugfix

#2232 fix(crypto): cast tx buffer to string in block audit
  packages/crypto/src/models/block.ts
Labels: Complexity: Low, Type: Bugfix

#2156 feat(crypto): Switch block id to full SHA256
  __tests__/integration/core-forger/__fixtures__/block.ts
  __tests__/integration/core-tester-cli/__fixtures__/block.json
  __tests__/unit/core-forger/__fixtures__/block.ts
  __tests__/unit/crypto/fixtures/block.ts
  __tests__/unit/crypto/models/block.test.ts
  __tests__/unit/crypto/transactions/deserializers/block.test.ts
  __tests__/unit/crypto/validation/ajv-wrapper.test.ts
  __tests__/unit/crypto/validation/keywords.test.ts
  packages/core-api/src/versions/2/blocks/schema.ts
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-api/src/versions/2/shared/schemas/block-id.ts
  packages/core-api/src/versions/2/transactions/schema.ts
  packages/core-api/src/versions/2/votes/schema.ts
  packages/core-api/src/versions/2/wallets/schema.ts
  packages/core-snapshots/src/transport/codecs/core/index.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/models/block.ts
  packages/crypto/src/networks/devnet/milestones.json
  packages/crypto/src/networks/mainnet/milestones.json
  packages/crypto/src/networks/testnet/milestones.json
  packages/crypto/src/networks/unitnet/milestones.json
  packages/crypto/src/transactions/deserializers/block.ts
  packages/crypto/src/transactions/serializers/block.ts
  packages/crypto/src/validation/keywords.ts
  packages/crypto/src/validation/schemas.ts
Labels: Complexity: Low, Difficulty: Advanced, Status: In Progress, Status: Needs Review, Type: Feature

#2235 test(core-forger): Extend tests with a block with full sha256 id
  __tests__/integration/core-forger/__fixtures__/block.ts
  __tests__/integration/core-forger/__fixtures__/blocks.ts
  __tests__/integration/core-forger/client.test.ts
Labels: Complexity: Medium, Test: Unit

#2237 refactor: move wallet class out of crypto
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
  __tests__/unit/core-database/wallet-manager.test.ts
  __tests__/unit/core-database/wallet.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/core-utils/delegate-calculator.test.ts
  __tests__/unit/crypto/transactions/__fixtures__/wallet.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/index.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-database/src/wallet.ts
  packages/core-forger/src/manager.ts
  packages/core-interfaces/src/core-database/business-repository/delegates-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/wallets-business-repository.ts
  packages/core-interfaces/src/core-database/wallet-manager.ts
  packages/core-transaction-pool/src/pool-wallet-manager.ts
  packages/core-transactions/src/interfaces.ts
  packages/core-transactions/src/services/delegate-registration.ts
  packages/core-transactions/src/services/delegate-resignation.ts
  packages/core-transactions/src/services/ipfs.ts
  packages/core-transactions/src/services/multi-payment.ts
  packages/core-transactions/src/services/multi-signature.ts
  packages/core-transactions/src/services/second-signature.ts
  packages/core-transactions/src/services/timelock-transfer.ts
  packages/core-transactions/src/services/transaction.ts
  packages/core-transactions/src/services/transfer.ts
  packages/core-transactions/src/services/vote.ts
  packages/core-vote-report/src/handler.ts
  packages/crypto/src/models/index.ts
  packages/crypto/src/transactions/serializers/block.ts
Labels: Complexity: High, Type: Refactor

#2236 feat(core-database-postgres): transaction asset column
  __tests__/unit/core-blockchain/mocks/database.ts
  __tests__/unit/core-database/__fixtures__/database-connection-stub.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/migrations/20190313000000-add-asset-column-to-transactions-table.sql
  packages/core-database-postgres/src/migrations/index.ts
  packages/core-database-postgres/src/models/transaction.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/queries/integrity-verifier/delegates.sql
  packages/core-database-postgres/src/queries/integrity-verifier/multi-signatures.sql
  packages/core-database-postgres/src/queries/integrity-verifier/second-signatures.sql
  packages/core-database-postgres/src/queries/integrity-verifier/votes.sql
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-connection.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-p2p/src/monitor.ts
  packages/crypto/src/transactions/deserializers/transaction.ts
  packages/crypto/src/transactions/types/transaction.ts
Labels: Complexity: Medium, Type: Feature

#2238 docs: less noise in the GitHub PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Low, Type: Documentation

#2239 chore(core): Disable webhooks on testnet
  packages/core/bin/config/testnet/plugins.js
Labels: Complexity: Low

#2240 chore: add publish scripts for npm
  deprecated/core-graphql/package.json
  deprecated/core-logger-winston/package.json
  deprecated/core-snapshots-cli/package.json
  package.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  scripts/publish/alpha.sh
  scripts/publish/beta.sh
  scripts/publish/latest.sh
  scripts/publish/rc.sh
  scripts/release.sh
Labels: Complexity: Medium, Type: Task

#2241 chore: remove unused typedoc dependency
  deprecated/core-graphql/package.json
  deprecated/core-logger-winston/package.json
  deprecated/core-snapshots-cli/package.json
  package.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  scripts/publish/alpha.sh
  yarn.lock
Labels: Complexity: Medium, Type: Task

#2242 chore: setup linting for tests
  __tests__/integration/core-api/repositories/transactions.test.ts
  __tests__/integration/core-api/v2/handlers/transactions.test.ts
  __tests__/integration/core-forger/__fixtures__/blocks.ts
  __tests__/unit/core-blockchain/mocks/config.ts
  __tests__/unit/core-blockchain/mocks/container.ts
  __tests__/unit/core-blockchain/mocks/p2p.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/core-blockchain/processor/handlers/accept-handler.test.ts
  __tests__/unit/core-blockchain/state-storage.test.ts
  __tests__/unit/core-transaction-pool/guard.test.ts
  __tests__/unit/crypto/fixtures/block.ts
  package.json
Labels: Complexity: High, Type: Task

#2244 chore: add update script for dependencies
  deprecated/core-graphql/package.json
  deprecated/core-logger-winston/package.json
  deprecated/core-snapshots-cli/package.json
  package.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  scripts/deps.sh
Labels: Complexity: Medium, Type: Task

#2243 chore: remove pretest and lint scripts from packages
  deprecated/core-graphql/package.json
  deprecated/core-logger-winston/package.json
  deprecated/core-snapshots-cli/package.json
  package.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Low, Type: Task

#2246 fix(tests): Reference the home directory via HOME, not ~
  __tests__/utils/helpers/container.ts
Labels: Complexity: Low, Type: Bugfix

#2247 refactor: custom transaction types
  __tests__/integration/core-transaction-pool/guard.test.ts
  __tests__/integration/core-transaction-pool/pool-wallet-manager.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/crypto/managers/config.test.ts
  packages/core-blockchain/src/state-storage.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/dynamic-fee/matcher.ts
  packages/core-transaction-pool/src/guard.ts
  packages/core-transaction-pool/src/pool-wallet-manager.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handler-registry.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/index.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/timelock-transfer.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/index.ts
  packages/core-transactions/src/interfaces.ts
  packages/core-transactions/src/service-registry.ts
  packages/core-transactions/src/services/index.ts
  packages/crypto/src/errors.ts
  packages/crypto/src/managers/config.ts
  packages/crypto/src/managers/fee.ts
  packages/crypto/src/transactions/index.ts
  packages/crypto/src/transactions/interfaces.ts
  packages/crypto/src/transactions/registry.ts
  packages/crypto/src/transactions/types/index.ts
  packages/crypto/src/transactions/types/schemas.ts
  packages/crypto/src/transactions/types/transaction.ts
  packages/crypto/src/validation/ajv-wrapper.ts
Labels: Complexity: High, Type: Refactor

#2245 fix(core-database): return array instead of joined string from applyOrder
  __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
  packages/core-api/src/versions/2/wallets/schema.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/repositories/utils/sort-entries.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Complexity: Low, Status: Collaborator Approved, Status: In Progress, Type: Bugfix

#2249 chore: add publish script for the next channel
  deprecated/core-snapshots-cli/package.json
  package.json
  packages/core-logger-pino/package.json
  packages/core-tester-cli/package.json
  packages/core-transactions/package.json
  scripts/publish/next.sh
Labels: Complexity: Low, Type: Task

#2250 feat(core): support for the next channel
  packages/core-p2p/src/defaults.ts
  packages/core/src/commands/config/cli.ts
  packages/core/src/helpers/update.ts
  packages/core/src/hooks/init/update.ts
Labels: Complexity: Low, Type: Feature

#2252 fix(core-webhooks): return an empty array if no webhooks exist for a …
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-webhooks/src/database.ts
  packages/core-webhooks/src/index.ts
  packages/core-webhooks/src/manager.ts
Labels: Complexity: Low, Type: Bugfix

#2253 test(core-webhooks): unit test the database
  __tests__/unit/core-webhooks/database.test.ts
  packages/core-webhooks/src/database.ts
  packages/core-webhooks/src/manager.ts
Labels: Complexity: Medium, Test: Unit

#2255 docs: initial 2.3.0 changelog
  CHANGELOG.md
Labels: Complexity: Low, Type: Documentation

#2256 chore: remove packages from codecov ignore list
  .codecov.yml
Labels: Complexity: Low, Type: Task

#2257 refactor: remove missed blocks and productivity
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-api/v1/utils.ts
  __tests__/integration/core-api/v2/handlers/delegates.test.ts
  __tests__/integration/core-api/v2/utils.ts
  __tests__/integration/core-tester-cli/__fixtures__/delegates-page-1.json
  __tests__/integration/core-tester-cli/__fixtures__/delegates-page-2.json
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-utils/delegate-calculator.test.ts
  deprecated/core-graphql/src/defs/types.ts
  packages/core-api/src/versions/1/delegates/transformer.ts
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-api/src/versions/2/delegates/transformer.ts
  packages/core-api/src/versions/2/wallets/schema.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/models/index.ts
  packages/core-database-postgres/src/models/wallet.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/wallet.ts
  packages/core-interfaces/src/core-database/wallet-manager.ts
  packages/core-utils/src/delegate-calculator.ts
  packages/core-utils/src/index.ts
Labels: Complexity: High

#2259 fix(core-utils): handle NSect edge case
  __tests__/unit/core-utils/nsect.test.ts
  packages/core-utils/src/nsect.ts
Labels: Complexity: Low, Type: Bugfix

#2260 fix(core-blockchain): handle unhandled event
  __tests__/unit/core-blockchain/blockchain.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/machines/actions/sync-with-network.ts
  packages/core-blockchain/src/state-machine.ts
Labels: Complexity: Low, Type: Bugfix

#2261 feat(core-logger-pino): set different log levels for console and file
  __tests__/unit/core-logger-pino/logger.test.ts
  packages/core-logger-pino/src/defaults.ts
  packages/core-logger-pino/src/driver.ts
Labels: Complexity: Low, Type: Feature

#2264 docs: fix broken references to plugins docs
  deprecated/core-graphql/README.md
  deprecated/core-logger-winston/README.md
  deprecated/core-snapshots-cli/README.md
  packages/core-api/README.md
  packages/core-blockchain/README.md
  packages/core-container/README.md
  packages/core-database/README.md
  packages/core-elasticsearch/README.md
  packages/core-error-tracker-bugsnag/README.md
  packages/core-error-tracker-sentry/README.md
  packages/core-event-emitter/README.md
  packages/core-forger/README.md
  packages/core-http-utils/README.md
  packages/core-json-rpc/README.md
  packages/core-logger/README.md
  packages/core-p2p/README.md
  packages/core-tester-cli/README.md
  packages/core-transaction-pool/README.md
  packages/core-transactions/README.md
  packages/core-utils/README.md
  packages/core-vote-report/README.md
  packages/core-webhooks/README.md
  packages/core/README.md
Labels: Bounty: Tier 5, Complexity: Low, Status: Collaborator Approved, Type: Documentation

#2266 chore: update readme files with all contributors and fix banners
  README.md
  deprecated/core-graphql/README.md
  deprecated/core-logger-winston/README.md
  deprecated/core-snapshots-cli/README.md
  packages/core-api/README.md
  packages/core-blockchain/README.md
  packages/core-container/README.md
  packages/core-database-postgres/README.md
  packages/core-database/README.md
  packages/core-elasticsearch/README.md
  packages/core-error-tracker-bugsnag/README.md
  packages/core-error-tracker-sentry/README.md
  packages/core-event-emitter/README.md
  packages/core-forger/README.md
  packages/core-http-utils/README.md
  packages/core-jest-matchers/README.md
  packages/core-json-rpc/README.md
  packages/core-logger-pino/README.md
  packages/core-logger/README.md
  packages/core-p2p/README.md
  packages/core-snapshots/README.md
  packages/core-tester-cli/README.md
  packages/core-transaction-pool/README.md
  packages/core-transactions/README.md
  packages/core-utils/README.md
  packages/core-vote-report/README.md
  packages/core-webhooks/README.md
  packages/core/README.md
  packages/crypto/README.md
Labels: Complexity: Medium, Type: Task

#2265 release: 2.2.2
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-api/src/versions/2/delegates/controller.ts
  packages/core-api/src/versions/2/delegates/methods.ts
  packages/core-api/src/versions/2/delegates/routes.ts
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-debugger-cli/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-graphql/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-test-utils/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High

#2267 chore: add missing oclif dependency
  deprecated/core-snapshots-cli/package.json
  package.json
  packages/core-tester-cli/package.json
  packages/core/package.json
  yarn.lock
Labels: Complexity: Medium, Type: Task

#2269 fix(core-snapshots): snapshot manager
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/db/queries/transactions/timestamp-range.sql
  packages/core-snapshots/src/db/utils/column-set.ts
  packages/core-snapshots/src/transport/codecs/core-codec.ts
  packages/core-snapshots/src/transport/codecs/core/index.ts
  packages/core-snapshots/src/transport/verification.ts
Labels: Complexity: Low, Type: Bugfix

#2270 fix(core-logger-pino): don't crash on rotate
  packages/core-logger-pino/package.json
  packages/core-logger-pino/src/driver.ts
  packages/core-tester-cli/package.json
Labels: Complexity: Low, Type: Bugfix

#2271 fix(core-p2p): pass all opts to the http client instead of just headers
  packages/core-p2p/src/peer.ts
Labels: Complexity: Low, Type: Bugfix

#2272 chore: add missing dependencies
  packages/core-api/package.json
  packages/core-database-postgres/package.json
  packages/core-elasticsearch/package.json
  packages/core-http-utils/package.json
  packages/core-jest-matchers/package.json
  packages/core-tester-cli/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Low, Type: Task

#2274 Remove source from image. Add build time ARG variable, so NPM channel channel can be defined on image build.
  docker/production/Dockerfile
  docker/production/devnet/docker-compose-build.yml
  docker/production/devnet/docker-compose.yml
  docker/production/mainnet/docker-compose-build.yml
  docker/production/mainnet/docker-compose.yml
Labels: Complexity: Low

#2275 build(docker): clean the yarn cache after the installation
  docker/production/Dockerfile
Labels: Complexity: Low

#2277 misc(crypto): Update devnet blockid milestone
  packages/crypto/src/networks/devnet/milestones.json
Labels: Complexity: Low, Type: Maintenance

#2278 Merge branch 'master' into develop
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-api/src/versions/2/delegates/controller.ts
  packages/core-api/src/versions/2/delegates/methods.ts
  packages/core-api/src/versions/2/delegates/routes.ts
  packages/core-api/src/versions/2/delegates/schema.ts
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High

#2280 fix(core-logger-pino): prettify filestream
  packages/core-logger-pino/package.json
  packages/core-logger-pino/src/driver.ts
  packages/core-tester-cli/package.json
  packages/core/package.json
  yarn.lock
Labels: Complexity: Medium, Type: Bugfix

#2281 fix(core-database-postgres): asset migration on mainnet
  packages/core-database-postgres/src/postgres-connection.ts
  packages/crypto/src/transactions/serializers/transaction.ts
Labels: Complexity: Low, Type: Bugfix

#2285 chore: import lodash functions from function packages instead of the full lodash
  __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
  __tests__/unit/core-snapshots/transport/codec/core/core.test.ts
  __tests__/utils/helpers/container.ts
  deprecated/core-logger-winston/src/driver.ts
  packages/core-api/src/repositories/repository.ts
  packages/core-api/src/repositories/transactions.ts
  packages/core-container/src/config/index.ts
  packages/core-container/src/registrars/plugin.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/utils/search-parameter-converter.ts
  packages/core-forger/src/client.ts
  packages/core-forger/src/manager.ts
  packages/core-interfaces/src/shared/config.ts
  packages/core-jest-matchers/src/api/block.ts
  packages/core-jest-matchers/src/api/peer.ts
  packages/core-jest-matchers/src/api/transaction.ts
  packages/core-jest-matchers/src/blockchain/execute-on-entry.ts
  packages/core-jest-matchers/src/models/delegate.ts
  packages/core-jest-matchers/src/models/transaction.ts
  packages/core-jest-matchers/src/models/wallet.ts
  packages/core-json-rpc/src/server/services/network.ts
  packages/core-json-rpc/src/server/services/processor.ts
  packages/core-logger-pino/src/driver.ts
  packages/core-p2p/src/court/guard.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/utils/check-dns.ts
  packages/core-p2p/src/utils/check-ntp.ts
  packages/core-snapshots/src/manager.ts
  packages/core-transaction-pool/src/dynamic-fee/matcher.ts
  packages/core-vote-report/src/handler.ts
  packages/core/src/hooks/command_not_found/suggest.ts
  packages/crypto/src/managers/config.ts
  packages/crypto/src/managers/network.ts
  packages/crypto/src/transactions/registry.ts
Labels: Complexity: Medium, Type: Task

#2286 release: 2.3.0-next.0
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  scripts/deps.sh
  scripts/publish/alpha.sh
  scripts/publish/beta.sh
  scripts/publish/latest.sh
  scripts/publish/next.sh
  scripts/publish/rc.sh
Labels: Complexity: High, Type: Release

#2287 feat(core-error-tracker-rollbar): initial implementation
  .circleci/config.yml
  packages/core-error-tracker-rollbar/.gitattributes
  packages/core-error-tracker-rollbar/README.md
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-rollbar/src/defaults.ts
  packages/core-error-tracker-rollbar/src/index.ts
  packages/core-error-tracker-rollbar/tsconfig.json
Labels: Complexity: Medium, Type: Feature

#2288 feat(core-error-tracker-raygun): initial implementation
  .circleci/config.yml
  packages/core-error-tracker-raygun/.gitattributes
  packages/core-error-tracker-raygun/README.md
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-raygun/src/defaults.ts
  packages/core-error-tracker-raygun/src/index.ts
  packages/core-error-tracker-raygun/tsconfig.json
Labels: Complexity: Medium, Type: Feature

#2289 feat(core-error-tracker-airbrake): initial implementation
  .circleci/config.yml
  packages/core-error-tracker-airbrake/.gitattributes
  packages/core-error-tracker-airbrake/README.md
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-airbrake/src/defaults.ts
  packages/core-error-tracker-airbrake/src/index.ts
  packages/core-error-tracker-airbrake/tsconfig.json
Labels: Complexity: Medium, Type: Feature

#2292 chore: remove extraneous .gitattributes entries
  __tests__/unit/core-logger-winston/.gitattributes
  deprecated/core-graphql/.gitattributes
  packages/core-api/.gitattributes
  packages/core-blockchain/.gitattributes
  packages/core-container/.gitattributes
  packages/core-database-postgres/.gitattributes
  packages/core-database/.gitattributes
  packages/core-elasticsearch/.gitattributes
  packages/core-error-tracker-airbrake/.gitattributes
  packages/core-error-tracker-bugsnag/.gitattributes
  packages/core-error-tracker-raygun/.gitattributes
  packages/core-error-tracker-rollbar/.gitattributes
  packages/core-error-tracker-sentry/.gitattributes
  packages/core-event-emitter/.gitattributes
  packages/core-forger/.gitattributes
  packages/core-http-utils/.gitattributes
  packages/core-jest-matchers/.gitattributes
  packages/core-json-rpc/.gitattributes
  packages/core-logger-pino/.gitattributes
  packages/core-logger-winston/.gitattributes
  packages/core-logger/.gitattributes
  packages/core-p2p/.gitattributes
  packages/core-tester-cli/.gitattributes
  packages/core-transaction-pool/.gitattributes
  packages/core-transactions/.gitattributes
  packages/core-utils/.gitattributes
  packages/core-vote-report/.gitattributes
  packages/core-webhooks/.gitattributes
  packages/core/.gitattributes
  packages/crypto/.gitattributes
Labels: Complexity: Medium, Type: Task

#2293 refactor: drop the git commit hash identifier
  __tests__/unit/core-container/container.test.ts
  __tests__/unit/core-p2p/mocks/core-container.ts
  packages/core-api/src/versions/1/peers/transformer.ts
  packages/core-api/src/versions/2/peers/transformer.ts
  packages/core-container/src/container.ts
  packages/core-interfaces/src/core-container/container.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/server/plugins/set-headers.ts
Labels: Complexity: Medium, Type: Refactor

#2294 chore(core-p2p): raise the minimum version to 2.3.0
  __tests__/integration/core-api/v2/handlers/peers.test.ts
  packages/core-p2p/src/defaults.ts
  packages/core-utils/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Medium, Type: Task

#2295 fix(core-database-postgres): support PG9.5 for asset column migration
  packages/core-database-postgres/src/migrations/20190313000000-add-asset-column-to-transactions-table.sql
Labels: Complexity: Low, Type: Bugfix

#2296 release: 2.3.0-next.1
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2298 fix(core-database): sort transactions by timestamp:desc by default
  __tests__/unit/core-database/repositories/transactions-business-repository.test.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
Labels: Complexity: Low, Type: Bugfix

#2302 fix(core-snapshots): always load core-database-postgres
  packages/core-snapshots/package.json
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/plugin.ts
  packages/core/src/helpers/snapshot.ts
Labels: Complexity: Low, Type: Bugfix

#2300 feat(core-snapshots): rollback by a given amount of blocks
  packages/core-snapshots/src/manager.ts
  packages/core/src/commands/snapshot/rollback.ts
Labels: Complexity: Low, Type: Feature

#2301 refactor(core-snapshots): make core the only codec for reliability
  __tests__/unit/core-snapshots/transport/codec.test.ts
  __tests__/unit/core-snapshots/transport/codec/lite/lite.test.ts
  packages/core-snapshots/src/defaults.ts
  packages/core-snapshots/src/manager.ts
  packages/core-snapshots/src/plugin.ts
  packages/core-snapshots/src/transport/codec.ts
  packages/core-snapshots/src/transport/codecs/core-codec.ts
  packages/core-snapshots/src/transport/codecs/core/index.ts
  packages/core-snapshots/src/transport/codecs/index.ts
  packages/core-snapshots/src/transport/codecs/lite-codec.ts
  packages/core-snapshots/src/transport/codecs/lite/index.ts
  packages/core-snapshots/src/transport/index.ts
  packages/core-snapshots/src/utils.ts
Labels: Complexity: Medium, Type: Refactor

#2276 refactor: replace any with proper types
  packages/core-api/src/services/cache.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/plugin.ts
  packages/core-elasticsearch/src/index.ts
  packages/core-error-tracker-bugsnag/src/index.ts
  packages/core-interfaces/src/core-container/container.ts
  packages/core-p2p/src/server/versions/internal/handlers/rounds.ts
  packages/core/src/helpers/snapshot.ts
  packages/core/src/shared/start.ts
  packages/core/src/types.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved

#2304 fix(core-snapshots): core codec
  packages/core-snapshots/src/transport/codec.ts
Labels: Complexity: Low, Type: Bugfix

#2305 fix(core-database): transaction timestamp
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database/src/database-service.ts
Labels: Complexity: Low, Type: Bugfix

#2306 fix(core-api): adjust schema validation of blocks show
  __tests__/integration/core-api/v2/handlers/blocks.test.ts
  packages/core-api/src/versions/2/blocks/schema.ts
Labels: Complexity: Low, Status: Collaborator Approved, Status: In Progress, Type: Bugfix

#2283 chore: use kebab case for aliases
  __tests__/integration/core-api/v2/handlers/node.test.ts
  __tests__/integration/core-transaction-pool/guard.test.ts
  __tests__/unit/core-blockchain/mocks/container.ts
  __tests__/utils/helpers/blockchain.ts
  deprecated/core-graphql/src/repositories/repository.ts
  packages/core-api/src/repositories/repository.ts
  packages/core-api/src/versions/1/transactions/controller.ts
  packages/core-api/src/versions/2/node/controller.ts
  packages/core-api/src/versions/2/transactions/controller.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-database-postgres/src/plugin.ts
  packages/core-database/src/plugin.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-http-utils/src/plugins/transaction-payload.ts
  packages/core-logger-pino/src/plugin.ts
  packages/core-logger-winston/src/plugin.ts
  packages/core-logger/src/plugin.ts
  packages/core-p2p/src/server/plugins/transaction-pool-ready.ts
  packages/core-p2p/src/server/versions/1/handlers.ts
  packages/core-transaction-pool/src/plugin.ts
Labels: Complexity: Low, Status: Collaborator Approved, Type: Task

#2290 feat(core-new-relic): initial implementation
  .circleci/config.yml
  .circleci/generateConfig.js
  .yarnrc
  packages/core-new-relic/.gitattributes
  packages/core-new-relic/README.md
  packages/core-new-relic/package.json
  packages/core-new-relic/src/index.ts
  packages/core-new-relic/tsconfig.json
Labels: Complexity: Medium, Status: On Hold, Type: Feature

#2307 perf(crypto): skip transaction verification overhead
  __tests__/unit/crypto/transactions/transaction.test.ts
  benchmark/transaction/create/0.js
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/queries/transactions/find-by-block.sql
  packages/core-database-postgres/src/queries/transactions/latest-by-block.sql
  packages/core-database-postgres/src/queries/transactions/latest-by-blocks.sql
  packages/core-database/src/database-service.ts
  packages/core-elasticsearch/src/indices/transactions.ts
  packages/core-snapshots/src/transport/codec.ts
  packages/crypto/src/transactions/deserializers/transaction.ts
  packages/crypto/src/transactions/types/transaction.ts
Labels: Type: Performance

#2309 fix(core): read the correct property for the new CLI version
  packages/core/src/commands/update.ts
Labels: Complexity: Low, Type: Bugfix, Type: Regression

#2313 fix(core-database-postgres): add EQ operator to block height
  packages/core-database-postgres/src/models/block.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Status: In Progress, Type: Bugfix

#2312 build(docker): create symbolic link for ark bin
  docker/production/entrypoint.sh
Labels: Complexity: Low, Type: Bugfix

#2315 fix(crypto): add signSignature to schema
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: Low, Type: Bugfix

#2317 fix(core-p2p): common blocks with sha256 ids
  packages/core-p2p/src/server/versions/1/handlers.ts
Labels: Complexity: Low, Type: Bugfix

#2318 fix(core-p2p): always refresh peer status
  packages/core-p2p/src/monitor.ts
Labels: Complexity: Low, Type: Bugfix

#2316 fix(core-database): map block to transaction in findById
  __tests__/unit/core-database/repositories/transactions-business-repository.test.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#2319 feat(core-database-postgres): support IN operator for block id, height and generator
  packages/core-database-postgres/src/models/block.ts
Labels: Complexity: Low, Type: Feature

#2311 refactor(core-p2p): remove the remote interface
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/server/index.ts
  packages/core-p2p/src/server/versions/remote/handlers/blockchain.ts
  packages/core-p2p/src/server/versions/remote/index.ts
  packages/core-p2p/src/server/versions/remote/schemas/blockchain.ts
  yarn.lock
Labels: Complexity: Medium, Type: Refactor

#2310 refactor(core): use nsfw for log watching instead of node-tail
  packages/core/package.json
  packages/core/src/commands/core/log.ts
  packages/core/src/commands/forger/log.ts
  packages/core/src/commands/relay/log.ts
  packages/core/src/commands/update.ts
  packages/core/src/shared/log.ts
  yarn.lock
Labels: Complexity: Medium, Type: Refactor

#2308 refactor(core-snapshots): remove dead code
  packages/core-snapshots/src/db/index.ts
  packages/core-snapshots/src/db/utils/column-set.ts
  packages/core-snapshots/src/manager.ts
  packages/core-snapshots/src/transport/index.ts
  packages/core-snapshots/src/transport/verification.ts
  packages/core-snapshots/src/utils.ts
  packages/core/src/commands/snapshot/dump.ts
  packages/core/src/commands/snapshot/restore.ts
  packages/core/src/commands/snapshot/truncate.ts
  packages/core/src/commands/snapshot/verify.ts
  packages/core/src/helpers/snapshot.ts
Labels: Complexity: High, Type: Refactor

#2320 release: 2.3.0-next.2
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2323 fix(crypto): check if block contains exceptions
  packages/crypto/src/models/block.ts
Labels: Complexity: Low, Type: Bugfix

#2324 fix(core-database-postgres): shutdown when integrity check fails
  packages/core-container/src/container.ts
  packages/core-database-postgres/src/postgres-connection.ts
Labels: Complexity: Medium, Type: Bugfix

#2322 fix(core): preserve existing logs and attach the last line when the log is modified
  packages/core/package.json
  packages/core/src/shared/log.ts
  yarn.lock
Labels: Complexity: Low, Type: Bugfix

#2327 perf(core-api): transaction transformer
  packages/core-api/src/repositories/transactions.ts
  packages/core-api/src/versions/1/transactions/transformer.ts
  packages/core-api/src/versions/2/transactions/controller.ts
  packages/core-api/src/versions/2/transactions/transformer.ts
  packages/core-api/src/versions/2/wallets/controller.ts
  packages/crypto/src/transactions/types/transaction.ts
Labels: Complexity: Low, Type: Performance

#2325 fix(core-p2p): two-way ban
  packages/core-interfaces/src/core-p2p/monitor.ts
  packages/core-p2p/src/monitor.ts
  packages/core-p2p/src/server/plugins/accept-request.ts
  packages/core-p2p/src/utils/index.ts
  packages/core-p2p/src/utils/is-valid-peer.ts
Labels: Complexity: Low, Type: Bugfix

#2321 feat: add more block and transaction pool events
  __tests__/unit/core-blockchain/blockchain.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Feature

#2328 fix(core-p2p): accept accepted peers
  packages/core-p2p/src/monitor.ts
Labels: Complexity: Low, Type: Bugfix

#2332 fix(core-database-postgres): run the asset migration before starting the record migration
  packages/core-database-postgres/src/postgres-connection.ts
Labels: Complexity: Low, Type: Bugfix

#2330 chore: install node.js 11 now that it is stable
  install.sh
Labels: Complexity: Low, Type: Task

#2331 fix: use the maxTransactionsPerRequest configuration for API validation
  packages/core-api/src/versions/2/transactions/schema.ts
  packages/core-p2p/src/server/versions/1/schema.ts
Labels: Complexity: Low, Type: Bugfix

#2329 fix(core-event-emitter): ensure the event listener won’t exceed the max listener count
  __tests__/unit/core-event-emitter/emitter.test.ts
  packages/core-event-emitter/package.json
  packages/core-event-emitter/src/emitter.ts
  packages/core-event-emitter/src/index.ts
  packages/core-interfaces/package.json
  packages/core-interfaces/src/core-event-emitter/index.ts
  yarn.lock
Labels: Complexity: Low, Type: Bugfix

#2334 fix(core-p2p): getNetworkHeight() was sorting incorrectly peer heights
  __tests__/unit/core-p2p/monitor.test.ts
  packages/core-p2p/src/monitor.ts
Labels: Complexity: Low, Type: Bugfix

#2336 release: 2.3.0-next.3
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2337 feat(core-database): add function to search a block by id or height
  __tests__/integration/core-api/v2/handlers/blocks.test.ts
  packages/core-api/src/versions/2/blocks/methods.ts
  packages/core-database/src/repositories/blocks-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/blocks-business-repository.ts
Labels: Complexity: Low, Type: Feature

#2338 refactor(core-database-postgres): add findByHeight to avoid confusion with the misleading findByHeights
  __tests__/unit/core-database/database-service.test.ts
  packages/core-database-postgres/src/plugin.ts
  packages/core-database-postgres/src/queries/blocks/find-by-height.sql
  packages/core-database-postgres/src/queries/blocks/find-by-heights.sql
  packages/core-database-postgres/src/queries/index.ts
  packages/core-database-postgres/src/repositories/blocks.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/database-repository/blocks-repository.ts
Labels: Complexity: Medium, Status: Needs Changes, Type: Refactor

#2333 test(functional): broadcast and forge all transaction types
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/generateConfig.js
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/functional/transaction-forging/delegate-registration.test.ts
  __tests__/functional/transaction-forging/second-signature-registration.test.ts
  __tests__/functional/transaction-forging/transfer.test.ts
  __tests__/functional/transaction-forging/vote.test.ts
  __tests__/integration/core-api/v2/handlers/transactions.test.ts
  __tests__/integration/core-p2p/server/1.test.ts
  __tests__/integration/core-p2p/server/internal.test.ts
  __tests__/integration/core-transaction-pool/__fixtures__/transactions.ts
  __tests__/integration/core-transaction-pool/guard.test.ts
  __tests__/integration/core-transaction-pool/pool-wallet-manager.test.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/core-database/wallet-manager.test.ts
  __tests__/unit/core-database/wallet.test.ts
  __tests__/unit/core-forger/manager.test.ts
  __tests__/unit/core-jest-matchers/transactions/valid-second-signature.test.ts
  __tests__/unit/core-transaction-pool/__fixtures__/transactions.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/guard.test.ts
  __tests__/unit/crypto/models/block.test.ts
  __tests__/utils/generators/transactions.ts
  __tests__/utils/generators/transactions/delegate.ts
  __tests__/utils/generators/transactions/index.ts
  __tests__/utils/generators/transactions/signature.ts
  __tests__/utils/generators/transactions/transfer.ts
  __tests__/utils/generators/transactions/vote.ts
  package.json
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-database/database-service.ts
Labels: Complexity: High, Status: In Progress, Test: Functional

#2339 refactor(core-database): use a raw query to get a block by height
  __tests__/unit/core-database/repositories/blocks-business-repository.test.ts
  packages/core-database/src/repositories/blocks-business-repository.ts
Labels: Complexity: Low, Type: Refactor

#2340 chore(ci): explicitly name integration test jobs
  .circleci/config.yml
  .circleci/configTemplate.json
Labels: Complexity: Low, Type: Task

#2342 fix(core-database): search a block ID if there is no height match
  packages/core-database/src/repositories/blocks-business-repository.ts
Labels: Complexity: Low, Type: Bugfix

#2343 feat(core-logger-signale): initial implementation
  .circleci/config.yml
  __tests__/unit/core-logger-signale/logger.test.ts
  packages/core-logger-signale/.gitattributes
  packages/core-logger-signale/README.md
  packages/core-logger-signale/package.json
  packages/core-logger-signale/src/defaults.ts
  packages/core-logger-signale/src/driver.ts
  packages/core-logger-signale/src/index.ts
  packages/core-logger-signale/src/plugin.ts
  packages/core-logger-signale/tsconfig.json
  yarn.lock
Labels: Complexity: High, Type: Feature

#2345 chore(ci): remove the postgres setup from unit test jobs
  .circleci/config.yml
  .circleci/configTemplate.json
Labels: Complexity: Low, Type: Task

#2346 refactor(core-database): clearly separate manager and factory behaviour
  packages/core-database-postgres/src/plugin.ts
  packages/core-database/src/factory.ts
  packages/core-database/src/manager.ts
  packages/core-database/src/plugin.ts
Labels: Complexity: Low, Type: Refactor

#2341 refactor(core-forger): memory leak, log spam, cleanup
  __tests__/integration/core-forger/client.test.ts
  __tests__/unit/core-forger/manager.test.ts
  packages/core-api/src/versions/1/delegates/controller.ts
  packages/core-database-postgres/src/repositories/rounds.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/wallet-manager.ts
  packages/core-forger/package.json
  packages/core-forger/src/client.ts
  packages/core-forger/src/errors.ts
  packages/core-forger/src/index.ts
  packages/core-forger/src/manager.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-database/database-repository/rounds-repository.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-database/wallet-manager.ts
  packages/core-p2p/src/index.ts
  packages/core-p2p/src/server/types.ts
  packages/core-p2p/src/server/versions/internal/handlers/utils.ts
  packages/core-p2p/src/server/versions/internal/index.ts
  packages/core-utils/src/httpie.ts
  packages/core-utils/src/index.ts
Labels: Complexity: High, Status: Needs Changes, Type: Refactor

#2348 refactor: replace various any with types and simpler interface naming
  __tests__/unit/core-database/__fixtures__/database-connection-stub.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/guard.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/utils/helpers/blockchain.ts
  deprecated/core-graphql/src/repositories/repository.ts
  packages/core-api/src/repositories/repository.ts
  packages/core-api/src/versions/1/transactions/controller.ts
  packages/core-api/src/versions/2/transactions/controller.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database/src/database-service-factory.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/factory.ts
  packages/core-database/src/manager.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-database/database-connection.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-database/event-types.ts
  packages/core-interfaces/src/core-event-emitter/index.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-interfaces/src/core-transaction-pool/connection.ts
  packages/core-interfaces/src/core-transaction-pool/guard.ts
  packages/core-interfaces/src/core-transaction-pool/index.ts
  packages/core-interfaces/src/shared/config.ts
  packages/core-p2p/src/server/plugins/transaction-pool-ready.ts
  packages/core-p2p/src/server/versions/1/handlers.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/guard.ts
  packages/core-transaction-pool/src/plugin.ts
  packages/core-transaction-pool/src/pool-wallet-manager.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/interfaces.ts
Labels: Complexity: Medium, Type: Refactor

#2347 refactor(core-transaction-pool): clearly separate manager and factory behaviour
  __tests__/unit/core-transaction-pool/__stubs__/connection.ts
  __tests__/unit/core-transaction-pool/manager.test.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/factory.ts
  packages/core-transaction-pool/src/manager.ts
  packages/core-transaction-pool/src/plugin.ts
Labels: Complexity: Low, Type: Refactor

#2349 refactor(core-event-emitter): expose all application events through an enum
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-database/database-service.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-database/package.json
  packages/core-database/src/database-service.ts
  packages/core-elasticsearch/package.json
  packages/core-elasticsearch/src/indices/rounds.ts
  packages/core-elasticsearch/src/indices/wallets.ts
  packages/core-event-emitter/src/index.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-webhooks/package.json
  packages/core-webhooks/src/manager.ts
Labels: Complexity: Low, Type: Refactor

#2344 refactor: reduce duplication in all logger packages
  __tests__/unit/core-logger-pino/logger.test.ts
  __tests__/unit/core-logger-signale/logger.test.ts
  __tests__/unit/core-logger-winston/logger.test.ts
  __tests__/unit/core-logger/manager.test.ts
  packages/core-interfaces/src/core-logger/logger.ts
  packages/core-logger-pino/package.json
  packages/core-logger-pino/src/driver.ts
  packages/core-logger-pino/src/plugin.ts
  packages/core-logger-signale/package.json
  packages/core-logger-signale/src/driver.ts
  packages/core-logger-signale/src/plugin.ts
  packages/core-logger-winston/package.json
  packages/core-logger-winston/src/driver.ts
  packages/core-logger-winston/src/formatter.ts
  packages/core-logger-winston/src/interfaces.ts
  packages/core-logger-winston/src/plugin.ts
  packages/core-logger/package.json
  packages/core-logger/src/factory.ts
  packages/core-logger/src/logger.ts
  packages/core-logger/src/manager.ts
  packages/core-logger/src/plugin.ts
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor
