Repository ArkEcosystem/core, pull requests merged in 2019-05, with the labels that each got.

#2511 test(functional): more multi signature tests
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/functional/transaction-forging/delegate-registration.test.ts
  __tests__/functional/transaction-forging/second-signature-registration.test.ts
  __tests__/functional/transaction-forging/vote.test.ts
  __tests__/unit/core-state/wallets/wallet.test.ts
  __tests__/unit/crypto/transactions/schemas.test.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: Medium, Test: Unit

#2514 refactor(crypto): extract transaction signing and utils out of the model
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/crypto/crypto/hash.test.ts
  __tests__/unit/crypto/transactions/__support__/index.ts
  __tests__/unit/crypto/transactions/builders/transactions/__shared__/transaction-builder.ts
  __tests__/unit/crypto/transactions/builders/transactions/delegate-registration.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/transactions/factory.test.ts
  __tests__/unit/crypto/transactions/signer.test.ts
  __tests__/unit/crypto/transactions/transaction.test.ts
  __tests__/unit/crypto/transactions/utils.test.ts
  __tests__/unit/crypto/transactions/verifier.test.ts
  benchmark/crypto/hash-algorithms.js
  benchmark/transaction/serialize/0.js
  packages/core-state/src/wallets/wallet.ts
  packages/crypto/src/blocks/serializer.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
  packages/crypto/src/transactions/factory.ts
  packages/crypto/src/transactions/index.ts
  packages/crypto/src/transactions/signer.ts
  packages/crypto/src/transactions/types/transaction.ts
  packages/crypto/src/transactions/utils.ts
  packages/crypto/src/transactions/verifier.ts
Labels: Complexity: High, Type: Refactor

#2515 refactor(core-interfaces): move the wallet interfaces to core-state
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/repositories/delegates-business-repository.test.ts
  __tests__/unit/core-database/repositories/transactions-business-repository.test.ts
  __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  packages/core-api/src/repositories/transactions.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/utils/validate-generator.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/database-service-factory.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/delegates-business-repository.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/delegates-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/wallets-business-repository.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  packages/core-interfaces/src/core-database/database-repository/wallets-repository.ts
  packages/core-interfaces/src/core-database/database-service.ts
  packages/core-interfaces/src/core-database/index.ts
  packages/core-interfaces/src/core-p2p/server.ts
  packages/core-interfaces/src/core-state/index.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-state/src/wallets/wallet.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/wallet-manager.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/timelock-transfer.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/interfaces.ts
  packages/core-vote-report/src/handler.ts
Labels: Complexity: High, Type: Refactor

#2516 test(e2e): specify sed extension to support macOS
  __tests__/e2e/lib/config/docker/docker-init.sh
Labels: Complexity: Low, Test: Unit

#2517 fix(core-tester-cli): use public API for auto-configuration
  __tests__/integration/core-tester-cli/commands/send/delegate-registration.test.ts
  __tests__/integration/core-tester-cli/commands/send/multi-signature-registration.test.ts
  __tests__/integration/core-tester-cli/commands/send/second-signature.test.ts
  __tests__/integration/core-tester-cli/commands/send/transfer.test.ts
  __tests__/integration/core-tester-cli/commands/send/vote.test.ts
  packages/core-api/src/versions/2/node/controller.ts
  packages/core-api/src/versions/2/node/routes.ts
  packages/core-tester-cli/src/commands/command.ts
  packages/core-tester-cli/src/commands/send/delegate-registration.ts
  packages/core-tester-cli/src/commands/send/multi-signature-registration.ts
  packages/core-tester-cli/src/commands/send/second-signature-registration.ts
  packages/core-tester-cli/src/commands/send/vote.ts
  packages/core-tester-cli/src/signer.ts
  packages/crypto/src/networks/unitnet/milestones.json
Labels: Complexity: Medium, Type: Bugfix

#2519 chore(benchmark): fix imports for hash algos
  benchmark/crypto/hash-algorithms.js
  benchmark/index.js
Labels: Complexity: Low, Type: Task

#2518 fix(core-snapshots): transform numerical values to BigNumber before serializing
  packages/core-snapshots/src/transport/codec.ts
  packages/core/src/helpers/snapshot.ts
Labels: Complexity: Low, Type: Bugfix

#2521 fix(core): mark the blocks flag as required for snapshot:verify
  packages/core/src/commands/snapshot/verify.ts
Labels: Complexity: Low, Type: Bugfix

#2522 feat(core): require the user to choose a snapshot if the blocks flag is missing
  packages/core/src/commands/snapshot/restore.ts
  packages/core/src/commands/snapshot/verify.ts
  packages/core/src/helpers/snapshot.ts
Labels: Complexity: Low, Type: Feature

#2520 chore(deps): update dependencies and types
  __tests__/unit/core-p2p/utils/check-ntp.test.ts
  package.json
  packages/core-api/package.json
  packages/core-container/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-raygun/src/index.ts
  packages/core-http-utils/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-signale/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-p2p/src/utils/check-ntp.ts
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-utils/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Medium, Type: Task

#2523 test: stop e2e test runner when no new blocks are coming
  __tests__/e2e/lib/test-runner.js
Labels: Complexity: Low, Test: Unit

#2513 fix(core-api): return transaction timestamp instead of block timestamp
  packages/core-api/src/versions/2/transactions/transformer.ts
Labels: Complexity: Low, Type: Bugfix

#2524 release: 2.3.22
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2525 fix(crypto): handle missing version
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/crypto/src/transactions/factory.ts
Labels: Complexity: Low, Type: Bugfix

#2527 chore(lint): enable ban rule for tslint
  __tests__/e2e/lib/test-runner.js
  packages/core-api/src/versions/2/transactions/controller.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-container/src/config/file-loader.ts
  packages/core-container/src/container.ts
  packages/core-container/src/registrars/plugin.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/models/model.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/repositories/repository.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/utils/search-parameter-converter.ts
  packages/core-elasticsearch/src/indices/base.ts
  packages/core-elasticsearch/src/indices/wallets.ts
  packages/core-forger/src/delegate.ts
  packages/core-forger/src/manager.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-state/src/stores/state.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-tester-cli/src/signer.ts
  packages/core-transaction-pool/src/storage.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/blocks/deserializer.ts
  packages/crypto/src/crypto/bip38.ts
  packages/crypto/src/crypto/hash-algorithms.ts
  packages/crypto/src/identities/public-key.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/validation/index.ts
  tslint.json
Labels: Complexity: High, Type: Task

#2529 refactor(crypto): move mainnet exceptions
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/networks/mainnet/exceptions.json
Labels: Complexity: Low, Type: Refactor

#2530 refactor: cleanup TODOs and FIXMEs
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/unit/crypto/transactions/schemas.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/crypto/src/blocks/deserializer.ts
  packages/crypto/src/crypto/bip38.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/transactions/signer.ts
  packages/crypto/src/transactions/verifier.ts
Labels: Complexity: Low, Type: Refactor

#2526 feat(core-blockchain): replay command
  packages/core-blockchain/package.json
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/plugin.ts
  packages/core-blockchain/src/replay/errors.ts
  packages/core-blockchain/src/replay/index.ts
  packages/core-blockchain/src/replay/memory-database-service.ts
  packages/core-blockchain/src/replay/replay-blockchain.ts
  packages/core-database/src/index.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core/package.json
  packages/core/src/commands/chain/replay.ts
  packages/core/src/helpers/replay.ts
  packages/crypto/src/blocks/deserializer.ts
Labels: Complexity: High, Type: Feature

#2533 test(crypto): ECDSA signature
  __tests__/unit/crypto/crypto/hash.test.ts
Labels: Complexity: Low, Test: Unit

#2534 docs: 2.4.0 changelog
  CHANGELOG.md
Labels: Complexity: Medium, Type: Documentation

#2528 refactor(crypto): invalidate blocks with expired transactions
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/functional/transaction-forging/transfer.test.ts
  __tests__/helpers/rest-client.ts
  __tests__/helpers/transaction-factory.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/unit/crypto/blocks/block.test.ts
  __tests__/unit/crypto/validation/keywords.test.ts
  packages/core-transaction-pool/src/processor.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/transactions/builders/transactions/transfer.ts
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: Medium, Type: Refactor

#2537 feat: Implement IPFS (AIP11)
  __tests__/e2e/lib/utils/test-utils.js
  __tests__/e2e/package.json
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/1.create-transactions.action.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/3.resend-BtoC.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.0.doublespend.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.1.doublespend2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.0.doubletransfer.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.1.doubletransfer2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.2.doublevote.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.3.doubledelreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.4.double2ndsigreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.0.transfer.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.1.transfer2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.2.vote.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.3.delreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.4.2ndsigreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/1.create-transactions.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.0.transaction.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.1.transaction2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/utils.js
  __tests__/functional/transaction-forging/ipfs.test.ts
  __tests__/helpers/transaction-factory.ts
  __tests__/integration/core-tester-cli/commands/send/ipfs.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/ipfs.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/queries/index.ts
  packages/core-database-postgres/src/queries/integrity-verifier/ipfs.sql
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet.ts
  packages/core-tester-cli/src/commands/send/ipfs.ts
  packages/core-tester-cli/src/signer.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/crypto/package.json
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/networks/testnet/milestones.json
  packages/crypto/src/networks/unitnet/milestones.json
  packages/crypto/src/transactions/builders/transactions/ipfs.ts
  packages/crypto/src/transactions/deserializer.ts
  packages/crypto/src/transactions/types/ipfs.ts
  packages/crypto/src/transactions/types/schemas.ts
  yarn.lock
Labels: Complexity: High, Status: In Progress, Type: Feature

#2536 refactor(core): let the process manager extend @faustbrian/foreman
  packages/core/package.json
  packages/core/src/commands/command.ts
  packages/core/src/commands/config/forger/bip38.ts
  packages/core/src/commands/config/forger/bip39.ts
  packages/core/src/commands/core/run.ts
  packages/core/src/commands/core/start.ts
  packages/core/src/commands/forger/run.ts
  packages/core/src/commands/forger/start.ts
  packages/core/src/commands/relay/run.ts
  packages/core/src/commands/relay/start.ts
  packages/core/src/commands/top.ts
  packages/core/src/process-manager.ts
  packages/core/src/shared/start.ts
  packages/core/src/shared/status.ts
  packages/core/src/types.ts
  yarn.lock
Labels: Complexity: Medium, Type: Refactor

#2540 release: 2.4.0-next.0
  CHANGELOG.md
  __tests__/integration/core-api/v2/handlers/peers.test.ts
  __tests__/integration/core-forger/mocks/core-container.ts
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/unit/core-p2p/mocks/core-container.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/peer-guard.test.ts
  __tests__/unit/core-p2p/peer-storage.test.ts
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-p2p/src/defaults.ts
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2539 refactor(core-database-postgres): wallets bootstrap
  __tests__/unit/core-transactions/handler-registry.test.ts
  packages/core-database-postgres/package.json
  packages/core-database-postgres/src/index.ts
  packages/core-database-postgres/src/integrity-verifier.ts
  packages/core-database-postgres/src/postgres-connection.ts
  packages/core-database-postgres/src/queries/index.ts
  packages/core-database-postgres/src/queries/state-builder/assets-by-type.sql
  packages/core-database-postgres/src/queries/state-builder/block-rewards.sql
  packages/core-database-postgres/src/queries/state-builder/delegates-forged-blocks.sql
  packages/core-database-postgres/src/queries/state-builder/delegates.sql
  packages/core-database-postgres/src/queries/state-builder/ipfs.sql
  packages/core-database-postgres/src/queries/state-builder/last-forged-blocks.sql
  packages/core-database-postgres/src/queries/state-builder/multi-signatures.sql
  packages/core-database-postgres/src/queries/state-builder/received-transactions.sql
  packages/core-database-postgres/src/queries/state-builder/second-signatures.sql
  packages/core-database-postgres/src/queries/state-builder/sent-transactions.sql
  packages/core-database-postgres/src/repositories/blocks.ts
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-database-postgres/src/state-builder.ts
  packages/core-database/src/repositories/blocks-business-repository.ts
  packages/core-database/src/repositories/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/blocks-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/transactions-business-repository.ts
  packages/core-interfaces/src/core-database/database-repository/blocks-repository.ts
  packages/core-interfaces/src/core-database/database-repository/transactions-repository.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/handler-registry.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/timelock-transfer.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/interfaces.ts
Labels: Complexity: High, Type: Refactor

#2541 release: 2.4.0-next.1
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2543 fix(core): use the --env flag to start testnet via CLI
  packages/core/package.json
Labels: Complexity: Low, Type: Bugfix

#2544 feat(core-wallet-api): initial implementation
  .circleci/config.yml
  packages/core-wallet-api/.gitattributes
  packages/core-wallet-api/README.md
  packages/core-wallet-api/package.json
  packages/core-wallet-api/src/index.ts
  packages/core-wallet-api/src/plugin.ts
  packages/core-wallet-api/src/server/handlers.ts
  packages/core-wallet-api/src/server/index.ts
  packages/core-wallet-api/src/server/transformers.ts
  packages/core-wallet-api/tsconfig.json
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
Labels: Complexity: Medium, Type: Feature

#2545 release: 2.4.0-next.2
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2546 chore(deps): update and remove unused dependencies
  package.json
  packages/core-container/package.json
  packages/core-elasticsearch/package.json
  packages/core-elasticsearch/src/client.ts
  packages/core-elasticsearch/src/defaults.ts
  packages/core-elasticsearch/src/indices/base.ts
  packages/core-elasticsearch/src/indices/transactions.ts
  packages/core-elasticsearch/src/indices/wallets.ts
  packages/core-elasticsearch/src/server.ts
  packages/core-error-tracker-sentry/package.json
  packages/core-http-utils/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-new-relic/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/build/webpack.base.js
  packages/crypto/build/webpack.config.js
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Undetermined, Status: In Progress, Type: Task

#2552 refactor(core-p2p): remove peer.os property
  __tests__/integration/core-api/v1/handlers/peers.test.ts
  __tests__/unit/core-p2p/peer.test.ts
  packages/core-api/src/versions/1/peers/controller.ts
  packages/core-api/src/versions/1/peers/schema.ts
  packages/core-api/src/versions/1/peers/transformer.ts
  packages/core-api/src/versions/2/peers/controller.ts
  packages/core-api/src/versions/2/peers/schema.ts
  packages/core-api/src/versions/2/peers/transformer.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/socket-server/utils/get-headers.ts
  packages/core-p2p/src/socket-server/utils/validate-headers.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
Labels: Complexity: Low, Type: Refactor

#2553 refactor(core-p2p): remove peer.nethash property
  __tests__/integration/core-p2p/__support__/mock-socket-server/manager.ts
  __tests__/integration/core-p2p/__support__/utils.ts
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/peer-guard.test.ts
  __tests__/unit/core-p2p/peer.test.ts
  packages/core-forger/src/client.ts
  packages/core-interfaces/src/core-p2p/peer-guard.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/socket-server/utils/get-headers.ts
  packages/core-p2p/src/socket-server/utils/validate-headers.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
Labels: Complexity: Low, Type: Refactor

#2554 revert(core-p2p): peer header changes
  __tests__/integration/core-api/v1/handlers/peers.test.ts
  __tests__/integration/core-p2p/__support__/mock-socket-server/manager.ts
  __tests__/integration/core-p2p/__support__/utils.ts
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/peer-guard.test.ts
  __tests__/unit/core-p2p/peer.test.ts
  packages/core-api/src/versions/1/peers/controller.ts
  packages/core-api/src/versions/1/peers/schema.ts
  packages/core-api/src/versions/1/peers/transformer.ts
  packages/core-api/src/versions/2/peers/controller.ts
  packages/core-api/src/versions/2/peers/schema.ts
  packages/core-api/src/versions/2/peers/transformer.ts
  packages/core-forger/src/client.ts
  packages/core-interfaces/src/core-p2p/peer-guard.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/socket-server/utils/get-headers.ts
  packages/core-p2p/src/socket-server/utils/validate-headers.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
Labels: Complexity: Medium

#2555 fix(core-blockchain): remove forged transactions from pool before discarding block
  __tests__/unit/core-blockchain/mocks/transactionPool.ts
  __tests__/unit/core-transaction-pool/__stubs__/connection.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-interfaces/src/core-transaction-pool/connection.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Bugfix

#2558 feat(core-wallets-api): proxy API calls to core-api until fully developed
  packages/core-wallet-api/package.json
  packages/core-wallet-api/src/plugin.ts
  packages/core-wallet-api/src/server/index.ts
Labels: Complexity: Low, Status: In Progress, Type: Feature

#2557 feat(core): add db configuration command
  packages/core/src/commands/config/database.ts
  packages/core/src/commands/config/forger/bip39.ts
  packages/core/src/commands/env/set.ts
  packages/core/src/types.ts
  packages/core/src/utils.ts
Labels: Bounty: Tier 2, Complexity: Medium, Status: Collaborator Approved, Status: In Progress, Status: Needs Changes, Type: Feature

#2564 refactor: replace pokemon.random with Math.random to avoid value collision
  __tests__/helpers/transaction-factory.ts
  __tests__/integration/core-tester-cli/commands/send/delegate-registration.test.ts
  packages/core-tester-cli/package.json
  packages/core-tester-cli/src/commands/send/delegate-registration.ts
  yarn.lock
Labels: Complexity: Low, Type: Refactor

#2562 feat(core-jest-matchers): functional test matchers
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/functional/transaction-forging/delegate-registration.test.ts
  __tests__/functional/transaction-forging/ipfs.test.ts
  __tests__/functional/transaction-forging/multi-signature-registration.test.ts
  __tests__/functional/transaction-forging/second-signature-registration.test.ts
  __tests__/functional/transaction-forging/transfer.test.ts
  __tests__/functional/transaction-forging/vote.test.ts
  __tests__/helpers/transaction-factory.ts
  packages/core-jest-matchers/package.json
  packages/core-jest-matchers/src/functional/accepted.ts
  packages/core-jest-matchers/src/functional/forged.ts
  packages/core-jest-matchers/src/functional/index.ts
  packages/core-jest-matchers/src/functional/rejected.ts
  packages/core-jest-matchers/src/index.ts
Labels: Complexity: High, Status: In Progress, Type: Feature

#2560 refactor(core-p2p): socketcluster shutdown and logging
  __tests__/integration/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  packages/core-container/src/container.ts
  packages/core-forger/src/client.ts
  packages/core-forger/src/manager.ts
  packages/core-interfaces/src/core-p2p/network-monitor.ts
  packages/core-p2p/src/event-listener.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/plugin.ts
Labels: Complexity: Medium, Type: Refactor

#2538 feat: Implement Delegate Resignation (AIP11)
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/1.create-transactions.action.js
  __tests__/e2e/tests/scenarios/scenario1/chained-tx/3.resend-BtoC.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.0.doublespend.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend-mix/1.1.doublespend2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.0.doubletransfer.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.1.doubletransfer2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.2.doublevote.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.3.doubledelreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/doublespend/1.4.double2ndsigreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.0.transfer.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.1.transfer2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.2.vote.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.3.delreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/insufficient-balance/1.4.2ndsigreg.action.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/pool-restart/1.create-transactions.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.0.transfer-new-wallet.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/0.1.init-2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.0.transaction.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/1.1.transaction2ndsig.action.js
  __tests__/e2e/tests/scenarios/scenario1/transactions-valid/utils.js
  __tests__/functional/transaction-forging/delegate-resignation.test.ts
  __tests__/helpers/transaction-factory.ts
  __tests__/unit/core-container/__stubs__/config/milestones.json
  __tests__/unit/core-jest-matchers/transactions/types/delegate-registration.test.ts
  __tests__/unit/core-jest-matchers/transactions/types/delegate.test.ts
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  __tests__/unit/core-state/wallets/wallet.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/delegate-registration.test.ts
  __tests__/unit/crypto/transactions/builders/transactions/delegate-resignation.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  __tests__/utils/helpers/container.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-jest-matchers/src/transactions/types/delegate-registration.ts
  packages/core-jest-matchers/src/transactions/types/index.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-state/src/wallets/wallet.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
  packages/crypto/src/networks/devnet/milestones.json
  packages/crypto/src/networks/mainnet/milestones.json
  packages/crypto/src/networks/testnet/milestones.json
  packages/crypto/src/networks/unitnet/milestones.json
  packages/crypto/src/transactions/builders/transactions/delegate-resignation.ts
Labels: Complexity: Medium, Status: Needs Changes, Type: Feature

#2565 fix: sync issues with devnet and mainnet
  __tests__/unit/crypto/blocks/block.test.ts
  packages/core-container/src/config/index.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/networks/devnet/milestones.json
  packages/crypto/src/networks/mainnet/exceptions.json
Labels: Complexity: Low, Type: Bugfix

#2567 feat(core-api): accept block height to list block transactions
  __tests__/integration/core-api/v2/handlers/blocks.test.ts
  packages/core-api/src/versions/2/blocks/methods.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Feature

#2571 refactor(core-http-utils): return all schema errors
  packages/core-http-utils/src/plugins/hapi-ajv.ts
Labels: Complexity: Low, Type: Refactor

#2572 fix(blockchain): use resolveOptions("blockchain") to get databaseRollback options
  __tests__/unit/core-blockchain/mocks/container.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  packages/core-blockchain/src/state-machine.ts
Labels: Complexity: Low, Type: Bugfix

#2575 test(core-transaction-pool): polish stress test and don't clock the TransactionFactory
  __tests__/unit/core-transaction-pool/connection.test.ts
Labels: Complexity: Medium, Test: Unit

#2574 fix(crypto): make amount required
  __tests__/unit/core-transactions/handler-registry.test.ts
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: Low, Type: Bugfix

#2578 refactor(core-api): register /api/v2 as a transition period fallback
  packages/core-api/src/defaults.ts
  packages/core-api/src/handlers/index.ts
  packages/core-api/src/server.ts
Labels: Complexity: Low, Type: Refactor

#2580 refactor: use ApplicationEvents enum instead of string
  __tests__/integration/core-webhooks/server.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-forger/manager.test.ts
  packages/core-blockchain/package.json
  packages/core-blockchain/src/blockchain.ts
  packages/core-database/src/database-service.ts
  packages/core-forger/package.json
  packages/core-forger/src/manager.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
  packages/core-transactions/package.json
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
Labels: Bounty: Tier 4, Complexity: Medium, Status: Collaborator Approved, Type: Refactor

#2559 feat(core-p2p): don't trust headers and verify config and plugin connectivity of peers
  __tests__/helpers/peers.ts
  __tests__/integration/core-api/v1/handlers/peers.test.ts
  __tests__/integration/core-api/v2/handlers/blocks.test.ts
  __tests__/integration/core-api/v2/handlers/peers.test.ts
  __tests__/integration/core-json-rpc/blocks.test.ts
  __tests__/integration/core-json-rpc/transactions.test.ts
  __tests__/integration/core-json-rpc/wallets.test.ts
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/integration/core-p2p/network-monitor.test.ts
  __tests__/integration/core-p2p/peer-communicator.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/mocks/core-container.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/peer-guard.test.ts
  __tests__/unit/core-p2p/peer-processor.test.ts
  __tests__/unit/core-p2p/peer-storage.test.ts
  __tests__/unit/core-p2p/peer.test.ts
  __tests__/unit/core-p2p/socket-server/versions/peer/index.test.ts
  __tests__/unit/core-p2p/utils/is-valid-version.test.ts
  __tests__/unit/core-state/wallets/wallet-manager.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-utils/transform-plugins.test.ts
  package.json
  packages/core-api/src/server.ts
  packages/core-api/src/versions/1/peers/controller.ts
  packages/core-api/src/versions/1/peers/transformer.ts
  packages/core-api/src/versions/2/peers/controller.ts
  packages/core-api/src/versions/2/peers/transformer.ts
  packages/core-forger/src/client.ts
  packages/core-interfaces/src/core-p2p/peer-guard.ts
  packages/core-interfaces/src/core-p2p/peer-processor.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-json-rpc/src/server/services/network.ts
  packages/core-p2p/src/interfaces.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/peer-storage.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/schemas.ts
  packages/core-p2p/src/socket-server/utils/get-peer-config.ts
  packages/core-p2p/src/socket-server/utils/validate-headers.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-p2p/src/socket-server/worker.ts
  packages/core-p2p/src/utils/index.ts
  packages/core-p2p/src/utils/is-valid-version.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-utils/src/index.ts
  packages/core-utils/src/transform-plugins.ts
  packages/core-wallet-api/package.json
  packages/core-wallet-api/src/server/handlers.ts
  packages/core-wallet-api/src/server/transformers.ts
  packages/core/src/commands/config/database.ts
  yarn.lock
Labels: Complexity: Medium, Status: In Progress, Type: Feature

#2581 fix(core-blockchain): delete bad rounds after unclean shutdown
  __tests__/unit/core-blockchain/state-machine.test.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-database-postgres/src/queries/rounds/delete.sql
Labels: Complexity: Low, Type: Bugfix

#2582 feat(core): command to generate network configuration
  packages/core/package.json
  packages/core/src/commands/network/generate.ts
Labels: Complexity: High, Status: In Progress, Type: Feature

#2583 fix(core-p2p): don't cause suspensions for unresponsive plugins
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Type: Bugfix

#2584 refactor(crypto): signature verification
  __tests__/unit/crypto/transactions/verifier.test.ts
  packages/crypto/src/transactions/verifier.ts
Labels: Complexity: Low, Type: Refactor

#2586 fix: divide blocks into smaller chunks for batch processing
  __tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/state-machine.ts
Labels: Complexity: Low, Type: Bugfix

#2474 chore(ci): setup node.js 12 on CircleCI
  .circleci/config.yml
  .circleci/configTemplate.json
  .circleci/generateConfig.js
  __tests__/unit/crypto/crypto/hdwallet.test.ts
  package.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-blockchain/src/blockchain.ts
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-forger/package.json
  packages/core-interfaces/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-winston/package.json
  packages/core-p2p/package.json
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
  packages/core-utils/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/crypto/src/crypto/hdwallet.ts
  yarn.lock
Labels: Complexity: High, Status: In Progress, Type: Task

#2591 chore(changelog): add latest changes for 2.4.0
  CHANGELOG.md
Labels: Complexity: Low, Type: Task

#2590 fix(core-p2p): do not suspend peer for `AppNotReady`
  __tests__/unit/core-blockchain/mocks/blockchain.ts
  __tests__/unit/core-blockchain/state-machine.test.ts
  __tests__/unit/core-p2p/peer-guard.test.ts
  __tests__/unit/core-state/mocks/blockchain.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/state-machine.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-guard.ts
Labels: Complexity: Low, Type: Bugfix

#2593 fix(core-json-rpc): allow use of old and new block IDs
  packages/core-json-rpc/src/server/methods/blocks/info.ts
  packages/core-json-rpc/src/server/methods/blocks/transactions.ts
Labels: Complexity: Low, Type: Bugfix

#2594 release: 2.3.23
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Status: In Progress, Type: Release

#2592 refactor: use dayjs as it now has official UTC support
  __tests__/unit/core-p2p/peer-guard.test.ts
  __tests__/unit/core-p2p/peer-storage.test.ts
  __tests__/unit/core-p2p/peer-suspension.test.ts
  __tests__/unit/core-transaction-pool/__stubs__/connection.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-api/package.json
  packages/core-database-postgres/package.json
  packages/core-database-postgres/src/repositories/transactions.ts
  packages/core-interfaces/package.json
  packages/core-interfaces/src/core-p2p/peer-guard.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-interfaces/src/core-transaction-pool/connection.ts
  packages/core-logger-winston/package.json
  packages/core-logger-winston/src/formatter.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/peer-suspension.ts
  packages/core-p2p/src/peer.ts
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
  packages/core-utils/package.json
  packages/core-utils/src/format-timestamp.ts
  packages/core/package.json
  packages/core/src/commands/top.ts
  packages/core/src/shared/status.ts
  packages/crypto/package.json
  packages/crypto/src/crypto/slots.ts
  yarn.lock
Labels: Complexity: Medium, Type: Refactor

#2595 fix(core-database-postgres): use day instead of date
  packages/core-database-postgres/src/repositories/transactions.ts
Labels: Complexity: Low, Type: Bugfix

#2598 chore: add core-state dependency to core-database-postgres
  packages/core-database-postgres/package.json
Labels: Complexity: Low, Type: Task

#2596 refactor(core-json-rpc): use blockId schema for validation
  packages/core-json-rpc/src/server/modules.ts
Labels: Complexity: Low, Type: Refactor

#2599 chore: add missing dependencies
  packages/core-blockchain/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-json-rpc/package.json
  packages/core-state/package.json
  packages/core-transaction-pool/package.json
  packages/core-wallet-api/package.json
Labels: Complexity: Low, Type: Bugfix

#2597 refactor(core-p2p): remove timeout banning
  __tests__/unit/core-p2p/peer-guard.test.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/peer.ts
Labels: Complexity: Low, Type: Refactor

#2602 release: 2.4.0-next.4
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2606 refactor(core-p2p): remove peer caching
  __tests__/unit/core-p2p/peer-storage.test.ts
  packages/core-interfaces/src/core-p2p/peer-storage.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-storage.ts
  packages/core-p2p/src/plugin.ts
  packages/core-p2p/src/utils/index.ts
  packages/core-p2p/src/utils/restore-peers.ts
Labels: Complexity: Medium, Type: Refactor

#2604 feat(core-explorer): initial implementation
  .circleci/config.yml
  packages/core-explorer/.gitattributes
  packages/core-explorer/README.md
  packages/core-explorer/package.json
  packages/core-explorer/src/defaults.ts
  packages/core-explorer/src/index.ts
  packages/core-explorer/tsconfig.json
  yarn.lock
Labels: Complexity: High, Type: Feature

#2603 chore: add commands to check for missing dependencies and types
  .circleci/config.yml
  package.json
  packages/core-api/package.json
  packages/core-jest-matchers/package.json
  packages/core-transaction-pool/package.json
  packages/core/package.json
  packages/crypto/package.json
  scripts/deps/missing.js
  scripts/deps/unused.js
  scripts/deps/update.sh
  yarn.lock
Labels: Complexity: Medium, Type: Task

#2607 fix(core-p2p): non blocking port ping
  packages/core-p2p/src/peer-communicator.ts
  packages/core-utils/src/httpie.ts
Labels: Complexity: Low, Type: Bugfix

#2605 refactor(core-p2p): show mapped IPs as IPv4
  __tests__/unit/core-blockchain/blockchain.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-p2p/src/socket-server/utils/map-addr.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
Labels: Complexity: Low, Type: Refactor

#2608 release: 2.4.0-next.5
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2610 fix(core-forger): use a static reconnect timeout
  packages/core-forger/src/client.ts
  packages/core-forger/src/manager.ts
  packages/core-p2p/src/peer-processors.ts
Labels: Complexity: Low, Type: Bugfix

#2609 chore: update contribution link
  .github/CONTRIBUTING.md
Labels: Bounty: Tier 6, Complexity: Low, Type: Task

#2611 fix(core-database): assign calculated delegate ranks from temp wallets
  packages/core-database/src/database-service.ts
Labels: Complexity: Low, Type: Bugfix

#2613 fix(core-wallet-api): return plugins with package names
  __tests__/unit/core-utils/transform-plugins.test.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-utils/src/transform-plugins.ts
  packages/core-wallet-api/src/server/handlers.ts
Labels: Complexity: Low, Type: Bugfix

#2614 release: 2.4.0-next.6
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2612 refactor(core-p2p): remove peer banning
  __tests__/helpers/peers.ts
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/integration/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/mocks/p2p.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/peer-guard.test.ts
  __tests__/unit/core-p2p/peer-processor.test.ts
  __tests__/unit/core-p2p/peer-storage.test.ts
  __tests__/unit/core-p2p/peer-suspension.test.ts
  packages/core-api/src/versions/2/peers/controller.ts
  packages/core-api/src/versions/2/peers/routes.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-interfaces/src/core-p2p/index.ts
  packages/core-interfaces/src/core-p2p/network-monitor.ts
  packages/core-interfaces/src/core-p2p/peer-guard.ts
  packages/core-interfaces/src/core-p2p/peer-processor.ts
  packages/core-interfaces/src/core-p2p/peer-service.ts
  packages/core-interfaces/src/core-p2p/peer-storage.ts
  packages/core-p2p/src/event-listener.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-guard.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/peer-processors.ts
  packages/core-p2p/src/peer-service.ts
  packages/core-p2p/src/peer-storage.ts
  packages/core-p2p/src/peer-suspension.ts
  packages/core-p2p/src/plugin.ts
  packages/core-p2p/src/socket-server/versions/utils.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Refactor

#2616 feat(core-api): allow retrieval of raw blocks and transactions
  __tests__/integration/core-api/handlers/blocks.test.ts
  __tests__/integration/core-api/handlers/transactions.test.ts
  packages/core-api/src/handlers/blocks/methods.ts
  packages/core-api/src/handlers/blocks/schema.ts
  packages/core-api/src/handlers/blocks/transformer.ts
  packages/core-api/src/handlers/delegates/methods.ts
  packages/core-api/src/handlers/delegates/schema.ts
  packages/core-api/src/handlers/peers/schema.ts
  packages/core-api/src/handlers/rounds/schema.ts
  packages/core-api/src/handlers/shared/controller.ts
  packages/core-api/src/handlers/shared/schemas/block-id.ts
  packages/core-api/src/handlers/shared/schemas/pagination.ts
  packages/core-api/src/handlers/transactions/controller.ts
  packages/core-api/src/handlers/transactions/methods.ts
  packages/core-api/src/handlers/transactions/schema.ts
  packages/core-api/src/handlers/transactions/transformer.ts
  packages/core-api/src/handlers/utils.ts
  packages/core-api/src/handlers/votes/methods.ts
  packages/core-api/src/handlers/votes/schema.ts
  packages/core-api/src/handlers/wallets/methods.ts
  packages/core-api/src/handlers/wallets/schema.ts
  packages/core-api/src/services/transformer.ts
Labels: Complexity: High, Type: Feature

#2617 release: 2.4.0-next.7
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2619 refactor(core-blockchain): remove coldstart period
  __tests__/e2e/lib/generate-files.js
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/integration/core-p2p/__support__/setup.ts
  __tests__/integration/core-transaction-pool/__support__/setup.ts
  __tests__/unit/core-forger/manager.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/utils/config/testnet/plugins.js
  __tests__/utils/config/unitnet/plugins.js
  packages/core-forger/src/manager.ts
  packages/core-interfaces/src/core-p2p/network-monitor.ts
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/enums.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/network-state.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
Labels: Complexity: Medium, Type: Refactor

#2618 feat(core-api): search transactions by asset
  __tests__/integration/core-api/handlers/transactions.test.ts
  packages/core-api/src/handlers/transactions/schema.ts
  packages/core-database-postgres/src/models/transaction.ts
  packages/core-database/src/repositories/utils/search-parameter-converter.ts
  packages/core-interfaces/src/core-database/search/search-parameters.ts
Labels: Complexity: Low, Type: Feature

#2620 chore(deps): update dependencies to latest versions
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-forger/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-tester-cli/package.json
  packages/core/package.json
  packages/crypto/package.json
  scripts/deps/update.sh
Labels: Complexity: Low, Type: Task

#2615 fix(core-snapshots): camelize block keys before bignum transformation
  packages/core-snapshots/src/transport/codec.ts
Labels: Complexity: Low, Type: Bugfix

#2621 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Documentation_issue.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/ISSUE_TEMPLATE/Security_vulnerabilities.md
  .github/ISSUE_TEMPLATE/Support_question.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#2622 refactor(core-transaction-pool): deserialize transactions before they leave the pool
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/unit/core-p2p/mocks/blockchain.ts
  __tests__/unit/core-p2p/mocks/core-container.ts
  __tests__/unit/core-p2p/mocks/transaction-pool.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/transactions.test.ts
  __tests__/unit/core-transaction-pool/__stubs__/connection.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/utils/config/testnet/plugins.js
  __tests__/utils/config/unitnet/plugins.js
  packages/core-api/src/versions/2/node/controller.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-forger/src/manager.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-transaction-pool/connection.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/storage.ts
  packages/crypto/src/blocks/deserializer.ts
  packages/crypto/src/transactions/deserializer.ts
  packages/crypto/src/transactions/factory.ts
  yarn.lock
Labels: Complexity: High, Status: In Progress, Type: Refactor

#2624 release: 2.4.0-next.8
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2587 refactor: do not temporary inc/dec nonce when checking tx validity
  __tests__/integration/core-api/handlers/transactions.test.ts
  __tests__/integration/core-api/utils.ts
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/integration/core-transaction-pool/wallet-manager.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-transaction-pool/__fixtures__/transactions.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/core-transactions/handler.test.ts
  __tests__/unit/crypto/transactions/utils.test.ts
  packages/core-database/src/database-service.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-state/src/wallets/wallet.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transaction-pool/src/wallet-manager.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/delegate-registration.ts
  packages/core-transactions/src/handlers/delegate-resignation.ts
  packages/core-transactions/src/handlers/ipfs.ts
  packages/core-transactions/src/handlers/multi-payment.ts
  packages/core-transactions/src/handlers/multi-signature.ts
  packages/core-transactions/src/handlers/second-signature.ts
  packages/core-transactions/src/handlers/timelock-transfer.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/transfer.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core-transactions/src/interfaces.ts
Labels: Complexity: High, Type: Refactor

#2629 fix(core-blockchain): chain replay stopped working after dependency update
  packages/core-blockchain/src/replay/replay-blockchain.ts
Labels: Complexity: Low, Type: Bugfix

#2630 fix(core-forger): wrap error message to satisfy schema
  __tests__/unit/core-forger/manager.test.ts
  packages/core-forger/src/client.ts
  packages/core-forger/src/manager.ts
Labels: Complexity: Low, Type: Bugfix

#2628 refactor(core-container): require a minimum of 0 as pubKeyHash
  packages/core-container/src/config/index.ts
Labels: Bounty: Tier 5, Complexity: Low, Status: Collaborator Approved, Type: Refactor

#2625 test(e2e): allow full sync testing
  __tests__/e2e/bin/e2e
  __tests__/e2e/lib/generate-files.js
  __tests__/e2e/lib/test-runner.js
  __tests__/e2e/lib/utils/sync.sh
  __tests__/e2e/lib/utils/test-utils.js
  __tests__/e2e/package.json
Labels: Complexity: Medium, Test: Unit

#2633 refactor: ask for a retry if installing core fails from install.sh
  install.sh
Labels: Complexity: Low, Type: Refactor

#2632 refactor: improve database configuration in install.sh script
  install.sh
Labels: Complexity: Low

#2634 fix(core-webhooks): require all properties in schema and handle 404 resources
  .circleci/config.yml
  __tests__/integration/core-webhooks/__support__/setup.ts
  __tests__/integration/core-webhooks/__support__/utils.ts
  __tests__/integration/core-webhooks/server.test.ts
  __tests__/unit/core-webhooks/server.test.ts
  packages/core-webhooks/src/conditions.ts
  packages/core-webhooks/src/database.ts
  packages/core-webhooks/src/listener.ts
  packages/core-webhooks/src/server/index.ts
  packages/core-webhooks/src/server/schema.ts
Labels: Complexity: Low, Status: In Progress, Type: Refactor

#2636 fix(core-p2p): handle undefined `curr` during block download
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Low, Type: Bugfix

#2635 fix(core-transaction-pool): check if transactions can still be applied before forging
  __tests__/unit/core-transaction-pool/connection.test.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Low, Type: Bugfix

#2637 release: 2.4.0-next.9
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-json-rpc/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#2638 chore(changelog): add latest changes for 2.4.0
  CHANGELOG.md
Labels: Complexity: Low, Type: Task

#2640 build: sequentially build modules with yarn
  .yarnrc
Labels: Complexity: Low, Status: In Progress, Type: Task

#2641 feat(core-api): allow easy retrieval of first and last block
  __tests__/integration/core-api/handlers/blocks.test.ts
  packages/core-api/src/handlers/blocks/controller.ts
  packages/core-api/src/handlers/blocks/routes.ts
  packages/core-api/src/handlers/blocks/schema.ts
  packages/core-api/src/handlers/blocks/transformer.ts
Labels: Complexity: Medium, Status: In Progress, Type: Feature

#2642 chore(deps): add missing @hapi/boom and @hapi/joi dependencies
  packages/core-api/package.json
  packages/core-api/src/handlers/blocks/methods.ts
  packages/core-api/src/handlers/delegates/methods.ts
  packages/core-api/src/handlers/rounds/methods.ts
  packages/core-api/src/handlers/transactions/methods.ts
  packages/core-api/src/handlers/utils.ts
  packages/core-api/src/handlers/votes/methods.ts
  packages/core-api/src/handlers/wallets/methods.ts
Labels: Complexity: Low, Status: In Progress, Type: Task

#2643 feat(core-exchange-json-rpc): use @arkecosystem/core-exchange-json-rpc programmatically
  .circleci/config.yml
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-json-rpc/__support__/request.ts
  __tests__/integration/core-json-rpc/__support__/setup.ts
  __tests__/integration/core-json-rpc/blocks.test.ts
  __tests__/integration/core-json-rpc/transactions.test.ts
  __tests__/integration/core-json-rpc/wallets.test.ts
  __tests__/unit/core-utils/transform-plugins.test.ts
  __tests__/utils/config/testnet/plugins.js
  __tests__/utils/config/unitnet/plugins.js
  deprecated/core-json-rpc/.gitattributes
  deprecated/core-json-rpc/README.md
  deprecated/core-json-rpc/package.json
  deprecated/core-json-rpc/src/defaults.ts
  deprecated/core-json-rpc/src/index.ts
  deprecated/core-json-rpc/src/interfaces.ts
  deprecated/core-json-rpc/src/server/index.ts
  deprecated/core-json-rpc/src/server/modules.ts
  deprecated/core-json-rpc/src/server/services/database.ts
  deprecated/core-json-rpc/src/server/services/network.ts
  deprecated/core-json-rpc/src/server/services/processor.ts
  deprecated/core-json-rpc/src/server/utils.ts
  deprecated/core-json-rpc/tsconfig.json
  docker/production/README.md
  docker/production/devnet/devnet.env
  docker/production/mainnet/mainnet.env
  packages/core-api/src/versions/1/shared/transformers/ports.ts
  packages/core-api/src/versions/2/shared/transformers/ports.ts
  packages/core-exchange-json-rpc/README.md
  packages/core-exchange-json-rpc/package.json
  packages/core-exchange-json-rpc/src/defaults.ts
  packages/core-exchange-json-rpc/src/index.ts
  packages/core-exchange-json-rpc/tsconfig.json
  packages/core-json-rpc/src/defaults.ts
  packages/core/bin/config/devnet/.env
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/.env
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/.env
  packages/core/bin/config/testnet/plugins.js
  packages/core/package.json
  yarn.lock
Labels: Complexity: High, Status: In Progress, Type: Refactor
