Repository ArkEcosystem/core, pull requests merged in 2020-07, with the labels that each got.

#3856 chore: upload codecov reports all at once
  .github/workflows/functional.yml
  .github/workflows/unit.yml
  .gitignore
Labels: Complexity: High, Status: Needs Review, Type: Task

#3844 fix(core-transactions): stream transactions during bootstrap
  __tests__/functional/core-database/repositories/transaction-repository.test.ts
  __tests__/unit/core-api/controllers/blocks.test.ts
  __tests__/unit/core-api/controllers/controller.test.ts
  __tests__/unit/core-api/controllers/delegates.test.ts
  __tests__/unit/core-api/controllers/locks.test.ts
  __tests__/unit/core-api/controllers/node.test.ts
  __tests__/unit/core-api/controllers/peers.test.ts
  __tests__/unit/core-api/controllers/rounds.test.ts
  __tests__/unit/core-api/controllers/votes.test.ts
  __tests__/unit/core-api/controllers/wallets.test.ts
  __tests__/unit/core-api/resources/wallet.test.ts
  __tests__/unit/core-database/transaction-history-service.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-update.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-registration.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-resignation.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-update.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/entity.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/general.test.ts
  __tests__/unit/core-transactions/handlers/handler-registry.test.ts
  __tests__/unit/core-transactions/handlers/one/multi-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/delegate-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/delegate-resignation.test.ts
  __tests__/unit/core-transactions/handlers/two/general.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-claim.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-lock.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-refund.test.ts
  __tests__/unit/core-transactions/handlers/two/ipfs.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-payment.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/second-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/transfer.test.ts
  __tests__/unit/core-transactions/handlers/two/vote.test.ts
  packages/core-database/src/repositories/abstract-repository.ts
  packages/core-database/src/transaction-history-service.ts
  packages/core-kernel/src/contracts/shared/transaction-history-service.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/resign.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/update.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
  packages/core-test-framework/src/internal/wallet-attributes.ts
  packages/core-transactions/src/handlers/handler-provider.ts
  packages/core-transactions/src/handlers/one/multi-signature-registration.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/two/delegate-registration.ts
  packages/core-transactions/src/handlers/two/delegate-resignation.ts
  packages/core-transactions/src/handlers/two/ipfs.ts
  packages/core-transactions/src/handlers/two/multi-payment.ts
  packages/core-transactions/src/handlers/two/multi-signature-registration.ts
  packages/core-transactions/src/handlers/two/second-signature-registration.ts
  packages/core-transactions/src/handlers/two/vote.ts
  packages/core-transactions/src/index.ts
  packages/core-transactions/src/transaction-reader.ts
Labels: Complexity: High, Type: Bugfix

#3864 fix(core-p2p): Ensure peer port is always an integer to avoid socket validation errors
  __tests__/unit/core-p2p/service-provider.test.ts
  __tests__/unit/core-p2p/socket-server/utils/get-headers.test.ts
  packages/core-p2p/src/service-provider.ts
  packages/core-p2p/src/socket-server/utils/get-headers.ts
Labels: Complexity: Medium, Type: Bugfix

#3865 test(core-api): increase coverage to 100%
  __tests__/unit/core-api/controllers/blocks.test.ts
  __tests__/unit/core-api/controllers/controller.test.ts
  __tests__/unit/core-api/controllers/node.test.ts
  __tests__/unit/core-api/controllers/peers.test.ts
  __tests__/unit/core-api/controllers/transactions.test.ts
  __tests__/unit/core-api/controllers/wallets.test.ts
  __tests__/unit/core-api/plugins/pagination.test.ts
  __tests__/unit/core-api/plugins/rate-limit.test.ts
  __tests__/unit/core-api/resources/block-with-transactions.test.ts
  __tests__/unit/core-api/resources/block.test.ts
  __tests__/unit/core-api/resources/delegate.test.ts
  __tests__/unit/core-api/resources/delegates.test.ts
  __tests__/unit/core-api/resources/ports.test.ts
  __tests__/unit/core-api/resources/round.test.ts
  __tests__/unit/core-api/resources/transaction-with-blocks.test.ts
  __tests__/unit/core-api/resources/transaction.test.ts
  __tests__/unit/core-api/service-provider.test.ts
  packages/core-api/src/plugins/pagination/config.ts
  packages/core-api/src/plugins/pagination/ext.ts
  packages/core-api/src/plugins/rate-limit.ts
  packages/core-api/src/server.ts
Labels: Complexity: Undetermined, Test: Unit

#3852 fix(core-magistrate-transactions): entity handler bootstrap method, fetch transactions using asset type/subType as number
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/unit/core-transactions/handlers/two/htlc-claim.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-refund.test.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
  packages/core-state/src/state-builder.ts
  packages/core-test-framework/src/internal/wallet-attributes.ts
  packages/core-transactions/src/handlers/two/htlc-claim.ts
  packages/core-transactions/src/handlers/two/htlc-lock.ts
  packages/core-transactions/src/handlers/two/htlc-refund.ts
Labels: Complexity: Low, Test: Unit

#3867 test(core-webhooks): increase test coverage to 100%
  __tests__/unit/core-webhooks/database.test.ts
  __tests__/unit/core-webhooks/server/utils.test.ts
Labels: Complexity: Low, Test: Unit

#3858 fix(core-database): remove duplicates entity resigned/isResigned
  __tests__/integration/core-api/handlers/entities.test.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Complexity: Low, Type: Bugfix

#3871 fix(core-transactions): version 1 multi-signature handler should check milestone data
  __tests__/unit/core-transactions/handlers/handler-registry.test.ts
  __tests__/unit/core-transactions/handlers/one/multi-signature-registration.test.ts
  packages/core-transactions/src/handlers/one/multi-signature-registration.ts
Labels: Complexity: Low, Type: Bugfix

#3876 fix(core-magistrate-transactions): allow dynamic fees
  __tests__/unit/core-magistrate-transactions/handlers/general.test.ts
  packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
Labels: Complexity: Low, Type: Bugfix

#3877 feat(core-magistrate): aip36 delegate entity
  __tests__/functional/transaction-forging/entity-register.test.ts
  __tests__/unit/core-magistrate/handlers/entity.test.ts
  packages/core-magistrate-crypto/src/enums.ts
  packages/core-magistrate-crypto/src/transactions/entity.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/errors.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/index.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/resign.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/update.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
Labels: Complexity: Medium, Type: Feature

#3878 refactor(core-p2p): remove excess code from hapi-nes
  packages/core-kernel/src/contracts/p2p/nes-client.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/hapi-nes/client.ts
  packages/core-p2p/src/hapi-nes/index.ts
  packages/core-p2p/src/hapi-nes/listener.ts
  packages/core-p2p/src/hapi-nes/socket.ts
  yarn.lock
Labels: Complexity: High, Type: Refactor

#3884 test(core-p2p): increase coverage to 100%
  __tests__/unit/core-p2p/hapi-nes/client.test.ts
  __tests__/unit/core-p2p/hapi-nes/listener.test.ts
  __tests__/unit/core-p2p/hapi-nes/plugin.test.ts
  __tests__/unit/core-p2p/hapi-nes/socket.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/network-state.test.ts
  __tests__/unit/core-p2p/peer-communicator.test.ts
  __tests__/unit/core-p2p/peer-processor.test.ts
  __tests__/unit/core-p2p/rate-limiter.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/peer.test.ts
  __tests__/unit/core-p2p/socket-server/plugins/accept-peer.test.ts
  __tests__/unit/core-p2p/socket-server/plugins/validate.test.ts
  __tests__/unit/core-p2p/socket-server/plugins/whitelist-forger.test.ts
  __tests__/unit/core-p2p/socket-server/utils/get-peer-config.test.ts
  packages/core-p2p/src/hapi-nes/client.ts
  packages/core-p2p/src/hapi-nes/index.ts
  packages/core-p2p/src/hapi-nes/plugin.ts
  packages/core-p2p/src/hapi-nes/socket.ts
  packages/core-p2p/src/network-state.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/peer-verifier.ts
Labels: Complexity: Undetermined, Test: Unit

#3879 fix(core-database): guaranteed transaction order
  __tests__/integration/core-api/handlers/transactions.test.ts
  __tests__/unit/core-database/__fixtures__/block1760000.ts
  __tests__/unit/core-database/block-history-service.test.ts
  __tests__/unit/core-database/transaction-history-service.test.ts
  __tests__/unit/core-snapshots/__fixtures__/assets.ts
  __tests__/unit/core-test-framework/utils/mapper.test.ts
  packages/core-database/src/block-history-service.ts
  packages/core-database/src/migrations/20200705000000-add-block-height-column-to-transactions-table.ts
  packages/core-database/src/model-converter.ts
  packages/core-database/src/models/transaction.ts
  packages/core-database/src/repositories/abstract-repository.ts
  packages/core-database/src/transaction-history-service.ts
  packages/core-kernel/src/contracts/database/models.ts
  packages/core-snapshots/src/codecs/message-pack-codec.ts
  packages/core-test-framework/src/utils/mapper.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/interfaces/transactions.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#3886 fix(core-p2p): uses new Promise instead Promise.race
  packages/core-p2p/src/network-monitor.ts
Labels: Complexity: Low, Type: Bugfix

#3885 fix(core-state): remove unnecessary assertion check to enable devnet sync
  __tests__/unit/core-state/block-state.test.ts
  packages/core-state/src/block-state.ts
Labels: Complexity: Low, Type: Bugfix

#3887 feat(core-p2p): forget unresponsive peer
  __tests__/unit/core-p2p/listeners.test.ts
  __tests__/unit/core-p2p/peer-communicator.test.ts
  __tests__/unit/core-p2p/service-provider.test.ts
  packages/core-kernel/src/contracts/p2p/peer.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/listeners.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/service-provider.ts
Labels: Complexity: Medium, Type: Feature

#3892 feat(core-database): add block and transactions indexes migration
  packages/core-database/src/migrations/20200304000000-add-type_group-index-to-transactions-table.ts
  packages/core-database/src/migrations/20200317000000-add-blocks-and-transactions-indexes.ts
Labels: Complexity: Medium

#3895 feat(core-api): enable registering routes with pagination
  __tests__/unit/core-api/plugins/pagination.test.ts
  packages/core-api/src/plugins/pagination/ext.ts
  packages/core-api/src/routes/blocks.ts
  packages/core-api/src/routes/delegates.ts
  packages/core-api/src/routes/locks.ts
  packages/core-api/src/routes/peers.ts
  packages/core-api/src/routes/transactions.ts
  packages/core-api/src/routes/votes.ts
  packages/core-api/src/routes/wallets.ts
Labels: Complexity: Medium, Type: Feature

#3896 feat(core-p2p): split into 3 ports for blocks / transactions / others
  __tests__/unit/core-forger/client.test.ts
  __tests__/unit/core-magistrate-api/controllers/entities.test.ts
  __tests__/unit/core-p2p/listeners.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/peer-communicator.test.ts
  __tests__/unit/core-p2p/peer-connector.test.ts
  __tests__/unit/core-p2p/peer-processor.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/blocks.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/peer.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/transactions.test.ts
  __tests__/unit/core-p2p/socket-server/server.test.ts
  packages/core-forger/src/client.ts
  packages/core-forger/src/interfaces.ts
  packages/core-kernel/src/contracts/p2p/peer-connector.ts
  packages/core-p2p/src/enums.ts
  packages/core-p2p/src/listeners.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/schemas.ts
  packages/core-p2p/src/socket-server/controllers/blocks.ts
  packages/core-p2p/src/socket-server/controllers/peer.ts
  packages/core-p2p/src/socket-server/controllers/transactions.ts
  packages/core-p2p/src/socket-server/plugins/validate.ts
  packages/core-p2p/src/socket-server/routes/blocks.ts
  packages/core-p2p/src/socket-server/routes/peer.ts
  packages/core-p2p/src/socket-server/routes/transactions.ts
  packages/core-p2p/src/socket-server/schemas/blocks.ts
  packages/core-p2p/src/socket-server/schemas/peer.ts
  packages/core-p2p/src/socket-server/schemas/transactions.ts
  packages/core-p2p/src/socket-server/server.ts
  packages/core-p2p/src/socket-server/utils/get-peer-port.ts
Labels: Complexity: High, Status: Needs Review, Type: Feature

#3898 feat(core-p2p): implement peer blacklisting
  __tests__/unit/core-kernel/utils/is-blacklisted.test.ts
  __tests__/unit/core-p2p/peer-processor.test.ts
  packages/core-kernel/src/utils/index.ts
  packages/core-kernel/src/utils/is-blacklisted.ts
  packages/core-p2p/src/peer-processor.ts
Labels: Complexity: Medium, Type: Feature

#3901 fix(core-p2p): reset sequentialErrorCounter after peer response
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Type: Bugfix

#3900 fix(core-database): order transactions by sequence on block save
  packages/core-database/src/repositories/block-repository.ts
Labels: Complexity: Low, Type: Bugfix

#3902 chore(core-database): blocksInCurrentRound and forgingDelegates are arrays
  __tests__/unit/core-database/database-service.test.ts
  packages/core-database/src/database-service.ts
Labels: Complexity: Low, Type: Task

#3904 fix(crypto): use bundled file for `browser` field
  packages/crypto/package.json
  packages/crypto/rollup.config.js
Labels: Complexity: Low, Type: Bugfix

#3905 fix: pool, p2p and crypto fixes
  __tests__/functional/pool/pool.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/crypto/blocks/block.test.ts
  __tests__/unit/crypto/crypto/hash.test.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/utils/build-rate-limiter.ts
  packages/core-transaction-pool/src/connection.ts
  packages/crypto/src/crypto/hash.ts
Labels: Complexity: High, Type: Bugfix

#3906 fix(core-database): expose two methods for findByHeightRangeWithTransactions
  __tests__/functional/core-database/__support__/index.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/service-provider.test.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/block-repository.ts
Labels: Complexity: Medium, Type: Bugfix

#3909 fix(core-p2p): disconnect all sockets on peer disconnect
  __tests__/unit/core-p2p/listeners.test.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/peer-communicator.test.ts
  packages/core-p2p/src/listeners.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Type: Bugfix

#3916 fix(core-p2p): limit max connection retries
  packages/core-p2p/src/peer-connector.ts
Labels: Complexity: Low, Type: Bugfix

#3915 chore(core-manager): trigger processes from ark-core or ark-forger
  __tests__/unit/core-manager/actions/info-current-delegate.test.ts
  __tests__/unit/core-manager/actions/info-last-forged-block.test.ts
  __tests__/unit/core-manager/actions/info-next-forging-slot.test.ts
  __tests__/unit/core-manager/utils/process.test.ts
  packages/core-manager/src/actions/info-current-delegate.ts
  packages/core-manager/src/actions/info-last-forged-block.ts
  packages/core-manager/src/actions/info-next-forging-slot.ts
  packages/core-manager/src/utils/index.ts
  packages/core-manager/src/utils/process.ts
  packages/core/src/commands/core-run.ts
  packages/core/src/commands/forger-run.ts
Labels: Complexity: Medium, Type: Task

#3922 release: 3.0.0-alpha.0
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database-postgres/src/migrations/20200304000000-add-type_group-index-to-transactions-table.sql
  packages/core-database-postgres/src/migrations/20200317000000-add-blocks-and-transactions-indexes.sql
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Type: Release
