Repository ArkEcosystem/core, pull requests merged in 2020-08, with the labels that each got.

#3924 chore(core-p2p): add 3.0.0 alpha channel to valid peer versions
  __tests__/unit/core-p2p/network-monitor.test.ts
  packages/core-p2p/src/defaults.ts
Labels: Complexity: Low, Type: Task

#3925 fix(core-api): fix transactions/${id} confirmations and timestamp fields
  .github/workflows/unit.yml
  __tests__/unit/core-api/controllers/transactions.test.ts
  packages/core-api/src/controllers/transactions.ts
Labels: Complexity: Low, Status: Needs Review

#3926 chore(core-p2p): implement HEAD HTTP request for ping
  __tests__/unit/core-p2p/peer-communicator.test.ts
  packages/core-cli/package.json
  packages/core-kernel/package.json
  packages/core-p2p/src/peer-communicator.ts
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Medium, Type: Task

#3928 chore(core-api): get registered server route
  __tests__/unit/core-api/server.test.ts
  packages/core-api/src/server.ts
Labels: Complexity: Medium, Type: Task

#3932 fix(core-api): fix order in delegates/{id}/blocks
  packages/core-api/src/routes/delegates.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3935 chore(core-kernel): process env over .env
  packages/core-kernel/src/services/config/drivers/local.ts
Labels: Complexity: Low, Type: Task

#3937 chore(core-magistrate): remove bridgechain from aip36 entities
  __tests__/functional/transaction-forging/entity-register.test.ts
  __tests__/functional/transaction-forging/entity-resign.test.ts
  __tests__/functional/transaction-forging/entity-update.test.ts
  __tests__/unit/core-transaction-pool/memory.test.ts
  packages/core-magistrate-crypto/src/enums.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/bridgechain/index.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/bridgechain/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/bridgechain/resign.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/bridgechain/update.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Complexity: Medium, Type: Task

#3940 refactor(core-api): put configuration into Joi context
  packages/core-api/src/schemas.ts
  packages/core-api/src/server.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#3949 chore(core-database): use GIN index on transactions.asset
  packages/core-database/src/migrations/20200317000000-add-blocks-and-transactions-indexes.ts
Labels: Complexity: Low, Type: Task

#3953 fix(core-api): limit parameter (rollback #3940)
  __tests__/integration/core-api/handlers/transactions.test.ts
  packages/core-api/src/schemas.ts
  packages/core-api/src/server.ts
Labels: Complexity: High, Type: Bugfix

#3954 merge: master
  CHANGELOG.md
  __tests__/unit/core-database/repositories/wallets-business-repository.test.ts
  __tests__/unit/crypto/crypto/hash.test.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/crypto/src/crypto/hash.ts
  packages/crypto/src/networks/mainnet/exceptions.json
Labels: Complexity: Medium

#3955 refactor(core-api): pagination configuration through joi context
  __tests__/integration/core-api/handlers/wallets.test.ts
  packages/core-api/src/schemas.ts
  packages/core-api/src/server.ts
Labels: Complexity: High, Type: Refactor

#3939 fix(core-state): fix delegate search order
  __tests__/unit/core-state/wallets/wallet-repository.test.ts
  packages/core-state/src/wallets/utils/get-property.ts
  packages/core-state/src/wallets/utils/sort-entries.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3948 fix(core-database): revertBlock
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-state/stores/state.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-database/src/database-service.ts
  packages/core-kernel/src/contracts/state/state-store.ts
  packages/core-state/src/stores/state.ts
  packages/core-transactions/src/handlers/two/ipfs.ts
Labels: Complexity: Low, Type: Bugfix

#3965 refactor(core-api): dot-separated-query hapi plugin
  __tests__/unit/core-api/plugins/dot-separated-query.test.ts
  packages/core-api/src/plugins/dot-separated-query.ts
  packages/core-api/src/plugins/index.ts
Labels: Complexity: Low, Status: Needs Review

#3962 chore(core-state): remove forget methods and use index instead
  __tests__/functional/transaction-forging/delegate-resignation.test.ts
  __tests__/integration/core-api/handlers/delegates.test.ts
  __tests__/unit/core-magistrate-api/controllers/entities.test.ts
  __tests__/unit/core-state/__utils__/fixture-generator.ts
  __tests__/unit/core-state/block-state.test.ts
  __tests__/unit/core-state/wallets/wallet-index.test.ts
  __tests__/unit/core-state/wallets/wallet-repository-clone.test.ts
  __tests__/unit/core-state/wallets/wallet-repository-copy-on-write.test.ts
  __tests__/unit/core-state/wallets/wallet-repository.test.ts
  __tests__/unit/core-transactions/handlers/two/delegate-resignation.test.ts
  packages/core-kernel/src/contracts/state/wallets.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-state/src/wallets/wallet-index.ts
  packages/core-state/src/wallets/wallet-repository.ts
  packages/core-transactions/src/handlers/one/delegate-registration.ts
  packages/core-transactions/src/handlers/two/delegate-resignation.ts
Labels: Complexity: Medium, Type: Task

#3967 chore(crypto): add devnet exception
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Complexity: Low, Type: Task

#3968 fix(core-kernel): dynamically import @pm2/io
  packages/core-kernel/src/services/process-actions/drivers/pm2.ts
Labels: Complexity: Low, Type: Bugfix

#3936 fix(core-database): decouple database and state packages
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/integration/core-api/handlers/rounds.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/core-blockchain/processor/handlers/accept-block-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts
  __tests__/unit/core-blockchain/service-provider.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/initialize.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/service-provider.test.ts
  __tests__/unit/core-forger/forger-service.test.ts
  __tests__/unit/core-forger/setup.ts
  __tests__/unit/core-kernel/utils/get-blocktime-lookup.test.ts
  __tests__/unit/core-p2p/peer-verifier.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/internal.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/peer.test.ts
  __tests__/unit/core-state/__fixtures__/block1760000.ts
  __tests__/unit/core-state/database-interactions.test.ts
  __tests__/unit/core-state/service-provider.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-blockchain/src/state-machine/actions/initialize.ts
  packages/core-database/src/actions/index.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/service-provider.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-kernel/src/utils/get-blocktime-lookup.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/socket-server/controllers/internal.ts
  packages/core-p2p/src/socket-server/controllers/peer.ts
  packages/core-state/src/actions/get-active-delegates.ts
  packages/core-state/src/actions/index.ts
  packages/core-state/src/database-interactions.ts
  packages/core-state/src/index.ts
  packages/core-state/src/service-provider.ts
  packages/core/bin/config/devnet/app.json
  packages/core/bin/config/mainnet/app.json
  packages/core/bin/config/testnet/app.json
Labels: Complexity: Undetermined, Type: Bugfix

#3976 refactor(core-transactions): throw more specific multi-signature exceptions
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/transaction.ts
Labels: Complexity: Low, Type: Refactor

#3974 chore(crypto): add publickey verification
  __tests__/unit/core-state/__utils__/build-delegate-and-vote-balances.ts
  __tests__/unit/core-state/block-state.test.ts
  __tests__/unit/core-state/wallets/wallet-repository.test.ts
  __tests__/unit/crypto/identities/public-key.test.ts
  packages/crypto/src/identities/address.ts
  packages/crypto/src/identities/public-key.ts
Labels: Complexity: Low, Type: Task

#3972 test(core-magistrate-transactions): increate coverage to 100 %
  __tests__/unit/core-magistrate-transactions/__support__/app.ts
  __tests__/unit/core-magistrate-transactions/handlers/__fixtures__/entity/index.ts
  __tests__/unit/core-magistrate-transactions/handlers/__fixtures__/index.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-update.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-registration.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-resignation.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-update.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/entity-subhandlers/register.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/entity-subhandlers/resign.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/entity-subhandlers/update.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/entity.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/general.test.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/update.ts
  packages/core-magistrate-transactions/src/handlers/index.ts
  packages/core-magistrate-transactions/src/wallet-indexes.ts
Labels: Complexity: High, Test: Unit

#3984 test(core-magistrate-api): incrase test coverage to 100%
  __tests__/unit/core-magistrate-api/resources/entity.test.ts
Labels: Complexity: Low, Test: Unit

#3985 chore(core-state): autoIndex option
  __tests__/unit/core-api/__support__/index.ts
  __tests__/unit/core-magistrate-api/__support__/index.ts
  __tests__/unit/core-magistrate-transactions/__support__/app.ts
  __tests__/unit/core-state/wallets/wallet-index.test.ts
  __tests__/unit/core-state/wallets/wallet-repository.test.ts
  __tests__/unit/core-transactions/handlers/__support__/app.ts
  packages/core-kernel/src/contracts/state/wallets.ts
  packages/core-magistrate-transactions/src/service-provider.ts
  packages/core-state/src/wallets/indexers/wallet-indexes.ts
  packages/core-state/src/wallets/wallet-index.ts
  packages/core-state/src/wallets/wallet-repository.ts
Labels: Complexity: Low, Type: Task

#3986 chore(core-magistrate): more flexible entity types / sub-types + fees update
  __tests__/functional/transaction-forging/entity-register.test.ts
  __tests__/functional/transaction-forging/entity-resign.test.ts
  __tests__/functional/transaction-forging/entity-update.test.ts
  __tests__/integration/core-api/handlers/entities.test.ts
  __tests__/unit/core-magistrate/fixtures/entity/assets/generate.ts
  __tests__/unit/core-magistrate/fixtures/entity/schemas/register.ts
  __tests__/unit/core-magistrate/fixtures/entity/schemas/resign.ts
  __tests__/unit/core-magistrate/fixtures/entity/schemas/update.ts
  __tests__/unit/core-magistrate/handlers/__fixtures__/entity/register.ts
  __tests__/unit/core-magistrate/handlers/__fixtures__/entity/resign.ts
  __tests__/unit/core-magistrate/handlers/__fixtures__/entity/update.ts
  __tests__/unit/core-magistrate/handlers/entity.test.ts
  packages/core-magistrate-crypto/src/enums.ts
  packages/core-magistrate-crypto/src/interfaces.ts
  packages/core-magistrate-crypto/src/transactions/entity.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/business/index.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/business/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/business/resign.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/business/update.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/errors.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/index.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/resign.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/delegate/update.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/developer/index.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/developer/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/developer/resign.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/developer/update.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/index.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/plugin-core/index.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/plugin-core/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/plugin-core/resign.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/plugin-core/update.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/plugin-desktop/index.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/plugin-desktop/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/plugin-desktop/resign.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/plugin-desktop/update.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
  packages/core-magistrate-transactions/src/interfaces.ts
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Complexity: High, Status: Needs Review, Type: Task

#3987 chore(core-state): export state-builder
  packages/core-state/src/index.ts
Labels: Complexity: Low, Type: Task

#3983 test(core-magistrate-crypto): increase test coverage to 100%
  __tests__/unit/core-magistrate-crypto/builders/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate-crypto/builders/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate-crypto/builders/bridgechain-update.test.ts
  __tests__/unit/core-magistrate-crypto/builders/business-registration.test.ts
  __tests__/unit/core-magistrate-crypto/builders/business-resignation.test.ts
  __tests__/unit/core-magistrate-crypto/builders/business-update.test.ts
  __tests__/unit/core-magistrate-crypto/builders/enity.test.ts
  __tests__/unit/core-magistrate-crypto/fixtures/entity/assets/generate.ts
  __tests__/unit/core-magistrate-crypto/helper.ts
  __tests__/unit/core-magistrate-crypto/transactions/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate-crypto/transactions/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate-crypto/transactions/bridgechain-update.test.ts
  __tests__/unit/core-magistrate-crypto/transactions/business-registration.test.ts
  __tests__/unit/core-magistrate-crypto/transactions/business-update.test.ts
  __tests__/unit/core-magistrate-crypto/transactions/entity.test.ts
Labels: Complexity: High, Test: Unit
