Repository ArkEcosystem/core, pull requests merged in 2020-03, with the labels that each got.

#3560 refactor(core-transaction-pool): no default addonBytes for magistrate transactions
  packages/core-transaction-pool/src/defaults.ts
Labels: Complexity: Low, Type: Refactor

#3541 perf(core): use jemalloc as the memory allocator
  install.sh
  packages/core/bin/run
Labels: Bounty: Tier 1, Complexity: Low, Status: Collaborator Approved, Type: Performance

#3561 fix(core-blockchain): set height 1 on config manager for processing genesis block (blockchain replay)
  packages/core-blockchain/src/replay/replay-blockchain.ts
Labels: Complexity: Low, Type: Bugfix

#3562 fix(core): handle multiple installations of jemalloc
  packages/core/bin/run
Labels: Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3563 refactor(core-state): merge index and reindex into one function inside WalletRepository
  __tests__/functional/transaction-forging/delegate-resignation.test.ts
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-api/handlers/delegates.test.ts
  __tests__/integration/core-api/handlers/locks.test.ts
  __tests__/integration/core-api/handlers/wallets.test.ts
  __tests__/unit/core-transactions/handlers/one/multi-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/delegate-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/delegate-resignation.test.ts
  __tests__/unit/core-transactions/handlers/two/general.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-claim.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-lock.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-refund.test.ts
  __tests__/unit/core-transactions/handlers/two/ipfs.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-payment.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/second-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/transfer.test.ts
  __tests__/unit/core-transactions/handlers/two/vote.test.ts
  packages/core-kernel/src/contracts/state/wallets.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-state/src/block-state.ts
  packages/core-state/src/wallets/wallet-repository-clone.ts
  packages/core-state/src/wallets/wallet-repository-copy-on-write.ts
  packages/core-state/src/wallets/wallet-repository.ts
  packages/core-transactions/src/handlers/one/delegate-registration.ts
  packages/core-transactions/src/handlers/one/multi-signature-registration.ts
  packages/core-transactions/src/handlers/two/delegate-registration.ts
  packages/core-transactions/src/handlers/two/delegate-resignation.ts
  packages/core-transactions/src/handlers/two/htlc-claim.ts
  packages/core-transactions/src/handlers/two/htlc-lock.ts
  packages/core-transactions/src/handlers/two/htlc-refund.ts
  packages/core-transactions/src/handlers/two/ipfs.ts
  packages/core-transactions/src/handlers/two/multi-signature-registration.ts
Labels: Complexity: Medium, Test: Unit

#3564 test(core-magistrate-transactions): increase coverage to 100%
  __tests__/unit/core-magistrate-transactions/__mocks__/block-repository.ts
  __tests__/unit/core-magistrate-transactions/__mocks__/transaction-repository.ts
  __tests__/unit/core-magistrate-transactions/__support__/app.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-update.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-registration.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-resignation.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-update.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/general.test.ts
  __tests__/unit/core-magistrate-transactions/service-provider.test.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/wallet-indexes.ts
Labels: Complexity: Undetermined

#3567 fix(core): jemalloc compatibility for ubuntu 16.04
  packages/core/bin/run
Labels: Bounty: Tier 5, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3570 fix(core-transaction-pool): always call applyToRecipient
  __tests__/functional/multipayment-applyToRecipient/__support__/index.ts
  __tests__/functional/multipayment-applyToRecipient/multipayment.test.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: High, Type: Bugfix

#3575 chore(deps): update xstate to v4.8.0
  packages/core-blockchain/package.json
  yarn.lock
Labels: Bounty: Tier 6, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3574 refactor: use application events from core-event-emitter
  packages/core-container/package.json
  packages/core-container/src/container.ts
  packages/core-event-emitter/src/index.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-snapshots/package.json
  packages/core-snapshots/src/transport/index.ts
  packages/core-state/package.json
  packages/core-state/src/stores/state.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transactions/src/handlers/vote.ts
  packages/core/src/commands/snapshot/restore.ts
Labels: Complexity: Low, Type: Refactor

#3573 fix(core-database-postgres): add missing transactions.type_group index
  packages/core-database-postgres/src/migrations/20200304000000-add-type_group-index-to-transactions-table.sql
Labels: Complexity: Low, Type: Bugfix

#3576 ci: setup auto publishing for master releases
  .github/workflows/publish-master.yml
Labels: Complexity: Low

#3577 chore: remove app.js from .gitignore
  .gitignore
Labels: Complexity: Low, Type: Task

#3578 test: fix github environment variable setup
  .github/workflows/test.yml
Labels: Complexity: Low, Test: Unit

#3579 chore: remove core-utils package
  packages/core-kernel/src/utils/expiration-calculator.ts
  packages/core-utils/src/lock-expiration-calculator.ts
Labels: Complexity: Low, Type: Task

#3580 test(core-logger-pino): increase coverage to 100%
  __tests__/unit/core-logger-pino/service-provider.test.ts
  __tests__/unit/core-transactions/service-provider.test.ts
  jest.config.js
  packages/core-logger-pino/src/driver.ts
Labels: Complexity: Low, Test: Unit

#3581 test(core-p2p): disable coverage collection until overhaul
  jest.config.js
Labels: Complexity: Low, Test: Unit

#3582 test(crypto): disable coverage collection until overhaul
  jest.config.js
Labels: Complexity: Low, Test: Unit

#3584 test(core-magistrate-api): increase coverage to 100%
  __tests__/unit/core-magistrate-api/__fixtures__/assets.ts
  __tests__/unit/core-magistrate-api/__fixtures__/index.ts
  __tests__/unit/core-magistrate-api/__support__/index.ts
  __tests__/unit/core-magistrate-api/controllers/bridgechains.test.ts
  __tests__/unit/core-magistrate-api/controllers/businesses.test.ts
  __tests__/unit/core-magistrate-api/resources/bridgechain.test.ts
  __tests__/unit/core-magistrate-api/resources/businesses.test.ts
  __tests__/unit/core-magistrate-api/service-provider.test.ts
Labels: Complexity: High

#3566 test(core-magistrate-crypto): increase coverage to 100%
  __tests__/unit/core-magistrate-crypto/helper.ts
  __tests__/unit/core-magistrate-crypto/transactions/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate-crypto/transactions/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate-crypto/transactions/bridgechain-update.test.ts
  __tests__/unit/core-magistrate-crypto/transactions/business-registration.test.ts
  __tests__/unit/core-magistrate-crypto/transactions/business-resgination.test.ts
  __tests__/unit/core-magistrate-crypto/transactions/business-update.test.ts
Labels: Complexity: Medium, Test: Unit

#3589 ci: use v2 for github actions checkout
  .github/workflows/benchmark.yml
  .github/workflows/functional.yml
  .github/workflows/test.yml
Labels: Complexity: Low, Type: Task

#3590 fix(core-blockchain): AcceptBlockHandler apply block to tx pool before db
  .github/workflows/functional.yml
  __tests__/functional/multipayment-applyToRecipient/multipayment.test.ts
  __tests__/functional/pool/__support__/index.ts
  __tests__/functional/pool/pool.test.ts
  __tests__/unit/core-blockchain/mocks/transactionPool.ts
  __tests__/unit/core-transaction-pool/__stubs__/connection.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-interfaces/src/core-transaction-pool/connection.ts
  packages/core-jest-matchers/src/functional/index.ts
  packages/core-jest-matchers/src/functional/unconfirmed.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: High, Type: Bugfix

#3585 chore(core-magistrate-transactions): fix bride -> bridge typo
  __tests__/unit/core-magistrate/handlers/business-resignation.test.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
Labels: Bounty: Tier 6, Complexity: Low, Type: Task

#3543 test(core-state): increase coverage to 100%
  __tests__/unit/core-magistrate-api/__support__/index.ts
  __tests__/unit/core-magistrate-api/controllers/businesses.test.ts
  __tests__/unit/core-magistrate-transactions/__support__/app.ts
  __tests__/unit/core-state/__utils__/build-delegate-and-vote-balances.ts
  __tests__/unit/core-state/__utils__/compact.ts
  __tests__/unit/core-state/__utils__/fixture-generator.ts
  __tests__/unit/core-state/__utils__/make-chained-block.ts
  __tests__/unit/core-state/__utils__/make-vote-transactions.ts
  __tests__/unit/core-state/__utils__/transactions.ts
  __tests__/unit/core-state/__utils__/unique.ts
  __tests__/unit/core-state/block-state.test.ts
  __tests__/unit/core-state/dpos/dpos-previous-round.test.ts
  __tests__/unit/core-state/dpos/dpos.test.ts
  __tests__/unit/core-state/service-provider.test.ts
  __tests__/unit/core-state/setup.ts
  __tests__/unit/core-state/state-builder.test.ts
  __tests__/unit/core-state/stores/blocks.test.ts
  __tests__/unit/core-state/stores/state.test.ts
  __tests__/unit/core-state/stores/transactions.test.ts
  __tests__/unit/core-state/transaction-validator.test.ts
  __tests__/unit/core-state/wallets/errors.test.ts
  __tests__/unit/core-state/wallets/utils/filter-rows.test.ts
  __tests__/unit/core-state/wallets/utils/limit-rows.test.ts
  __tests__/unit/core-state/wallets/utils/mock-database-model.ts
  __tests__/unit/core-state/wallets/utils/search-entires.test.ts
  __tests__/unit/core-state/wallets/utils/search-entries.test.ts
  __tests__/unit/core-state/wallets/utils/search-parameter-converter.test.ts
  __tests__/unit/core-state/wallets/utils/sort-entries.test.ts
  __tests__/unit/core-state/wallets/wallet-index.test.ts
  __tests__/unit/core-state/wallets/wallet-repository-clone.test.ts
  __tests__/unit/core-state/wallets/wallet-repository-copy-on-write.test.ts
  __tests__/unit/core-state/wallets/wallet-repository.test.ts
  __tests__/unit/core-state/wallets/wallet.test.ts
  __tests__/unit/core-transactions/handlers/__support__/app.ts
  __tests__/unit/core-transactions/handlers/two/ipfs.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-payment.test.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-kernel/src/contracts/state/wallets.ts
  packages/core-magistrate-api/src/controllers/businesses.ts
  packages/core-magistrate-crypto/package.json
  packages/core-state/src/block-state.ts
  packages/core-state/src/dpos/dpos.ts
  packages/core-state/src/service-provider.ts
  packages/core-state/src/state-builder.ts
  packages/core-state/src/stores/blocks.ts
  packages/core-state/src/wallets/indexers/index.ts
  packages/core-state/src/wallets/indexers/indexers.ts
  packages/core-state/src/wallets/indexers/wallet-indexes.ts
  packages/core-state/src/wallets/utils/filter-rows.ts
  packages/core-state/src/wallets/utils/get-property.ts
  packages/core-state/src/wallets/utils/limit-rows.ts
  packages/core-state/src/wallets/utils/search-entries.ts
  packages/core-state/src/wallets/utils/search-parameter-converter.ts
  packages/core-state/src/wallets/utils/sort-entries.ts
  packages/core-state/src/wallets/wallet-repository.ts
  packages/core-test-framework/src/factories/factories/block.ts
  packages/core-test-framework/src/utils/generic.ts
  packages/core/bin/config/devnet/peers.json
  packages/crypto/src/networks/testnet/milestones.json
Labels: Complexity: Undetermined, Test: Unit

#3594 fix(core-transaction-pool): always apply to sender wallet on acceptChainedBlock
  __tests__/integration/core-transaction-pool/processor.test.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3593 test(core-kernel): increase coverage to 100%
  __tests__/unit/core-kernel/__stubs__/config-empty/.gitkeep
  __tests__/unit/core-kernel/__stubs__/config-invalid-app/.env
  __tests__/unit/core-kernel/__stubs__/config-invalid-app/app.js
  __tests__/unit/core-kernel/__stubs__/config-invalid-app/delegates.json
  __tests__/unit/core-kernel/__stubs__/config-invalid-app/peers.json
  __tests__/unit/core-kernel/__stubs__/config-invalid-delegates/.env
  __tests__/unit/core-kernel/__stubs__/config-invalid-delegates/app.js
  __tests__/unit/core-kernel/__stubs__/config-invalid-delegates/delegates.json
  __tests__/unit/core-kernel/__stubs__/config-invalid-delegates/peers.json
  __tests__/unit/core-kernel/__stubs__/config-invalid-peers/.env
  __tests__/unit/core-kernel/__stubs__/config-invalid-peers/app.js
  __tests__/unit/core-kernel/__stubs__/config-invalid-peers/delegates.json
  __tests__/unit/core-kernel/__stubs__/config-invalid-peers/peers.json
  __tests__/unit/core-kernel/bootstrap/app/watch-configuration.test.ts
  __tests__/unit/core-kernel/ioc/selectors.test.ts
  __tests__/unit/core-kernel/providers/plugin-configuration.test.ts
  __tests__/unit/core-kernel/providers/plugin-manifest.test.ts
  __tests__/unit/core-kernel/services/cache/drivers/memory.test.ts
  __tests__/unit/core-kernel/services/cache/drivers/null.test.ts
  __tests__/unit/core-kernel/services/config/drivers/local.test.ts
  __tests__/unit/core-kernel/services/events/drivers/null.test.ts
  __tests__/unit/core-kernel/services/filesystem/drivers/null.test.ts
  __tests__/unit/core-kernel/services/log/drivers/null.test.ts
  __tests__/unit/core-kernel/services/log/service-provider.test.ts
  __tests__/unit/core-kernel/services/pipeline/drivers/null.test.ts
  __tests__/unit/core-kernel/services/pipeline/service-provider.test.ts
  __tests__/unit/core-kernel/services/queue/drivers/null.test.ts
  __tests__/unit/core-kernel/services/validation/drivers/joi.test.ts
  __tests__/unit/core-kernel/services/validation/drivers/null.test.ts
  __tests__/unit/core-kernel/support/class-manager.test.ts
  __tests__/unit/core-kernel/support/instance-manager.test.ts
  __tests__/unit/core-kernel/utils/delegate-calculator.test.ts
  __tests__/unit/core-kernel/utils/expiration-calculator.test.ts
  __tests__/unit/core-kernel/utils/is-blocked-chained.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-kernel/src/services/cache/drivers/null.ts
  packages/core-kernel/src/services/config/drivers/local.ts
  packages/core-kernel/src/services/events/drivers/null.ts
  packages/core-kernel/src/services/queue/service-provider.ts
  packages/core-kernel/src/support/class-manager.ts
  packages/core-kernel/src/support/instance-manager.ts
  packages/core-kernel/src/utils/index.ts
  packages/core-kernel/src/utils/is-block-chained.ts
Labels: Complexity: Undetermined, Status: Needs Review, Test: Unit

#3595 ci: set up nightly devnet sync on github
  .github/sync-script/sync-script.sh
  .github/workflows/devnet-sync.yml
Labels: Complexity: Medium, Type: Task

#3596 fix(core-p2p): block incomplete sockets
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Medium, Type: Bugfix

#3598 refactor(core-blockchain): reset missedBlocks before await call
  packages/core-blockchain/src/blockchain.ts
Labels: Complexity: Low, Type: Refactor

#3602 test(core-magistrate-api): increase coverage to 100%
  __tests__/unit/core-magistrate-api/controllers/businesses.test.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
Labels: Complexity: Low

#3601 test(core-api): increase coverage to 100%
  __tests__/unit/core-api/__fixtures__/key.pem
  __tests__/unit/core-api/__fixtures__/server.crt
  __tests__/unit/core-api/__support__/index.ts
  __tests__/unit/core-api/controllers/blockchain.test.ts
  __tests__/unit/core-api/controllers/blocks.test.ts
  __tests__/unit/core-api/controllers/controller.test.ts
  __tests__/unit/core-api/controllers/delegates.test.ts
  __tests__/unit/core-api/controllers/locks.test.ts
  __tests__/unit/core-api/controllers/node.test.ts
  __tests__/unit/core-api/controllers/peers.test.ts
  __tests__/unit/core-api/controllers/rounds.test.ts
  __tests__/unit/core-api/controllers/transactions.test.ts
  __tests__/unit/core-api/controllers/votes.test.ts
  __tests__/unit/core-api/controllers/wallets.test.ts
  __tests__/unit/core-api/mocks/block-repository.ts
  __tests__/unit/core-api/mocks/blockchain.ts
  __tests__/unit/core-api/mocks/index.ts
  __tests__/unit/core-api/mocks/network-monitor.ts
  __tests__/unit/core-api/mocks/peer-storage.ts
  __tests__/unit/core-api/mocks/query.ts
  __tests__/unit/core-api/mocks/round-repository.ts
  __tests__/unit/core-api/mocks/service-provider-repository.ts
  __tests__/unit/core-api/mocks/state-store.ts
  __tests__/unit/core-api/mocks/transaction-pool-processor.ts
  __tests__/unit/core-api/mocks/transaction-repository.ts
  __tests__/unit/core-api/plugins/__support__/index.ts
  __tests__/unit/core-api/plugins/cache.test.ts
  __tests__/unit/core-api/plugins/hapi-ajv.test.ts
  __tests__/unit/core-api/plugins/pagination.test.ts
  __tests__/unit/core-api/plugins/rate-limit.test.ts
  __tests__/unit/core-api/plugins/whitelist.test.ts
  __tests__/unit/core-api/resources/delegates.test.ts
  __tests__/unit/core-api/resources/fee-statistics.test.ts
  __tests__/unit/core-api/resources/lock.test.ts
  __tests__/unit/core-api/resources/peer.test.ts
  __tests__/unit/core-api/resources/ports.test.ts
  __tests__/unit/core-api/resources/round.test.ts
  __tests__/unit/core-api/resources/transaction.test.ts
  __tests__/unit/core-api/resources/wallet.test.ts
  __tests__/unit/core-api/server.test.ts
  __tests__/unit/core-api/service-provider.test.ts
  packages/core-api/src/controllers/controller.ts
  packages/core-api/src/controllers/node.ts
  packages/core-api/src/controllers/wallets.ts
  packages/core-api/src/handlers/shared/schemas/address.ts
  packages/core-api/src/handlers/shared/schemas/block-id.ts
  packages/core-api/src/handlers/shared/schemas/generic-name.ts
  packages/core-api/src/handlers/shared/schemas/index.ts
  packages/core-api/src/handlers/shared/schemas/public-key.ts
  packages/core-api/src/handlers/shared/schemas/username.ts
  packages/core-api/src/handlers/shared/schemas/wallet-id.ts
  packages/core-api/src/plugins/cache.ts
  packages/core-api/src/plugins/hapi-ajv.ts
  packages/core-api/src/plugins/index.ts
  packages/core-api/src/plugins/pagination/decorate.ts
  packages/core-api/src/plugins/pagination/ext.ts
  packages/core-api/src/plugins/pagination/index.ts
  packages/core-api/src/plugins/set-headers.ts
  packages/core-api/src/server.ts
  yarn.lock
Labels: Complexity: Undetermined

#3603 test(core-webhooks): increase coverage to 100%
  __tests__/unit/core-webhooks/__fixtures__/assets.ts
  __tests__/unit/core-webhooks/conditions.test.ts
  __tests__/unit/core-webhooks/database.test.ts
  __tests__/unit/core-webhooks/listener.test.ts
  __tests__/unit/core-webhooks/server/__support__/index.ts
  __tests__/unit/core-webhooks/server/plugins/whitelist.test.ts
  __tests__/unit/core-webhooks/server/server.test.ts
  __tests__/unit/core-webhooks/service-provider.test.ts
  packages/core-webhooks/src/database.ts
  packages/core-webhooks/src/server/plugins/trailing-slash.ts
Labels: Complexity: High

#3605 perf: database optimization
  .github/workflows/functional.yml
  __tests__/integration/core-api/handlers/blocks.test.ts
  packages/core-api/src/defaults.ts
  packages/core-api/src/handlers/blocks/schema.ts
  packages/core-api/src/handlers/shared/iteratees.ts
  packages/core-database-postgres/src/migrations/20200317000000-add-blocks-and-transactions-indexes.sql
Labels: Complexity: Medium, Type: Performance

#3607 test(core-forger): increase coverage to 100%
  __tests__/unit/core-forger/__utils__/calculate-active-delegates.ts
  __tests__/unit/core-forger/__utils__/create-block-with-transactions.ts
  __tests__/unit/core-forger/client.test.ts
  __tests__/unit/core-forger/delegate-factory.test.ts
  __tests__/unit/core-forger/delegate-tracker.test.ts
  __tests__/unit/core-forger/errors.test.ts
  __tests__/unit/core-forger/forger-service.test.ts
  __tests__/unit/core-forger/methods/bip38.test.ts
  __tests__/unit/core-forger/methods/bip39.test.ts
  __tests__/unit/core-forger/service-provider.test.ts
  __tests__/unit/core-forger/setup.ts
Labels: Complexity: Undetermined, Test: Unit

#3611 fix(core-forger): log warning when active delegates are under the required delegate count
  __tests__/unit/core-forger/delegate-tracker.test.ts
  __tests__/unit/core-forger/setup.ts
  packages/core-forger/src/delegate-tracker.ts
Labels: Complexity: Low, Type: Bugfix

#3604 test(core-blockchain): increase coverage to 100%
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/core-blockchain/processor/handlers/accept-block-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/already-forged-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/exception-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/incompatible-transactions-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/invalid-generator-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/nonce-out-of-order-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/verification-failed-handler.test.ts
  __tests__/unit/core-blockchain/service-provider.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/blockchain-ready.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/check-last-block-synced.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/check-last-downloaded-block-synced.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/check-later.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/download-blocks.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/download-finished.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/download-paused.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/exit-app.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/initialize.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/rollback-database.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/start-fork-recovery.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/stopped.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/syncing-complete.test.ts
  __tests__/unit/core-blockchain/state-machine/state-machine.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/handlers/incompatible-transactions-handler.ts
  packages/core-blockchain/src/processor/handlers/nonce-out-of-order-handler.ts
Labels: Complexity: Undetermined, Status: Needs Review, Test: Unit

#3612 fix(core-test-framework): change import scope from @package to @arkecosystem
  packages/core-test-framework/src/factories/factories/wallet.ts
Labels: Bounty: Tier 5, Complexity: Low, Type: Bugfix

#3614 fix(core-blockchain): allow transition to fork from idle
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/machines/blockchain.ts
Labels: Complexity: Low, Type: Bugfix

#3619 fix: blockchain and p2p fixes to be able to launch a network
  .github/workflows/lint-test-benchmark.yml
  __tests__/e2e/README.md
  __tests__/e2e/img/core-e2e-banner.png
  __tests__/e2e/lib/config/docker-compose.yml
  __tests__/e2e/lib/config/nginx/nginx.conf
  __tests__/e2e/lib/config/nodes/Dockerfile
  __tests__/e2e/lib/config/nodes/core0/.env
  __tests__/e2e/lib/config/nodes/core0/app.json
  __tests__/e2e/lib/config/nodes/core0/delegates.json
  __tests__/e2e/lib/config/nodes/core0/peers.json
  __tests__/e2e/lib/config/nodes/core1/.env
  __tests__/e2e/lib/config/nodes/core1/app.json
  __tests__/e2e/lib/config/nodes/core1/delegates.json
  __tests__/e2e/lib/config/nodes/core1/peers.json
  __tests__/e2e/lib/config/nodes/core2/.env
  __tests__/e2e/lib/config/nodes/core2/app.json
  __tests__/e2e/lib/config/nodes/core2/delegates.json
  __tests__/e2e/lib/config/nodes/core2/peers.json
  __tests__/e2e/lib/config/nodes/core3/.env
  __tests__/e2e/lib/config/nodes/core3/app.json
  __tests__/e2e/lib/config/nodes/core3/delegates.json
  __tests__/e2e/lib/config/nodes/core3/peers.json
  __tests__/e2e/lib/config/nodes/core4/.env
  __tests__/e2e/lib/config/nodes/core4/app.json
  __tests__/e2e/lib/config/nodes/core4/delegates.json
  __tests__/e2e/lib/config/nodes/core4/peers.json
  __tests__/e2e/lib/config/peer-discovery/Dockerfile
  __tests__/e2e/lib/config/peer-discovery/index.js
  __tests__/e2e/lib/config/peer-discovery/package.json
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-kernel/src/contracts/blockchain/blockchain.ts
  packages/core-kernel/src/contracts/p2p/peer-connector.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/schemas.ts
Labels: Complexity: High, Type: Bugfix

#3631 fix(core): add check in config-cli command to check whether the token flag has been set
  __tests__/unit/core/commands/config-cli.test.ts
  packages/core-test-framework/src/cli/console.ts
  packages/core/src/commands/config-cli.ts
Labels: Complexity: Low, Type: Bugfix
