Repository ArkEcosystem/core, pull requests merged in 2020-10, with the labels that each got.

#4070 refactor: remove import from dist or src
  packages/core-blockchain/src/actions/process-block.ts
  packages/core-forger/src/actions/forge-new-block.ts
  packages/core-forger/src/actions/is-forging-allowed.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/update.ts
  packages/core-p2p/src/actions/validate-and-accept-peer.ts
  packages/core-p2p/src/index.ts
  packages/core-snapshots/src/contracts/database.ts
  packages/core-snapshots/src/contracts/stream.ts
  packages/core-snapshots/src/workers/actions/test-worker-action.ts
  packages/core-state/src/actions/build-delegate-ranking.ts
  packages/core-state/src/actions/get-active-delegates.ts
  packages/core-test-framework/src/matchers/functional/entity.ts
  packages/core-test-framework/src/mocks/block-repository.ts
  packages/core-test-framework/src/mocks/blockchain.ts
  packages/core-test-framework/src/mocks/network-monitor.ts
  packages/core-test-framework/src/mocks/peer-storage.ts
  packages/core-test-framework/src/mocks/query.ts
  packages/core-test-framework/src/mocks/round-repository.ts
  packages/core-test-framework/src/mocks/state-store.ts
  packages/core-test-framework/src/mocks/transaction-repository.ts
  packages/core-test-framework/src/mocks/wallet-respository.ts
  packages/core-test-framework/src/utils/api.ts
  packages/core-transaction-pool/src/actions/apply-transaction.ts
  packages/core-transaction-pool/src/actions/revert-transaction.ts
  packages/core-transaction-pool/src/actions/throw-if-cannot-enter-pool.ts
  packages/core-transaction-pool/src/actions/verify-transaction.ts
Labels: Complexity: Medium, Type: Refactor

#4073 release: 3.0.0-alpha.12
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Type: Release

#4074 chore: force typeorm version 0.2.25
  packages/core-database/package.json
  packages/core-manager/package.json
  packages/core-snapshots/package.json
Labels: Complexity: Low, Type: Task

#4075 release: 3.0.0-alpha.13
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Type: Release

#4077 feat(core-kernel): implement `Queue#isRunning/isStarted/onDrain/onError/onData` methods
  __tests__/unit/core-kernel/services/queue/drivers/memory.test.ts
  __tests__/unit/core-kernel/services/queue/drivers/null.test.ts
  __tests__/unit/core-kernel/services/queue/service-provider.test.ts
  packages/core-kernel/src/contracts/kernel/queue.ts
  packages/core-kernel/src/enums/events.ts
  packages/core-kernel/src/services/queue/drivers/memory.ts
  packages/core-kernel/src/services/queue/drivers/null.ts
  yarn.lock
Labels: Complexity: High

#4079 chore(core-api): allow array query parameter in all schemas
  __tests__/integration/core-api/handlers/delegates.test.ts
  __tests__/integration/core-api/handlers/wallets.test.ts
  __tests__/unit/core-magistrate-api/controllers/entities.test.ts
  packages/core-api/src/resources-new/delegate.ts
  packages/core-api/src/resources-new/lock.ts
  packages/core-api/src/resources-new/wallet.ts
  packages/core-api/src/routes/delegates.ts
  packages/core-api/src/routes/locks.ts
  packages/core-api/src/routes/wallets.ts
  packages/core-api/src/schemas.ts
  packages/core-magistrate-api/src/controllers/entities.ts
  packages/core-magistrate-api/src/resources/entity.ts
  packages/core-magistrate-api/src/routes/entities.ts
Labels: Complexity: Medium, Type: Task

#4076 refactor(core-state): fire wallet events
  __tests__/integration/core-api/services/__support__/setup.ts
  __tests__/integration/core-magistrate-api/services/__support__/setup.ts
  __tests__/unit/core-manager/service-provider.test.ts
  __tests__/unit/core-manager/watcher-wallet.test.ts
  __tests__/unit/core-state/setup.ts
  __tests__/unit/core-state/wallets/wallet-repository-copy-on-write.test.ts
  __tests__/unit/core-state/wallets/wallet.test.ts
  packages/core-kernel/src/services/attributes/attribute-map.ts
  packages/core-manager/src/service-provider.ts
  packages/core-manager/src/watcher-wallet.ts
  packages/core-state/src/service-provider.ts
  packages/core-state/src/wallets/index.ts
  packages/core-state/src/wallets/indexers/wallet-indexes.ts
  packages/core-state/src/wallets/wallet-event.ts
  packages/core-state/src/wallets/wallet-factory.ts
  packages/core-state/src/wallets/wallet.ts
  packages/core-state/src/wallets/watcher-wallet.ts
Labels: Complexity: High, Type: Refactor

#4081 docs: 3.0 changelog
  CHANGELOG.md
Labels: Complexity: High

#4083 release: 3.0.0-next.0
  .github/workflows/publish-develop.yml
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: release

#4084 chore(core): remove `@arkecosystem/core-manager` from default configs
  packages/core/bin/config/devnet/app.json
  packages/core/bin/config/mainnet/app.json
  packages/core/bin/config/testnet/app.json
Labels: low

#4085 release: 3.0.0-next.1
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: medium, release

#4082 syntax(core-cli): latest version instead of current in updater output
  packages/core-cli/src/services/updater.ts
Labels: Complexity: Low

#4086 fix(core-state): don't throw forgetting undefined attribute
  packages/core-kernel/src/services/attributes/attribute-map.ts
  packages/core-state/src/wallets/wallet.ts
Labels: bugfix, low

#4087 release: 3.0.0-next.2
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: medium, release

#4097 fix(core-transactions): fix unvote+vote bootstrap
  packages/core-transactions/src/handlers/two/vote.ts
Labels: Complexity: Low, bugfix, needsReview

#4100 fix(core-transaction-pool): don't spam dynamic fee messages
  __tests__/unit/core-transaction-pool/processor.test.ts
  __tests__/unit/core-transaction-pool/service.test.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transaction-pool/src/service.ts
Labels: Complexity: Medium, bugfix, needsReview

#4098 fix(core-api): fix block returned by api by either id or height
  packages/core-api/src/controllers/blocks.ts
Labels: Complexity: Low, bugfix

#4099 fix(core-state): update vote balance for each asset vote
  packages/core-state/src/block-state.ts
Labels: Complexity: Low, bugfix, needsReview

#4101 release: 3.0.0-next.3
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, release

#4102 release: 3.0.0-next.4
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Type: Release

#4110 chore(core-p2p): define default p2p timeouts
  packages/core-p2p/src/peer-connector.ts
Labels: Complexity: Low, Type: Task

#4109 fix(core-p2p): respond with error when blockchain is not ready
  __tests__/unit/core-p2p/socket-server/plugins/is-app-ready.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-kernel/src/contracts/blockchain/blockchain.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/socket-server/plugins/is-app-ready.ts
  packages/core-p2p/src/socket-server/server.ts
Labels: Complexity: Medium, Type: Bugfix

#4111 fix(core-blockchain): run state builder after database integrity
  __tests__/unit/core-blockchain/state-machine/actions/initialize.test.ts
  packages/core-blockchain/src/state-machine/actions/initialize.ts
  packages/core-kernel/src/contracts/state/index.ts
  packages/core-kernel/src/contracts/state/state-builder.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-state/src/service-provider.ts
Labels: Complexity: Low, Type: Bugfix

#4116 chore: update banner
  banner.png
Labels: Complexity: Low

#4117 chore: update install script for setting env
  install.sh
Labels: Complexity: Low, Type: Task

#4118 fix(core-blockchain): fork recovery
  __tests__/unit/core-blockchain/blockchain.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-state/src/database-interactions.ts
  packages/core-state/src/service-provider.ts
Labels: Complexity: Low, Type: Bugfix

#4121 fix(core-p2p): strict greater than
  packages/core-p2p/src/socket-server/versions/peer.ts
Labels: Complexity: Low, Type: Bugfix

#4119 fix(core-transaction-pool): do not await tx broadcast in processor
  __tests__/unit/core-transaction-pool/processor.test.ts
  packages/core-transaction-pool/src/processor.ts
Labels: Complexity: Low, Type: Bugfix

#4122 release: 3.0.0-next.5
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Type: Release

#4125 chore(core-kernel): implement trigger unbind and rebind methods
  __tests__/unit/core-kernel/services/triggers/triggers.test.ts
  packages/core-kernel/src/services/triggers/triggers.ts
Labels: Complexity: Medium, Type: Task

#4108 feat(core-state): sync wallet to database
  __tests__/unit/core-blockchain/state-machine/actions/initialize.test.ts
  __tests__/unit/core-kernel/application.test.ts
  __tests__/unit/core-state/service-provider.test.ts
  __tests__/unit/core-transaction-pool/service-provider.test.ts
  __tests__/unit/core-webhooks/server/__support__/index.ts
  __tests__/unit/core-webhooks/service-provider.test.ts
  packages/core-database/src/migrations/20201013000000-create-wallets-table.ts
  packages/core-database/src/service-provider.ts
  packages/core-database/src/wallets-table-service.ts
  packages/core-kernel/src/application.ts
  packages/core-kernel/src/contracts/database/index.ts
  packages/core-kernel/src/contracts/database/wallets-table-service.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-state/src/defaults.ts
  packages/core-state/src/service-provider.ts
  packages/core-state/src/wallets/wallet-sync-service.ts
  packages/core-state/src/wallets/watcher-wallet.ts
  packages/core-transaction-pool/src/service-provider.ts
  packages/core-transaction-pool/src/service.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#4127 feat(core-state): enable wallet sync though environment variable
  packages/core-state/src/defaults.ts
Labels: Complexity: Low

#4129 fix(core-p2p): clear hapi-nes request on timeout
  __tests__/unit/core-p2p/hapi-nes/client.test.ts
  packages/core-p2p/src/hapi-nes/client.ts
Labels: Complexity: Low, Type: Bugfix

#4130 chore: remove deprecated env variables
  __tests__/e2e/lib/config/nodes/core0/.env
  __tests__/e2e/lib/config/nodes/core1/.env
  __tests__/e2e/lib/config/nodes/core2/.env
  __tests__/e2e/lib/config/nodes/core3/.env
  __tests__/e2e/lib/config/nodes/core4/.env
  docker/production/README.md
  docker/production/devnet/devnet.env
  docker/production/mainnet/mainnet.env
  packages/core/bin/config/devnet/.env
  packages/core/bin/config/mainnet/.env
  packages/core/bin/config/testnet/.env
Labels: Complexity: Low, Type: Task

#4126 fix(core-api): filter asset by original or cast values
  __tests__/unit/core-database/transaction-filter.test.ts
  packages/core-database/src/transaction-filter.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix
