Repository ArkEcosystem/core, pull requests merged in 2020-09, with the labels that each got.

#3995 test(core-magistrate-crypto): additional test cases
  __tests__/unit/core-magistrate-crypto/fixtures/entity/assets/generate.ts
  __tests__/unit/core-magistrate-crypto/transactions/entity.test.ts
Labels: Complexity: Medium, Test: Unit

#3994 fix: replace micromatch with nanomatch
  packages/core-api/package.json
  packages/core-api/src/plugins/rate-limit.ts
  packages/core-kernel/src/services/events/drivers/memory.ts
Labels: Complexity: Low, Type: Bugfix

#3992 test(core-transactions): increase coverage to 100%
  __tests__/unit/core-transactions/handlers/handler-registry.test.ts
  __tests__/unit/core-transactions/handlers/one/delegate-registration.test.ts
  __tests__/unit/core-transactions/handlers/one/multi-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/one/second-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/one/transafer.test.ts
  __tests__/unit/core-transactions/handlers/one/vote.test.ts
  __tests__/unit/core-transactions/handlers/two/delegate-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-claim.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-lock.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-refund.test.ts
  __tests__/unit/core-transactions/handlers/two/ipfs.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-payment.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/second-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/transaction.test.ts
  __tests__/unit/core-transactions/handlers/two/vote.test.ts
  packages/core-transactions/src/handlers/one/delegate-registration.ts
  packages/core-transactions/src/handlers/one/second-signature-registration.ts
  packages/core-transactions/src/handlers/two/htlc-claim.ts
  packages/core-transactions/src/handlers/two/htlc-refund.ts
  packages/core-transactions/src/handlers/two/ipfs.ts
Labels: Complexity: Undetermined, Test: Unit

#3999 chore: include missing dependencies in package.json
  __tests__/unit/core-manager/utils/process-actions.test.ts
  packages/core-cli/package.json
  packages/core-manager/package.json
  packages/core-manager/src/actions/log-log.ts
  packages/core-manager/src/log-service-wrapper.ts
  packages/core-snapshots/package.json
  packages/core-snapshots/src/codecs/json-codec.ts
  packages/core-snapshots/src/contracts/codec.ts
  packages/core-snapshots/src/contracts/database.ts
  packages/core-snapshots/src/contracts/stream.ts
  packages/core-snapshots/src/repositories/block-repository.ts
  packages/core-snapshots/src/workers/actions/test-worker-action.ts
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-test-framework/src/mocks/transaction-pool-processor.ts
  packages/core/package.json
Labels: Complexity: Low

#4003 deps: include missing dependencies
  packages/core-api/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-test-framework/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Medium

#3998 fix(core-state): clone wallet on mempool wallet-repository
  __tests__/unit/core-state/wallets/wallet-index.test.ts
  __tests__/unit/core-state/wallets/wallet-repository-copy-on-write.test.ts
  packages/core-kernel/src/contracts/state/wallets.ts
  packages/core-state/src/wallets/wallet-index.ts
  packages/core-state/src/wallets/wallet-repository-copy-on-write.ts
Labels: Complexity: Medium, Type: Bugfix

#4006 chore(core-test-framework): resolve .env and app.json file path from package name
  packages/core-test-framework/package.json
  packages/core-test-framework/src/app/generators/core.ts
Labels: Complexity: Low, Type: Task

#3996 chore(core-p2p): set maxPayload on ws server
  __tests__/unit/core-p2p/hapi-nes/listener.test.ts
  __tests__/unit/core-p2p/socket-server/server.test.ts
  packages/core-p2p/src/hapi-nes/listener.ts
  packages/core-p2p/src/hapi-nes/plugin.ts
  packages/core-p2p/src/socket-server/server.ts
Labels: Complexity: Low, Type: Task

#4004 test(core-p2p): increase test coverage to 100%
  __tests__/unit/core-p2p/socket-server/routes/blocks.test.ts
  __tests__/unit/core-p2p/socket-server/routes/transactions.test.ts
  __tests__/unit/core-p2p/socket-server/server.test.ts
  __tests__/unit/core-p2p/utils/build-rate-limiter.test.ts
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Medium, Test: Unit

#4007 chore: add exports for bridgechains
  packages/core-kernel/src/services/cache/drivers/index.ts
  packages/core-kernel/src/services/cache/index.ts
  packages/core-kernel/src/services/events/drivers/index.ts
  packages/core-kernel/src/services/events/index.ts
  packages/core-state/src/index.ts
  packages/core-state/src/stores/index.ts
  packages/core-state/src/wallets/index.ts
  packages/core-state/src/wallets/indexers/index.ts
  packages/core-test-framework/src/index.ts
  packages/core-test-framework/src/internal/delegates.ts
  packages/core-test-framework/src/internal/index.ts
  packages/core-transaction-pool/src/index.ts
  packages/core-transactions/src/handlers/index.ts
Labels: Complexity: Low, Type: Task

#4008 fix(magistrate): entity name only unique by type
  __tests__/unit/core-magistrate/handlers/entity.test.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/resign.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/update.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Complexity: High, Type: Bugfix

#4010 test(core-transactions): consider delegate collected fees
  __tests__/functional/transaction-forging/htlc-lock.test.ts
  packages/core-test-framework/src/utils/api.ts
Labels: Complexity: Medium, Test: Unit

#4015 merge: master
  CHANGELOG.md
  packages/core-api/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-jest-matchers/package.json
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Undetermined

#4019 fix(core-api): fix delegate.lastBlock.timestamp property
  packages/core-api/src/services/delegate-search-service.ts
Labels: Complexity: Low, Type: Bugfix

#4017 fix(core-webooks): ignore type errors thrown with lowdb deep methods
  packages/core-webhooks/src/database.ts
Labels: Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#4018 chore(core-state): add indexers export
  packages/core-state/src/wallets/index.ts
Labels: Complexity: Low, Type: Task

#4020 chore(magistrate): activate all entity types + re-allocate entity type enum
  __tests__/functional/transaction-forging/entity-register.test.ts
  __tests__/functional/transaction-forging/entity-resign.test.ts
  __tests__/functional/transaction-forging/entity-update.test.ts
  __tests__/integration/core-api/handlers/entities.test.ts
  __tests__/unit/core-magistrate/fixtures/entity/assets/generate.ts
  __tests__/unit/core-magistrate/fixtures/entity/schemas/register.ts
  __tests__/unit/core-magistrate/fixtures/entity/schemas/resign.ts
  __tests__/unit/core-magistrate/fixtures/entity/schemas/update.ts
  packages/core-magistrate-crypto/src/enums.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
Labels: Complexity: Medium, Type: Task

#4021 test(core-test-framework): increase test coverage to 100%
  __tests__/unit/core-test-framework/app/generators/core.test.ts
  __tests__/unit/core-test-framework/app/sandbox.test.ts
  __tests__/unit/core-test-framework/cli/console.test.ts
  __tests__/unit/core-test-framework/factories/factories/block.test.ts
  __tests__/unit/core-test-framework/factories/factories/identity.test.ts
  __tests__/unit/core-test-framework/factories/factory-builder.test.ts
  __tests__/unit/core-test-framework/internal/signer.test.ts
  __tests__/unit/core-test-framework/matchers/blockchain/dispatch.test.ts
  __tests__/unit/core-test-framework/matchers/functional/entity.test.ts
  __tests__/unit/core-test-framework/matchers/functional/forged.test.ts
  __tests__/unit/core-test-framework/matchers/functional/unconfirmed.test.ts
  __tests__/unit/core-test-framework/matchers/functional/vote-balance.test.ts
  __tests__/unit/core-test-framework/utils/__fixtures__/assets.ts
  __tests__/unit/core-test-framework/utils/api-http-client.test.ts
  __tests__/unit/core-test-framework/utils/api-inject-client.test.ts
  __tests__/unit/core-test-framework/utils/api.test.ts
  __tests__/unit/core-test-framework/utils/transaction-factory.test.ts
  packages/core-magistrate-api/package.json
  packages/core-test-framework/src/app/generators/core.ts
  packages/core-test-framework/src/factories/factories/block.ts
  packages/core-test-framework/src/matchers/functional/rejected.ts
  packages/core-test-framework/src/matchers/functional/unconfirmed.ts
  packages/core-test-framework/src/matchers/functional/vote-balance.ts
  packages/core-test-framework/src/utils/api-http-client.ts
  packages/core-test-framework/src/utils/api-inject-client.ts
  packages/core-test-framework/src/utils/api.ts
  packages/core-test-framework/src/utils/generic.ts
  packages/core-test-framework/src/utils/transaction-factory.ts
  packages/crypto/src/crypto/slots.ts
  packages/crypto/src/utils/index.ts
Labels: Complexity: Undetermined, Test: Unit

#4023 chore(core-kernel): use deepmerge in pluginConfiguration
  packages/core-kernel/package.json
  packages/core-kernel/src/providers/plugin-configuration.ts
  packages/core/bin/config/testnet/app.json
Labels: Complexity: Low, Type: Task

#4009 fix(core-state): wallet repository clone instantiation
  __tests__/unit/core-state/wallets/wallet-index.test.ts
  __tests__/unit/core-state/wallets/wallet-repository-clone.test.ts
  packages/core-kernel/src/contracts/state/wallets.ts
  packages/core-state/src/wallets/wallet-index.ts
  packages/core-state/src/wallets/wallet-repository-clone.ts
  packages/core-state/src/wallets/wallet-repository.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#4024 fix(magistrate): delegate check only needed on entity register
  __tests__/unit/core-magistrate/handlers/entity.test.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
Labels: Complexity: Medium, Type: Bugfix

#4029 chore(core-api): custom entity fees for register/update/resign
  __tests__/integration/core-api/handlers/transactions.test.ts
  packages/core-api/src/handlers/node/controller.ts
  packages/core-api/src/handlers/transactions/controller.ts
Labels: Complexity: Low, Type: Task

#4031 chore(crypto): add devnet exception
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Complexity: Low, Type: Task

#4027 chore(core-state): cloneWallet method in wallet-repository
  packages/core-kernel/src/contracts/state/wallets.ts
  packages/core-state/src/wallets/wallet-repository-clone.ts
  packages/core-state/src/wallets/wallet-repository-copy-on-write.ts
  packages/core-state/src/wallets/wallet-repository.ts
Labels: Complexity: Low, Type: Task

#4041 release: 3.0.0-alpha.10
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Type: Release

#4042 merge: master into 2.7
  CHANGELOG.md
  packages/core-forger/package.json
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/socket-server/utils/validate.ts
Labels: Complexity: Low

#4034 fix: slot, round and forgingInfo calculation for dynamic block times
  __tests__/unit/core-kernel/utils/calculate-forging-info.test.ts
  __tests__/unit/core-kernel/utils/round-calculator/calculate-round.test.ts
  __tests__/unit/crypto/crypto/slots.test.ts
  jest.config.js
  packages/core-kernel/src/utils/calculate-forging-info.ts
  packages/core-kernel/src/utils/round-calculator.ts
  packages/crypto/src/crypto/slots.ts
Labels: Complexity: High, Type: Bugfix

#4045 refactor(core-api): do not bind directly handler to class method to allow extending response
  __tests__/unit/core-p2p/socket-server/controllers/blocks.test.ts
  packages/core-api/src/routes/blockchain.ts
  packages/core-api/src/routes/blocks.ts
  packages/core-api/src/routes/delegates.ts
  packages/core-api/src/routes/locks.ts
  packages/core-api/src/routes/node.ts
  packages/core-api/src/routes/peers.ts
  packages/core-api/src/routes/rounds.ts
  packages/core-api/src/routes/transactions.ts
  packages/core-api/src/routes/votes.ts
  packages/core-api/src/routes/wallets.ts
Labels: Complexity: Medium, Type: Refactor

#4046 fix(core-api): use getRegisteredHandlers() to get all registered handlers in /node/fees controller
  packages/core-api/src/controllers/node.ts
Labels: Complexity: Low, Type: Bugfix

#4044 feat(core-transactions): unvote+vote transaction
  __tests__/unit/core-transactions/handlers/two/vote.test.ts
  packages/core-transactions/src/handlers/one/vote.ts
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#4047 chore(magistrate-api): extend /node/fees and /transactions/fees with entities static fees
  packages/core-magistrate-api/src/service-provider.ts
Labels: Complexity: Low, Type: Task

#4049 test(core): increase test coverage
  packages/core/src/utils/snapshot-progress-renderer.ts
Labels: Complexity: Low, Test: Unit

#4032 test(core-kernel): increase test coverage
  __tests__/unit/core-kernel/bootstrap/service-providers/__stubs__/service-providers.ts
  __tests__/unit/core-kernel/bootstrap/service-providers/register-service-providers.test.ts
  __tests__/unit/core-kernel/ioc/selectors.test.ts
  __tests__/unit/core-kernel/services/events/drivers/memory.test.ts
  __tests__/unit/core-kernel/services/log/drivers/memory.test.ts
  __tests__/unit/core-kernel/services/search/errors.test.ts
  __tests__/unit/core-kernel/services/search/standard-criteria-service.test.ts
  __tests__/unit/core-kernel/support/instance-manager.test.ts
  __tests__/unit/core-kernel/utils/ipc-subprocess.test.ts
  packages/core-kernel/src/bootstrap/service-providers/register-service-providers.ts
  packages/core-kernel/src/services/cache/drivers/memory.ts
  packages/core-kernel/src/services/config/watcher.ts
  packages/core-kernel/src/services/events/drivers/memory.ts
  packages/core-kernel/src/services/log/drivers/memory.ts
  packages/core-kernel/src/services/pipeline/drivers/memory.ts
  packages/core-kernel/src/services/queue/drivers/memory.ts
  packages/core-kernel/src/services/search/standard-criteria-service.ts
  packages/core-kernel/src/services/validation/drivers/joi.ts
  packages/core-kernel/src/utils/ipc-handler.ts
  packages/core-kernel/src/utils/is-block-chained.ts
  packages/core-kernel/src/utils/search.ts
Labels: Complexity: High, Test: Unit

#4051 deps(crypto): update bcrypto
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Medium

#4053 chore(crypto): aip36 milestone for mainnet
  packages/crypto/src/networks/mainnet/milestones.json
Labels: Complexity: Low, Type: Task

#4054 fix(core-p2p): rate limit and peer broadcast
  __tests__/integration/core-p2p/peer-communicator.test.ts
  packages/core-interfaces/src/core-p2p/peer.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
Labels: Complexity: Low, Type: Bugfix

#4052 release: 2.7.0
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: High, Status: Needs Review, Type: Release

#4056 merge: master
  CHANGELOG.md
  packages/core-kernel/src/contracts/p2p/peer.ts
  packages/core-p2p/src/peer.ts
  packages/core-p2p/src/socket-server/controllers/peer.ts
  packages/crypto/src/networks/mainnet/milestones.json
  yarn.lock
Labels: Complexity: Medium

#4055 docs: 3.0 changelog
  CHANGELOG-2.X.md
  CHANGELOG.md
Labels: Complexity: Undetermined

#4065 fix(core-p2p): destroy connection after terminate
  packages/core-p2p/src/peer-connector.ts
Labels: Complexity: Low, Type: Bugfix

#4066 chore: 3.0 docker updates
  docker/production/devnet/docker-compose-build.yml
  docker/production/devnet/docker-compose.yml
  docker/production/entrypoint.sh
  docker/production/mainnet/docker-compose.yml
  scripts/docker/templates/devnet/Dockerfile
  scripts/docker/templates/devnet/docker-compose.yml
  scripts/docker/templates/testnet/Dockerfile
  scripts/docker/templates/testnet/docker-compose.yml
Labels: Complexity: Low

#4067 refactor(core-api): remove search endpoints
  __tests__/integration/core-api/controllers/delegates.test.ts
  __tests__/integration/core-api/controllers/wallets.test.ts
  __tests__/integration/core-api/handlers/blocks.test.ts
  __tests__/integration/core-api/handlers/transactions.test.ts
  __tests__/unit/core-api/controllers/blocks.test.ts
  __tests__/unit/core-api/controllers/locks.test.ts
  __tests__/unit/core-api/controllers/transactions.test.ts
  __tests__/unit/core-api/controllers/wallets.test.ts
  packages/core-api/src/controllers/blocks.ts
  packages/core-api/src/controllers/delegates.ts
  packages/core-api/src/controllers/locks.ts
  packages/core-api/src/controllers/transactions.ts
  packages/core-api/src/controllers/wallets.ts
  packages/core-api/src/resources-new/delegate.ts
  packages/core-api/src/resources-new/lock.ts
  packages/core-api/src/resources-new/wallet.ts
  packages/core-api/src/routes/blocks.ts
  packages/core-api/src/routes/delegates.ts
  packages/core-api/src/routes/locks.ts
  packages/core-api/src/routes/transactions.ts
  packages/core-api/src/routes/wallets.ts
Labels: Complexity: High, Type: Task

#4061 test(core-api): increate test coverage to 100%
  __tests__/unit/core-api/__support__/app.ts
  __tests__/unit/core-api/__support__/index.ts
  __tests__/unit/core-api/__support__/server.ts
  __tests__/unit/core-api/controllers/controller.test.ts
  __tests__/unit/core-api/controllers/delegates.test.ts
  __tests__/unit/core-api/controllers/locks.test.ts
  __tests__/unit/core-api/controllers/transactions.test.ts
  __tests__/unit/core-api/controllers/wallets.test.ts
  __tests__/unit/core-api/plugins/cache.test.ts
  __tests__/unit/core-api/plugins/dot-separated-query.test.ts
  __tests__/unit/core-api/plugins/hapi-ajv.test.ts
  __tests__/unit/core-api/plugins/pagination.test.ts
  __tests__/unit/core-api/plugins/rate-limit.test.ts
  __tests__/unit/core-api/plugins/whitelist.test.ts
  __tests__/unit/core-api/routes/__fixtures__/index.ts
  __tests__/unit/core-api/routes/__fixtures__/results.ts
  __tests__/unit/core-api/routes/__fixtures__/server-defaults.ts
  __tests__/unit/core-api/routes/blockchain.test.ts
  __tests__/unit/core-api/routes/blocks.test.ts
  __tests__/unit/core-api/routes/delegates.test.ts
  __tests__/unit/core-api/routes/locks.test.ts
  __tests__/unit/core-api/routes/node.test.ts
  __tests__/unit/core-api/routes/peers.test.ts
  __tests__/unit/core-api/routes/rounds.test.ts
  __tests__/unit/core-api/routes/transactions.test.ts
  __tests__/unit/core-api/routes/votes.test.ts
  __tests__/unit/core-api/routes/wallets.test.ts
  __tests__/unit/core-api/schemas.test.ts
  __tests__/unit/core-api/server.test.ts
  __tests__/unit/core-api/services/__fixtures__/delegates.ts
  __tests__/unit/core-api/services/__fixtures__/index.ts
  __tests__/unit/core-api/services/__fixtures__/locks.ts
  __tests__/unit/core-api/services/delegate-search-service.test.ts
  __tests__/unit/core-api/services/lock-search-service.test.ts
  __tests__/unit/core-api/services/wallet-search-service.test.ts
  __tests__/unit/core-p2p/peer.test.ts
  packages/core-api/src/controllers/controller.ts
  packages/core-api/src/routes/wallets.ts
Labels: Complexity: Undetermined, Test: Unit

#4057 fix(core-blockchain): block download
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/core-blockchain/processor/handlers/accept-block-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/already-forged-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/exception-handler.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-blockchain/src/processor/handlers/exception-handler.ts
  packages/core-blockchain/src/processor/handlers/invalid-generator-handler.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/processor/handlers/verification-failed-handler.ts
  packages/core-blockchain/src/state-machine/actions/download-blocks.ts
  yarn.lock
Labels: Complexity: Low, Type: Bugfix

#4068 feat(core-api): transform comma query into array to allow OR
  __tests__/unit/core-api/plugins/comma-array-query.test.ts
  packages/core-api/src/plugins/comma-array-query.ts
  packages/core-api/src/plugins/index.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#4069 release: 3.0.0-alpha.11
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Type: Release
