Repository ArkEcosystem/core, pull requests merged in 2020-01, with the labels that each got.

#3372 fix(core-database): allow legacy transaction in getBlocksForRound
  __tests__/unit/crypto/blocks/factory.test.ts
  packages/core-database/src/database-service.ts
Labels: Complexity: Low, Type: Bugfix

#3312 refactor(core-api): wallet transform
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/1.1.check-business-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/2.1.check-business-update.test.js
  __tests__/integration/core-api/handlers/businesses.test.ts
  __tests__/integration/core-api/handlers/wallets.test.ts
  packages/core-api/src/handlers/businesses/methods.ts
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-api/src/handlers/businesses/transformer.ts
  packages/core-api/src/handlers/wallets/transformer.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-interfaces/src/core-state/wallets.ts
  packages/core-state/src/wallets/wallet.ts
Labels: Complexity: Low, Type: Refactor

#3375 feat(core-magistrate): add bridgechain asset repository (bridgechain registration and update)
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/3.1.check-bridgechain-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/4.1.check-bridgechain-update.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/utils.js
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  __tests__/functional/transaction-forging/bridgechain-resignation.test.ts
  __tests__/functional/transaction-forging/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/builders/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/helper.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/wallet.test.ts
  packages/core-magistrate-crypto/src/builders/bridgechain-registration.ts
  packages/core-magistrate-crypto/src/interfaces.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-registration.ts
  packages/core-magistrate-crypto/src/transactions/bridgechain-update.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#3381 refactor(core-api): do not include /api prefix in pagination
  __tests__/integration/core-api/handlers/blocks.test.ts
  __tests__/integration/core-api/handlers/bridgechains.test.ts
  __tests__/integration/core-api/handlers/businesses.test.ts
  __tests__/integration/core-api/handlers/delegates.test.ts
  __tests__/integration/core-api/handlers/locks.test.ts
  __tests__/integration/core-api/handlers/peers.test.ts
  __tests__/integration/core-api/handlers/transactions.test.ts
  __tests__/integration/core-api/handlers/votes.test.ts
  __tests__/integration/core-api/handlers/wallets.test.ts
  packages/core-api/src/plugins/pagination/ext.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#3379 feat(core-api): retrieve business by username, address or public key
  __tests__/integration/core-api/handlers/businesses.test.ts
  packages/core-api/src/handlers/businesses/methods.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
Labels: Complexity: Low, Status: Collaborator Approved, Type: Feature

#3391 fix: relax network interface check for seednode ips
  __tests__/unit/crypto/utils/is-valid-peer.test.ts
  packages/crypto/src/utils/is-valid-peer.ts
  packages/crypto/src/validation/formats.ts
Labels: Complexity: Low, Type: Bugfix

#3404 fix(core-p2p): edge cases handling
  CHANGELOG.md
  packages/core-p2p/src/socket-server/errors.ts
  packages/core-p2p/src/socket-server/utils/validate.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-p2p/src/socket-server/versions/utils.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Medium, Type: Bugfix

#3406 release: 2.5.36
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3409 fix(core-p2p): remove banning when peer opens multiple sockets
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Bugfix

#3410 release: 2.5.37
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3411 release: 2.5.38
  CHANGELOG.md
  lerna.json
  packages/a
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3412 fix(core-p2p): handle p2p edge cases
  __tests__/integration/core-api/handlers/transactions.test.ts
  __tests__/integration/core-p2p/mocks/core-container.ts
  __tests__/integration/core-p2p/socket-server/peer-with-remote-access.test.ts
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/mocks/p2p/network-monitor.ts
  __tests__/unit/core-p2p/mocks/request.ts
  __tests__/unit/core-p2p/socket-server/versions/internal/handlers/rate-limiter.test.ts
  __tests__/unit/core-p2p/socket-server/worker.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
  packages/core-interfaces/src/core-p2p/network-monitor.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/rate-limiter.ts
  packages/core-p2p/src/socket-server/errors.ts
  packages/core-p2p/src/socket-server/utils/validate.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-p2p/src/socket-server/versions/utils.ts
  packages/core-p2p/src/socket-server/worker.ts
  packages/crypto/src/networks/unitnet/milestones.json
Labels: Complexity: High, Type: Bugfix

#3415 refactor(core-p2p): remove unnecessary termination
  packages/core-p2p/src/socket-server/worker.ts
Labels: Bounty: Tier 5, Complexity: Low, Status: Collaborator Approved, Type: Refactor

#3416 feat(core-magistrate): implement dynamic fees
  __tests__/integration/core-magistrate/__support__/setup.ts
  __tests__/integration/core-magistrate/dynamic-fee.test.ts
  __tests__/integration/core-magistrate/fixtures/transaction-pool.ts
  __tests__/integration/core-magistrate/fixtures/transactions.ts
  __tests__/integration/core-magistrate/mocks/core-container.ts
  __tests__/integration/core-magistrate/mocks/database.ts
  __tests__/integration/core-magistrate/mocks/state.ts
  __tests__/integration/core-magistrate/processor.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate/handlers/handlers.test.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/plugins.js
  packages/core/bin/config/testnet/plugins.js
Labels: Complexity: High, Type: Feature

#3418 release: 2.6.0-next.8
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3419 release: 2.6.0-next.9
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
  packages/crypto/src/networks/devnet/milestones.json
Labels: Complexity: High, Type: Release

#3421 chore(crypto): fix typo in `isSupportedTansactionVersion` method name
  packages/crypto/src/transactions/deserializer.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/utils/index.ts
Labels: Complexity: Low, Status: Collaborator Approved, Type: Refactor

#3426 fix(core-blockchain): pass IBlockData to processBlocks instead of IBlock
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-transaction-pool/processor.test.ts
  __tests__/integration/core-transaction-pool/wallet-manager.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/replay/replay-blockchain.ts
  packages/core-interfaces/src/core-blockchain/blockchain.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3430 perf(core-database-postgres): use type index when querying multipayments
  packages/core-database-postgres/src/repositories/transactions.ts
Labels: Complexity: Low, Type: Refactor
