Repository ArkEcosystem/core, pull requests merged in 2020-02, with the labels that each got.

#3435 docs: 2.6.0 changelog
  CHANGELOG.md
Labels: Complexity: Medium, Type: Documentation

#3432 fix(core-tester-cli): set network height on configManager
  __tests__/integration/core-tester-cli/commands/send/delegate-registration.test.ts
  __tests__/integration/core-tester-cli/commands/send/fixtures.ts
  __tests__/integration/core-tester-cli/commands/send/htlc-claim.test.ts
  __tests__/integration/core-tester-cli/commands/send/htlc-lock.test.ts
  __tests__/integration/core-tester-cli/commands/send/htlc-refund.test.ts
  __tests__/integration/core-tester-cli/commands/send/ipfs.test.ts
  __tests__/integration/core-tester-cli/commands/send/multi-payment.test.ts
  __tests__/integration/core-tester-cli/commands/send/multi-signature-registration.test.ts
  __tests__/integration/core-tester-cli/commands/send/second-signature.test.ts
  __tests__/integration/core-tester-cli/commands/send/transfer.test.ts
  __tests__/integration/core-tester-cli/commands/send/vote.test.ts
  packages/core-tester-cli/src/commands/command.ts
Labels: Complexity: Low, Type: Bugfix

#3437 refactor(core-api): re-enable username and 2nd public key as top api attributes
  __tests__/integration/core-api/handlers/wallets.test.ts
  packages/core-api/src/handlers/wallets/transformer.ts
Labels: Complexity: Low, Type: Refactor

#3439 refactor(core-p2p): timeouts for peer socket messages
  packages/core-p2p/src/peer-communicator.ts
Labels: Complexity: Low, Type: Refactor

#3440 fix(core-transactions): apply genesis wallet exception to lastForgedBlocks
  packages/core-transactions/src/handlers/delegate-registration.ts
Labels: Complexity: Low, Type: Bugfix

#3441 release: 2.6.0-next.10
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3454 release: 2.6.0
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3456 chore(core-p2p): merge patch from master
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Task

#3460 chore: update aip11 milestone + update p2p minver defaults
  packages/core-p2p/src/defaults.ts
  packages/crypto/src/networks/mainnet/milestones.json
Labels: Complexity: Low, Type: Task

#3462 test(core-p2p): fix minver unit test
  __tests__/unit/core-p2p/utils/is-valid-version.test.ts
Labels: Complexity: Low, Test: Unit

#3458 chore(exchange-json-rpc): use @arkecosystem/exchange-json-rpc@2.0.0
  packages/core-exchange-json-rpc/package.json
  yarn.lock
Labels: Complexity: Low, Type: Task

#3496 refactor(core-kernel): add symbol for TransactionHandlerProvider
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-transactions/src/handlers/handler-registry.ts
  packages/core-transactions/src/service-provider.ts
Labels: Complexity: Low, Type: Refactor

#3465 feat(core-api): filter peers by version range
  __tests__/integration/core-api/handlers/peers.test.ts
  packages/core-api/src/handlers/peers/controller.ts
Labels: Complexity: Medium, Status: Collaborator Approved, Status: Needs Review, Type: Feature

#3459 feat(core): add flag to skip export of rolled back transactions
  packages/core-snapshots/src/manager.ts
  packages/core/src/commands/snapshot/rollback.ts
Labels: Complexity: Low, Status: Collaborator Approved, Type: Feature

#3498 refactor(core-transactions): use findByPublicKey to set both publickey and address on the multisig wallet
  __tests__/integration/core-transactions/handlers/multi-signature.test.ts
  packages/core-transactions/src/handlers/multi-signature.ts
Labels: Complexity: Low, Type: Refactor

#3500 refactor(core-transaction-pool): storage
  packages/core-kernel/src/contracts/transaction-pool/index.ts
  packages/core-kernel/src/contracts/transaction-pool/storage.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-transaction-pool/src/cleaner.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/index.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/service-provider.ts
  packages/core-transaction-pool/src/storage.ts
  packages/core-transaction-pool/src/synchronizer.ts
Labels: Complexity: High, Type: Refactor

#3489 fix(crypto): multisig legacy allow signatures property
  __tests__/unit/crypto/transactions/schemas.test.ts
  packages/crypto/src/transactions/registry.ts
  packages/crypto/src/transactions/types/schemas.ts
Labels: Complexity: Low, Type: Refactor

#3501 refactor(core-state): wallet repositories
  packages/core-state/src/dpos/dpos-previous-round.ts
  packages/core-state/src/service-provider.ts
  packages/core-state/src/transaction-validator.ts
  packages/core-state/src/wallets/index.ts
  packages/core-state/src/wallets/temp-wallet-repository.ts
  packages/core-state/src/wallets/wallet-repository-clone.ts
  packages/core-state/src/wallets/wallet-repository-copy-on-write.ts
  packages/core-transaction-pool/src/connection.ts
Labels: Complexity: Medium, Type: Refactor

#3507 fix(core-database): check for missed blocks before applying round
  packages/core-database/src/database-service.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3505 chore: remove pm2 from docker
  .nvmrc
  docker/production/Dockerfile
  docker/production/README.md
  docker/production/devnet/devnet.env
  docker/production/devnet/docker-compose-build.yml
  docker/production/devnet/docker-compose.yml
  docker/production/entrypoint.sh
  docker/production/mainnet/docker-compose-build.yml
  docker/production/mainnet/docker-compose.yml
  docker/production/mainnet/mainnet.env
  packages/core-blockchain/package.json
  packages/core-p2p/package.json
  packages/core/package.json
  yarn.lock
Labels: Complexity: Low, Type: Bugfix

#3502 refactor(crypto): remove long dependency
  __tests__/unit/core-transaction-pool/connection.forging.test.ts
  __tests__/unit/core-transactions/handler-registry.test.ts
  __tests__/unit/crypto/transactions/deserializer.test.ts
  packages/crypto/package.json
  packages/crypto/src/blocks/serializer.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/transactions/types/htlc-lock.ts
  packages/crypto/src/transactions/types/multi-payment.ts
  packages/crypto/src/transactions/types/transfer.ts
Labels: Complexity: Low, Type: Refactor

#3514 refactor(core-transaction-pool): processor and errors
  packages/core-api/src/controllers/transactions.ts
  packages/core-kernel/src/contracts/transaction-pool/connection.ts
  packages/core-kernel/src/contracts/transaction-pool/dynamic-fee-matcher.ts
  packages/core-kernel/src/contracts/transaction-pool/errors.ts
  packages/core-kernel/src/contracts/transaction-pool/index.ts
  packages/core-kernel/src/contracts/transaction-pool/processor.ts
  packages/core-kernel/src/contracts/transaction-pool/query.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/dynamic-fee-matcher.ts
  packages/core-transaction-pool/src/errors.ts
  packages/core-transaction-pool/src/interfaces.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transaction-pool/src/query.ts
  packages/core-transaction-pool/src/service-provider.ts
  packages/core-transactions/src/handlers/one/delegate-registration.ts
  packages/core-transactions/src/handlers/one/multi-signature-registration.ts
  packages/core-transactions/src/handlers/one/second-signature-registration.ts
  packages/core-transactions/src/handlers/one/transfer.ts
  packages/core-transactions/src/handlers/one/vote.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/two/delegate-resignation.ts
  packages/core-transactions/src/handlers/two/htlc-claim.ts
  packages/core-transactions/src/handlers/two/htlc-lock.ts
  packages/core-transactions/src/handlers/two/htlc-refund.ts
  packages/core-transactions/src/handlers/two/ipfs.ts
  packages/core-transactions/src/handlers/two/multi-payment.ts
  packages/core-transactions/src/handlers/two/multi-signature-registration.ts
Labels: Complexity: Undetermined

#3510 fix(core): make app.js optional as initially intended
  packages/core/bin/config/testnet/app.js
  packages/core/src/utils.ts
Labels: Complexity: Low, Type: Bugfix

#3515 release: 2.6.9
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3516 refactor(core-p2p): transaction broadcaster
  .eslintrc.json
  __tests__/unit/core-p2p/transaction-broadcaster.test.ts
  __tests__/unit/core-transaction-pool/processor.test.ts
  packages/core-kernel/src/contracts/p2p/index.ts
  packages/core-kernel/src/contracts/p2p/network-monitor.ts
  packages/core-kernel/src/contracts/p2p/transaction-broadcaster.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/service-provider.ts
  packages/core-p2p/src/transaction-broadcaster.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/errors.ts
  packages/core-transaction-pool/src/processor.ts
  tsconfig.eslint.json
Labels: Complexity: Medium, Type: Refactor

#3518 fix(core-p2p): disable permessage-deflate
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/socket-server/index.ts
Labels: Bounty: Tier 1, Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3522 chore: setup Wallaby.js configuration
  wallaby.js
Labels: Complexity: Low

#3504 refactor(core-magistrate): allow multiple ports in bridgechain schema
  .github/workflows/test.yml
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/utils.js
  __tests__/unit/core-magistrate/handlers/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-update.test.ts
  __tests__/unit/core-magistrate/helper.ts
  __tests__/unit/core-magistrate/transactions/bridgechain-registration.test.ts
  packages/core-magistrate-crypto/src/transactions/utils/bridgechain-schemas.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/utils.ts
Labels: Complexity: Low, Type: Refactor

#3524 refactor(magistrate): allow to resign business only when bridgechains are resigned
  __tests__/functional/transaction-forging/bridgechain-registration.test.ts
  __tests__/functional/transaction-forging/business-resignation.test.ts
  __tests__/unit/core-magistrate/handlers/business-resignation.test.ts
  packages/core-magistrate-transactions/src/errors.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
Labels: Complexity: Medium, Type: Refactor

#3523 refactor(core-magistrate): make bridgechain genesis hash only unique per wallet
  __tests__/integration/core-api/handlers/bridgechains.test.ts
  __tests__/integration/core-api/handlers/businesses.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate/handlers/bridgechain-update.test.ts
  packages/core-api/src/handlers/bridgechains/controller.ts
  packages/core-api/src/handlers/bridgechains/methods.ts
  packages/core-api/src/handlers/bridgechains/routes.ts
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-api/src/handlers/businesses/controller.ts
  packages/core-api/src/handlers/businesses/methods.ts
  packages/core-api/src/handlers/businesses/routes.ts
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/plugin.ts
  packages/core-magistrate-transactions/src/wallet-manager.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#3537 fix(core-p2p): only accept valid http path (SC http server)
  __tests__/integration/core-p2p/socket-server/peer.test.ts
  __tests__/unit/core-p2p/socket-server/worker.test.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Medium, Type: Bugfix

#3538 release: 2.6.11
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3540 chore: update readme links
  README.md
Labels: Complexity: Low, Type: Task

#3499 refactor(core-transaction-pool): segregate pools by wallets
  __tests__/unit/core-transaction-pool/collator.test.ts
  __tests__/unit/core-transaction-pool/processor.test.ts
  __tests__/unit/crypto/transactions/transaction.test.ts
  packages/core-api/src/controllers/transactions.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-blockchain/src/state-machine/actions/initialize.ts
  packages/core-forger/src/forger-service.ts
  packages/core-kernel/src/contracts/transaction-pool/connection.ts
  packages/core-kernel/src/contracts/transaction-pool/expiration-service.ts
  packages/core-kernel/src/contracts/transaction-pool/index.ts
  packages/core-kernel/src/contracts/transaction-pool/memory.ts
  packages/core-kernel/src/contracts/transaction-pool/processor.ts
  packages/core-kernel/src/contracts/transaction-pool/query.ts
  packages/core-kernel/src/contracts/transaction-pool/sender-state.ts
  packages/core-kernel/src/contracts/transaction-pool/service.ts
  packages/core-kernel/src/contracts/transaction-pool/storage.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-transaction-pool/src/cleaner.ts
  packages/core-transaction-pool/src/collator.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/dynamic-fee-matcher.ts
  packages/core-transaction-pool/src/expiration-service.ts
  packages/core-transaction-pool/src/index.ts
  packages/core-transaction-pool/src/listeners.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transaction-pool/src/pool-wallet-repository.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transaction-pool/src/query.ts
  packages/core-transaction-pool/src/sender-state.ts
  packages/core-transaction-pool/src/service-provider.ts
  packages/core-transaction-pool/src/service.ts
  packages/core-transaction-pool/src/storage.ts
  packages/core-transaction-pool/src/utils.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/two/delegate-resignation.ts
  packages/crypto/src/transactions/types/transaction.ts
Labels: Complexity: Undetermined, Status: Needs Review

#3531 test(core-p2p): clear mock in transaction broadcaster test
  __tests__/unit/core-p2p/transaction-broadcaster.test.ts
Labels: Complexity: Low, Type: Refactor

#3551 chore(magistrate): add exceptions for business resignation
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/crypto/src/networks/devnet/exceptions.json
Labels: Complexity: Low, Type: Task

#3520 test(core-transactions): increase coverage to 100%
  __tests__/unit/core-transactions/handlers/__fixtures__/htlc-secrets.ts
  __tests__/unit/core-transactions/handlers/__mocks__/block-repository.ts
  __tests__/unit/core-transactions/handlers/__mocks__/transaction-repository.ts
  __tests__/unit/core-transactions/handlers/__support__/app.ts
  __tests__/unit/core-transactions/handlers/handler-registry.test.ts
  __tests__/unit/core-transactions/handlers/one/multi-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/delegate-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/delegate-resignation.test.ts
  __tests__/unit/core-transactions/handlers/two/general.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-claim.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-lock.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-refund.test.ts
  __tests__/unit/core-transactions/handlers/two/ipfs.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-payment.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/second-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/transfer.test.ts
  __tests__/unit/core-transactions/handlers/two/vote.test.ts
  __tests__/unit/core-transactions/service-provider.test.ts
  packages/core-test-framework/src/factories/factories/wallet.ts
  packages/core-test-framework/src/internal/wallet-attributes.ts
  packages/core-transaction-pool/src/index.ts
  packages/core-transactions/src/errors.ts
  packages/core-transactions/src/handlers/one/delegate-registration.ts
  packages/core-transactions/src/handlers/one/multi-signature-registration.ts
  packages/core-transactions/src/handlers/one/second-signature-registration.ts
  packages/core-transactions/src/handlers/one/transfer.ts
  packages/core-transactions/src/handlers/one/vote.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/crypto/src/transactions/builders/transactions/htlc-lock.ts
Labels: Complexity: Undetermined
