Repository ArkEcosystem/core, pull requests merged in 2020-06, with the labels that each got.

#3756 fix(core-database): handle multipayment recipientId during search
  __tests__/unit/core-database/transaction-filter.test.ts
  packages/core-database/src/transaction-filter.ts
Labels: Complexity: Low, Type: Bugfix

#3755 refactor(core-p2p): `getPeerConfig` return plugins information
  __tests__/unit/core-kernel/utils/transform-plugins.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/peer.test.ts
  __tests__/unit/core-p2p/socket-server/utils/get-peer-config.test.ts
  packages/core-kernel/src/utils/index.ts
  packages/core-kernel/src/utils/transform-plugins.ts
  packages/core-p2p/src/socket-server/utils/get-peer-config.ts
Labels: Complexity: High, Type: Refactor

#3754 feat(core-manager): implement events listener and events database
  __tests__/unit/core-manager/action-reader.test.ts
  __tests__/unit/core-manager/database-service.test.ts
  __tests__/unit/core-manager/listener.test.ts
  __tests__/unit/core-manager/service-provider.test.ts
  __tests__/unit/core-snapshots/service-provider.test.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-manager/package.json
  packages/core-manager/src/database-service.ts
  packages/core-manager/src/defaults.ts
  packages/core-manager/src/ioc/identifiers.ts
  packages/core-manager/src/listener.ts
  packages/core-manager/src/service-provider.ts
  packages/core-snapshots/src/service-provider.ts
  packages/core/bin/config/testnet/app.json
Labels: Complexity: High

#3733 fix(core-api): include multipayment in forged amount
  __tests__/functional/core-database/repositories/block-repository.test.ts
  __tests__/functional/core-database/repositories/transaction-repository.test.ts
  __tests__/unit/core-api/controllers/blocks.test.ts
  __tests__/unit/core-api/controllers/controller.test.ts
  __tests__/unit/core-api/controllers/delegates.test.ts
  __tests__/unit/core-database/block-history-service.test.ts
  __tests__/unit/core-database/block-model-converter.test.ts
  __tests__/unit/core-database/transaction-history-service.test.ts
  __tests__/unit/core-database/transaction-model-converter.test.ts
  packages/core-api/src/controllers/blocks.ts
  packages/core-api/src/controllers/delegates.ts
  packages/core-api/src/resources/block-with-transactions.ts
  packages/core-api/src/resources/block.ts
  packages/core-api/src/resources/index.ts
  packages/core-database/src/block-filter.ts
  packages/core-database/src/block-history-service.ts
  packages/core-database/src/block-model-converter.ts
  packages/core-database/src/repositories/abstract-repository.ts
  packages/core-database/src/transaction-filter.ts
  packages/core-database/src/transaction-history-service.ts
  packages/core-database/src/transaction-model-converter.ts
  packages/core-kernel/src/contracts/database/block-filter.ts
  packages/core-kernel/src/contracts/database/block-model-converter.ts
  packages/core-kernel/src/contracts/database/transaction-filter.ts
  packages/core-kernel/src/contracts/database/transaction-model-converter.ts
  packages/core-kernel/src/contracts/shared/block-history-service.ts
Labels: Complexity: High, Status: Needs Review, Type: Bugfix

#3761 fix(core-api): fix wallet/transactions confirmations and timestamp fields
  __tests__/unit/core-database/block-filter.test.ts
  __tests__/unit/core-database/block-history-service.test.ts
  __tests__/unit/core-database/block-model-converter.test.ts
  __tests__/unit/core-database/model-converter.test.ts
  __tests__/unit/core-database/service-provider.test.ts
  __tests__/unit/core-database/transaction-filter.test.ts
  __tests__/unit/core-database/transaction-history-service.test.ts
  __tests__/unit/core-database/utils/query-helper.test.ts
  __tests__/unit/core-kernel/utils/search.test.ts
  packages/core-api/src/controllers/wallets.ts
  packages/core-api/src/resources/index.ts
  packages/core-api/src/resources/transaction-with-block.ts
  packages/core-api/src/schemas.ts
  packages/core-database/src/block-filter.ts
  packages/core-database/src/block-history-service.ts
  packages/core-database/src/block-model-converter.ts
  packages/core-database/src/model-converter.ts
  packages/core-database/src/repositories/abstract-repository.ts
  packages/core-database/src/service-provider.ts
  packages/core-database/src/transaction-filter.ts
  packages/core-database/src/transaction-history-service.ts
  packages/core-database/src/transaction-model-converter.ts
  packages/core-database/src/utils/query-helper.ts
  packages/core-kernel/src/contracts/database/block-model-converter.ts
  packages/core-kernel/src/contracts/database/index.ts
  packages/core-kernel/src/contracts/database/model-converter.ts
  packages/core-kernel/src/contracts/database/transaction-model-converter.ts
  packages/core-kernel/src/contracts/search/expressions.ts
  packages/core-kernel/src/contracts/shared/block-history-service.ts
  packages/core-kernel/src/contracts/shared/transaction-history-service.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-kernel/src/utils/search.ts
Labels: Complexity: Undetermined, Status: Needs Review, Type: Bugfix

#3767 feat(core-manager): implements DatabaseLogger
  __tests__/unit/core-manager/database-logger.test.ts
  packages/core-database/src/service-provider.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-manager/src/database-logger.ts
  packages/core-manager/src/service-provider.ts
Labels: Complexity: Medium, Type: Feature

#3766 feat(core-transaction-pool): disaptch additional transaction-pool events
  __tests__/unit/core-transaction-pool/sender-state.test.ts
  __tests__/unit/core-transaction-pool/service.test.ts
  packages/core-transaction-pool/src/sender-state.ts
  packages/core-transaction-pool/src/service.ts
Labels: Complexity: Medium, Type: Feature

#3762 feat(core-manager): implement log watcher
  __tests__/unit/core-manager/database-service.test.ts
  __tests__/unit/core-manager/log-service-wrapper.test.ts
  __tests__/unit/core-manager/service-provider.test.ts
  packages/core-manager/src/database-service.ts
  packages/core-manager/src/defaults.ts
  packages/core-manager/src/log-service-wrapper.ts
  packages/core-manager/src/service-provider.ts
  packages/core/bin/config/testnet/app.json
Labels: Complexity: Medium, Type: Feature

#3760 feat(core-manager): implement `watcher.getEvents` action
  __tests__/unit/core-manager/actions/watcher-get-events.test.ts
  packages/core-manager/src/actions/watcher-get-events.ts
Labels: Complexity: Medium, Type: Feature

#3772 fix(core-database): round deletion when deleting blocks
  packages/core-database/src/repositories/block-repository.ts
Labels: Complexity: Low, Type: Bugfix

#3773 fix(core-database): straight delete blocks during rollback
  __tests__/functional/core-database/repositories/block-repository.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-database/src/repositories/block-repository.ts
Labels: Complexity: Medium, Type: Bugfix

#3771 feat(core-webhooks): dispatch webhook events
  __tests__/unit/core-webhooks/listener.test.ts
  packages/core-webhooks/src/events.ts
  packages/core-webhooks/src/listener.ts
Labels: Complexity: Medium, Type: Feature

#3747 feat(core-manager): implement `info.lastForgedBlock` action
  __tests__/unit/core-manager/__fixtures__/trigger-responses.ts
  __tests__/unit/core-manager/actions/info-last-forged-block.test.ts
  packages/core-manager/src/actions/info-last-forged-block.ts
Labels: Complexity: Medium, Type: Feature

#3774 fix(core-test-framework): use hapi inject when creating transfer transaction
  __tests__/unit/core-test-framework/utils/api.test.ts
  packages/core-test-framework/src/utils/api.ts
Labels: Complexity: Low, Status: Needs Review

#3765 fix(core-transaction-pool): introduce CORE_RESET_POOL env variable
  packages/core-transaction-pool/src/service.ts
Labels: Complexity: Low, Type: Bugfix

#3775 chore: update nsfw 2.0.0 to support node.js 14
  packages/core-kernel/package.json
  packages/core-kernel/src/services/config/watcher.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Task

#3777 fix(core-api): set default orderBy value
  packages/core-api/src/routes/blocks.ts
  packages/core-api/src/routes/transactions.ts
  packages/core-api/src/routes/votes.ts
  packages/core-api/src/routes/wallets.ts
  packages/core-api/src/schemas.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3769 feat(core-kernel): dispatch queue events
  __tests__/unit/core-kernel/services/queue/drivers/memory.test.ts
  packages/core-kernel/src/enums/events.ts
  packages/core-kernel/src/services/queue/drivers/memory.ts
Labels: Complexity: Medium, Type: Feature

#3770 feat(core-kernel): dispatch schedule events
  __tests__/unit/core-kernel/services/schedule/block-job.test.ts
  __tests__/unit/core-kernel/services/schedule/cron-job.test.ts
  packages/core-kernel/src/enums/events.ts
  packages/core-kernel/src/services/schedule/block-job.ts
  packages/core-kernel/src/services/schedule/cron-job.ts
Labels: Complexity: Medium, Type: Feature

#3764 fix(core-transaction-pool): re-add transactions to pool when milestone changes
  __tests__/unit/core-transaction-pool/service.test.ts
  __tests__/unit/core-transaction-pool/storage.test.ts
  packages/core-kernel/src/contracts/transaction-pool/storage.ts
  packages/core-transaction-pool/src/service.ts
  packages/core-transaction-pool/src/storage.ts
Labels: Complexity: Low, Type: Bugfix

#3779 ci: use `codecov/codecov-action` to report coverage
  .codacy.yml
  .codecov.yml
  .github/workflows/benchmark.yml
  .github/workflows/e2e.yml
  .github/workflows/functional.yml
  .github/workflows/integration.yml
  .github/workflows/lint.yml
  .github/workflows/unit.yml
  package.json
Labels: Complexity: Low

#3776 feat(core-manager): dispatch wallet events
  __tests__/unit/core-manager/service-provider.test.ts
  __tests__/unit/core-manager/watcher-wallet.test.ts
  packages/core-manager/package.json
  packages/core-manager/src/events.ts
  packages/core-manager/src/service-provider.ts
  packages/core-manager/src/watcher-wallet.ts
  packages/core-state/src/wallets/indexers/wallet-indexes.ts
  packages/core-state/src/wallets/wallet.ts
Labels: Complexity: Medium, Type: Feature

#3780 feat(core-manager): implement database query support
  __tests__/unit/core-manager/database-service.test.ts
  packages/core-manager/src/actions/watcher-get-events.ts
  packages/core-manager/src/database-service.ts
Labels: Complexity: Medium, Type: Feature

#3788 chore(core-manager): fix configuration and plugin actions
  __tests__/unit/core-manager/actions/configuration-get-env.test.ts
  __tests__/unit/core-manager/actions/configuration-update-plugins.test.ts
  __tests__/unit/core-manager/database-service.test.ts
  packages/core-manager/src/actions/configuration-get-env.ts
  packages/core-manager/src/actions/configuration-get-plugins.ts
  packages/core-manager/src/actions/configuration-update-plugins.ts
  packages/core-manager/src/actions/support-argon2id.ts
  packages/core-manager/src/database-service.ts
  packages/core-manager/src/defaults.ts
  packages/core-manager/src/service-provider.ts
  packages/core/bin/config/devnet/app.json
  packages/core/bin/config/devnet/plugins.js
  packages/core/bin/config/mainnet/app.json
  packages/core/bin/config/mainnet/plugins.js
  packages/core/src/commands/core-run.ts
  packages/core/src/commands/manager-run.ts
Labels: Complexity: High, Type: Task

#3789 ci: collect functional coverage
  .github/workflows/functional.yml
Labels: Complexity: Undetermined

#3790 ci: report coverage in `lcov` format
  .github/workflows/functional.yml
  .github/workflows/integration.yml
  .github/workflows/unit.yml
Labels: Complexity: Medium

#3797 refactor(core-state): log milestone change
  packages/core-state/src/stores/state.ts
Labels: Complexity: Low, Type: Refactor

#3796 refactor:(core-transaction-pool): better readd log
  __tests__/functional/transaction-forging/entity-register.test.ts
  packages/core-transaction-pool/src/service.ts
Labels: Complexity: Medium, Type: Refactor

#3794 fix(core-api): fix transaction resource responses
  packages/core-api/src/controllers/transactions.ts
  packages/core-api/src/controllers/wallets.ts
Labels: Complexity: Undetermined, Type: Bugfix

#3792 fix(core-api): log all unexpected errors
  packages/core-api/src/server.ts
Labels: Complexity: Low

#3791 fix(core-p2p): replace ws connection logging method
  __tests__/unit/core-p2p/peer-connector.test.ts
  packages/core-p2p/src/peer-connector.ts
Labels: Complexity: Low

#3800 fix(core-transaction-pool): rebuild vs update race
  __tests__/functional/transaction-forging/entity-register.test.ts
  __tests__/unit/core-api/__support__/index.ts
  __tests__/unit/core-magistrate-api/service-provider.test.ts
  __tests__/unit/core-state/block-state.test.ts
  __tests__/unit/core-state/setup.ts
  __tests__/unit/core-transaction-pool/expiration-service.test.ts
  __tests__/unit/core-transaction-pool/sender-state.test.ts
  __tests__/unit/core-transaction-pool/service.test.ts
  packages/core-kernel/src/contracts/transaction-pool/expiration-service.ts
  packages/core-kernel/src/contracts/transaction-pool/service.ts
  packages/core-transaction-pool/src/expiration-service.ts
  packages/core-transaction-pool/src/sender-state.ts
  packages/core-transaction-pool/src/service.ts
Labels: Complexity: High, Type: Bugfix

#3801 fix(core-p2p): return last common block
  __tests__/unit/core-p2p/socket-server/controllers/peer.test.ts
  packages/core-p2p/src/socket-server/controllers/peer.ts
Labels: Complexity: Low, Type: Bugfix

#3803 refactor(core-transactions): remove custom wallet repository
  __tests__/unit/core-magistrate-transactions/handlers/__mocks__/transaction-handler.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-registration.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-resignation.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/bridgechain-update.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-registration.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-resignation.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/business-update.test.ts
  __tests__/unit/core-magistrate-transactions/handlers/general.test.ts
  __tests__/unit/core-transactions/handlers/handler-registry.test.ts
  __tests__/unit/core-transactions/handlers/one/multi-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/delegate-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/delegate-resignation.test.ts
  __tests__/unit/core-transactions/handlers/two/general.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-claim.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-lock.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-refund.test.ts
  __tests__/unit/core-transactions/handlers/two/ipfs.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-payment.test.ts
  __tests__/unit/core-transactions/handlers/two/multi-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/second-signature-registration.test.ts
  __tests__/unit/core-transactions/handlers/two/transfer.test.ts
  __tests__/unit/core-transactions/handlers/two/vote.test.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-registration.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
  packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
  packages/core-transactions/src/handlers/one/delegate-registration.ts
  packages/core-transactions/src/handlers/one/multi-signature-registration.ts
  packages/core-transactions/src/handlers/one/second-signature-registration.ts
  packages/core-transactions/src/handlers/one/transfer.ts
  packages/core-transactions/src/handlers/one/vote.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/two/delegate-resignation.ts
  packages/core-transactions/src/handlers/two/htlc-claim.ts
  packages/core-transactions/src/handlers/two/htlc-lock.ts
  packages/core-transactions/src/handlers/two/htlc-refund.ts
  packages/core-transactions/src/handlers/two/ipfs.ts
  packages/core-transactions/src/handlers/two/multi-payment.ts
  packages/core-transactions/src/handlers/two/multi-signature-registration.ts
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#3802 refactor(core-transaction-pool): better locking
  __tests__/unit/core-kernel/utils/lock.test.ts
  __tests__/unit/core-transaction-pool/mempool.test.ts
  __tests__/unit/core-transaction-pool/sender-mempool.test.ts
  __tests__/unit/core-transaction-pool/service.test.ts
  __tests__/unit/core-transaction-pool/utils.test.ts
  packages/core-kernel/src/contracts/transaction-pool/sender-mempool.ts
  packages/core-kernel/src/utils/index.ts
  packages/core-kernel/src/utils/lock.ts
  packages/core-transaction-pool/src/mempool.ts
  packages/core-transaction-pool/src/sender-mempool.ts
  packages/core-transaction-pool/src/service.ts
  packages/core-transaction-pool/src/utils.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#3793 fix(core-transaction-pool): handle transaction deserialize error
  __tests__/unit/core-transaction-pool/dynamic-fee-matcher.test.ts
  __tests__/unit/core-transaction-pool/errors.test.ts
  __tests__/unit/core-transaction-pool/processor.test.ts
  __tests__/unit/core-transaction-pool/service-provider.test.ts
  packages/core-kernel/src/contracts/transaction-pool/errors.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-resignation.ts
  packages/core-magistrate-transactions/src/handlers/bridgechain-update.ts
  packages/core-magistrate-transactions/src/handlers/business-registration.ts
  packages/core-magistrate-transactions/src/handlers/business-resignation.ts
  packages/core-magistrate-transactions/src/handlers/business-update.ts
  packages/core-transaction-pool/src/errors.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transaction-pool/src/service.ts
  packages/core-transactions/src/handlers/one/delegate-registration.ts
  packages/core-transactions/src/handlers/one/multi-signature-registration.ts
  packages/core-transactions/src/handlers/one/second-signature-registration.ts
  packages/core-transactions/src/handlers/one/transfer.ts
  packages/core-transactions/src/handlers/one/vote.ts
  packages/core-transactions/src/handlers/two/delegate-resignation.ts
  packages/core-transactions/src/handlers/two/htlc-claim.ts
  packages/core-transactions/src/handlers/two/htlc-refund.ts
  packages/core-transactions/src/handlers/two/multi-signature-registration.ts
Labels: Complexity: Low, Type: Bugfix

#3806 fix(core-blockchain): block schema violation
  __tests__/integration/core-blockchain/blockchain.test.ts
  __tests__/integration/core-p2p/network-monitor.test.ts
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/crypto/blocks/block.test.ts
  __tests__/unit/crypto/utils/is-exception.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/replay/replay-blockchain.ts
  packages/core-container/src/config/index.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/crypto/src/crypto/hash.ts
  packages/crypto/src/networks/devnet/exceptions.json
  packages/crypto/src/networks/mainnet/exceptions.json
  packages/crypto/src/utils/index.ts
Labels: Complexity: High, Type: Bugfix

#3804 refactor(core-api): use shorter default timeouts
  __tests__/unit/core-api/plugins/cache.test.ts
  __tests__/unit/core-api/plugins/hapi-ajv.test.ts
  __tests__/unit/core-api/plugins/pagination.test.ts
  __tests__/unit/core-api/plugins/rate-limit.test.ts
  __tests__/unit/core-api/plugins/whitelist.test.ts
  __tests__/unit/core-api/server.test.ts
  packages/core-api/src/defaults.ts
  packages/core-api/src/server.ts
Labels: Bounty: Tier 5, Complexity: Low, Status: Collaborator Approved, Type: Refactor

#3807 test: fix blockchain unit test
  __tests__/unit/core-blockchain/blockchain.test.ts
Labels: Complexity: Low, Test: Unit

#3810 fix(core-database): transaction filter multipayment recipientId
  __tests__/unit/core-database/transaction-filter.test.ts
  packages/core-database/src/transaction-filter.ts
Labels: Complexity: Low, Type: Bugfix

#3812 chore(core-database): upgrade typeorm and pg packages
  packages/core-database/package.json
  packages/core-database/src/repositories/round-repository.ts
  packages/core-database/src/repositories/transaction-repository.ts
  yarn.lock
Labels: Complexity: Low, Status: Needs Review, Type: Task

#3811 feat(core-magistrate): set up aip36 milestone to enable entity transactions
  __tests__/functional/transaction-forging/entity-register.test.ts
  __tests__/functional/transaction-forging/entity-resign.test.ts
  __tests__/functional/transaction-forging/entity-update.test.ts
  __tests__/integration/core-api/handlers/transactions.test.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
  packages/core-magistrate-transactions/src/handlers/magistrate-handler.ts
  packages/crypto/src/networks/testnet/milestones.json
Labels: Complexity: Low, Type: Feature

#3815 refactor(core-blockchain): process blocks log line
  __tests__/unit/core-blockchain/blockchain.test.ts
  packages/core-blockchain/src/blockchain.ts
Labels: Complexity: Low, Type: Refactor

#3814 fix(core-database): fix delete blocks
  __tests__/functional/core-database/repositories/block-repository.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-database/src/repositories/block-repository.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3816 fix(core-database): fix round order
  __tests__/functional/core-database/repositories/round-repository.test.ts
  __tests__/unit/core-database/database-service.test.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/round-repository.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3818 fix(core-tester-cli): use incremental timestamps for `make:block`
  packages/core-tester-cli/src/commands/make/block.ts
Labels: Bounty: Tier 4, Complexity: Low, Status: Collaborator Approved, Type: Task

#3813 chore(core-p2p): copy over `@hapi/nes` with forked code
  __tests__/unit/core-forger/client.test.ts
  __tests__/unit/core-p2p/peer-connector.test.ts
  __tests__/unit/core-p2p/socket-server/server.test.ts
  packages/core-forger/package.json
  packages/core-forger/src/client.ts
  packages/core-forger/src/interfaces.ts
  packages/core-kernel/src/contracts/p2p/nes-client.ts
  packages/core-kernel/src/contracts/p2p/peer-connector.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/hapi-nes/client.ts
  packages/core-p2p/src/hapi-nes/index.ts
  packages/core-p2p/src/hapi-nes/listener.ts
  packages/core-p2p/src/hapi-nes/socket.ts
  packages/core-p2p/src/index.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/socket-server/server.ts
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor

#3823 chore(crypto): update `bcrypto` dependency to v5
  packages/crypto/package.json
  packages/crypto/src/identities/public-key.ts
  yarn.lock
Labels: Complexity: Low, Type: Task

#3824 fix(core-database): return serialized transactions
  __tests__/functional/core-database/__support__/index.ts
  packages/core-database/src/repositories/block-repository.ts
Labels: Complexity: Low, Type: Bugfix

#3828 fix(core-state): remove state=blockchain tag from block state
  __tests__/unit/core-state/setup.ts
  packages/core-state/src/block-state.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3827 fix(core-database): initializeActiveDelegates just use current round
  __tests__/unit/core-database/database-service.test.ts
  packages/core-database/src/database-service.ts
Labels: Complexity: Low, Type: Bugfix

#3829 feat(core-manager): disable individual watchers
  __tests__/unit/core-manager/listener.test.ts
  __tests__/unit/core-manager/service-provider.test.ts
  packages/core-manager/src/defaults.ts
  packages/core-manager/src/listener.ts
  packages/core-manager/src/service-provider.ts
Labels: Complexity: Medium, Type: Feature

#3830 feat(crypto): add rollup config for browsers
  packages/crypto/package.json
  packages/crypto/rollup.config.js
  packages/crypto/src/transactions/types/schemas.ts
  yarn.lock
Labels: Complexity: Undetermined, Type: Feature

#3832 ci: setup CodeQL Analysis
  .github/workflows/codeql-analysis.yml
Labels: Complexity: Low

#3833 refactor(core-kernel): remove app.log and all of its usages
  __tests__/unit/core-kernel/services/config/watcher.test.ts
  __tests__/unit/core-magistrate-api/__support__/index.ts
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/utils/check-ntp.test.ts
  __tests__/unit/core-transactions/handlers/handler-registry.test.ts
  packages/core-api/src/server.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-database/src/service-provider.ts
  packages/core-kernel/src/application.ts
  packages/core-kernel/src/bootstrap/service-providers/boot-service-providers.ts
  packages/core-kernel/src/bootstrap/service-providers/register-service-providers.ts
  packages/core-kernel/src/contracts/kernel/application.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/socket-server/server.ts
  packages/core-p2p/src/utils/check-dns.ts
  packages/core-p2p/src/utils/check-ntp.ts
  packages/core-state/src/state-builder.ts
  packages/core-state/src/stores/state.ts
  packages/core-transactions/src/handlers/handler-registry.ts
  packages/core-transactions/src/handlers/transaction.ts
  packages/core-transactions/src/handlers/two/htlc-claim.ts
  packages/core-transactions/src/handlers/two/htlc-refund.ts
  packages/core-webhooks/src/server/index.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#3834 fix(core-kernel): prevent watcher from calling app.reboot multiple times
  packages/core-kernel/src/services/config/watcher.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3837 test(core-manager): increase coverage to 100%
  __tests__/unit/core-manager/actions/process-list.test.ts
  __tests__/unit/core-manager/actions/process-restart.test.ts
  __tests__/unit/core-manager/actions/process-start.test.ts
  __tests__/unit/core-manager/actions/process-stop.test.ts
  __tests__/unit/core-manager/database-service.test.ts
  __tests__/unit/core-manager/server/server.test.ts
  __tests__/unit/core-manager/server/validators/token.test.ts
  __tests__/unit/core-manager/service-provider.test.ts
  __tests__/unit/core-manager/utils/api-connection.test.ts
  packages/core-manager/src/actions/process.stop.ts
  packages/core-manager/src/database-service.ts
  packages/core-manager/src/server/validators/token.ts
  packages/core-manager/src/watcher-wallet.ts
  yarn.lock
Labels: Complexity: High, Test: Unit

#3835 refactor(core-kernel): remove app.events and all of its usages
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-kernel/services/queue/service-provider.test.ts
  __tests__/unit/core-kernel/services/schedule/schedule.test.ts
  __tests__/unit/core-manager/watcher-wallet.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/state-machine/actions/blockchain-ready.ts
  packages/core-database/src/database-service.ts
  packages/core-kernel/src/application.ts
  packages/core-kernel/src/bootstrap/service-providers/boot-service-providers.ts
  packages/core-kernel/src/contracts/kernel/application.ts
  packages/core-kernel/src/services/queue/drivers/memory.ts
  packages/core-kernel/src/services/schedule/block-job.ts
  packages/core-kernel/src/services/schedule/cron-job.ts
  packages/core-manager/src/listener.ts
  packages/core-manager/src/service-provider.ts
  packages/core-manager/src/watcher-wallet.ts
  packages/core-p2p/src/event-listener.ts
  packages/core-p2p/src/listeners.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/socket-server/controllers/internal.ts
  packages/core-snapshots/src/progress-dispatcher.ts
  packages/core-state/src/state-builder.ts
  packages/core-transaction-pool/src/sender-state.ts
  packages/core-transaction-pool/src/service.ts
  packages/core-webhooks/src/listener.ts
  packages/core-webhooks/src/service-provider.ts
  packages/core/src/utils/snapshot-progress-renderer.ts
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#3843 chore(crypto): run rollup before publishing to NPM
  packages/crypto/package.json
Labels: Complexity: Low, Type: Task

#3842 release: 2.6.42
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3831 fix(crypto): transaction builder should build and sign versioned transactions
  __tests__/unit/crypto/transactions/builders/transactions/transaction-builder.test.ts
  packages/crypto/src/interfaces/transactions.ts
  packages/crypto/src/transactions/builders/transactions/transaction.ts
  packages/crypto/src/transactions/deserializer.ts
  packages/crypto/src/transactions/factory.ts
  packages/crypto/src/transactions/serializer.ts
  packages/crypto/src/transactions/signer.ts
  packages/crypto/src/transactions/types/transaction.ts
  packages/crypto/src/transactions/verifier.ts
Labels: Complexity: Medium, Type: Bugfix

#3845 chore(crypto): add aip36 milestone for devnet
  packages/crypto/src/networks/devnet/milestones.json
Labels: Complexity: Low, Type: Task

#3847 refactor: remove obsolete magistrate endpoints (AIP36)
  __tests__/integration/core-api/handlers/bridgechains.test.ts
  __tests__/integration/core-api/handlers/businesses.test.ts
  packages/core-api/src/handlers/bridgechains/controller.ts
  packages/core-api/src/handlers/bridgechains/index.ts
  packages/core-api/src/handlers/bridgechains/methods.ts
  packages/core-api/src/handlers/bridgechains/routes.ts
  packages/core-api/src/handlers/bridgechains/schema.ts
  packages/core-api/src/handlers/bridgechains/transformer.ts
  packages/core-api/src/handlers/businesses/controller.ts
  packages/core-api/src/handlers/businesses/index.ts
  packages/core-api/src/handlers/businesses/methods.ts
  packages/core-api/src/handlers/businesses/routes.ts
  packages/core-api/src/handlers/businesses/schema.ts
  packages/core-api/src/handlers/businesses/transformer.ts
  packages/core-api/src/handlers/entities/controller.ts
  packages/core-api/src/handlers/index.ts
  packages/core-api/src/plugins/pagination/ext.ts
  packages/core-api/src/services/transformer.ts
  packages/core-database/src/repositories/wallets-business-repository.ts
  packages/core-interfaces/src/core-database/business-repository/wallets-business-repository.ts
Labels: Complexity: High, Type: Task

#3848 chore(core-p2p): accept peers in the 2.7 range
  packages/core-p2p/src/defaults.ts
Labels: Complexity: Low, Type: Task

#3846 chore(core-snapshots): skip verification of transactions sent from multisignature wallets
  __tests__/unit/core-snapshots/verifier.test.ts
  packages/core-snapshots/src/verifier.ts
Labels: Complexity: Low, Type: Task

#3817 fix(core-blockchain): add missing return type to this.queue
  packages/core-blockchain/src/blockchain.ts
Labels: Complexity: Low, Status: Collaborator Approved, Type: Bugfix

#3849 test(e2e): fix magistrate tests
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/1.1.check-business-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/2.1.check-business-update.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/3.1.check-bridgechain-registration.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/4.1.check-bridgechain-update.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/5.1.check-bridgechain-resignation.test.js
  __tests__/e2e/tests/scenarios/scenario1/business-bridgechain/6.1.check-business-resignation.test.js
Labels: Complexity: Medium, Test: Unit

#3851 fix(core-magistrate): fix entity bootstrap methods
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/register.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/resign.ts
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/update.ts
  packages/core-magistrate-transactions/src/handlers/entity.ts
Labels: Complexity: Low, Type: Bugfix

#3850 fix(core-magistrate): fix entity register bootstrap method
  packages/core-magistrate-transactions/src/handlers/entity-subhandlers/register.ts
Labels: Complexity: Low, Type: Bugfix

#3854 refactor(core-transaction-pool): union query typeGroup with number
  packages/core-kernel/src/contracts/transaction-pool/query.ts
  packages/core-transaction-pool/src/query.ts
Labels: Complexity: Low

#3855 fix(core-api): respect CORE_API_RATE_LIMIT_DISABLED env variable
  packages/core-api/src/defaults.ts
Labels: Complexity: Low, Type: Bugfix

#3857 fix(core-transaction-pool): union type with number in pool query
  packages/core-kernel/src/contracts/transaction-pool/query.ts
  packages/core-transaction-pool/src/query.ts
Labels: Complexity: Low, Type: Bugfix

#3853 fix(core-p2p): Restrict internal routes to whitelisted IPs
  __tests__/unit/core-p2p/socket-server/plugins/whitelist-forger.test.ts
  packages/core-kernel/src/contracts/p2p/peer-processor.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/socket-server/plugins/whitelist-forger.ts
  packages/core-p2p/src/socket-server/server.ts
Labels: Complexity: Medium, Type: Bugfix

#3859 test(core-snapshot): increase coverage to 100%
  __tests__/unit/core-snapshots/database-service.test.ts
  __tests__/unit/core-snapshots/filesystem/filesystem.test.ts
  __tests__/unit/core-snapshots/filesystem/stream-reader-writer.test.ts
  __tests__/unit/core-snapshots/service-provider.test.ts
  __tests__/unit/core-snapshots/workers/actions/__support__/helper.ts
  __tests__/unit/core-snapshots/workers/actions/test-worker-action.test.ts
  __tests__/unit/core-snapshots/workers/actions/worker-action.test.ts
  __tests__/unit/core-snapshots/workers/worker-wrapper.test.ts
  packages/core-snapshots/src/database-service.ts
  packages/core-snapshots/src/filesystem/filesystem.ts
  packages/core-snapshots/src/filesystem/stream-reader.ts
  packages/core-snapshots/src/repositories/block-repository.ts
  packages/core-snapshots/src/repositories/round-repository.ts
  packages/core-snapshots/src/repositories/transaction-repository.ts
  packages/core-snapshots/src/workers/actions/read-processor.ts
  packages/core-snapshots/src/workers/actions/restore-worker-action.ts
  packages/core-snapshots/src/workers/actions/test-worker-action.ts
  packages/core-snapshots/src/workers/actions/verify-worker-action.ts
  packages/core-snapshots/src/workers/worker-wrapper.ts
  packages/core-snapshots/src/workers/worker.ts
Labels: Complexity: High
