Repository ArkEcosystem/core, pull requests merged in 2020-04, with the labels that each got.

#3639 chore(readme): fix build status badge
  README.md
Labels: Complexity: Low, Type: Task

#3634 feat: integrate triggers and actions
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts
  __tests__/unit/core-blockchain/service-provider.test.ts
  __tests__/unit/core-forger/forger-service.test.ts
  __tests__/unit/core-forger/service-provider.test.ts
  __tests__/unit/core-forger/setup.ts
  __tests__/unit/core-kernel/services/triggers/triggers.test.ts
  __tests__/unit/core-magistrate-transactions/__support__/app.ts
  __tests__/unit/core-state/service-provider.test.ts
  __tests__/unit/core-state/setup.ts
  __tests__/unit/core-transaction-pool/sender-state.test.ts
  __tests__/unit/core-transaction-pool/service-provider.test.ts
  __tests__/unit/core-transactions/handlers/__support__/app.ts
  packages/core-blockchain/src/actions/index.ts
  packages/core-blockchain/src/actions/process-block.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/service-provider.ts
  packages/core-database/src/actions/get-active-delegates.ts
  packages/core-database/src/actions/index.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/service-provider.ts
  packages/core-forger/src/actions/forge-new-block.ts
  packages/core-forger/src/actions/index.ts
  packages/core-forger/src/actions/is-forging-allowed.ts
  packages/core-forger/src/delegate-tracker.ts
  packages/core-forger/src/forger-service.ts
  packages/core-forger/src/service-provider.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-kernel/src/services/triggers/action.ts
  packages/core-kernel/src/services/triggers/triggers.ts
  packages/core-p2p/src/actions/index.ts
  packages/core-p2p/src/actions/validate-and-accept-peer.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/service-provider.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-state/src/actions/build-delegate-ranking.ts
  packages/core-state/src/actions/index.ts
  packages/core-state/src/dpos/dpos-previous-round.ts
  packages/core-state/src/service-provider.ts
  packages/core-transaction-pool/src/actions/apply-transaction.ts
  packages/core-transaction-pool/src/actions/index.ts
  packages/core-transaction-pool/src/actions/revert-transaction.ts
  packages/core-transaction-pool/src/actions/throw-if-cannot-enter-pool.ts
  packages/core-transaction-pool/src/actions/verify-transaction.ts
  packages/core-transaction-pool/src/sender-state.ts
  packages/core-transaction-pool/src/service-provider.ts
Labels: Complexity: Undetermined

#3643 feat(core-p2p): hapi/nes implementation
  __tests__/e2e/lib/config/docker-compose.yml
  __tests__/e2e/lib/config/nodes/core0/app.json
  __tests__/e2e/lib/config/nodes/core0/peers.json
  __tests__/unit/core-forger/client.test.ts
  __tests__/unit/core-forger/forger-service.test.ts
  __tests__/unit/core-forger/mocks/nes.ts
  __tests__/unit/core-forger/service-provider.test.ts
  jest.config.js
  packages/core-forger/package.json
  packages/core-forger/src/client.ts
  packages/core-forger/src/interfaces.ts
  packages/core-kernel/src/contracts/p2p/network-monitor.ts
  packages/core-kernel/src/contracts/p2p/peer-connector.ts
  packages/core-kernel/src/providers/service-provider-repository.ts
  packages/core-p2p/package.json
  packages/core-p2p/src/actions/index.ts
  packages/core-p2p/src/actions/validate-and-accept-peer.ts
  packages/core-p2p/src/defaults.ts
  packages/core-p2p/src/event-listener.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-connector.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/schemas.ts
  packages/core-p2p/src/service-provider.ts
  packages/core-p2p/src/socket-server/controllers/controller.ts
  packages/core-p2p/src/socket-server/controllers/internal.ts
  packages/core-p2p/src/socket-server/controllers/peer.ts
  packages/core-p2p/src/socket-server/index.ts
  packages/core-p2p/src/socket-server/payload-processor.ts
  packages/core-p2p/src/socket-server/plugins/accept-peer.ts
  packages/core-p2p/src/socket-server/plugins/validate.ts
  packages/core-p2p/src/socket-server/routes/internal.ts
  packages/core-p2p/src/socket-server/routes/peer.ts
  packages/core-p2p/src/socket-server/routes/route.ts
  packages/core-p2p/src/socket-server/schemas/internal.ts
  packages/core-p2p/src/socket-server/schemas/peer.ts
  packages/core-p2p/src/socket-server/server.ts
  packages/core-p2p/src/socket-server/utils/validate.ts
  packages/core-p2p/src/socket-server/versions/index.ts
  packages/core-p2p/src/socket-server/versions/internal.ts
  packages/core-p2p/src/socket-server/versions/peer.ts
  packages/core-p2p/src/socket-server/versions/utils.ts
  packages/core-p2p/src/socket-server/worker.ts
  packages/core-p2p/src/utils/index.ts
  packages/core-p2p/src/utils/sc-codec.ts
  packages/core-p2p/src/utils/socket.ts
  packages/core-state/src/actions/build-delegate-ranking.ts
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#3657 test(core-database): block and transaction history services
  __tests__/integration/core-api/handlers/transactions.test.ts
  __tests__/unit/core-api/controllers/blocks.test.ts
  __tests__/unit/core-database/__fixtures__/block1760000.ts
  __tests__/unit/core-database/block-filter.test.ts
  __tests__/unit/core-database/block-history-service.test.ts
  __tests__/unit/core-database/block-model-converter.test.ts
  __tests__/unit/core-database/repositories/query-helper.test.ts
  __tests__/unit/core-database/transaction-filter.test.ts
  __tests__/unit/core-database/transaction-history-service.test.ts
  __tests__/unit/core-database/transaction-model-converter.test.ts
  __tests__/unit/core-kernel/utils/search.test.ts
  __tests__/unit/core-state/wallets/wallet-repository.test.ts
  __tests__/unit/core-test-framework/mocks/block-repository.test.ts
  packages/core-api/src/controllers/controller.ts
  packages/core-api/src/controllers/transactions.ts
  packages/core-database/src/block-filter.ts
  packages/core-database/src/block-history-service.ts
  packages/core-database/src/block-model-converter.ts
  packages/core-database/src/criteria-handler.ts
  packages/core-database/src/models/block.ts
  packages/core-database/src/models/transaction.ts
  packages/core-database/src/repositories/block-repository.ts
  packages/core-database/src/repositories/query-helper.ts
  packages/core-database/src/repositories/repository.ts
  packages/core-database/src/repositories/transaction-repository.ts
  packages/core-database/src/service-provider.ts
  packages/core-database/src/transaction-filter.ts
  packages/core-database/src/transaction-history-service.ts
  packages/core-database/src/transaction-model-converter.ts
  packages/core-kernel/src/contracts/database/block-filter.ts
  packages/core-kernel/src/contracts/database/block-model-converter.ts
  packages/core-kernel/src/contracts/database/index.ts
  packages/core-kernel/src/contracts/database/models.ts
  packages/core-kernel/src/contracts/database/transaction-filter.ts
  packages/core-kernel/src/contracts/database/transaction-model-converter.ts
  packages/core-kernel/src/contracts/index.ts
  packages/core-kernel/src/contracts/search/criteria.ts
  packages/core-kernel/src/contracts/search/expressions.ts
  packages/core-kernel/src/contracts/search/index.ts
  packages/core-kernel/src/contracts/shared/block-history-service.ts
  packages/core-kernel/src/contracts/shared/criteria.ts
  packages/core-kernel/src/contracts/shared/expressions.ts
  packages/core-kernel/src/contracts/shared/index.ts
  packages/core-kernel/src/contracts/shared/transaction-history-service.ts
  packages/core-kernel/src/contracts/state/wallets.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-kernel/src/utils/index.ts
  packages/core-kernel/src/utils/search.ts
  packages/core-state/src/wallets/utils/search-entries.ts
  packages/core-state/src/wallets/wallet-repository.ts
  packages/core-test-framework/src/mocks/block-repository.ts
  packages/core-test-framework/src/mocks/transaction-repository.ts
  wallaby.js
Labels: Complexity: Undetermined, Test: Unit

#3658 fix(core-tester-framework): import scope
  packages/core-test-framework/src/utils/mapper.ts
  packages/core-test-framework/src/utils/transaction-factory.ts
Labels: Bounty: Tier 4, Complexity: Low, Type: Bugfix

#3659 fix(core-elasticsearch): create a unique round ID
  packages/core-elasticsearch/src/indices/rounds.ts
Labels: Complexity: Low, Type: Bugfix

#3650 feat(crypto): dynamic block times
  .github/workflows/lint-test-benchmark.yml
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/download-blocks.test.ts
  __tests__/unit/core-database/block-model-converter.test.ts
  __tests__/unit/core-database/transaction-model-converter.test.ts
  __tests__/unit/core-forger/__utils__/create-block-with-transactions.ts
  __tests__/unit/core-forger/delegate-tracker.test.ts
  __tests__/unit/core-forger/forger-service.test.ts
  __tests__/unit/core-forger/methods/bip38.test.ts
  __tests__/unit/core-forger/methods/bip39.test.ts
  __tests__/unit/core-forger/setup.ts
  __tests__/unit/core-kernel/utils/assert.test.ts
  __tests__/unit/core-kernel/utils/calculate-forging-info.test.ts
  __tests__/unit/core-kernel/utils/get-blocktime-lookup.test.ts
  __tests__/unit/core-kernel/utils/is-blocked-chained.test.ts
  __tests__/unit/core-logger-pino/driver.test.ts
  __tests__/unit/core-transaction-pool/expiration-service.test.ts
  __tests__/unit/crypto/blocks/block.test.ts
  __tests__/unit/crypto/blocks/factory.test.ts
  __tests__/unit/crypto/crypto/slots.test.ts
  __tests__/unit/crypto/managers/config.test.ts
  __tests__/unit/crypto/utils/block-time-calculator.test.ts
  __tests__/unit/crypto/utils/fixtures/block-time-milestones.json
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/processor/block-processor.ts
  packages/core-blockchain/src/state-machine/actions/download-blocks.ts
  packages/core-database/src/database-service.ts
  packages/core-forger/src/delegate-tracker.ts
  packages/core-forger/src/forger-service.ts
  packages/core-forger/src/interfaces.ts
  packages/core-forger/src/methods/bip38.ts
  packages/core-forger/src/methods/bip39.ts
  packages/core-forger/src/methods/method.ts
  packages/core-kernel/src/contracts/shared/forging-info.ts
  packages/core-kernel/src/contracts/shared/index.ts
  packages/core-kernel/src/utils/calculate-forging-info.ts
  packages/core-kernel/src/utils/get-blocktime-lookup.ts
  packages/core-kernel/src/utils/index.ts
  packages/core-kernel/src/utils/is-block-chained.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/network-state.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/socket-server/controllers/internal.ts
  packages/core-p2p/src/socket-server/controllers/peer.ts
  packages/core-test-framework/src/factories/factories/block.ts
  packages/core-test-framework/src/utils/generic.ts
  packages/core-transaction-pool/src/expiration-service.ts
  packages/core-transaction-pool/src/sender-state.ts
  packages/core-transaction-pool/src/service.ts
  packages/core-transactions/src/handlers/two/htlc-lock.ts
  packages/crypto/src/blocks/block.ts
  packages/crypto/src/blocks/factory.ts
  packages/crypto/src/crypto/index.ts
  packages/crypto/src/crypto/slots.ts
  packages/crypto/src/managers/config.ts
  packages/crypto/src/utils/block-time-calculator.ts
  packages/crypto/src/utils/index.ts
Labels: Complexity: Undetermined, Type: Feature

#3597 test(core-database): increase coverage
  .github/workflows/lint-test-benchmark.yml
  __tests__/functional/core-database/__support__/index.ts
  __tests__/functional/core-database/migrations.test.ts
  __tests__/functional/core-database/repositories/block-repository.test.ts
  __tests__/functional/core-database/repositories/round-repository.test.ts
  __tests__/functional/core-database/repositories/transaction-repository.test.ts
  __tests__/unit/core-database/utils/query-helper.test.ts
  __tests__/unit/core-database/utils/snake-naming-strategy.test.ts
  __tests__/unit/core-database/utils/transform.test.ts
  __tests__/unit/core-test-framework/mocks/transaction-repository.test.ts
  __tests__/unit/core-transactions/handlers/two/htlc-lock.test.ts
  packages/core-api/src/controllers/votes.ts
  packages/core-database/src/actions/get-active-delegates.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/migrations/20180305100000-create-wallets-table.ts
  packages/core-database/src/migrations/20180305200000-create-rounds-table.ts
  packages/core-database/src/migrations/20180305300000-create-blocks-table.ts
  packages/core-database/src/migrations/20180305400000-create-transactions-table.ts
  packages/core-database/src/migrations/20181204100000-add-generator_public_key-index-to-blocks-table.ts
  packages/core-database/src/migrations/20181204400000-add-recipient_id-index-to-transactions-table.ts
  packages/core-database/src/migrations/20190307000000-drop-wallets-table.ts
  packages/core-database/src/migrations/20190626000000-enforce-chained-blocks.ts
  packages/core-database/src/migrations/20190718000000-check_previous_block-add-schema.ts
  packages/core-database/src/migrations/20190806000000-add-nonce-column-to-transactions-table.ts
  packages/core-database/src/migrations/20190905000000-change-set_row_nonce-to-use-max-nonce.ts
  packages/core-database/src/migrations/20191003000000-migrate-vendor-field-hex.ts
  packages/core-database/src/models/block.ts
  packages/core-database/src/models/round.ts
  packages/core-database/src/models/transaction.ts
  packages/core-database/src/repositories/block-repository.ts
  packages/core-database/src/repositories/repository.ts
  packages/core-database/src/repositories/transaction-repository.ts
  packages/core-database/src/service-provider.ts
  packages/core-database/src/utils/query-helper.ts
  packages/core-database/src/utils/snake-naming-strategy.ts
  packages/core-database/src/utils/transform.ts
  packages/core-test-framework/src/mocks/transaction-repository.ts
  packages/core-transactions/src/handlers/two/htlc-claim.ts
  packages/core-transactions/src/handlers/two/htlc-lock.ts
  packages/core-transactions/src/handlers/two/htlc-refund.ts
Labels: Complexity: Undetermined, Status: Needs Review, Test: Unit

#3665 chore: update @arkecosystem/utils dependency
  packages/core-api/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-jest-matchers/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Low, Type: Task

#3667 perf(core-transaction-pool): use tree memory structure to sort by fee and by sender nonce
  __tests__/unit/core-utils/tree.test.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-utils/src/index.ts
  packages/core-utils/src/tree.ts
Labels: Complexity: High, Type: Performance

#3666 release: 2.6.34
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3669 fix(core-state): update vote balance with htlc locked balance on vote transactions
  __tests__/functional/transaction-forging/htlc-lock.test.ts
  packages/core-jest-matchers/src/functional/index.ts
  packages/core-jest-matchers/src/functional/vote-balance.ts
  packages/core-state/src/wallets/wallet-manager.ts
Labels: Complexity: Medium, Type: Bugfix
