Repository ArkEcosystem/core, pull requests merged in 2020-05, with the labels that each got.

#3678 fix(core-transaction-pool): use sorted array (instead of tree) for storing transactions by fee and nonce
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/memory.test.ts
  __tests__/unit/core-utils/sorted-array.test.ts
  __tests__/unit/core-utils/tree.test.ts
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-utils/src/index.ts
  packages/core-utils/src/sorted-array.ts
  packages/core-utils/src/tree.ts
Labels: Complexity: High, Type: Bugfix

#3679 Merge 2.6 into master
  CHANGELOG.md
  __tests__/functional/transaction-forging/htlc-lock.test.ts
  __tests__/unit/core-transaction-pool/connection.test.ts
  __tests__/unit/core-transaction-pool/memory.test.ts
  __tests__/unit/core-utils/sorted-array.test.ts
  __tests__/unit/core-utils/tree.test.ts
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-jest-matchers/src/functional/index.ts
  packages/core-jest-matchers/src/functional/vote-balance.ts
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-state/src/wallets/wallet-manager.ts
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transaction-pool/src/connection.ts
  packages/core-transaction-pool/src/defaults.ts
  packages/core-transaction-pool/src/memory.ts
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-utils/src/index.ts
  packages/core-utils/src/sorted-array.ts
  packages/core-utils/src/tree.ts
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Undetermined

#3677 refactor: use `export * as ns` syntax
  packages/core-api/src/index.ts
  packages/core-cli/src/index.ts
  packages/core-database/src/index.ts
  packages/core-kernel/src/bootstrap/index.ts
  packages/core-kernel/src/contracts/index.ts
  packages/core-kernel/src/exceptions/index.ts
  packages/core-kernel/src/index.ts
  packages/core-kernel/src/ioc/index.ts
  packages/core-kernel/src/services/index.ts
  packages/core-kernel/src/utils/index.ts
  packages/core-magistrate-crypto/src/index.ts
  packages/core-magistrate-transactions/src/index.ts
  packages/core-state/src/index.ts
  packages/core-test-framework/src/factories/index.ts
  packages/core-test-framework/src/index.ts
  packages/core-test-framework/src/mocks/index.ts
  packages/core-test-framework/src/utils/index.ts
  packages/core-transactions/src/handlers/index.ts
  packages/core-transactions/src/index.ts
  packages/crypto/src/crypto/index.ts
  packages/crypto/src/index.ts
  packages/crypto/src/transactions/types/index.ts
Labels: Complexity: High, Type: Refactor

#3676 chore: enable assumeChangesOnlyAffectDirectDependencies for TypeScript
  tsconfig.json
Labels: Complexity: Low, Type: Task

#3673 test(core-database): increase coverage to 100%
  __tests__/functional/transaction-forging/__support__/index.ts
  __tests__/integration/core-api/__support__/setup.ts
  __tests__/integration/core-api/handlers/rounds.test.ts
  __tests__/unit/core-blockchain/processor/block-processor.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/initialize.test.ts
  __tests__/unit/core-database/database-service.test.ts
  __tests__/unit/core-database/service-provider.test.ts
  packages/core-blockchain/src/state-machine/actions/initialize.ts
  packages/core-database/src/database-service.ts
  packages/core-database/src/repositories/abstract-repository.ts
  packages/core-database/src/repositories/block-repository.ts
  packages/core-database/src/repositories/index.ts
  packages/core-database/src/repositories/transaction-repository.ts
  packages/core-database/src/service-provider.ts
  packages/core-snapshots/src/repositories/block-repository.ts
  packages/core-snapshots/src/repositories/round-repository.ts
  packages/core-snapshots/src/repositories/transaction-repository.ts
Labels: Complexity: High, Status: Needs Review, Test: Unit

#3681 fix(core-logger-pino): show log levels <= defined threshold level
  __tests__/e2e/lib/config/nodes/core0/.env
  __tests__/e2e/lib/config/nodes/core1/.env
  __tests__/e2e/lib/config/nodes/core2/.env
  __tests__/e2e/lib/config/nodes/core3/.env
  __tests__/e2e/lib/config/nodes/core4/.env
  __tests__/unit/core-logger-pino/driver.test.ts
  packages/core-logger-pino/src/defaults.ts
  packages/core-logger-pino/src/driver.ts
Labels: Complexity: Low, Type: Bugfix

#3684 fix(core-kernel): get app version from package.json
  __tests__/e2e/lib/config/docker-compose.yml
  __tests__/unit/core-database/database-service.test.ts
  packages/core-database/src/database-service.ts
  packages/core-kernel/src/bootstrap/app/register-base-bindings.ts
  packages/core-p2p/src/defaults.ts
Labels: Complexity: Low, Type: Bugfix

#3685 feat(core-manager): implement core-manager skeleton
  __tests__/unit/core-manager/__fixtures__/assets.ts
  __tests__/unit/core-manager/__fixtures__/index.ts
  __tests__/unit/core-manager/__fixtures__/key.pem
  __tests__/unit/core-manager/__fixtures__/server.crt
  __tests__/unit/core-manager/action-reader.test.ts
  __tests__/unit/core-manager/server-boot-dispose.test.ts
  __tests__/unit/core-manager/server.test.ts
  __tests__/unit/core-manager/service-provider.test.ts
  __tests__/unit/core/commands/manager-run.test.ts
  packages/core-manager/.gitattributes
  packages/core-manager/README.md
  packages/core-manager/package.json
  packages/core-manager/src/action-reader.ts
  packages/core-manager/src/actions/test.ts
  packages/core-manager/src/contracts/action.ts
  packages/core-manager/src/contracts/index.ts
  packages/core-manager/src/defaults.ts
  packages/core-manager/src/index.ts
  packages/core-manager/src/ioc/identifiers.ts
  packages/core-manager/src/ioc/index.ts
  packages/core-manager/src/server.ts
  packages/core-manager/src/service-provider.ts
  packages/core-manager/tsconfig.json
  packages/core/bin/config/testnet/.env
  packages/core/bin/config/testnet/app.json
  packages/core/package.json
  packages/core/src/commands/manager-run.ts
  yarn.lock
Labels: Complexity: High, Type: Feature

#3686 feat(core-manager): implement IP whitelisting
  __tests__/unit/core-manager/server-boot-dispose.test.ts
  __tests__/unit/core-manager/server.test.ts
  packages/core-manager/src/contracts/index.ts
  packages/core-manager/src/contracts/plugins.ts
  packages/core-manager/src/defaults.ts
  packages/core-manager/src/ioc/identifiers.ts
  packages/core-manager/src/plugins/index.ts
  packages/core-manager/src/plugins/plugin-factory.ts
  packages/core-manager/src/plugins/rpc-response-handler.ts
  packages/core-manager/src/server.ts
  packages/core-manager/src/service-provider.ts
  packages/core/bin/config/testnet/.env
Labels: Complexity: High, Type: Feature

#3687 feat(core-manager): implement basic authentication
  __tests__/unit/core-manager/server/plugins/rpc-response-handler.test.ts
  __tests__/unit/core-manager/server/server-boot-dispose.test.ts
  __tests__/unit/core-manager/server/server.test.ts
  packages/core-manager/package.json
  packages/core-manager/src/actions/argon2id.ts
  packages/core-manager/src/contracts/action.ts
  packages/core-manager/src/contracts/authentication.ts
  packages/core-manager/src/contracts/index.ts
  packages/core-manager/src/defaults.ts
  packages/core-manager/src/ioc/identifiers.ts
  packages/core-manager/src/server/plugins/index.ts
  packages/core-manager/src/server/plugins/plugin-factory.ts
  packages/core-manager/src/server/plugins/rpc-response-handler.ts
  packages/core-manager/src/server/server.ts
  packages/core-manager/src/server/validators/argon2id.ts
  packages/core-manager/src/server/validators/index.ts
  packages/core-manager/src/service-provider.ts
  yarn.lock
Labels: Complexity: High, Type: Feature

#3688 feat(core-manager) implement token authentication
  __tests__/unit/core-manager/server/server-boot-dispose.test.ts
  __tests__/unit/core-manager/server/server.test.ts
  packages/core-manager/package.json
  packages/core-manager/src/defaults.ts
  packages/core-manager/src/server/plugins/plugin-factory.ts
  packages/core-manager/src/server/validators/index.ts
  packages/core-manager/src/server/validators/token.ts
  packages/core-manager/src/service-provider.ts
  yarn.lock
Labels: Complexity: Medium

#3692 feat(core-manager): implement `info.coreVersion` action
  __tests__/unit/core-manager/__fixtures__/assets.ts
  __tests__/unit/core-manager/actions/info-core-version.test.ts
  __tests__/unit/core-manager/server/plugins/rpc-response-handler.test.ts
  __tests__/unit/core-manager/server/server.test.ts
  packages/core-manager/package.json
  packages/core-manager/src/action-reader.ts
  packages/core-manager/src/actions/info-core-version.ts
  packages/core-manager/src/actions/support-argon2id.ts
  packages/core-manager/src/actions/test.ts
  packages/core-manager/src/contracts/action.ts
  packages/core-manager/src/defaults.ts
Labels: Complexity: Undetermined, Type: Feature

#3695 refactor(core-p2p): custom validation for postBlock in worker
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Low, Type: Refactor

#3694 feat(core-manager): implement `info.coreStatus` action
  __tests__/unit/core-manager/actions/info-core-status.test.ts
  __tests__/unit/core-manager/utils/__mocks__/axios.ts
  __tests__/unit/core-manager/utils/http-client.test.ts
  packages/core-manager/package.json
  packages/core-manager/src/actions/info-core-status.ts
  packages/core-manager/src/ioc/identifiers.ts
  packages/core-manager/src/service-provider.ts
  packages/core-manager/src/utils/http-client.ts
  packages/core-manager/src/utils/index.ts
  yarn.lock
Labels: Complexity: Medium, Type: Feature

#3696 feat(core-manager): implement `info.blockchainHeight` action
  __tests__/unit/core-manager/actions/info-blockchain-height.test.ts
  __tests__/unit/core-manager/utils/__mocks__/axios.ts
  __tests__/unit/core-manager/utils/http-client.test.ts
  packages/core-manager/package.json
  packages/core-manager/src/action-reader.ts
  packages/core-manager/src/actions/info-blockchain-height.ts
  packages/core-manager/src/actions/info-core-status.ts
  packages/core-manager/src/actions/info-core-version.ts
  packages/core-manager/src/actions/support-argon2id.ts
  packages/core-manager/src/contracts/action.ts
  packages/core-manager/src/contracts/authentication.ts
  packages/core-manager/src/contracts/http-client.ts
  packages/core-manager/src/contracts/index.ts
  packages/core-manager/src/contracts/plugins.ts
  packages/core-manager/src/defaults.ts
  packages/core-manager/src/ioc/index.ts
  packages/core-manager/src/server/plugins/index.ts
  packages/core-manager/src/server/plugins/plugin-factory.ts
  packages/core-manager/src/server/plugins/rpc-response-handler.ts
  packages/core-manager/src/server/server.ts
  packages/core-manager/src/server/validators/argon2id.ts
  packages/core-manager/src/server/validators/index.ts
  packages/core-manager/src/server/validators/token.ts
  packages/core-manager/src/service-provider.ts
  packages/core-manager/src/utils/api-connection.ts
  packages/core-manager/src/utils/http-client.ts
  packages/core-manager/src/utils/index.ts
  yarn.lock
Labels: Complexity: Medium, Type: Feature

#3698 feat(core-manager): implement `info.diskSpace` action
  __tests__/unit/core-manager/actions/info-disk-space.test.ts
  packages/core-manager/package.json
  packages/core-manager/src/actions/info-disk-space.ts
  yarn.lock
Labels: Complexity: Medium, Type: Feature

#3699 feat(core-manager): implement `info.databaseSize` action
  __tests__/unit/core-manager/action-reader.test.ts
  __tests__/unit/core-manager/actions/info-database-size.test.ts
  __tests__/unit/core-manager/actions/info-disk-space.test.ts
  packages/core-manager/package.json
  packages/core-manager/src/actions/info-database-size.ts
Labels: Complexity: Medium, Type: Feature

#3704 feat(core-manager): implement `process.restart` action
  __tests__/unit/core-manager/actions/process-restart.test.ts
  packages/core-manager/src/actions/process-restart.ts
Labels: Complexity: Medium, Type: Feature

#3703 feat(core-manager): implement `process.start` action
  __tests__/unit/core-manager/actions/process-start.test.ts
  packages/core-manager/src/actions/process-start.ts
Labels: Complexity: Medium, Type: Feature

#3702 feat(core-manager): implement `process.stop` action
  __tests__/unit/core-manager/actions/process.stop.test.ts
  packages/core-manager/src/actions/process.stop.ts
Labels: Complexity: Medium, Type: Feature

#3706 feat(core-database): count estimation
  __tests__/functional/core-database/repositories/block-repository.test.ts
  __tests__/functional/core-database/repositories/transaction-repository.test.ts
  __tests__/unit/core-database/block-history-service.test.ts
  __tests__/unit/core-database/transaction-history-service.test.ts
  packages/core-database/src/block-history-service.ts
  packages/core-database/src/repositories/abstract-repository.ts
  packages/core-database/src/transaction-history-service.ts
  packages/core-kernel/src/contracts/search/index.ts
  packages/core-kernel/src/contracts/shared/block-history-service.ts
  packages/core-kernel/src/contracts/shared/transaction-history-service.ts
Labels: Complexity: Medium, Status: Needs Review

#3716 feat(core-manager): implement `configuration.getEnv` action
  __tests__/unit/core-manager/action-reader.test.ts
  __tests__/unit/core-manager/actions/configuration-env-get.test.ts
  packages/core-manager/src/actions/configuration-env-get.ts
Labels: Complexity: Low, Type: Feature

#3710 feat(core-kernel): implement process actions
  __tests__/unit/core-kernel/services/process-actions/drivers/pm2.test.ts
  __tests__/unit/core-kernel/services/process-actions/service-provider.test.ts
  packages/core-kernel/package.json
  packages/core-kernel/src/bootstrap/app/register-base-service-providers.ts
  packages/core-kernel/src/contracts/kernel/index.ts
  packages/core-kernel/src/contracts/kernel/process-actions.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-kernel/src/services/index.ts
  packages/core-kernel/src/services/process-actions/drivers/pm2.ts
  packages/core-kernel/src/services/process-actions/index.ts
  packages/core-kernel/src/services/process-actions/manager.ts
  packages/core-kernel/src/services/process-actions/service-provider.ts
  yarn.lock
Labels: Complexity: High

#3727 refactor(core-snapshot) improve snapshotService interface
  packages/core-kernel/src/contracts/snapshot/snapshot-service.ts
  packages/core-snapshots/src/contracts/options.ts
  packages/core-snapshots/src/snapshot-service.ts
  packages/core/src/commands/snapshot-dump.ts
  packages/core/src/commands/snapshot-restore.ts
  packages/core/src/commands/snapshot-verify.ts
Labels: Complexity: Low

#3728 feat(core-manager): implement `snapshots.create` action
  __tests__/unit/core-manager/action-reader.test.ts
  __tests__/unit/core-manager/actions/snapshots-create.test.ts
  __tests__/unit/core-manager/snapshots/snapshot-manager.test.ts
  packages/core-manager/src/actions/snapshots-create.ts
  packages/core-manager/src/ioc/identifiers.ts
  packages/core-manager/src/service-provider.ts
  packages/core-manager/src/snapshots/snapshots-manager.ts
  packages/core/bin/config/devnet/app.json
  packages/core/bin/config/mainnet/app.json
  packages/core/bin/config/testnet/app.json
Labels: Complexity: Medium, Type: Feature

#3724 feat(core-manager): implement `snapshots.delete` action
  __tests__/unit/core-manager/actions/snapshots-delete.test.ts
  packages/core-manager/src/actions/snaphsots-delete.ts
  packages/core/src/commands/core-run.ts
Labels: Complexity: Medium, Type: Feature

#3723 feat(core-forger): implements `forger.currentDelegate` process action
  __tests__/unit/core-forger/forger-service.test.ts
  __tests__/unit/core-forger/process-actions/current-delegate.test.ts
  __tests__/unit/core-forger/service-provider.test.ts
  packages/core-forger/src/forger-service.ts
  packages/core-forger/src/process-actions/current-delegate.ts
  packages/core-forger/src/process-actions/index.ts
  packages/core-forger/src/service-provider.ts
Labels: Complexity: Medium, Type: Feature

#3722 feat(core-manager): implement `snapshots.list` action
  __tests__/unit/core-manager/actions/snapshots-list.test.ts
  packages/core-manager/src/actions/snapshots-list.ts
Labels: Complexity: Medium, Type: Feature

#3725 feat(core-api): estimateTotalCount API parameter
  __tests__/functional/core-database/repositories/block-repository.test.ts
  __tests__/functional/core-database/repositories/transaction-repository.test.ts
  packages/core-api/src/controllers/blocks.ts
  packages/core-api/src/controllers/controller.ts
  packages/core-api/src/controllers/delegates.ts
  packages/core-api/src/controllers/locks.ts
  packages/core-api/src/controllers/transactions.ts
  packages/core-api/src/controllers/votes.ts
  packages/core-api/src/controllers/wallets.ts
  packages/core-api/src/defaults.ts
  packages/core-api/src/routes/blocks.ts
  packages/core-database/src/defaults.ts
  packages/core-database/src/repositories/abstract-repository.ts
  packages/core-kernel/src/contracts/search/index.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#3736 feat(core-cli): implement trigger method in ProcessManager
  __tests__/unit/core-cli/services/process-manager.test.ts
  packages/core-cli/src/services/process-manager.ts
Labels: Complexity: Low, Type: Feature

#3734 feat(core-forger): implements `forger.lastForgedBlock` process actions
  __tests__/unit/core-forger/forger-service.test.ts
  __tests__/unit/core-forger/process-actions/last-forged-block.test.ts
  packages/core-forger/src/forger-service.ts
  packages/core-forger/src/process-actions/index.ts
  packages/core-forger/src/process-actions/last-forged-block.ts
  packages/core-forger/src/service-provider.ts
Labels: Complexity: Medium, Type: Feature

#3732 feat(core-manager): implement `snapshots.restore` action
  __tests__/unit/core-manager/actions/snapshots-create.test.ts
  __tests__/unit/core-manager/actions/snapshots-restore.test.ts
  __tests__/unit/core-manager/snapshots/snapshot-manager.test.ts
  packages/core-manager/src/actions/snapshots-create.ts
  packages/core-manager/src/actions/snapshots-restore.ts
  packages/core-manager/src/snapshots/snapshots-manager.ts
Labels: Complexity: Medium, Type: Feature

#3738 chore: CentOS install fixes
  install.sh
Labels: Complexity: Low

#3743 fix(core-transaction-pool): throw ERR_HIGH_FEE when fee is too high
  __tests__/unit/core-transaction-pool/dynamic-fee-matcher.test.ts
  __tests__/unit/core-transaction-pool/processor.test.ts
  packages/core-kernel/src/contracts/transaction-pool/dynamic-fee-matcher.ts
  packages/core-transaction-pool/src/dynamic-fee-matcher.ts
  packages/core-transaction-pool/src/errors.ts
  packages/core-transaction-pool/src/processor.ts
Labels: Complexity: Medium, Type: Bugfix

#3739 feat(core-manager): implement `info.currentDelegate` action
  __tests__/unit/core-manager/__fixtures__/index.ts
  __tests__/unit/core-manager/__fixtures__/trigger-responses.ts
  __tests__/unit/core-manager/actions/info-current-delegate.test.ts
  __tests__/unit/core-manager/utils/process-actions.test.ts
  packages/core-manager/src/actions/info-current-delegate.ts
  packages/core-manager/src/utils/index.ts
  packages/core-manager/src/utils/process-actions.ts
Labels: Complexity: Medium, Type: Feature

#3735 feat(core-forger): implements `forger.nextSlot` process actions
  __tests__/unit/core-forger/forger-service.test.ts
  __tests__/unit/core-forger/process-actions/next-slot.test.ts
  packages/core-forger/src/forger-service.ts
  packages/core-forger/src/process-actions/index.ts
  packages/core-forger/src/process-actions/next-slot.ts
  packages/core-forger/src/service-provider.ts
Labels: Complexity: Medium

#3737 chore(deps): update bcrypto dependency
  packages/crypto/package.json
  packages/crypto/src/identities/public-key.ts
Labels: Complexity: Low, Type: Bugfix

#3746 fix(core-p2p): discard late-forged blocks from forger
  __tests__/unit/core-blockchain/blockchain.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-p2p/src/socket-server/worker.ts
Labels: Complexity: Medium, Type: Bugfix

#3745 release: 2.6.38
  CHANGELOG.md
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#3693 feat(core-transaction-pool): implement workers
  __tests__/unit/core-kernel/utils/ipc-handler.test.ts
  __tests__/unit/core-kernel/utils/ipc-subprocess.test.ts
  __tests__/unit/core-transaction-pool/processor.test.ts
  __tests__/unit/core-transaction-pool/service-provider.test.ts
  __tests__/unit/core-transaction-pool/worker-pool.test.ts
  __tests__/unit/core-transaction-pool/worker-script-handler.test.ts
  __tests__/unit/core-transaction-pool/worker-script.test.ts
  __tests__/unit/core-transaction-pool/worker.test.ts
  packages/core-kernel/src/contracts/transaction-pool/index.ts
  packages/core-kernel/src/contracts/transaction-pool/worker.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-kernel/src/utils/index.ts
  packages/core-kernel/src/utils/ipc-handler.ts
  packages/core-kernel/src/utils/ipc-subprocess.ts
  packages/core-manager/package.json
  packages/core-transaction-pool/src/defaults.ts
  packages/core-transaction-pool/src/processor.ts
  packages/core-transaction-pool/src/service-provider.ts
  packages/core-transaction-pool/src/worker-pool.ts
  packages/core-transaction-pool/src/worker-script-handler.ts
  packages/core-transaction-pool/src/worker-script.ts
  packages/core-transaction-pool/src/worker.ts
Labels: Complexity: High, Status: Needs Review

#3748 feat(core-manager): implement `info.nextForgingSlot` action
  __tests__/unit/core-manager/__fixtures__/trigger-responses.ts
  __tests__/unit/core-manager/actions/info-next-forging-slot.test.ts
  packages/core-manager/src/actions/info-next-forging-slot.ts
Labels: Complexity: Medium, Type: Feature

#3749 chore: support fedora
  install.sh
Labels: Complexity: Low, Type: Task
