Repository ArkEcosystem/core, pull requests merged in 2021-02, with the labels that each got.

#4331 release: 2.7.25
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-container/package.json
  packages/core-database-postgres/package.json
  packages/core-database/package.json
  packages/core-elasticsearch/package.json
  packages/core-error-tracker-airbrake/package.json
  packages/core-error-tracker-bugsnag/package.json
  packages/core-error-tracker-raygun/package.json
  packages/core-error-tracker-rollbar/package.json
  packages/core-error-tracker-sentry/package.json
  packages/core-event-emitter/package.json
  packages/core-exchange-json-rpc/package.json
  packages/core-explorer/package.json
  packages/core-forger/package.json
  packages/core-http-utils/package.json
  packages/core-interfaces/package.json
  packages/core-jest-matchers/package.json
  packages/core-logger-pino/package.json
  packages/core-logger-signale/package.json
  packages/core-logger-winston/package.json
  packages/core-logger/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-new-relic/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-tester-cli/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-utils/package.json
  packages/core-vote-report/package.json
  packages/core-wallet-api/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: High, Type: Release

#4334 release: 3.0.0-next.22
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Type: Release

#4333 chore(core-state): add missing interfaces
  packages/core-kernel/src/contracts/state/block-state.ts
  packages/core-kernel/src/contracts/state/block-store.ts
  packages/core-kernel/src/contracts/state/blocks.ts
  packages/core-kernel/src/contracts/state/index.ts
  packages/core-kernel/src/contracts/state/transaction-store.ts
  packages/core-state/src/block-state.ts
  packages/core-state/src/database-interactions.ts
  packages/core-state/src/dpos/dpos.ts
  packages/core-state/src/stores/blocks.ts
  packages/core-state/src/stores/transactions.ts
Labels: Complexity: Medium, Type: Task

#4329 fix(core-api): cache status code and headers
  __tests__/unit/core-api/service-provider.test.ts
  packages/core-api/src/plugins/cache.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#4330 feat(core-api): fee stats from last 20 tx when no days param is provided
  __tests__/functional/core-database/repositories/transaction-repository.test.ts
  __tests__/unit/core-api/controllers/node.test.ts
  __tests__/unit/core-test-framework/mocks/transaction-repository.test.ts
  packages/core-api/src/controllers/node.ts
  packages/core-api/src/routes/node.ts
  packages/core-database/src/repositories/transaction-repository.ts
  packages/core-test-framework/src/mocks/transaction-repository.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#4332 refactor(core-state): expose get & set methods on StateStore
  __tests__/unit/core-blockchain/blockchain.test.ts
  __tests__/unit/core-blockchain/process-blocks-job.test.ts
  __tests__/unit/core-blockchain/processor/handlers/accept-block-handler.test.ts
  __tests__/unit/core-blockchain/processor/handlers/unchained-handler.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/blockchain-ready.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/check-last-downloaded-block-synced.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/check-later.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/download-blocks.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/download-finished.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/initialize.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/start-fork-recovery.test.ts
  __tests__/unit/core-blockchain/state-machine/state-machine.test.ts
  __tests__/unit/core-p2p/socket-server/utils/get-headers.test.ts
  __tests__/unit/core-state/stores/state.test.ts
  packages/core-blockchain/src/blockchain.ts
  packages/core-blockchain/src/process-blocks-job.ts
  packages/core-blockchain/src/processor/handlers/accept-block-handler.ts
  packages/core-blockchain/src/processor/handlers/unchained-handler.ts
  packages/core-blockchain/src/state-machine/actions/blockchain-ready.ts
  packages/core-blockchain/src/state-machine/actions/check-last-downloaded-block-synced.ts
  packages/core-blockchain/src/state-machine/actions/check-later.ts
  packages/core-blockchain/src/state-machine/actions/download-blocks.ts
  packages/core-blockchain/src/state-machine/actions/download-finished.ts
  packages/core-blockchain/src/state-machine/actions/initialize.ts
  packages/core-blockchain/src/state-machine/actions/start-fork-recovery.ts
  packages/core-blockchain/src/state-machine/state-machine.ts
  packages/core-kernel/src/contracts/blockchain/blockchain.ts
  packages/core-kernel/src/contracts/state/state-store.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/socket-server/utils/get-headers.ts
  packages/core-p2p/src/utils/check-ntp.ts
  packages/core-state/src/stores/state.ts
Labels: Complexity: High, Type: Refactor

#4338 fix(core-transaction-pool): eliminate collator pool clean
  __tests__/unit/core-transaction-pool/collator.test.ts
  packages/core-transaction-pool/src/collator.ts
  packages/core-transaction-pool/src/expiration-service.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#4336 chore(core-state): remove unused clear method on stateStore
  __tests__/unit/core-state/stores/state.test.ts
  packages/core-kernel/src/contracts/state/state-store.ts
  packages/core-state/src/stores/state.ts
Labels: Complexity: Low, Type: Task

#4335 deps: update node-forge, better-sqlite3, bip32
  packages/core-forger/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-transaction-pool/package.json
  packages/crypto/package.json
  yarn.lock
Labels: Complexity: Medium
