Repository ArkEcosystem/core, pull requests merged in 2021-03, with the labels that each got.

#4340 chore(core-p2p): build server on boot
  __tests__/unit/core-p2p/service-provider.test.ts
  packages/core-kernel/src/ioc/identifiers.ts
  packages/core-p2p/src/service-provider.ts
Labels: Complexity: Medium, Type: Task

#4337 chore(core-p2p): remove unnecessary block check
  __tests__/unit/core-p2p/socket-server/controllers/peer.test.ts
  packages/core-p2p/src/socket-server/controllers/peer.ts
Labels: Complexity: Low, Type: Task

#4339 chore(core-forger): register ForgerService on boot
  __tests__/unit/core-forger/service-provider.test.ts
  packages/core-forger/src/service-provider.ts
Labels: Complexity: Low, Type: Task

#4344 fix(core-p2p): dispose server
  __tests__/unit/core-p2p/service-provider.test.ts
  packages/core-p2p/src/service-provider.ts
Labels: Complexity: Low, Type: Bugfix

#4341 refactor(core-p2p): inject objects with Inversify
  __tests__/unit/core-p2p/network-monitor.test.ts
  __tests__/unit/core-p2p/peer-verifier.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/blocks.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/internal.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/peer.test.ts
  __tests__/unit/core-p2p/socket-server/controllers/transactions.test.ts
  __tests__/unit/core-p2p/socket-server/plugins/is-app-ready.test.ts
  packages/core-kernel/src/contracts/p2p/peer-verifier.ts
  packages/core-p2p/src/network-monitor.ts
  packages/core-p2p/src/peer-communicator.ts
  packages/core-p2p/src/peer-processor.ts
  packages/core-p2p/src/peer-verifier.ts
  packages/core-p2p/src/service-provider.ts
  packages/core-p2p/src/socket-server/controllers/blocks.ts
  packages/core-p2p/src/socket-server/controllers/internal.ts
  packages/core-p2p/src/socket-server/controllers/peer.ts
  packages/core-p2p/src/socket-server/plugins/is-app-ready.ts
  packages/core-p2p/src/socket-server/schemas/blocks.ts
  packages/core-p2p/src/socket-server/schemas/peer.ts
  packages/core-p2p/src/socket-server/schemas/transactions.ts
Labels: Complexity: High, Type: Refactor

#4345 refactor(core-p2p): expose NetworkState getters
  __tests__/unit/core-forger/forger-service.test.ts
  __tests__/unit/core-p2p/network-state.test.ts
  packages/core-forger/src/forger-service.ts
  packages/core-kernel/src/contracts/p2p/network-state.ts
  packages/core-p2p/src/network-state.ts
Labels: Complexity: Medium, Type: Refactor

#4346 chore(core-blockchain): pushPingBlock after slot check
  packages/core-blockchain/src/blockchain.ts
Labels: Complexity: Low, Type: Task

#4348 fix(core-p2p): remove connection from list onError
  __tests__/unit/core-p2p/peer-connector.test.ts
  packages/core-p2p/src/peer-connector.ts
Labels: Complexity: Low, Type: Bugfix

#4350 chore(core): set default file log level to `debug`
  packages/core-logger-pino/src/defaults.ts
  packages/core/bin/config/mainnet/.env
  packages/core/bin/config/testnet/.env
Labels: Complexity: Low, Type: Task

#4349 fix(core-api): fix rate limit plugin headers
  packages/core-api/src/plugins/rate-limit.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#4354 reafactor(core-state): implement get and set for restoredDatabaseIntegrity
  __tests__/unit/core-blockchain/state-machine/actions/initialize.test.ts
  __tests__/unit/core-blockchain/state-machine/actions/rollback-database.test.ts
  __tests__/unit/core-state/stores/state.test.ts
  packages/core-blockchain/src/state-machine/actions/initialize.ts
  packages/core-blockchain/src/state-machine/actions/rollback-database.ts
  packages/core-database/src/database-service.ts
  packages/core-kernel/src/contracts/state/state-store.ts
  packages/core-state/src/stores/state.ts
Labels: Complexity: Medium

#4358 release: 3.0.0-next.23
  lerna.json
  packages/core-api/package.json
  packages/core-blockchain/package.json
  packages/core-cli/package.json
  packages/core-database/package.json
  packages/core-forger/package.json
  packages/core-kernel/package.json
  packages/core-logger-pino/package.json
  packages/core-magistrate-api/package.json
  packages/core-magistrate-crypto/package.json
  packages/core-magistrate-transactions/package.json
  packages/core-manager/package.json
  packages/core-p2p/package.json
  packages/core-snapshots/package.json
  packages/core-state/package.json
  packages/core-test-framework/package.json
  packages/core-transaction-pool/package.json
  packages/core-transactions/package.json
  packages/core-webhooks/package.json
  packages/core/package.json
  packages/crypto/package.json
Labels: Complexity: Medium, Status: Needs Review, Type: Release
